{{- if .Values.enabled }}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.watchAllNamespaces }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  name: {{ include "teleport-cluster.operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "teleport-cluster.operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
{{- if .Values.watchAllNamespaces }}
  kind: ClusterRole
{{- else }}
  kind: Role
{{- end }}
  name: {{ include "teleport-cluster.operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "teleport-cluster.operator.serviceAccountName" . }}
{{- if .Values.watchAllNamespaces }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
