{{- if .Values.enabled }}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "teleport-cluster.operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  # Rights to manage the Teleport CRs
  - apiGroups:
      - "resources.teleport.dev"
    resources:
      - "*"
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  # Used to perform leader election when running with multiple replicas
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - create
      - get
      - update
  # Ability to emit reconciliation events
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  # Ability to lookup sensitive values from secrets rather than CRs
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "list"
      - "watch"
{{- end -}}
{{- end -}}
