{{- if .Values.enabled }}
{{ if .Values.scope }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teleport-cluster.operator.shared-state-name" . | quote }}
  namespace: {{ .Release.Namespace }}
data: {}
  # data is empty on purpose, it will be filled by the operator
type: Opaque
{{- end }}
{{- end }}
