FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# نصب پکیج‌های مورد نیاز برای نصب پکیج deb و اجرای Teleport
RUN apt-get update && apt-get install -y \
    ca-certificates \
    dumb-init \
    libpam0g \
    libaudit1 \
    libcap-ng0 \
    libfido2-1 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# ورژن و فایل .deb را به صورت آرگومان دریافت می‌کنیم
ARG TELEPORT_VERSION
ARG TELEPORT_RELEASE_INFIX=
ARG TARGETARCH=amd64
ENV TELEPORT_DEB_FILE_NAME=teleport${TELEPORT_RELEASE_INFIX}_${TELEPORT_VERSION}_${TARGETARCH}.deb

# کپی فایل deb
COPY ${TELEPORT_DEB_FILE_NAME} /tmp/

# نصب Teleport
RUN dpkg -i /tmp/${TELEPORT_DEB_FILE_NAME} && rm -f /tmp/${TELEPORT_DEB_FILE_NAME}

# پوشه‌های مورد نیاز
RUN mkdir -p /etc/teleport /var/lib/teleport

# سیگنال برای shutdown مرتب
STOPSIGNAL SIGQUIT

# اجرای Teleport با dumb-init
ENTRYPOINT ["/usr/bin/dumb-init", "/usr/local/bin/teleport", "start", "-c", "/etc/teleport/teleport.yaml"]