#!/bin/bash 
set -e
mkdir -p /opt/staging/root
mkdir -p /opt/staging/status

for pkg in "$@"; do
    apt-get download "$pkg" && dpkg-deb -R $pkg*.deb /tmp/$pkg
    cp /tmp/$pkg/DEBIAN/control /opt/staging/status/$pkg
    rm -r /tmp/$pkg/DEBIAN
    cp -r /tmp/$pkg/* /opt/staging/root
    rm -rf /tmp/$pkg
done

rm -rf /opt/staging/root/usr/share/locale
rm -rf /opt/staging/root/usr/share/doc