{{- if not .Values.jira.apiTokenFromSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jira.fullname" . }}-secret
  {{- with .Values.annotations.secret }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  jiraApiToken: {{ default "" (.Values.jira.apiToken | b64enc) | quote}}
type: Opaque
{{- end }}
