---
name: Build release on Windows (native)
# run-name: "Push Build for ${{ inputs.release-target }} of ${{ inputs.oss-teleport-repo }} branch ${{ inputs.oss-teleport-ref }}"

on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: "The name of the OSS teleport repo to checkout"
        required: false
        default: "gravitational/teleport"
        type: string
      oss-teleport-ref:
        description: 'Git SHA, tag or branch of the revision of OSS teleport to build'
        required: true
        type: string
      artifact-version:
        description: "The version associated with the artifact to deploy (eg. 1.2.3)"
        type: string
        required: true
      environment:
        description: "Environment to build and upload the package to"
        type: string
        required: true

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: windows-2022-16core
    environment: ${{ inputs.environment }}
    env:
      ARTIFACT_DIRECTORY: 'C:\artifacts'
      RELCLI_DIR: 'C:\relcli'
    steps:
      - name: Checkout Teleport
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        with:
          oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
          oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
          edition: enterprise
          repo-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
          repo-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}
      - name: Load environment values
        uses: gravitational/shared-workflows/tools/env-loader@e28b4323d6c036f904996b9a4a77578e52560570 # tools/env-loader/v0.0.5
        with:
          tool-version: v0.0.5
          environment-name: ${{ inputs.environment }}
          value-sets: windows-signing
          environments-directory: e/.environments
      # TODO move this to an action in the share-workflows repo
      - name: Install Ubuntu WSL
        run: |
          Write-Host "Beginning WSL setup"
          Import-Module -Name Appx -UseWindowsPowerShell

          # This is required by the Ubuntu appx for some reason
          $AppxPackagePath="VCLibs14.appx"
          # TODO: self host/cache this artifact
          # the aka.ms link from the docs is a redirect service that is prone to unexpectedly serving content with a different checksum, use the redirect target instead
          Invoke-WebRequest -Uri https://download.microsoft.com/download/4/7/c/47c6134b-d61f-4024-83bd-b9c9ea951c25/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile "$AppxPackagePath"
          if($(Get-FileHash -Path "$AppxPackagePath").Hash -ne "B56A9101F706F9D95F815F5B7FA6EFBAC972E86573D378B96A07CFF5540C5961") {
            throw "The VCLibs app package downloaded did not match the expected checksum"
          }
          Add-AppxPackage -Path "$AppxPackagePath"

          # Install Ubuntu
          $CommandTime = Measure-Command {
            wsl --update
          }
          Write-Host $("Updated WSL in {0:g}" -f $CommandTime)

          $AppxPackagePath="Ubuntu.appx"
          $CommandTime = Measure-Command {
            Invoke-WebRequest -Uri "https://wslstorestorage.blob.core.windows.net/wslblob/Ubuntu2204-221101.AppxBundle" -OutFile "$AppxPackagePath" -UseBasicParsing
          }
          if($(Get-FileHash -Path "$AppxPackagePath").Hash -ne "6AD6D88763451A50F98F2469CE80464D666204C08D07F8F6A89E0D5CA05B097A") {
            throw "The Ubuntu 22.04 app package downloaded did not match the expected checksum"
          }
          Write-Host $("Downloaded Ubuntu appx in {0:g}" -f $CommandTime)
          $CommandTime = Measure-Command {
            Add-AppxPackage "$AppxPackagePath"
          }
          Write-Host $("Installed Ubuntu appx in {0:g}" -f $CommandTime)

          # Perform Ubuntu setup
          $DistroPath=Join-Path "$env:LOCALAPPDATA" "Microsoft" "WindowsApps" "ubuntu.exe"
          $CommandTime = Measure-Command {
            &$DistroPath install --root
          }
          Write-Host $("Installed Ubuntu in {0:g}" -f $CommandTime)

          # Build scripts to facilitate calling Linux commands from Windows
          $ShellScriptDirectory = Join-Path "$env:RUNNER_TEMP" "wsl"
          New-Item -ItemType Directory -Path "$ShellScriptDirectory" -Force | Out-Null
          Write-Output "$ShellScriptDirectory" | Out-File -FilePath "$env:GITHUB_PATH" -Encoding utf8 -Append

          # Build wrapper script that populates WSL with Windows environment variables
          $ScriptContents = @'
          # Pass all environment variables not already defined by default in WSL bash
          $WslDefaultVars = @(wsl -e env | ForEach-Object {$_.Split("=")[0].ToUpper()})
          $WSLENVVars=@()
          $WSLENVVars += "$env:WSLENV"
          # Case invariant check to see if the environment variable is already set in the WSL environment
          $WSLENVVars += (
            Get-ChildItem env: |
            Where-Object {-not $WslDefaultVars.Contains($_.Name.ToUpper())} |
            ForEach-Object {
                $Name = $_.Name
                $Value = $_.Value
                # Translate variables that start with a fully-qualified path
                # This results in a false negative in some cases, but works in 99.9% of the ones we may ever see
                if($Name.Length -ge 3 -and $Value -imatch '[a-z]:\\' -and $(Test-Path $Value.Substring(0, 3))) {
                    return "$Name/p"
                }

                return $Name
            }
          )
          $env:WSLENV = ($WSLENVVars | Where-Object {$_ -ne ""}) -join ":"

          # Jump to WSL
          wsl -e $Args
          '@
          $WslUbuntuCommandPath = Join-Path "$ShellScriptDirectory" "wsl-ubuntu-command.ps1"
          Write-Output "$ScriptContents" | Out-File -FilePath "$WslUbuntuCommandPath"

          # Build scripts for GHA "shell" directives
          # Write the "backend" Powershell script
          $ScriptContents = @"
          `$ErrorActionPreference = "Stop"

          `$WSLScriptPath = `$(wsl -e wslpath "`$(`$args[0])")

          # Cleaning DOS line endings
          wsl -e sed -i 's/\r`$//' "`$WSLScriptPath"

          # Jump to WSL
          $WslUbuntuCommandPath bash --noprofile --norc -euo pipefail "`$WSLScriptPath"
          `$ScriptExitCode = "`$LASTEXITCODE"

          # Pass the error code upwards
          exit `$ScriptExitCode
          "@
          $ShellScriptBackendPath = Join-Path "$ShellScriptDirectory" "wsl-ubuntu-backend.ps1"
          Write-Output "$ScriptContents" | Out-File -FilePath "$ShellScriptBackendPath"

          # Write the "frontend" batch script
          # This is a hacky workaround that allows GHA to use a Powershell script as a shell
          $ShellScriptPath = Join-Path "$ShellScriptDirectory" "wsl-ubuntu.bat"
          Write-Output "@Powershell.exe -File `"$ShellScriptBackendPath`" %*" | Out-File -FilePath "$ShellScriptPath" -Encoding ascii
      # TODO move this and the next step to an action in the share-workflows repo
      - name: Assume AWS code signing role
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: us-west-2
          role-to-assume: ${{ env.WINDOWS_SIGNING_ROLE_ARN }}
          role-session-name: "build-windows-${{ github.run_number }}"
          role-duration-seconds: 1800 # 30 minutes
      - name: Download and test the signing tools
        shell: wsl-ubuntu {0}
        env:
          WINDOWS_SIGNING_CERT_SSM_PARAMETER_PATH: ${{ env.WINDOWS_SIGNING_CERT_SSM_PARAMETER_PATH }}
          WINDOWS_SIGNING_CERT_KMS_KEY_ARN: ${{ env.WINDOWS_SIGNING_KEY_ARN }}
        run: |
          # Install required utilities
          # Install the 20.04 security repo for libssl1.1 and libjson-c4, which are required by aws-kms-pkcs11.
          # These packages are not available on 22.04.
          echo "::group::Installing dependencies..."
          echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list > /dev/null
          apt update
          apt install --no-install-recommends -y unzip libssl-dev libengine-pkcs11-openssl libssl1.1 libjson-c4 awscli openssl
          echo "::endgroup::"

          echo "::group::Installing osslsigncode..."
          DOWNLOAD_PATH="/tmp/osslsigncode.zip"
          echo "Downloading release..."
          curl -o "$DOWNLOAD_PATH" -L https://github.com/mtrojnar/osslsigncode/releases/download/2.6/osslsigncode-2.6-ubuntu-22.04.zip
          echo "3cc2474891605f29adbc58e08e0330052cda1f53540d2ce751783be5bd9088e1  $DOWNLOAD_PATH" | sha256sum --check --status || \
            (echo "The osslsigncode zip file downloaded did not match the expected checksum"; exit 1)
          echo "osslsigncode release artifact files:"
          unzip -v "$DOWNLOAD_PATH"

          echo "Extracting release..."
          unzip "$DOWNLOAD_PATH" -d /usr
          chmod +x /usr/bin/osslsigncode

          echo "Release version:"
          osslsigncode --version
          echo "::endgroup::"

          echo "::group::Installing aws-kms-pkcs11..."
          PKCS11_MODULE_PATH=/usr/lib/x86_64-linux-gnu/pkcs11/aws_kms_pkcs11.so
          mkdir -pv "$(dirname "$PKCS11_MODULE_PATH")"
          echo "Downloading release..."
          curl -o "$PKCS11_MODULE_PATH" -L https://github.com/JackOfMostTrades/aws-kms-pkcs11/releases/download/v0.0.10/aws_kms_pkcs11.x86_64.so
          echo "93c10632f11c6936373e9ff3a9877624320aa6c24bdcdff3da39cda519241ec7  $PKCS11_MODULE_PATH" | sha256sum --check --status || \
            (echo "The aws-kms-pkcs11 module downloaded did not match the expected checksum"; exit 1)

          echo "Downloaded module:"
          ls -l "$PKCS11_MODULE_PATH"
          echo "::endgroup::"

          # Create config data
          echo "::group::Creating aws-kms-pkcs11 config data..."
          CONFIG_DIRECTORY_PATH="/etc/aws-kms-pkcs11"  # This specific directory is required by aws-kms-pkcs11
          mkdir -p "$CONFIG_DIRECTORY_PATH"

          # Download the code signing certificate from SSM Parameter Store
          CERT_FILE_PATH="$CONFIG_DIRECTORY_PATH/signing-cert.crt"
          echo "Pulling Windows signing cert from SSM at $WINDOWS_SIGNING_CERT_SSM_PARAMETER_PATH"
          aws ssm get-parameter --name "$WINDOWS_SIGNING_CERT_SSM_PARAMETER_PATH" --query "Parameter.Value" --output text > "$CERT_FILE_PATH"
          echo "Signing certificate info:"
          openssl x509 -in "$CERT_FILE_PATH" -noout -text

          # Resolve the key alias or ID ARN to the key ID alone
          KMS_KEY_ID=$(aws kms describe-key --key-id "$WINDOWS_SIGNING_CERT_KMS_KEY_ARN" --output text --query 'KeyMetadata.KeyId')
          echo "Using KMS key ID $KMS_KEY_ID for key $WINDOWS_SIGNING_CERT_KMS_KEY_ARN"

          # Write the aws-kms-pkcs11 provider configuration file
          CONFIG_FILE_PATH="$CONFIG_DIRECTORY_PATH/config.json"
          PKCS11_LABEL="signing-key"
          cat > "$CONFIG_FILE_PATH" << EOF
          {
            "slots": [
              {
                "label": "$PKCS11_LABEL",
                "kms_key_id": "$KMS_KEY_ID",
                "aws_region": "$AWS_REGION",
                "certificate_path": "$CERT_FILE_PATH"
              }
            ]
          }
          EOF

          echo "Configured aws-kms-pkcs11 as:"
          cat "$CONFIG_FILE_PATH"
          echo "::endgroup::"

          # Make "sign file" scripts available to the build pipeline
          echo "::group::Creating sign-binary script..."
          SIGN_BINARY_PATH="/usr/local/bin/sign-binary"
          cat > "$SIGN_BINARY_PATH" << EOF
          #!/bin/bash
          set -euo pipefail

          UNSIGNED_FILE="\$1"
          if [ "\${UNSIGNED_FILE#*:}" != "\$UNSIGNED_FILE" ]; then
            UNSIGNED_FILE=\$(wslpath "\$UNSIGNED_FILE")
          fi

          SIGNED_FILE="\$2"
          if [ "\${SIGNED_FILE#*:}" != "\$SIGNED_FILE" ]; then
            SIGNED_FILE=\$(wslpath "\$SIGNED_FILE")
          fi

          echo "Signing \$UNSIGNED_FILE => \$SIGNED_FILE as AWS user \$(aws sts get-caller-identity --query "Arn" --output text)"

          mkdir -p "\$(dirname \$SIGNED_FILE)"
          export AWS_KMS_PKCS11_DEBUG=1
          osslsigncode sign \\
            -h sha256 \\
            -pkcs11engine /usr/lib/x86_64-linux-gnu/engines-3/pkcs11.so \\
            -pkcs11module "$PKCS11_MODULE_PATH" \\
            -pkcs11cert "pkcs11:token=$PKCS11_LABEL" \\
            -in "\$UNSIGNED_FILE" \\
            -out "\$SIGNED_FILE" \\
            -verbose
          EOF
          chmod +x "$SIGN_BINARY_PATH"
          echo "Created sign-binary script at $SIGN_BINARY_PATH"
          echo "::endgroup::"

          echo "::group::Testing signing tools..."
          # This executable is used because it is known that all Windows Server installs will have it at this path
          SIGNED_FILE_PATH="/tmp/signed.exe"
          sign-binary 'C:\Windows\SysWOW64\explorer.exe' "$SIGNED_FILE_PATH"

          echo "Signed binary at $SIGNED_FILE_PATH:"
          ls -l "$SIGNED_FILE_PATH"

          rm -f "$SIGNED_FILE_PATH"
          echo "::endgroup::"
      - name: Build the artifacts
        env:
          ARTIFACT_TAG: ${{ inputs.artifact-version }}
        run: |
          $ProgressPreference = 'SilentlyContinue'
          $ErrorActionPreference = 'Stop'
          $PSNativeCommandUseErrorActionPreference = $true
          . "build.assets/windows/build.ps1"
          Install-BuildRequirements -InstallDirectory "C:\toolchains" -TeleportSourceDirectory "$(Get-Location)"
          Write-Version-Objects -TeleportSourceDirectory "$(Get-Location)" -TeleportVersion "$env:ARTIFACT_TAG"
          Build-Artifacts -TeleportSourceDirectory "$(Get-Location)" -TeleportVersion "$env:ARTIFACT_TAG" -ArtifactDirectory "$env:ARTIFACT_DIRECTORY"
      - name: Get the release server CLI
        env:
          RELCLI_URL: 'https://cdn.teleport.dev/relcli-${{ env.RELCLI_VERSION }}-windows.exe'
        run: |
          $ErrorActionPreference = 'Stop'
          $PSNativeCommandUseErrorActionPreference = $true
          $ProgressPreference = 'SilentlyContinue'
          . "build.assets/windows/build.ps1"
          Get-Relcli -Url "$env:RELCLI_URL" -Workspace "$env:RELCLI_DIR"
      - name: Register the artifact with the release server
        env:
          RELEASE_REPO: ${{ inputs.oss-teleport-repo }}
          ARTIFACT_VERSION: ${{ inputs.artifact-version }}
        run: |
          $ErrorActionPreference = 'Stop'
          $PSNativeCommandUseErrorActionPreference = $true
          $ProgressPreference = 'SilentlyContinue'
          . "build.assets/windows/build.ps1"
          Generate-Artifacts -Workspace "$env:RELCLI_DIR" -ArtifactDirectory "$env:ARTIFACT_DIRECTORY"
      - name: Assume AWS S3 artifact upload role
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-skip-session-tagging: true
          aws-region: us-west-2
          role-to-assume: ${{ env.ARTIFACT_UPLOAD_AWS_ROLE }}
          role-session-name: "release-windows-${{ github.run_number }}"
          role-duration-seconds: 900
      - name: Upload the artifacts to the artifact storage bucket
        env:
          ARTIFACT_BUCKET: ${{ env.ARTIFACT_SOURCE_BUCKET }}
          ARTIFACT_TAG: ${{ inputs.artifact-version }}
        run: |
          aws s3 cp "$env:ARTIFACT_DIRECTORY" "s3://$env:ARTIFACT_BUCKET/teleport/tag/$env:ARTIFACT_TAG/" --recursive --no-progress
