name: Build multiarch buildbox base images
run-name: Build multiarch buildbox base images
on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  BUILDBOX_PREFIX: ghcr.io/gravitational

jobs:
  build-base:
    name: Build multiarch base images

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - arch: arm
            runner:
              group: prod
              labels: ['self-hosted', 'linux', 'arm64']
            platform: linux/arm/v7
          - arch: arm64
            runner:
              group: prod
              labels: ['self-hosted', 'linux', 'arm64']
            platform: linux/arm64
          - arch: 386
            runner: ubuntu-latest
            platform: linux/386
          - arch: amd64
            runner: ubuntu-latest
            platform: linux/amd64

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout OSS Teleport
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Login to registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # We need to keep env vars in sync, so, we can't use standard build actions
      - name: Build gcc image
        run: |
          make -C build.assets PLATFORM=${{ matrix.platform }} ARCH=${{ matrix.arch }} build-multiarch-base

      - name: Docker push the latest built image
        run: docker push $(docker images -a --format '{{.Repository}}:{{.Tag}}'| head -1)

  build-clang:
    needs: build-base
    name: Build multiarch clang images

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
            platform: linux/amd64
            version: 7
          - arch: arm64
            runner:
              group: prod
              labels: ['self-hosted', 'linux', 'arm64']
            platform: linux/arm64
            version: 10
          - arch: amd64
            runner: ubuntu-latest
            platform: linux/amd64
            version: 10

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout OSS Teleport
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Login to registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build clang image
        run: |
          make -C build.assets PLATFORM=${{ matrix.platform }} ARCH=${{ matrix.arch }} build-multiarch-clang${{ matrix.version }}

      - name: Docker push the latest built image
        run: docker push $(docker images -a --format '{{.Repository}}:{{.Tag}}'| head -1)
