name: Build Generic Linux
on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: "The name of the OSS teleport repo to checkout"
        required: false
        default: "gravitational/teleport"
        type: string

      oss-teleport-ref:
        description: 'Git SHA, tag or branch of the revision of OSS teleport to build'
        required: true
        type: string

      ent-teleport-ref:
        description: |
          Git SHA, tag or branch of the revision of Enterprise teleport to build. If no
          value is supplied this workflow will use whatever reference is specified in
          the OSS teleport submodule record.
        required: false
        default: ""
        type: string

      arch:
        description: 'CPU architecture to build. Currently supports `arm` and `arm64`'
        required: true
        type: string

      release:
        description: 'Release level to build. Currently supports `oss` and `enterprise`'
        required: true
        type: string

      save-artifacts:
        description: 'Should the build export the build artifacts'
        required: false
        type: boolean
        default: false

      builder:
        # This needs to be encoded as JSON, as parameters can opnly be strings, numbers
        # or booleans, and we need to pass an array if we're running on a self-hosted
        # builder.
        description: |
          JSON-encoded labels and groups for selecting the action runner to use when 
          executing this workflow. This allows callers to select self-hosted runners
          (e.g. for arm64) or any of the github-supplied runners (e.g. ubuntu-latest)
          depending on the build requirements.

          Example: `toJSON({"group": "prod", "labels": ["self-hosted", "X64"]})`
        required: true
        type: string        
    secrets:
      dockerhub-username:
        description: 'Dockerhub login username'
        required: true

      dockerhub-token:
        description: 'Dockerhub login password'
        required: true

      deploy-access-app-id:
        description: |
          The ID of the GitHub app used to grant deployment access for repos
          to the workflow.
        required: true

      deploy-access-app-key:
        description: | 
          The private key used to authenticate against the seployment access
          GitGub app.
        required: true

jobs:
  build-release-artifacts:
    permissions:
      contents: read

    runs-on: ${{ fromJSON(inputs.builder) }}

    env:
      GOMODCACHE: /tmp/gomodcache
      GOCACHE: /tmp/gocache

    steps:
      - name: Ensure required packages are installed
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          if [ "$CI_SYSTEM" = "ARC" ]; then
            sudo apt update
            sudo apt install -y make
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Checkout Teleport
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        with:
          oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
          oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
          edition: ${{ inputs.release }}
          ent-teleport-ref: ${{ inputs.ent-teleport-ref }}
          repo-access-app-id: ${{ secrets.deploy-access-app-id }}
          repo-access-app-key: ${{ secrets.deploy-access-app-key }}

      - name: Build Buildbox
        run: |
          make -C build.assets                                               \
            buildbox-centos7                                                 \
            ARCH=${{ inputs.arch }}                                          \
            BUILDBOX_CENTOS7=teleport-buildbox-${{ inputs.arch }}:latest     \

      - name: Fix cache permissions
        run: |
          sudo mkdir -p ${{ env.GOMODCACHE }} ${{ env.GOCACHE }} 
          sudo chown -Rf $(id -u):$(id -g) ${{ env.GOMODCACHE }} ${{ env.GOCACHE }}

      - name: Build Release
        run: |
            make -C build.assets                                           \
              release-centos7                                              \
              ARCH=${{ inputs.arch }}                                      \
              BUILDBOX_CENTOS7=teleport-buildbox-${{ inputs.arch }}:latest \
              GOMODCACHE=${{ env.GOMODCACHE }}                             \
              GOCACHE=${{ env.GOCACHE }}                                   \
              WORKSPACE=${{ github.workspace  }}

      - name: Gather artifacts
        if: ${{ inputs.save-artifacts }}
        run: find -name "teleport-*.tar.gz" -type f -not -path "./teleport-*.tar.gz" | xargs -Itarball cp tarball .

      - name: Checksum artifacts
        if: ${{ inputs.save-artifacts }}
        run: |
          for f in teleport-*.tar.gz
          do
            sha256sum $f > $f.sha256
          done

      - name: Upload artifacts
        if: ${{ inputs.save-artifacts }}
        uses: actions/upload-artifact@v3
        with:
          name: tarballs
          path: |
            ./teleport-*.tar.gz
            ./teleport-*.tar.gz.sha256
          retention-days: 1
