---
name: Build Helm charts
on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: The name of the OSS teleport repo to checkout.
        type: string
        default: gravitational/teleport

      oss-teleport-ref:
        description: Git SHA, tag or branch of the revision of OSS teleport to build.
        type: string
        required: true

      teleport-version:
        description: |
          The semver version of Teleport version that we're building for.
        type: string

      environment:
        description: GitHub environment to build in.
        type: string
        default: stage/build

  # The workflow_dispatch event duplicates the workflow_call input parameters, without descriptions.
  workflow_dispatch:
    inputs:
      oss-teleport-repo:
        type: string
        default: gravitational/teleport
      oss-teleport-ref:
        type: string
        required: true
      teleport-version:
        type: string
      environment:
        type: string
        default: stage/build
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
    steps:
      # "Build" the assets
      - name: Checkout Teleport
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        with:
          oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
          oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
          edition: enterprise
          repo-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
          repo-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}
      - name: Load environment values
        uses: gravitational/shared-workflows/tools/env-loader@b90d744feb39522329fba9c7764a4fe07d039d29 # tools/env-loader/v0.1.2
        with:
          tool-version: v0.0.5
          environment-name: ${{ inputs.environment }}
          environments-directory: e/.environments

      - name: Copy the scripts to the release directory
        env:
          RELEASE_VERSION: ${{ inputs.teleport-version }}
        run: |
          mkdir -p build/artifacts
          cp ./assets/install-scripts/install.sh "./build/artifacts/install-v${RELEASE_VERSION}.sh"
          cp ./assets/install-scripts/install-connect.sh "./build/artifacts/install-connect-v${RELEASE_VERSION}.sh"
          cp ./assets/install-scripts/license-check.sh "./build/artifacts/license-check-v${RELEASE_VERSION}.sh"
      
      # Generate the manifests
      - name: Assume AWS ECR pull role
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-skip-session-tagging: true
          aws-region: ${{ env.RELCLI_IMAGE_REGION }}
          role-to-assume: ${{ env.RELCLI_IMAGE_PULL_ROLE_ARN }}
          role-session-name: "pull-relcli-build-install-scripts-${{ github.run_attempt }}"
          role-duration-seconds: 900
  
      - name: Log into ECR
        uses: aws-actions/amazon-ecr-login@fa648b43de3d4d023bcb3f89ed6940096949c419 # v2.1.5

      - name: Generate release server manifests
        working-directory: build/artifacts
        env:
          RELCLI_IMAGE: ${{ env.RELCLI_IMAGE }}
          RELEASE_VERSION: ${{ inputs.teleport-version }}
        run: |
          docker pull "${RELCLI_IMAGE}"

          ls -lah

          # Generate the manifests
          docker run -u "$(id -u):$(id -g)" -v "$(pwd):/assets" \
            "${RELCLI_IMAGE}" generate-manifest \
            --path "/assets/install-v${RELEASE_VERSION}.sh" --os "linux" --architecture "universal" \
            --description "Linux install script"
          
          docker run -u "$(id -u):$(id -g)" -v "$(pwd):/assets" \
            "${RELCLI_IMAGE}" generate-manifest \
            --path "/assets/install-connect-v${RELEASE_VERSION}.sh" --os "linux" --architecture "universal" \
            --description "Linux Connect install script"

          docker run -u "$(id -u):$(id -g)" -v "$(pwd):/assets" \
            "${RELCLI_IMAGE}" generate-manifest \
            --path "/assets/license-check-v${RELEASE_VERSION}.sh" --os "linux" --architecture "universal" \
            --description "Linux license check script"

          ls -lah

      # Upload the files
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-skip-session-tagging: true
          aws-region: us-west-2
          role-to-assume: ${{ env.ARTIFACT_UPLOAD_AWS_ROLE }}
          role-session-name: upload-artifacts-${{ github.run_number }}
          role-duration-seconds: 3600
          
      - name: Copy artifacts to S3 bucket
        working-directory: build/artifacts
        env:
          PENDING_BUCKET_NAME: ${{ env.ARTIFACT_SOURCE_BUCKET }}
          RELEASE_VERSION: ${{ inputs.teleport-version }}
        run: |
          aws s3 cp . "s3://$PENDING_BUCKET_NAME/teleport/tag/${RELEASE_VERSION}/" --recursive
