name: Build MacOS (Darwin)

on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: 'The name of the OSS Teleport repo to checkout'
        required: false
        default: "gravitational/teleport"
        type: string

      oss-teleport-ref:
        description: 'Git SHA, tag or branch of the revision of OSS teleport to build'
        required: true
        type: string

      ent-teleport-ref:
        description: |
          Git SHA, tag or branch of the revision of Enterprise teleport to build. If no
          value is supplied this workflow will use whatever reference is specified in
          the OSS teleport submodule record.
        required: false
        default: ""
        type: string

      arch:
        description: 'Build architecture. Either amd64 or arm64'
        required: true
        type: string

      release:
        description: 'Release level to build. Currently supports `oss` and `enterprise`'
        required: true
        type: string

      release-version:
        description: |
          Override the build version from what is in the Makefile.
          Use this override to specify a tag for build debugging purposes.
        type: string
        default: ""

      environment:
        description: |
          GitHub Actions environment in which to run the build. Can be either
          `promote` or `build`. The default `promote` can only be used for
          `master` and `branch/*` branches. `build` should be used for testing
          workflow changes on a dev branch.
        required: false
        type: string
        default: promote

jobs:
  build-release-artifacts:
    environment: ${{ inputs.environment }}
    runs-on: macos-13-xl-arm64
    permissions:
      contents: read
    env:
      GOMODCACHE: /tmp/gomodcache
      GOCACHE: /tmp/gocache
      ARCH: ${{ inputs.arch }}
    steps:
      # --- Setup -------------------------------------------------------------

      # https://github.com/actions/runner/issues/2996
      # time.windows.com because github runners are in azure.
      - name: Fix time sync
        run: |
          sudo sntp -sS time.windows.com

      - name: Checkout Teleport
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        with:
          oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
          oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
          edition: ${{ inputs.release }}
          ent-teleport-ref: ${{ inputs.ent-teleport-ref }}
          repo-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
          repo-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}

      - name: Determine Toolchain Versions and cache paths
        run: |
          echo NODE_VERSION=$(make -C build.assets print-node-version) >> $GITHUB_ENV
          echo GOLANG_VERSION=$(make -C build.assets print-go-version | sed 's/^go//') >> $GITHUB_ENV
          echo RUST_VERSION=$(make -C build.assets print-rust-version) >> $GITHUB_ENV
          echo PKG_CONFIG_PATH="$(make print-fido2-pkg-path)" >> $GITHUB_ENV

      - name: Print versions
        run: |
          echo "make: $(make --version)"
          echo "node: ${NODE_VERSION}"
          echo "go: ${GOLANG_VERSION}"
          echo "rust: ${RUST_VERSION}"

      - name: Install Node Toolchain
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup yarn
        run: |
          corepack enable yarn

      - name: Install Go Toolchain
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Install Rust Toolchain
        run: |
          make ARCH=${ARCH} RUST_VERSION=${RUST_VERSION} rustup-install-target-toolchain

      - name: Setup keychain
        env:
          APP_KEY: ${{ secrets.APPLE_APPLICATION_PRIVATE_KEY }}
          APP_KEY_PASSWORD: ${{ secrets.APPLE_APPLICATION_PRIVATE_KEY_PASSWORD }}
          INST_KEY: ${{ secrets.APPLE_INSTALLER_PRIVATE_KEY }}
          INST_KEY_PASSWORD: ${{ secrets.APPLE_INSTALLER_PRIVATE_KEY_PASSWORD }}
        run: |
          ./build.assets/keychain-setup.sh -a APP_KEY -A APP_KEY_PASSWORD -i INST_KEY -I INST_KEY_PASSWORD -v

      # --- Build -------------------------------------------------------------
      - name: Build FIDO2
        run: |
          make ARCH=${ARCH} build-fido2

      - name: Build Teleport Tarball
        env:
          APPLE_USERNAME: ${{ vars.APPLE_USERNAME }}
          APPLE_PASSWORD: ${{ secrets.APPLE_APPLICATION_PASSWORD }}
          ENVIRONMENT_NAME: ${{ vars.ENVIRONMENT_NAME }}
          TELEPORT_VERSION: ${{ inputs.release-version }}
        run: |
          make release OS=darwin ARCH=${ARCH} FIDO2=yes TOUCHID=yes PIV=yes ${TELEPORT_VERSION:+VERSION=${TELEPORT_VERSION}}

      # --- Upload ------------------------------------------------------------
      - name: Checksum artifacts
        run: |
          cd build/artifacts
          for f in *; do
            shasum -a 256 "$f" > "$f.sha256"
            cat "$f.sha256"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact/@v3
        with:
          name: release
          path: |
            build/artifacts
            !**/*-unsigned*
          retention-days: 1
