name: Build Buildboxes
on:
  workflow_call:
    inputs:
      branch:
        description: Branch to build the buildboxes for.
        type: string
        required: true
  workflow_dispatch:
    inputs:
      branch:
        # Not required on workflow_dispatch as github.ref_name is valid.
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  buildbox:
    strategy:
      matrix:
        hostarch: [amd64, arm64]
        target: [buildbox, buildbox-node, buildbox-arm, buildbox-centos7, buildbox-centos7-fips]
        exclude:
          # Exclude buildbox, buildbox-node and buildbox-arm on arm64. They are amd64 only
          - hostarch: arm64
            target: buildbox
          - hostarch: arm64
            target: buildbox-node
          - hostarch: arm64
            target: buildbox-arm

        include:
          # Add our self-hosted builder to arm64 matrix combos
          - hostarch: arm64
            builder:
              group: prod
              labels: [ self-hosted, linux, arm64 ]

    name: ${{ matrix.hostarch }} ${{ matrix.target }}
    runs-on: ${{ matrix.builder || 'ubuntu-22.04-32core' }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Teleport
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        with:
          oss-teleport-ref: ${{ inputs.branch || github.ref_name }}
          edition: oss

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
        with:
          driver: docker

      - name: Login to registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure required packages are installed
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          if [[ "${CI_SYSTEM}" == "ARC" ]]; then
            sudo apt update
            sudo apt install -y make
          fi

      - name: Build and push buildbox image
        env:
          ARCH: ${{ matrix.hostarch }}
          TARGET: ${{ matrix.target }}
        run: |
          make --no-print-directory -C build.assets "${TARGET}" PUSH=1 ARCH="${ARCH}"
