# This workflow builds a Teleport release on a Linux-based buildbox using the
# release-* targets defined in build.assets/Makefile of the OSS Teleport
# repository. Both the OSS and Enterprise release tarballs will be built.

name: Build Release on Linux
on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: "The name of the OSS teleport repo to checkout"
        required: false
        default: "gravitational/teleport"
        type: string

      oss-teleport-ref:
        description: "Git SHA, tag or branch of the revision of OSS teleport to build"
        required: true
        type: string

      ent-teleport-ref:
        description: |
          Git SHA, tag or branch of the revision of Enterprise teleport to build. If no
          value is supplied this workflow will use whatever reference is specified in
          the OSS teleport submodule record.
        required: false
        default: ""
        type: string

      release:
        description: "Release level to build. Currently supports `oss` and `enterprise`"
        required: true
        type: string

      release-target:
        description: "Release target to run from build.assets/Makefile."
        required: true
        type: string

      save-artifacts:
        description: "Should the build export the build artifacts"
        required: false
        type: boolean
        default: false

      build-connect:
        description: "Should Teleport Connect be built"
        required: false
        type: boolean
        default: false

      build-deb:
        description: "Should a Debian package of the release be built"
        required: false
        type: boolean
        default: false

      build-rpm:
        description: "Should a RPM package of the release be built"
        required: false
        type: boolean
        default: false

      arch:
        description: "Architecture for OS package builds"
        required: false
        type: string

      builder:
        # This needs to be encoded as JSON, as parameters can opnly be strings, numbers
        # or booleans, and we need to pass an array or object if we're running on a
        # self-hosted runner.
        description: |
          JSON-encoded labels and groups for selecting the action runner to use when
          executing this workflow. This allows callers to select self-hosted runners
          (e.g. for arm64) or any of the github-supplied runners (e.g. ubuntu-latest)
          depending on the build requirements.
          Example - `toJSON({"group": "prod", "labels": ["self-hosted", "X64"]})`
        required: true
        type: string

      environment:
        description: |
          GitHub Actions environment in which to run the build. Can be either
          `promote` or `build`.
        required: false
        type: string
        default: promote

jobs:
  build-release-artifacts:
    permissions:
      contents: read
      id-token: write # required for aws-actions/configure-aws-credentials for OIDC

    runs-on: ${{ fromJSON(inputs.builder) }}

    environment: ${{ inputs.environment }}

    env:
      # GOMODCACHE and GOCACHE can be removed when we commit to the self-hosted
      # ARC runners, as these runners set up these vars for us. We still need
      # these though for the GitHub runners (ubuntu).
      GOMODCACHE: /tmp/gomodcache
      GOCACHE: /tmp/gocache

    steps:
      - name: Ensure required packages are installed
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          if [[ "${CI_SYSTEM}" == "ARC" ]]; then
            sudo apt update
            sudo apt install -y make
          fi

      - name: Determine FIPS
        id: determine-fips
        env:
          RELEASE_TARGET: ${{ inputs.release-target }}
        run: |
          case "$RELEASE_TARGET" in
          *-fips) echo 'is-fips=true' ;;
          *) echo 'is-fips=false' ;;
          esac >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log into Docker Hub to increase rate limits
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Assume AWS role log into ECR
      - name: Assume teleport build user AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::146628656107:role/tf-teleport-build-read-only-role-gha
          role-session-name: "gha-build-linux-${{ github.run_number }}"
          role-duration-seconds: 3600

      # Log into ECR to raise rate limits, needed for the public.ecr.aws/gravitational/fpm
      # image used for building .deb and .rpm files.
      - name: Log into ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
        env:
          # GetAuthorizationToken command is only supported in us-east-1.
          AWS_REGION: us-east-1

      # The step can be removed when we commit to the self-hosted ARC runners,
      # as it runs with a consistent UID/GID and creates the directories with
      # the correct ownership. We still need this for the GitHub runners though.
      - name: Create cache directories with correct owner/group
        run: |
          sudo mkdir -p "$GOCACHE" "$GOMODCACHE"
          sudo chown -Rf "$(id -u):$(id -g)" "$GOCACHE" "$GOMODCACHE"

      - name: Checkout Teleport
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        with:
          oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
          oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
          edition: ${{ inputs.release }}
          ent-teleport-ref: ${{ inputs.ent-teleport-ref }}
          repo-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
          repo-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}

      # FIPS and Teleport Connect builds need VERSION set in the environment as those
      # builds do not go through the top-level teleport Makefile, which sets it for
      # other builds.
      - name: Set Version
        run: |
          VERSION=$(grep -oP '^VERSION=\K.*' Makefile)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Build Release
        env:
          RELEASE: ${{ inputs.release }}
          RELEASE_TARGET: ${{ inputs.release-target }}
          RELEASE_DIR: ${{ github.workspace }}/build/artifacts
        run: |
          mkdir -p "$RELEASE_DIR" # TODO(camscale): Move -p to Makefile
          make -C build.assets "$RELEASE_TARGET"
          # CentOS7 builds are used for all Linux AMD64 targets, but are also named with a
          # centos7 tag too.
          # TODO(camscale): Move this naming to the Makefile
          if [ "$RELEASE_TARGET" = 'release-amd64-centos7' ]; then
            cp "build/artifacts/teleport-v${VERSION}-linux-amd64-bin.tar.gz" \
               "build/artifacts/teleport-v${VERSION}-linux-amd64-centos7-bin.tar.gz"
            if [ "$RELEASE" = 'enterprise' ]; then
              cp "build/artifacts/teleport-ent-v${VERSION}-linux-amd64-bin.tar.gz" \
                 "build/artifacts/teleport-ent-v${VERSION}-linux-amd64-centos7-bin.tar.gz"
            fi
          elif [ "$RELEASE_TARGET" = 'release-amd64-centos7-fips' ]; then
            # FIPS builds end up in e/build/artifacts as $RELEASE_DIR does not pass through
            # to the docker build.
            cp "e/build/artifacts/teleport-ent-v${VERSION}-linux-amd64-fips-bin.tar.gz" build/artifacts
            cp "build/artifacts/teleport-ent-v${VERSION}-linux-amd64-fips-bin.tar.gz" \
               "build/artifacts/teleport-ent-v${VERSION}-linux-amd64-centos7-fips-bin.tar.gz"
          fi

      - name: Build Teleport Connect
        if: inputs.build-connect
        run: |
          make -C build.assets teleterm VERSION="$VERSION"
          cp web/packages/teleterm/build/release/teleport-connect* build/artifacts

      - name: Build Debian package
        if: inputs.build-deb && steps.determine-fips.outputs.is-fips == 'false'
        env:
          ARCH: ${{ inputs.arch }}
          ENT_TARBALL_PATH: ${{ github.workspace }}/build/artifacts
          OSS_TARBALL_PATH: ${{ github.workspace }}/build/artifacts
          RELEASE: ${{ inputs.release }}
        run: |
          make deb
          # TODO(camscale): Move artifact copying to Makefile(s)
          cp build/*.deb build/artifacts
          if [ "$RELEASE" = 'enterprise' ]; then
            cp e/build/*.deb build/artifacts
          fi

      - name: Build FIPS Debian package
        if: inputs.build-deb && steps.determine-fips.outputs.is-fips == 'true'
        env:
          ARCH: ${{ inputs.arch }}
          FIPS: yes
          RUNTIME: fips
          ENT_TARBALL_PATH: ${{ github.workspace }}/build/artifacts
        run: |
          make -C e deb
          # TODO(camscale): Move artifact copying to Makefile(s)
          cp e/build/*.deb build/artifacts

      # TODO(camscale): Convert this step to use ./github/actions/load-gpg-key
      - name: Extract RPM Signing Archive
        if: inputs.build-rpm
        env:
          GPG_SIGNING_ARCHIVE: ${{ secrets.GPG_SIGNING_ARCHIVE }}
          GNUPG_DIR: /tmp/gnupg
        run: |
          if [ -z "$GPG_SIGNING_ARCHIVE" ]; then
            echo "GPG signing archive is unset or empty, aborting"
            exit 1
          fi
          mkdir -m 0700 "$GNUPG_DIR"
          echo "$GPG_SIGNING_ARCHIVE" | base64 -d | tar -xzf - --no-same-owner --no-overwrite-dir -C "$GNUPG_DIR"
          chown -Rv "$(id -un):$(id -gn)" "$GNUPG_DIR"

      - name: Build RPM package
        if: inputs.build-rpm && steps.determine-fips.outputs.is-fips == 'false'
        env:
          ARCH: ${{ inputs.arch }}
          ENT_TARBALL_PATH: ${{ github.workspace }}/build/artifacts
          OSS_TARBALL_PATH: ${{ github.workspace }}/build/artifacts
          RELEASE: ${{ inputs.release }}
          GNUPG_DIR: /tmp/gnupg
        run: |
          make rpm
          # TODO(camscale): Move artifact copying to Makefile(s)
          cp build/*.rpm build/artifacts
          if [ "$RELEASE" = 'enterprise' ]; then
            cp e/build/*.rpm build/artifacts
          fi

      - name: Build FIPS RPM package
        if: inputs.build-rpm && steps.determine-fips.outputs.is-fips == 'true'
        env:
          ARCH: ${{ inputs.arch }}
          FIPS: yes
          RUNTIME: fips
          ENT_TARBALL_PATH: ${{ github.workspace }}/build/artifacts
          RELEASE: ${{ inputs.release }}
          GNUPG_DIR: /tmp/gnupg
        run: |
          make -C e rpm
          # TODO(camscale): Move artifact copying to Makefile(s)
          cp e/build/*.rpm build/artifacts

      - name: Checksum artifacts
        if: inputs.save-artifacts
        run: |
          cd build/artifacts
          for f in *; do
            [ -f "$f.sha256" ] && continue
            shasum -a 256 "$f" > "$f.sha256"
            cat "$f.sha256"
          done

      - name: Upload artifacts
        if: inputs.save-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: |
            build/artifacts
