name: Build Generic Linux
on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: "The name of the OSS teleport repo to checkout"
        required: false
        default: "gravitational/teleport"
        type: string

      oss-teleport-ref:
        description: 'Git SHA, tag or branch of the revision of OSS teleport to build'
        required: true
        type: string

      ent-teleport-ref:
        description: |
          Git SHA, tag or branch of the revision of Enterprise teleport to build. If no
          value is supplied this workflow will use whatever reference is specified in
          the OSS teleport submodule record.
        required: false
        default: ""
        type: string

      arch:
        description: 'CPU architecture to build. Currently supports `arm` and `arm64`'
        required: true
        type: string

      release:
        description: 'Release level to build. Currently supports `oss` and `enterprise`'
        required: true
        type: string

      save-artifacts:
        description: 'Should the build export the build artifacts'
        required: false
        type: boolean
        default: false

      builder:
        # This needs to be encoded as JSON, as parameters can opnly be strings, numbers
        # or booleans, and we need to pass an array if we're running on a self-hosted
        # builder.
        description: |
          JSON-encoded tags for selecting the action runner to use when executing this
          workflow. This allows callers to select self-hosted runners (e.g. for arm64)
          or any of the github-supplied runners (e.g. ubuntu-latest) depending on the
          build requirements.
        required: true
        type: string        
    secrets:
      dockerhub-username:
        description: 'Dockerhub login username'
        required: true

      dockerhub-token:
        description: 'Dockerhub login password'
        required: true

      deploy-access-app-id:
        description: |
          The ID of the GitHub app used to grant deployment access for repos
          to the workflow.
        required: true

      deploy-access-app-key:
        description: | 
          The private key used to authenticate against the seployment access
          GitGub app.
        required: true

jobs:
  build-release-artifacts:
    permissions:
      contents: read

    runs-on: ${{ fromJSON(inputs.builder) }}

    env:
      GOMODCACHE: /tmp/gomodcache
      GOCACHE: /tmp/gocache

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      # Attempt to fetch a deploy token from the GitHub App we use to broker
      # access to private repositories. If this fails, we are in one of 2 
      # situations:
      #
      # 1. The App is not installed on the target repo (e.g. public Teleport), or
      # 2. Something is wrong with GitHub
      #
      # In either case, the workflow will carry on and attempt to use the
      # default workflow token to check out the target repo, which will be
      # fine if that repo is public.
      #
      - name: Fetch deploy token
        uses: tibdex/github-app-token@v1
        id: fetch-token
        continue-on-error: true
        with:
          app_id: ${{ secrets.deploy-access-app-id }}
          repository: ${{ inputs.oss-teleport-repo }}
          private_key: ${{ secrets.deploy-access-app-key }}

      - name: Select token
        id: select-deploy-token
        run: |
          TOKEN=${{ github.token }}
          if [[ -n "${{ steps.fetch-token.outputs.token }}" ]]; then
            TOKEN=${{ steps.fetch-token.outputs.token }}
          fi
          echo oss_teleport=$TOKEN >> $GITHUB_OUTPUT

      - name: Checkout OSS Teleport
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.oss-teleport-repo }}
          ref: ${{ inputs.oss-teleport-ref }}
          token: ${{ steps.select-deploy-token.outputs.oss_teleport }}

      - name: Determine Enterprise Teleport reference
        if: inputs.release == 'enterprise'
        run: |
          if [[ -z "${{ inputs.ent-teleport-ref }}" ]]; then
            echo TELEPORT_E_REF=$(git rev-parse @:e) >> $GITHUB_ENV
          else
            echo TELEPORT_E_REF=${{ inputs.ent-teleport-ref }} >> $GITHUB_ENV
          fi

      - name: Checkout Enterprise Teleport
        if: inputs.release == 'enterprise'
        uses: actions/checkout@v3
        with:
          repository: gravitational/teleport.e
          ref: ${{ env.TELEPORT_E_REF }}
          path: e

      # We are not guaranteed to have an available `make` at this point, (e.g.
      # when using the self-hosted ARM runners) so for now we will scrape the
      # info we need directly out of the makefile using grep. This is not
      # ideal, and should be replaced with a call to make as soon as we can
      # guarantee the runner image has `make` baked in.
      - name: Determine toolchain versions
        run: |
          echo NODE_VERSION=$(grep -Po 'NODE_VERSION \?\= \K\S*' build.assets/Makefile) >> $GITHUB_ENV
          echo GOLANG_VERSION=$(grep -Po 'GOLANG_VERSION \?\= \Kgo\S*' build.assets/Makefile) >> $GITHUB_ENV
          echo RUST_VERSION=$(grep -Po 'RUST_VERSION \?\= \K\S*' build.assets/Makefile) >> $GITHUB_ENV

      - name: Build Buildbox
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          context: build.assets
          file: ./build.assets/Dockerfile-multiarch
          platforms: linux/${{ inputs.arch }}
          tags: teleport-buildbox-${{ inputs.arch }}:latest
          build-args: |
            BUILD_ARCH=${{ inputs.arch }}
            NODE_VERSION=${{ env.NODE_VERSION }}
            RUST_VERSION=${{ env.RUST_VERSION }}
            GOLANG_VERSION=${{ env.GOLANG_VERSION }}
            UID=1000
            GID=1000

      - name: Build Release
        run: |
            make -C build.assets                                           \
              release-${{ inputs.release }}                                \
              ARCH=${{ inputs.arch }}                                      \
              BUILDBOX=teleport-buildbox-${{ inputs.arch }}:latest         \
              GOMODCACHE=${{ env.GOMODCACHE }}                             \
              GOCACHE=${{ env.GOCACHE }}                                   \
              WORKSPACE=${{ github.workspace  }}

      - name: Gather artifacts
        if: ${{ inputs.save-artifacts }}
        run: find -name "teleport-*.tar.gz" -type f -not -path "./teleport-*.tar.gz" | xargs -Itarball cp tarball .

      - name: Checksum artifacts
        if: ${{ inputs.save-artifacts }}
        run: |
          for f in teleport-*.tar.gz
          do
            sha256sum $f > $f.sha256
          done

      - name: Upload artifacts
        if: ${{ inputs.save-artifacts }}
        uses: actions/upload-artifact@v3
        with:
          name: tarballs
          path: |
            ./teleport-*.tar.gz
            ./teleport-*.tar.gz.sha256
          retention-days: 1
