---
name: Build Teleport Plugins

on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: The name of the OSS teleport repo to checkout.
        type: string
        default: gravitational/teleport

      oss-teleport-ref:
        description: Git SHA, tag or branch of the revision of OSS teleport to build.
        type: string
        required: true

      teleport-version:
        description: |
          The semver version of Teleport version that we're building for.
        type: string

      environment:
        description: |
          GitHub Actions environment in which to run the build. Can be either
          `build-stage` or `build-prod`.
        type: string
        default: build-stage

jobs:
  build-plugins:
    runs-on: ubuntu-22.04-32core
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
    env:
      ARTIFACT_DIRECTORY: /tmp/build
    steps:
      # Setup
      - name: Checkout Teleport
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        with:
          oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
          oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
          edition: oss  # We don't need teleport.e even when building enterprise AMI
          repo-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
          repo-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}
          oss-fetch-depth: 0  # This is required by some of the commands in the makefiles
          
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"
          check-latest: true
          cache: false

      - name: Set environment variables for Makefiles
        env:
          VERSION_TAG: ${{ inputs.teleport-version || inputs.oss-teleport-ref }}
        run: |
          echo "VERSION=${VERSION_TAG##v}" >> "$GITHUB_ENV"

      # File artifacts
      - name: Download Go dependencies once
        run: go mod download
      - name: Build the access plugins release tarballs
        env:
          ACCESS_SUBDIRECTORIES: >-
            discord
            pagerduty
            msteams
            jira
            slack
            mattermost
            email
        run: |
          read -ra plugins <<<"${ACCESS_SUBDIRECTORIES}"
          for plugin in "${plugins[@]}"; do
            make -C "integrations/access/$plugin/" OS=linux ARCH=amd64 release
            make -C "integrations/access/$plugin/" OS=linux ARCH=arm64 release
          done

      - name: Build the terraform provider release tarballs
        run: |
          # Required to make universal images
          go install github.com/konoui/lipo@latest

          make -C integrations/terraform release OS=linux ARCH=amd64
          make -C integrations/terraform release OS=linux ARCH=arm64
          make -C integrations/terraform release OS=darwin ARCH=amd64
          make -C integrations/terraform release OS=darwin ARCH=arm64
          make -C integrations/terraform release OS=darwin ARCH=universal

      - name: Build the event handler release tarballs
        run: |
          make -C integrations/event-handler release OS=linux ARCH=amd64
          make -C integrations/event-handler release OS=linux ARCH=arm64
          make -C integrations/event-handler release OS=darwin ARCH=amd64
          make -C integrations/event-handler release OS=darwin ARCH=arm64

      - name: Collect the build files
        run: |
          mkdir -pv "$ARTIFACT_DIRECTORY"
          find . -name '*.tar.gz' -type f -exec cp {} "$ARTIFACT_DIRECTORY" \;

      - name: Generate checksum files for built files
        working-directory: ${{ env.ARTIFACT_DIRECTORY }}
        run: |
          shopt -s nullglob
          for tarball in *.tar.gz; do
            sha256sum "$(basename "$tarball")" > "${tarball}.sha256"
          done
          echo "Artifacts:"
          ls -lh

      - name: Assume AWS role for uploading the artifacts
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          role-skip-session-tagging: true
          aws-region: us-west-2
          role-to-assume: ${{ vars.ARTIFACT_UPLOAD_AWS_ROLE }}
          role-session-name: "tag-build-artifact-upload-${{ github.run_attempt }}"
          role-duration-seconds: 900

      - name: Upload artifacts to S3
        working-directory: ${{ env.ARTIFACT_DIRECTORY }}
        env:
          PENDING_BUCKET: ${{ vars.ARTIFACT_SOURCE_BUCKET }}
        run: |
          aws s3 cp . "s3://$PENDING_BUCKET/teleport-plugins/tag/$VERSION/" --recursive

  # Container artifacts
  build-docker-images:
    name: Build OCI container images
    permissions:
      actions: read
      contents: read
      id-token: write  # required for aws-actions/configure-aws-credentials
      security-events: write # required for trivy scan
    strategy:
      matrix:
        plugins:
          # Access plugins
          - name: discord
            artifact-name: access-discord
            dockerfile-path: integrations/access/Dockerfile
          - name: email
            artifact-name: access-email
            dockerfile-path: integrations/access/Dockerfile
          - name: jira
            artifact-name: access-jira
            dockerfile-path: integrations/access/Dockerfile
          - name: mattermost
            artifact-name: access-mattermost
            dockerfile-path: integrations/access/Dockerfile
          - name: msteams
            artifact-name: access-msteams
            dockerfile-path: integrations/access/Dockerfile
          - name: pagerduty
            artifact-name: access-pagerduty
            dockerfile-path: integrations/access/Dockerfile
          - name: slack
            artifact-name: access-slack
            dockerfile-path: integrations/access/Dockerfile
          # Event handler
          - name: event-handler
            artifact-name: event-handler
            dockerfile-path: integrations/event-handler/Dockerfile
    needs: build-plugins
    uses: ./.github/workflows/oci-image-build.yml
    with:
      teleport-release: oss
      base-image: 'gcr.io/distroless/static-debian12:latest'
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      source-tag: ${{ inputs.teleport-version }}
      teleport-version: ${{ inputs.teleport-version }}
      dest-image-repo: teleport-plugin-${{ matrix.plugins.name }}
      dest-image-tags: ${{ inputs.teleport-version }}
      architectures: |
        amd64
        arm64
      s3-file-name-override: |-
        teleport-plugins/tag/${{ inputs.teleport-version }}/teleport-${{ matrix.plugins.artifact-name }}-v${{ inputs.teleport-version }}-linux-{arch}-bin.tar.gz
      image-build-context: ./teleport/. # Teleport repo directory
      image-build-dockerfile: ${{ matrix.plugins.dockerfile-path }}
      allow-overwrites: false
      environment: ${{ inputs.environment }}
    secrets:
      deploy-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
      deploy-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}
  
