name: Build MacOS (Darwin) Universal

on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: "The name of the OSS Teleport repo to checkout"
        required: false
        default: "gravitational/teleport"
        type: string

      oss-teleport-ref:
        description: "Git SHA, tag or branch of the revision of OSS teleport to build"
        required: true
        type: string

      ent-teleport-ref:
        description: |
          Git SHA, tag or branch of the revision of Enterprise teleport to build. If no
          value is supplied this workflow will use whatever reference is specified in
          the OSS teleport submodule record.
        required: false
        default: ""
        type: string

      release:
        description: "Release level to build. Currently supports `oss` and `enterprise`"
        required: true
        type: string

      release-version:
        description: |
          Override the build version from what is in the Makefile.
          Use this override to specify a tag for build debugging purposes.
        type: string
        default: ""

      build-packages:
        description: |
          Build Mac packages for Teleport, tsh and Teleport Connect.
          Packages are not build for push builds. Release builds do
          build packages.
        required: false
        type: boolean
        default: false

      environment:
        description: |
          GitHub Actions environment in which to run the build. Can be either
          `build-stage` or `build-prod`.
        type: string
        default: build-stage

jobs:
  build-release-artifacts:
    environment: ${{ inputs.environment }}
    runs-on: macos-13-xlarge
    permissions:
      contents: read
      id-token: write
    env:
      GOMODCACHE: /tmp/gomodcache
      GOCACHE: /tmp/gocache
    steps:
      # --- Setup -------------------------------------------------------------

      # https://github.com/actions/runner/issues/2996
      # time.windows.com because github runners are in azure.
      - name: Fix time sync
        run: |
          sudo sntp -sS time.windows.com

      - name: Checkout Teleport
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        with:
          oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
          oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
          edition: ${{ inputs.release }}
          ent-teleport-ref: ${{ inputs.ent-teleport-ref }}
          repo-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
          repo-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}

      - name: Determine Toolchain Versions and cache paths
        run: |
          echo "NODE_VERSION=$(make -s -C build.assets print-node-version)" >> "${GITHUB_ENV}"

      - name: Print versions
        run: |
          echo "make: $(make --version)"
          echo "node: ${NODE_VERSION}"

      # This is needed to build Teleport Connect.
      # The @electron/rebuild tool that rebuilds native dependencies still
      # uses node-gyp@9 that relies on distutils.
      # Remove this step after @electron/rebuild migrates to node-gyp@10
      # (which is compatible with Python 3.12).
      - name: Install Python setuptools
        run: |
          brew install python-setuptools

      - name: Install Node Toolchain
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        run: |
          corepack enable pnpm 

      - name: Setup keychain
        env:
          APP_KEY: ${{ secrets.APPLE_APPLICATION_PRIVATE_KEY }}
          APP_KEY_PASSWORD: ${{ secrets.APPLE_APPLICATION_PRIVATE_KEY_PASSWORD }}
          INST_KEY: ${{ secrets.APPLE_INSTALLER_PRIVATE_KEY }}
          INST_KEY_PASSWORD: ${{ secrets.APPLE_INSTALLER_PRIVATE_KEY_PASSWORD }}
        run: |
          ./build.assets/keychain-setup.sh -a APP_KEY -A APP_KEY_PASSWORD -i INST_KEY -I INST_KEY_PASSWORD -v

      - name: Assume AWS role for downloading the arch-specific artifacts
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-skip-session-tagging: true
          aws-region: us-west-2
          role-to-assume: ${{ vars.ARTIFACT_DOWNLOAD_AWS_ROLE }}
          role-session-name: "gha-macos-artifact-download-${{ github.run_number }}"
          role-duration-seconds: 900

      - name: Download architecture-specific artifacts
        env:
          DOWNLOAD_DIRECTORY: build/artifacts/
          S3_PREFIX: s3://${{ vars.ARTIFACT_SOURCE_BUCKET }}/teleport/tag/${{ inputs.release-version }}
          TELEPORT_VERSION: ${{ inputs.release-version }}
          RELEASE: ${{ inputs.release }}
        run: |
          mkdir -pv "${DOWNLOAD_DIRECTORY}"
          cd "${DOWNLOAD_DIRECTORY}"

          # `aws s3 cp` occasionally segfaults on mac for unknown reasons. `aws s3 sync` seems to work better.
          aws s3 sync "${S3_PREFIX}/" . --exclude "*" --include "teleport-v${TELEPORT_VERSION}*-darwin-*bin.tar.gz"
          if [[ "${RELEASE}" == enterprise ]]; then
            aws s3 sync "${S3_PREFIX}/" . --exclude "*" --include "teleport-ent-v${TELEPORT_VERSION}*-darwin-*bin.tar.gz"
          fi

          ls -laht

      # --- Build -------------------------------------------------------------
      - name: Build Teleport Tarball
        env:
          APPLE_USERNAME: ${{ vars.APPLE_USERNAME }}
          APPLE_PASSWORD: ${{ secrets.APPLE_APPLICATION_PASSWORD }}
          ENVIRONMENT_NAME: ${{ vars.ENVIRONMENT_NAME }}
          TELEPORT_VERSION: ${{ inputs.release-version }}
        run: |
          make release OS=darwin ARCH=universal FIDO2=yes TOUCHID=yes VNETDAEMON=yes PIV=yes ${TELEPORT_VERSION:+VERSION=${TELEPORT_VERSION}}

      - name: Build Teleport Package
        if: inputs.build-packages
        env:
          APPLE_USERNAME: ${{ vars.APPLE_USERNAME }}
          APPLE_PASSWORD: ${{ secrets.APPLE_APPLICATION_PASSWORD }}
          ENVIRONMENT_NAME: ${{ vars.ENVIRONMENT_NAME }}
          OSS_TARBALL_PATH: ${{ github.workspace }}/build/artifacts
          TELEPORT_VERSION: ${{ inputs.release-version }}
        run: |
          make pkg ARCH=universal OS=darwin ${TELEPORT_VERSION:+VERSION=${TELEPORT_VERSION}}

      - name: Prepare tsh Package for Teleport Connect
        if: inputs.build-packages
        env:
          TELEPORT_VERSION: ${{ inputs.release-version }}
        run: |
          mkdir -p build/pkg
          cd build/pkg
          pkgutil --expand-full ../tsh-*.pkg tsh
          echo "CONNECT_TSH_APP_PATH=${PWD}/tsh/Payload/tsh.app" >> "${GITHUB_ENV}"

      - name: Build Teleport Connect
        env:
          APPLE_USERNAME: ${{ vars.APPLE_USERNAME }}
          APPLE_PASSWORD: ${{ secrets.APPLE_APPLICATION_PASSWORD }}
          BUILD_NUMBER: ${{ github.run_number }}
          CONNECT_TSH_BIN_PATH: ${{ github.workspace }}/build/tsh
          ENVIRONMENT_NAME: ${{ vars.ENVIRONMENT_NAME }}
          TELEPORT_VERSION: ${{ inputs.release-version }}
        run: |
          # Make CONNECT_TSH_APP_PATH override CONNECT_TSH_BIN_PATH by unsetting
          # the latter if the former is set (by the previous step).
          [ -n "${CONNECT_TSH_APP_PATH:-}" ] && unset CONNECT_TSH_BIN_PATH
          make release-connect ARCH=universal ${TELEPORT_VERSION:+VERSION=${TELEPORT_VERSION}}

      # --- Upload ------------------------------------------------------------
      # Generate release server manifests
      - name: Generate release server manifests
        env:
          RELCLI_VERSION: ${{ vars.RELCLI_VERSION }}
          RELCLI_PATH: /tmp/relcli
          TELEPORT_VERSION: ${{ inputs.release-version }}
          RELEASE: ${{ inputs.release }}
        shell: bash
        working-directory: build/artifacts
        run: |
          # Download the release server CLI tool
          curl -fsSL -o "${RELCLI_PATH}" "https://cdn.teleport.dev/relcli-${RELCLI_VERSION}-macos-$(uname -m)"
          chmod +x "${RELCLI_PATH}"
          ls -lh "${RELCLI_PATH}"

          ls -lah

          "${RELCLI_PATH}" generate-manifest \
            --path "teleport-v${TELEPORT_VERSION}-darwin-universal-bin.tar.gz" \
            --products 'teleport' --os 'darwin' --architecture 'universal' \
            --description "MacOS Universal"

          "${RELCLI_PATH}" generate-manifest \
            --path "teleport-${TELEPORT_VERSION}.pkg" \
            --products 'teleport' --os 'darwin' --architecture 'universal' \
            --description "MacOS Universal .pkg installer"

          if [[ "${RELEASE}" == 'enterprise' ]]; then
            "${RELCLI_PATH}" generate-manifest \
              --path "Teleport Connect-${TELEPORT_VERSION}.dmg" \
              --products 'teleport' --products 'teleport-ent' \
              --os 'darwin' --architecture 'universal' \
              --description "Teleport Connect"

            "${RELCLI_PATH}" generate-manifest \
              --path "teleport-ent-v${TELEPORT_VERSION}-darwin-universal-bin.tar.gz" \
              --products 'teleport-ent' --os 'darwin' --architecture 'universal' \
              --description "MacOS Universal"

            "${RELCLI_PATH}" generate-manifest \
              --path "teleport-ent-${TELEPORT_VERSION}.pkg" \
              --products 'teleport-ent' --os 'darwin' --architecture 'universal' \
              --description "MacOS Universal .pkg installer"
          else
            # Still publish Connect for non-enterprise releases, but don't 
            # release it under the "teleport-ent" product
            "${RELCLI_PATH}" generate-manifest \
              --path "Teleport Connect-${TELEPORT_VERSION}.dmg" \
              --products 'teleport' \
              --os 'darwin' --architecture 'universal' \
              --description "Teleport Connect"
          fi

          ls -lah

      # Upload to the pending artifacts bucket
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-skip-session-tagging: true
          aws-region: us-west-2
          role-to-assume: ${{ vars.ARTIFACT_UPLOAD_AWS_ROLE }}
          role-session-name: upload-artifacts-${{ github.run_number }}
          role-duration-seconds: 3600

      - name: Copy artifacts to S3 bucket
        working-directory: build/artifacts
        env:
          PENDING_BUCKET_NAME: ${{ vars.ARTIFACT_SOURCE_BUCKET}}
          TELEPORT_VERSION: ${{ inputs.release-version }}
        run: |
          aws s3 sync . "s3://$PENDING_BUCKET_NAME/teleport/tag/${TELEPORT_VERSION}/"
