# Build Teleport Operator OCI images for amd64, arm64 and arm architectures.
name: Build Operator OCI Images
run-name: Build Operator OCI Images
on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: |
          The name of the OSS teleport repo to checkout
        type: string
        default: "gravitational/teleport"

      oss-teleport-ref:
        description: |
          Git SHA, tag or branch of the revision of OSS teleport to build
        required: true
        type: string

      teleport-version:
        description: |
          The semver version of Teleport version that we're building for.
        type: string

      architectures:
        description:
          Space-separated list of architectures to build the image for. Must be Docker
          architectures - amd64, arm, arm64, etc.
        type: string
        default: "amd64 arm64 arm"

      environment:
        description: |
          GitHub Actions environment in which to run the build. Can be either
          `build-stage` or `build-prod`.
        type: string
        default: build-stage

jobs:
  build-image:
    name: Build OCI Images
    runs-on: ubuntu-22.04-16core
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Teleport
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        with:
          oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
          oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
          edition: oss
          repo-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
          repo-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}

      - name: Parameterize build
        id: params
        env:
          ARCHITECTURES: ${{ inputs.architectures }}
          TELEPORT_VERSION: ${{ inputs.teleport-version || inputs.oss-teleport-ref }}
        run: |
          # Convert architectures into docker platform args
          read -ra arches <<<"${ARCHITECTURES}" # safely read into array to prevent globbing
          {
            echo 'platforms<<EOF'
            printf 'linux/%s\n' "${arches[@]}"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
          echo "teleport-version=${TELEPORT_VERSION#v}" >> "$GITHUB_OUTPUT"

      # Log into Docker Hub to increase rate limits
      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Assume Build AWS role
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: us-west-2
          role-to-assume: ${{ vars.BUILD_OPERATOR_OCI_AWS_ROLE }}
          role-session-name: "gha-build-operator-oci-${{ github.run_attempt }}"
          role-duration-seconds: 3600

      - name: Log into Destination ECR Registry
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Check if Image Exists
        id: check
        env:
          IMAGE: ${{ vars.OPERATOR_PENDING_ECR_REPO }}:${{ steps.params.outputs.teleport-version }}
        run: |
          if docker manifest inspect "${IMAGE}" >/dev/null 2>&1; then
            echo "Skipping build/push as image already exists: ${IMAGE}" >> "$GITHUB_STEP_SUMMARY"
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Build OCI Image
        if: steps.check.outputs.exists == 'false'
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          push: true
          context: .
          file: ./integrations/operator/Dockerfile.gha
          platforms: ${{ steps.params.outputs.platforms }}
          tags: ${{ vars.OPERATOR_PENDING_ECR_REPO }}:${{ steps.params.outputs.teleport-version }}
