# Workflow will trigger on all pull request (except draft), pull request
# review, and commit push to a pull request (synchronize) event types
#
# NOTE: Unlike the OSS branch, pull_request_target is not necessary here
# because there are no forks possible from the enterprise branch.
name: Check
on:
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request:
    types: [opened, ready_for_review, synchronize, labeled, unlabeled]

# Limit the permissions on the GitHub token for this workflow to the subset
# that is required. In this case, the check workflow needs to invalidate
# reviews and delete workflow runs, so it needs write access to "actions" and
# "pull-requests", nothing else.
permissions:
    actions: write
    pull-requests: write

jobs:
  check-reviews:
    name: Checking reviewers
    if: ${{ !github.event.pull_request.draft && !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.REVIEWERS_APP_ID }}
          private-key: ${{ secrets.REVIEWERS_PRIVATE_KEY }}
      # Checkout main branch of shared-workflow repository.
      - name: Checkout shared-workflow
        uses: actions/checkout@v6
        with:
          repository: gravitational/shared-workflows
          path: .github/shared-workflows
          ref: dd8f30e8fd5dd1d1655b9d27049e5d0f6f4f9ef2 # workflows/v0.0.3
      - name: Installing Go
        uses: actions/setup-go@v6
        with:
          go-version-file: .github/shared-workflows/bot/go.mod
        # Run "check" subcommand on bot.
      - name: Checking reviewers
        run: cd .github/shared-workflows/bot && go run main.go -workflow=check -token="${{ steps.generate_token.outputs.token }}" -reviewers="${{ secrets.reviewers }}"
