---
name: Deploy OS packages to repos
run-name: Deploy OS packages to ${{ inputs.repo-type }} repos

on:
  workflow_dispatch:
    inputs:
      repo-type:
        description: "The type of OS package repo that the package should be deployed to"
        required: true
        type: choice
        options:
          - apt
          - yum
      environment:
        description: "Environment to deploy the package to"
        type: environment
        required: true
      package-name-filter:
        description: "Filter that limits what packages will be deployed. This is evalulated in a shell context, applied following the s3 sync include rules."
        default: "*"
        type: string
        required: true
      artifact-tag:
        description: "The tag associated with the artifact to deploy (eg. v1.2.3)"
        type: string
        required: true
      version-channel:
        description: "The version channel of the repos that the artifacts should be added to. Semver values will be truncated to major version. Examples: \"v1.2.3\" (truncated to \"v1\"), \"cloud\"."
        type: string
        required: true
      # This is here to facilitate the addition of new release channels when/if the OPRT supports them
      release-channel:
        description: "The release channel that the artifact should be deployed to"
        type: choice
        required: true
        options:
          - stable
        default: stable
      package-to-test:
        description: "The package to install and test during the smoke test"
        type: string
        required: false
      # This is a workaround so that the actor who initiated a workflow run via a workflow dispatch event can determine the run ID of the started workflow run
      workflow-tag:
        description: "This field adds the provided value to a run step, allowing the calling actor to associate the started run with the GHA run ID."
        type: string
        required: false

jobs:
  deploy:
    name: Deploy packages to ${{ inputs.repo-type }} repo
    # Note that the value of this string is arbitrary as long as it contains the `${{ inputs.repo-type }}`
    # and `${{ inputs.environment }}` expressions
    concurrency:
      group: Only allow a single OS package deployment at a time
      cancel-in-progress: false
    permissions:
      contents: read
      id-token: write   # Required for aws-actions/configure-aws-credentials
    environment: ${{ inputs.environment }}
    runs-on:
      - self-hosted
      - linux
      - x64
      - os-package-repo-tool
    outputs:
      # This is the actual name of the version channel used in the repo component. It's calculated here and
      # used when installing pacakges for smoke tests.
      component-version-channel: ${{ steps.component-version-channel.outputs.component-version-channel }}
    env:
      TOOL_BINARY_PATH: os-package-repo-tool
      DOWNLOAD_DIRECTORY: /tmp/artifacts
      GNUPGHOME: /tmp/gnupg
      # These paths must be updated in the mount script in the `cloud-terraform` repo if they are changed here
      APT_CACHE_PATH: /mnt/apt-cache/${{ inputs.environment }}
      YUM_CACHE_PATH: /mnt/yum-cache/${{ inputs.environment }}
    steps:
      - name: Disallow prerelease artifacts from being deployed to production repos
        if: inputs.environment == 'production' || inputs.environment == 'promote'
        uses: actions/github-script@v6
        with: 
          script: |
            if ("${{ inputs.artifact-tag }}".indexOf("-") > -1)
              core.setFailed("Prerelease artifacts may not be deployed to production repos");
      - name: Derive and set version channel
        id: component-version-channel
        if: inputs.package-to-test != ''
        env:
          # This is copy/pasted from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
          # with the addition of "v?" to match Teleport's tag naming scheme
          SEMVER_TAG_REGEX: ^v?(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
          VERSION_CHANNEL: ${{ inputs.version-channel }}
        run: |
          # Check if the artifact version is a semver
          if echo "$VERSION_CHANNEL" | grep --perl-regexp --quiet "$SEMVER_TAG_REGEX"; then
            # Ensure exactly one "v" prefix exists, and trim the first '.' and everything after
            echo "component-version-channel=$(echo "v${VERSION_CHANNEL#v}" | sed -e 's/\..*//')" >> "$GITHUB_OUTPUT"
            exit
          fi

          # If not a semver (such as when it's set to "cloud")
          echo "component-version-channel=$VERSION_CHANNEL" >> "$GITHUB_OUTPUT"
      - name: Derive and set repo type-specific variables for APT
        if: inputs.repo-type == 'apt'
        run: |
          echo "PACKAGE_TYPE=deb" >> "$GITHUB_ENV"
          echo "CACHE_PATH=$APT_CACHE_PATH" >> "$GITHUB_ENV"
          echo "BUCKET_NAME=${{ vars.APT_S3_BUCKET }}" >> "$GITHUB_ENV"
          echo "TOOL_ARGUMENTS=-aptly-root-dir $APT_CACHE_PATH/aptly" >> "$GITHUB_ENV"
          echo "DEPLOYMENT_AWS_ROLE=${{ vars.APT_DEPLOYMENT_AWS_ROLE }}" >> "$GITHUB_ENV"
      - name: Derive and set repo type-specific variables for YUM
        if: inputs.repo-type == 'yum'
        run: |
          echo "PACKAGE_TYPE=rpm" >> "$GITHUB_ENV"
          echo "CACHE_PATH=$YUM_CACHE_PATH" >> "$GITHUB_ENV"
          echo "BUCKET_NAME=${{ vars.YUM_S3_BUCKET }}" >> "$GITHUB_ENV"
          echo "TOOL_ARGUMENTS=-cache-dir $YUM_CACHE_PATH/createrepo -repo-domain-name ${{ vars.YUM_REPO_DOMAIN_NAME }}" >> "$GITHUB_ENV"
          echo "DEPLOYMENT_AWS_ROLE=${{ vars.YUM_DEPLOYMENT_AWS_ROLE }}" >> "$GITHUB_ENV"
      - name: Log set variables
        run: |
          echo "Set variables:"
          env
      - name: Log general runner information
        run: |
          echo "OS info:"
          cat /etc/os-release
          uname -a

          echo
          echo "EC2 instance info:"
          TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
          curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/dynamic/instance-identity/document

          echo
          echo
          echo "YUM repo info:"
          sudo yum repolist

          echo
          echo "Disk info:"
          df -hT
      # Future TODO package the tool as an action or separate workflow
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "./tooling/os-package-repo-tool/go.mod"
          cache-dependency-path: "./tooling/os-package-repo-tool/go.sum"
          check-latest: true
      - name: Log installed Go version
        run: go version
      - name: Build tool
        run: |
          sudo yum install -y gcc
          CGO_ENABLED=1 go build -race -o "$(pwd)/$TOOL_BINARY_PATH" -C "./tooling/os-package-repo-tool/" "./src/"
      - name: Install the required runtime dependencies
        run: |
          # Exit on error, and error on unset vars
          set -o errexit
          set -o nounset

          # Create new bin directory for the user
          RUNNER_BIN_DIR="$HOME/bin"
          mkdir -pv "$RUNNER_BIN_DIR"
          export PATH="$RUNNER_BIN_DIR:$PATH"
          echo "PATH=$PATH" | tee -a "$GITHUB_ENV"

          # Aptly
          # Download the artifact (tarball archive)
          # TODO add something to hook dependabot here
          TARBALL_FILE_NAME="/tmp/aptly.tar.gz"
          LATEST_APTLY_RELEASE_URL=$(curl -s "https://api.github.com/repos/aptly-dev/aptly/releases/latest" | jq -r ".assets[].browser_download_url" | grep "linux_amd64.tar.gz")
          wget -nv -O "$TARBALL_FILE_NAME" "$LATEST_APTLY_RELEASE_URL"
          
          # Extract the artifact
          EXTRACT_FOLDER="/tmp/aptly_extraction"
          mkdir -pv "$EXTRACT_FOLDER"
          tar -xzvf "$TARBALL_FILE_NAME" --strip-components=1 -C "$EXTRACT_FOLDER"

          # Copy the extracted binary to the bin directory
          APTLY_DEST_PATH="$RUNNER_BIN_DIR/aptly"
          cp "$EXTRACT_FOLDER/aptly" "$APTLY_DEST_PATH"
          chmod +x "$APTLY_DEST_PATH"

          # Cleanup temporary files
          rm -rfv "$EXTRACT_FOLDER"
          rm -rfv "$TARBALL_FILE_NAME"

          # Verify the install
          aptly version

          # Createrepo
          sudo yum install -y createrepo_c

          # Verify the install
          createrepo_c --version

          # GPG >=2.2, required for both Aptly and createrepo
          # Amazon Linux 2 only has up to gpg 2.0.22 available for some reason despite being a decade old
          # See:
          # * https://stackoverflow.com/questions/72973055/static-install-gnupg2-gpg-version-2-3-6-on-amazon-linux-2
          # * https://stackoverflow.com/questions/72197579/how-to-upgrade-the-gpg-version-installed-on-aws-ec2
          # Unfortunately this really is the simplest solution until the base AMI is updated to the new version
          # of Amazon Linux.
          # Download the artifacts from CentOS 8 repos (rpm archive)
          RPM_DIR="/tmp/gpg_rpms"
          mkdir -pv "$RPM_DIR"

          WGET_URL_FILE="$RPM_DIR/wget_urls"
          cat <<EOF > "$WGET_URL_FILE"
          https://vault.centos.org/centos/8/BaseOS/x86_64/os/Packages/gnupg2-2.2.20-2.el8.x86_64.rpm
          https://vault.centos.org/centos/8/BaseOS/x86_64/os/Packages/libgcrypt-1.8.5-6.el8.x86_64.rpm
          https://vault.centos.org/centos/8/BaseOS/x86_64/os/Packages/readline-7.0-10.el8.x86_64.rpm
          https://vault.centos.org/centos/8/BaseOS/x86_64/os/Packages/libgpg-error-1.31-1.el8.x86_64.rpm
          https://vault.centos.org/centos/8/BaseOS/x86_64/os/Packages/npth-1.5-4.el8.x86_64.rpm
          https://vault.centos.org/centos/8/BaseOS/x86_64/os/Packages/libassuan-2.5.1-3.el8.x86_64.rpm
          EOF
          cat "$WGET_URL_FILE"
          wget -nv -P "$RPM_DIR/" -i "$WGET_URL_FILE"

          # Force install the artifact despite lots of missing dependencies and conflicts (if it works, it works)
          sudo rpm -i --nodeps --force "$RPM_DIR/*.rpm"

          # Cleanup temporary files
          rm -rfv "$RPM_DIR"

          # Stop the existing agent if running and start a new process with the new version
          pkill -9 gpg-agent || true
          source <(gpg-agent --daemon)

          # Verify the install
          gpg --version
      # Download the artifacts
      - name: Assume AWS role for downloading the artifacts
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-skip-session-tagging: true
          aws-region: us-west-2
          role-to-assume: ${{ vars.ARTIFACT_DOWNLOAD_AWS_ROLE }}
          role-session-name: "gha-oprt-artifact-download-${{ github.run_number }}"
          role-duration-seconds: 900
          # Given that the repo is private this should have a low security impact while making debugging easier
          mask-aws-account-id: false
      - name: Log the AWS role assumed
        run: aws sts get-caller-identity
      - name: Define the version number used in the artifact download key
        run: |
          echo "Setting artifact download version..."
          FULL_TAG="${{ inputs.artifact-tag }}"
          echo "ARTIFACT_DOWNLOAD_VERSION=${FULL_TAG#v}" | tee -a "$GITHUB_ENV"
      - name: Download artifacts to the download directory
        run: |
          echo "Creating download directory..."
          mkdir -pv "$DOWNLOAD_DIRECTORY"

          FILTER="${{ inputs.package-name-filter }}.${PACKAGE_TYPE}*"
          S3_PATH="s3://${{ vars.ARTIFACT_SOURCE_BUCKET }}/teleport/tag/${ARTIFACT_DOWNLOAD_VERSION}/"
          echo
          echo "Downloading files matching '$FILTER' from '$S3_PATH' to '$DOWNLOAD_DIRECTORY'..."
          aws s3 sync --no-progress --delete --exclude "*" --include "$FILTER" "$S3_PATH" "$DOWNLOAD_DIRECTORY"

          echo
          echo "Downloaded files:"
          ls -lAht "$DOWNLOAD_DIRECTORY"

          # Record packages for job summary
          echo "PACKAGES<<EOF" >> "$GITHUB_ENV"
          ls "$DOWNLOAD_DIRECTORY"/*.${PACKAGE_TYPE} >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"

          echo ""
          [ "$(ls -A "$DOWNLOAD_DIRECTORY")" ] && echo "Found $(ls -lA | wc -l) artifacts for $ARTIFACT_DOWNLOAD_VERSION" || (echo "No artifacts found for $ARTIFACT_DOWNLOAD_VERSION!"; exit 1)
      # Publish the package
      - name: Assume AWS role for deploying ${{ inputs.repo-type }} artifacts
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-skip-session-tagging: true
          aws-region: us-west-2
          role-to-assume: ${{ env.DEPLOYMENT_AWS_ROLE }}
          role-session-name: "gha-os-package-repo-tool-deploy-${{ github.run_number }}"
          role-duration-seconds: 3600  # 1 hour, the max that the Terraform module allows. DR takes a long time (6 hrs+) so this will cause DR to fail the first time.
          # Given that the repo is private this should have a low security impact while making debugging easier
          mask-aws-account-id: false
      - name: Log the AWS role assumed
        run: aws sts get-caller-identity
      - name: Setup GPG signing key
        uses: ./.github/actions/load-gpg-key
        with:
          gpg-signing-archive: ${{ secrets.GPG_SIGNING_ARCHIVE }}
          gnupghome: ${{ env.GNUPGHOME }}
      - name: Ensure the environment cache path exists
        run: |
          echo "Creating the ${{ inputs.environment }} environment cache path at $CACHE_PATH"
          mkdir -pv -m0770 "$CACHE_PATH"
          sudo chown -v "ec2-user:ec2-user" "$CACHE_PATH"

          # Clear out files to trigger DR
          # Do not uncomment this unless you know what you are doing!
          # rm -rf "$CACHE_PATH"/*
      - name: Publish the ${{ inputs.artifact-tag }} version artifacts to the ${{ inputs.repo-type }} repo in ${{ inputs.environment }} environment
        env:
          LOG_LEVEL: 4
        run: >
            "./$TOOL_BINARY_PATH" ${{ inputs.repo-type }}
            -bucket "$BUCKET_NAME"
            -local-bucket-path "$CACHE_PATH/bucket-contents"
            -version-channel "${{ inputs.version-channel }}"
            -release-channel "${{ inputs.release-channel }}"
            -artifact-path "$DOWNLOAD_DIRECTORY"
            -log-level "$LOG_LEVEL"
            $TOOL_ARGUMENTS # This is not quoted as it should be expanded by the shell
      - name: Log runner state post-job
        run: |
          # Log information that may have changed during job execution so that we can catch future issues before they happen
          echo "Disk info:"
          df -hT
      - name: Set job summary
        run: |
          PACKAGES=($PACKAGES)  # Turn into an array
          echo "### Uploaded ${#PACKAGES[@]} packages uploaded to ${{ inputs.release-channel }}/${{ inputs.version-channel }} \
            in ${{ inputs.repo-type }} repo stored in S3 bucket at $BUCKET_NAME" | tee -a "$GITHUB_STEP_SUMMARY"
          for package in "${PACKAGES[@]}"
          do
            echo "* $(basename "$package")" | tee -a "$GITHUB_STEP_SUMMARY"
          done
      - name: ${{ inputs.workflow-tag }}
        run: |
          # This is a do-nothing step so that agents calling this workflow can identify the run ID associated
          # with the run they started
  
  # These jobs are designed to be a very final test to verify that we didn't just publish a broken release
  # They are very much not a catch-all even of the few basic tests they run - but if they fail, something
  # is really broken.
  apt-debian-smoke-test:
    name: Test packages deployed to APT repo on Debian
    if: inputs.repo-type == 'apt' && inputs.package-to-test != ''
    needs: deploy
    runs-on: ubuntu-latest
    # A container is used here to maintain consistency in the testing methodology for both APT and YUM
    strategy:
      fail-fast: false
      matrix:
        # Multiple images are used to test for the ever recurring libc version issue
        container-image: ["ubuntu:22.04", "ubuntu:20.04", "ubuntu:18.04", "debian:10", "debian:11"]
    container:
      image: ${{ matrix.container-image }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Log package to test
        run: echo "${{ inputs.package-to-test }}"
      # Note: These values are intentionally hard-coded here to prevent false positives or negatives due
      #       to a value in one of our code/IaC repos changing without the change propegating everywhere.
      - name: Derive and set Github environment-specific variables for production
        if: inputs.environment == 'production' || inputs.environment == 'promote'
        run: |
          echo "APT_REPO_DOMAIN_NAME=apt.releases.teleport.dev" >> "$GITHUB_ENV"
      - name: Derive and set Github environment-specific variables for development
        if: inputs.environment == 'staging' || inputs.environment == 'build'
        run: |
          echo "APT_REPO_DOMAIN_NAME=apt.releases.development.teleport.dev" >> "$GITHUB_ENV"
      - name: Log set variables
        run: |
          echo "Set variables:"
          env
      - name: Setup for package install
        env:
          ARTIFACT_TAG: ${{ inputs.artifact-tag }}
        run: |
          # The container images are missing a couple of minor things needed for the install instructions
          # on the downloads page
          # sudo is not available in the image, so create a simple do-nothing script to replace it
          SUDO_PATH="/usr/bin/sudo"
          echo '$@' > "$SUDO_PATH"
          chmod +x "$SUDO_PATH"
          sudo echo "Running this with pseudo-sudo"

          # Install curl
          apt update
          apt install -y curl

          # Set the package version
          echo "PACKAGE_VERSION=${ARTIFACT_TAG#v}" >> "$GITHUB_ENV"
      - name: Install package
        env:
          RELEASE_CHANNEL: ${{ inputs.release-channel }}
          VERSION_CHANNEL: ${{ needs.deploy.outputs.component-version-channel }}
          PACKAGE_TO_TEST: ${{ inputs.package-to-test }}
        run: |
          # Install teleport based off of instructions from https://goteleport.com/docs/installation/#linux
          # This is designed to be changed as little as possible from the source
          sudo curl https://$APT_REPO_DOMAIN_NAME/gpg \
            -o /usr/share/keyrings/teleport-archive-keyring.asc
          source /etc/os-release
          echo "deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] \
            https://$APT_REPO_DOMAIN_NAME/${ID?} ${VERSION_CODENAME?} $RELEASE_CHANNEL/$VERSION_CHANNEL" \
            | sudo tee /etc/apt/sources.list.d/teleport.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y "$PACKAGE_TO_TEST=$PACKAGE_VERSION"
      - name: Log Teleport version
        run: teleport version
      - name: Log package cache information
        run: |
          apt-cache policy ${{ inputs.package-to-test }}
      - name: Verify installed Teleport version matches provided artifact version
        env:
          ARTIFACT_TAG: ${{ inputs.artifact-tag }}
        run: |
          REPORTED_VERSION=$(teleport version --raw)
          if [ "$REPORTED_VERSION" != "${ARTIFACT_TAG#v}" ]; then
            echo "Installed version ($REPORTED_VERSION) does not match uploaded artifact version (${ARTIFACT_TAG#v})!!!"
            exit 406  # Picking this number as Googling "error code 406" will show that it is a "not acceptable" error
          fi
  yum-rhel-smoke-test:
    name: Test packages deployed to YUM repo on RHEL
    if: inputs.repo-type == 'yum' && inputs.package-to-test != ''
    needs: deploy
    runs-on: ubuntu-latest
    # A container is used here to maintain consistency in the testing methodology for both APT and YUM
    strategy:
      fail-fast: false
      matrix:
        # Multiple images are used to test for the ever recurring libc version issue
        container-image: 
          - centos:7
          # These are the closest we can easily get to rhel 7/8/9
          - registry.access.redhat.com/ubi7:7.9
          - registry.access.redhat.com/ubi8:8.7
          - registry.access.redhat.com/ubi9:9.1
    container:
      image: ${{ matrix.container-image }}
    defaults:
      run:
        shell: bash
    steps:
      # Note: These values are intentionally hard-coded here to prevent false positives or negatives due
      #       to a value in one of our code/IaC repos changing without the change propegating everywhere.
      - name: Derive and set Github environment-specific variables for production
        if: inputs.environment == 'production' || inputs.environment == 'promote'
        run: |
          echo "YUM_REPO_DOMAIN_NAME=yum.releases.teleport.dev" >> "$GITHUB_ENV"
          echo "FORCE_INSTALL_PROD_PUBLIC_KEY=false" >> "$GITHUB_ENV"
      - name: Derive and set Github environment-specific variables for development
        if: inputs.environment == 'staging' || inputs.environment == 'build'
        run: |
          echo "YUM_REPO_DOMAIN_NAME=yum.releases.development.teleport.dev" >> "$GITHUB_ENV"
          # This is required as the RPMs are signed by the prod key, not the dev key
          # Without this yum will fail due to a signing key mismatch
          echo "FORCE_INSTALL_PROD_PUBLIC_KEY=true" >> "$GITHUB_ENV"
      - name: Log set variables
        run: |
          echo "Set variables:"
          env
      - name: Setup for package install
        env:
          ARTIFACT_TAG: ${{ inputs.artifact-tag }}
        run: |
          # The container images are missing a couple of minor things needed for the install instructions
          # on the downloads page
          # sudo is not available in the image, so create a simple do-nothing script to replace it
          SUDO_PATH="/usr/bin/sudo"
          echo '$@' > "$SUDO_PATH"
          chmod +x "$SUDO_PATH"
          sudo echo "Running this with pseudo-sudo"

          # Install yum-utils for yum-config-manager
          yum install -y yum-utils

          # Add the prod signing key specifically if required in a dev context to deal with prod-signed RPMs
          if $FORCE_INSTALL_PROD_PUBLIC_KEY; then
            rpm --import https://yum.releases.teleport.dev/gpg
          fi

          # Set the package version
          echo "PACKAGE_VERSION=$(echo "${ARTIFACT_TAG#v}" | sed 's/-/_/g')" >> "$GITHUB_ENV"
      - name: Install package
        env:
          RELEASE_CHANNEL: ${{ inputs.release-channel }}
          VERSION_CHANNEL: ${{ needs.deploy.outputs.component-version-channel }}
          PACKAGE_TO_TEST: ${{ inputs.package-to-test }}
        run: |
          # Install teleport based off of instructions from https://goteleport.com/docs/installation/#linux
          # This is designed to be changed as little as possible from the source
          source /etc/os-release

          # The UBI images use a slightly different from normal format for VERSION_ID so it must be accounted for here
          VERSION_ID=$(echo $VERSION_ID | cut -d'.' -f1)

          sudo yum-config-manager --add-repo $(rpm --eval "https://${YUM_REPO_DOMAIN_NAME}/$ID/$VERSION_ID/Teleport/%{_arch}/$RELEASE_CHANNEL/$VERSION_CHANNEL/teleport.repo")
          sudo yum install -y "$PACKAGE_TO_TEST-$PACKAGE_VERSION"
      - name: Log Teleport version
        run: teleport version
      - name: Log package cache information
        run: |
          yum --showduplicates list available ${{ inputs.package-to-test }}
      - name: Verify installed Teleport version matches provided artifact version
        env:
          ARTIFACT_TAG: ${{ inputs.artifact-tag }}
        run: |
          REPORTED_VERSION=$(teleport version --raw)
          if [ "$REPORTED_VERSION" != "${ARTIFACT_TAG#v}" ]; then
            echo "Installed version ($REPORTED_VERSION) does not match uploaded artifact version (${ARTIFACT_TAG#v})!!!"
            exit 406  # Picking this number as Googling "error code 406" will show that it is a "not acceptable" error
          fi
