name: Flaky Integration Tests Detector
run-name: Flaky Integration Tests Detector - ${{ github.run_id }} - @${{ github.actor }}

on:
  pull_request:

permissions:
  pull-requests: read
  issues: read

jobs:
  flaky-test:
    name: Flaky Integration Tests Detector
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-22.04-16core

    permissions:
      contents: read
      packages: read

    container:
      image: ghcr.io/gravitational/teleport-buildbox:teleport19
      options: --cap-add=SYS_ADMIN --privileged

    steps:
      - name: Checkout Teleport
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        with:
          oss-teleport-ref: ${{ github.base_ref }}
          edition: enterprise
          ent-teleport-ref: ${{ github.event.pull_request.head.ref }}
          ent-fetch-depth: 0

      - name: Generate GitHub Token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.REVIEWERS_APP_ID }}
          private-key: ${{ secrets.REVIEWERS_PRIVATE_KEY }}

      - name: Checkout shared-workflows
        uses: actions/checkout@v4
        with:
          repository: gravitational/shared-workflows
          path: .github/shared-workflows
          ref: 664e788d45a7f56935cf63094b4fb52a41b12015 # workflows/v0.0.2

      - name: Find excluded tests
        id: find_excluded
        run: cd .github/shared-workflows/bot && go run main.go -workflow=exclude-flakes -token="${{ steps.generate_token.outputs.token }}" -reviewers="${{ secrets.reviewers }}"

      - name: Run tests/integration difftest
        uses: ./.github/actions/difftest
        with:
          flags: --skip="${{ steps.find_excluded.outputs.FLAKE_SKIP }}"  --include "tests/integration/**/*"
          target: test-go-integration INTEGRATION_TEST_TIMEOUT=40m
          attempts: 40
          path: .
          directory: e
