name: Lint

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04-16core

    permissions:
      contents: read

    container:
      image: ghcr.io/gravitational/teleport-buildbox:teleport14
      env:
        GO_LINT_FLAGS: --timeout=30m

    steps:
      - name: Checkout OSS Teleport
        uses: actions/checkout@v4
        with:
          repository: gravitational/teleport  # This may need to be updated
          ref: ${{ github.base_ref }}

      - name: Checkout Enterprise Teleport
        uses: actions/checkout@v4
        with:
          path: e

      - name: Mark paths as safe
        run: git config --global --add safe.directory $( realpath . )

      - uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: latest
          skip-cache: true
