# Scheduled jobs only run from the main branch (master).
# This worfklow is not invoked from branches so should be ignored for those.
name: Nightly Release Run
on:
  schedule:
    # This should be coordinated with weekly AMI cleanups so that releases are (usually)
    # avoided when the AMI cleanup is running.
    - cron: "0 8 * * *" # At 0800 UTC every day (12am/1am PST/PDT)
    - cron: "0 10 * * *" # At 1000 UTC every day
    - cron: "0 12 * * *"
    - cron: "0 14 * * *"
jobs:
  release:
    permissions:
      contents: read
      actions: write # Required to start the release workflow
    runs-on: ubuntu-latest
    env:
      BRANCH: >-
        ${{
          github.event.schedule == '0 8 * * *' && 'branch/v18' ||
          github.event.schedule == '0 10 * * *' && 'branch/v17' ||
          github.event.schedule == '0 12 * * *' && 'branch/v16' ||
          'master'
        }}
    steps:
      - name: Checkout Teleport - ${{ env.BRANCH }}
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        with:
          oss-teleport-repo: "gravitational/teleport"
          oss-teleport-ref: ${{ env.BRANCH }}
          edition: "oss"
          repo-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
          repo-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}
      # Get the VERSION defined in Makefile and add nightly prelease suffix
      # .outputs.version: The resulting full version to use for overriding default version.
      - name: Generate Version - ${{ env.BRANCH }}
        id: gen-version
        run: |
          MAKE_VERSION=$(make print-version)
          DATE="$(date '+%Y%m%d')"
          REF="$(git rev-parse --short HEAD)"
          echo "version=$MAKE_VERSION-nightly$DATE-1-$REF" >> "$GITHUB_OUTPUT"
      - name: Release - ${{ env.BRANCH }}
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{ steps.gen-version.outputs.version }}
          SLACK_NOTIFY_CHANNEL: C0DF0TPMY # dev-teleport channel
        run: |
          gh workflow run tag-release.yaml \
            --repo gravitational/teleport.e \
            --ref "${BRANCH}" \
            -f "oss-teleport-repo=gravitational/teleport" \
            -f "oss-teleport-ref=${BRANCH}" \
            -f "teleport-version=${VERSION}" \
            -f "cloud-only=false" \
            -f "slack-notify-channel=${SLACK_NOTIFY_CHANNEL}" \
            -f "environment=stage"
