# Scheduled jobs only run from the main branch (master).
# This worfklow is not invoked from branches so should be ignored for those.
name: Nightly Release Run
on:
  schedule:
    - cron: "0 10 * * *" # At 1000 UTC every day (2am/3am PST/PDT)
jobs:
  release:
    permissions:
      contents: read
      actions: write # Required to start the release workflow
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - branch/v15
          - branch/v16
          - master
          # The branch for the next release.
          # As part of the preflight process this should be uncommented to prepare
          # nightly builds for prereleases of a new release. Once the new version has
          # fully released, this should be bumped to the next release and commented out.
          - branch/v17
    steps:
      - name: Checkout Teleport
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        with:
          oss-teleport-repo: "gravitational/teleport"
          oss-teleport-ref: ${{ matrix.branch }}
          edition: "oss"
          repo-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
          repo-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}
      # Get the VERSION defined in Makefile and add nightly prelease suffix
      # .outputs.version: The resulting full version to use for overriding default version.
      - name: Generate Version
        id: gen-version
        run: |
          MAKE_VERSION=$(make print-version)
          DATE="$(date '+%Y%m%d')"
          REF="$(git rev-parse --short HEAD)"
          echo "version=$MAKE_VERSION-nightly$DATE-1-$REF" >> "$GITHUB_OUTPUT"
      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
          BRANCH: ${{ matrix.branch }}
          VERSION: ${{ steps.gen-version.outputs.version }}
          SLACK_NOTIFY_CHANNEL: C0DF0TPMY # dev-teleport channel
        run: |
          gh workflow run tag-release.yaml \
            --repo gravitational/teleport.e \
            --ref "${BRANCH}" \
            -f "oss-teleport-repo=gravitational/teleport" \
            -f "oss-teleport-ref=${BRANCH}" \
            -f "teleport-version=${VERSION}" \
            -f "cloud-only=false" \
            -f "slack-notify-channel=${SLACK_NOTIFY_CHANNEL}" \
            -f "environment=stage"
