name: Promote Docker image
on:
  workflow_call:
    inputs:
      pending-registry:
        description: |
          The address of the pending image registry 
        required: true
        type: string

      pending-repository:
        description: |
          The namespace and repository name holding the pending image
        required: true
        type: string

      pending-tag:
        description: |
          Tag or digest identifying the pending image (or image list) to
          promote from the pending repository
        required: true
        type: string

      production-registry:
        description: |
          The registry that will receive the production image
        required: true
        type: string

      production-registry-region:
        description: |
          The AWS region containing the production registry
        required: true
        type: string

      production-repository:
        description: |
          The namespace and name of the repository that will receive the
          promoted image
        required: true
        type: string

      production-tags:
        description: |
          Space-delimited list of tags to give the released image
        required: true
        type: string

      promotion-role-arn:
        description: |
          ARN of the role that grants promotion rights
        required: true
        type: string

      validation-key-url:
        description: |
          URL of the key used to validate internal Teleport images, in the
          format expected by `cosign`.
        required: true
        type: string

      production-signing-key-url:
        description: |
          URL of the key used to sign the production images as Official
          Teleport images, in the format expected by `cosign`.
        required: true
        type: string

run-name: "Promote OCI image ${{ inputs.pending-repository }}:${{ inputs.pending-tag }}"

jobs:
  promote-image: 
    name: "Promote ${{ inputs.pending-tag }}"
    runs-on: ubuntu-latest
    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@1fc5bd396d372bee37d608f955b336615edf79c8 # v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
       
      - name: Assume AWS Promotion Role
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          aws-region:  us-west-2
          role-to-assume: ${{ inputs.promotion-role-arn }}
          role-session-name: "gha-oci-image-promote-${{ github.run_number }}"
          # Promotion should take roughly a minute, so 15 mins gives us plenty
          # of leeway (and is the miminum value we can ask for).
          role-duration-seconds: 900
     
      - name: Login to Pending ECR Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.pending-registry }}

      - name: Validate pending image signature using signing key and GitHub OIDC Token
        env:
          CERT_IDENTITY_REGEXP: 'https://github\.com/gravitational/teleport\.e/\.github/workflows/oci-image-build\.yml@refs/tags/.+'
          CERT_OIDC_ISSUER: "https://token.actions.githubusercontent.com/teleport"
          SIGNING_KEY_URL: "${{ inputs.validation-key-url }}"
          SRC_IMAGE: "${{ inputs.pending-registry }}/${{ inputs.pending-repository }}:${{ inputs.pending-tag }}"
        run: |
          cosign verify --key ${SIGNING_KEY_URL} ${SRC_IMAGE} > validated-image.json
          # TODO(reed): Re-enable OIDC identity verification when signature is attached
          # cosign verify ${SRC_IMAGE} --certificate-identity-regexp="${CERT_IDENTITY_REGEXP}" --certificate-oidc-issuer="${CERT_OIDC_ISSUER}"
          TELEPORT_IMAGE_LIST_HASH=$(jq -r '.[0].critical.image."docker-manifest-digest"' validated-image.json)
          echo TELEPORT_IMAGE_LIST_HASH=$TELEPORT_IMAGE_LIST_HASH >> $GITHUB_ENV

      # From this point we should only refer to the source image by digest rather 
      # than by tag. Referring to an image by tag across multiple operations is 
      # racy, as someone could retag the image underneath us while we're busy.
      #
      # In practice, all of our `pending` repositories are ECR repos with tag
      # immutability enabled so this shouldn't happen, but better to have 
      # defence in depth.

      - name: Login to Production ECR Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.production-registry }}
        env:
          AWS_REGION: ${{ inputs.production-registry-region }}
          DEFAULT_AWS_REGION: ${{ inputs.production-registry-region }}

      - name: Copy multiarch image to production repository
        shell: bash
        run: |
          SRC_IMAGE="${{ inputs.pending-registry }}/${{ inputs.pending-repository }}@${{ env.TELEPORT_IMAGE_LIST_HASH }}"
          DST_REPO="${{ inputs.production-registry }}/${{ inputs.production-repository }}"
          for tag in ${{ inputs.production-tags }}; do
            docker buildx imagetools create --tag $DST_REPO:$tag $SRC_IMAGE
          done

      - name: Sign production images using signing key and GitHub OIDC Token
        env:
          SIGNING_KEY_URL: ${{ inputs.production-signing-key-url }}
          DST_IMAGE: "${{ inputs.production-registry }}/${{ inputs.production-repository }}@${{ env.TELEPORT_IMAGE_LIST_HASH }}"
        run: |
          # TODO(reed): TLog uploads temporarily disabled due to https://github.com/sigstore/cosign/issues/3356.
          cosign sign --yes --tlog-upload=false --key ${SIGNING_KEY_URL} --recursive ${DST_IMAGE}
          cosign sign --yes --upload=false --tlog-upload=false --recursive ${DST_IMAGE}
