name: Build Docker image
on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: "The name of the OSS teleport repo to checkout"
        required: false
        type: string

      oss-teleport-ref:
        description: 'Git SHA, tag or branch of the revision of OSS teleport to build'
        required: true
        type: string

      source-tag:
        description: "The semver version tag of the Teleport revision that we're building."
        required: true
        type: string

      base-image:
        description: "The base image to be used when building the docker image"
        required: true
        type: string

      dest-image-registry:
        description: "The destination image registry"
        required: true
        type: string

      dest-image-registry-region:
        description: "AWS region containing the destination repository"
        type: string
        default: us-west-2

      dest-image-repo:
        description: "The destination image repository (omitting tag)"
        required: true
        type: string

      dest-image-tags:
        description: |
          Space separated list of tags for the destination image
        required: false
        type: string

      teleport-release:
        description: |
          The release of teleport to include on the image. Must be either `oss`
          `enterprise`, or `fips`
        required: true
        type: string

      teleport-version:
        description: |
          Teleport version used for constructing the debian package filename. Must
          not include a leading `v` in the version tag.
        required: true
        type: string

      dronestorage-access-role-arn:
        description: |
          ARN of the role used to access the dronestorage bucket, for retreiving
          artefacts built by Drone. This is required only when
          inputs.dronestorage-bucket-name is set.
        required: false
        type: string

      dronestorage-bucket-name:
        description: |
          Name of the dronestorage bucket holding the debian package artifacts
          built by Drone. This is required only when building the main teleport
          image because it fetches build artifacts from drone. The workflow will
          skip the package download steps when the input is not provided.
        required: false
        type: string

      build-role-arn:
        description: |
          ARN of the AWS role to assume for storing and signing the OCI
          container images
        required: true
        type: string

      signing-key-url:
        description: |
          URL of AWS KMS key to use when signing the resulting image
        type: string
        required: true

      image-build-args:
        description: |
          An optional string containing arbitrary extra build args to be passed
          to `docker buildx build`. Formatted as a newline-separated list, as
          per https://github.com/marketplace/actions/docker-setup-buildx#inputs
        type: string
        required: false

      image-build-context:
        description: |
          Newline-separated list of paths containing the files that
          must be copied into the build directory. When not specified, defaults
          to './teleport/build.assets/charts/.'. This is used to build images
          for Teleport integrations. Wildcards are not supported. To copy a the
          content of a directory, use the `./dir/.` notation.
        type: string
        default: |
          ./teleport/build.assets/charts/.

      image-build-dockerfile:
        description: |
          An optional file path pointing to the Dockerfile to use. The path is
          relative to the build context specified in inputs.
        type: string
        default: "Dockerfile-distroless"

      scan-image:
        description: |
          Should the resulting image be run through the `trivy` scanner as part
          of the build? Only turn this off if you know that the image will be
          automatically scanned in some other way.
        type: boolean
        default: true

      skip-base-image-verify:
        description: |
          Should the verification of the signature of the base image be skipped?
          Only turn this off if it is not possible to verify the signature of a
          base image (e.g it is not signed).
        type: boolean
        default: false

      allow-overwrites:
        description: |
          Allow this script to overwrite any tags in the destination image. If
          set to false, thie image will not be rebuilt and signed if the
          workflow detects that any of the requested tags exists in the
          destination repository, but the build will still succeed.
        type: boolean
        default: true

      architectures:
        description:
          A newline-separated list of the CPU architectures to build for
        type: string
        default: |
          arm64
          amd64

    secrets:
      deploy-access-app-id:
        description: |
          The ID of the GitHub app used to grant deployment access for repos
          to the workflow.
        required: true

      deploy-access-app-key:
        description: |
          The private key used to authenticate against the deployment access
          GitGub app.
        required: true

run-name: "Rebuilding ${{ inputs.dest-image-repo }}"

jobs:
  build-docker-image:
    name: Build Multiarch OCI image
    runs-on: ubuntu-22.04-16core
    environment: staging
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-built: ${{ steps.check.outputs.build_image }}
    env:
      BASE_IMAGE: ${{ inputs.base-image }}
    steps:
      - name: Configure environment
        env:
          TELEPORT_RELEASE: ${{ inputs.teleport-release }}
        run: |
          DEB_RELEASE_INFIX=""
          DEB_FIPS_INFIX=""
          case "$TELEPORT_RELEASE" in
            "oss")
              ;;

            "enterprise")
              DEB_RELEASE_INFIX="-ent"
              ;;

            "fips")
              DEB_RELEASE_INFIX="-ent"
              DEB_FIPS_INFIX="-fips"
              ;;

            *)
              echo "Unsupported release type: $TELEPORT_RELEASE"
              exit 1
              ;;
          esac
          echo "DEB_RELEASE_INFIX=$DEB_RELEASE_INFIX" >> $GITHUB_ENV
          echo "DEB_FIPS_INFIX=$DEB_FIPS_INFIX" >> $GITHUB_ENV

      - name: Set up Docker QEMU integration
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
        with:
          driver: docker-container

      - name: Install cosign
        uses: sigstore/cosign-installer@1fc5bd396d372bee37d608f955b336615edf79c8 # v3.2.0

      # Attempt to fetch a deploy token from the GitHub App we use to broker
      # access to private repositories. If this fails, we are in one of 2
      # situations:
      #
      # 1. The App is not installed on the target repo (e.g. public Teleport), or
      # 2. Something is wrong with GitHub
      #
      # In either case, the workflow will carry on and attempt to use the
      # default workflow token to check out the target repo, which will be
      # fine if that repo is public.
      #
      - name: Fetch GitHub deploy token
        uses: actions/create-github-app-token@v1
        id: fetch-token
        continue-on-error: true
        with:
          app-id: ${{ secrets.deploy-access-app-id }}
          private-key: ${{ secrets.deploy-access-app-key }}
          repositories: ${{ inputs.oss-teleport-repo }}

      - name: Select GitHub deploy token
        id: select-deploy-token
        run: |
          TOKEN=${{ github.token }}
          if [[ -n "${{ steps.fetch-token.outputs.token }}" ]]; then
            TOKEN=${{ steps.fetch-token.outputs.token }}
          fi
          echo oss_teleport=$TOKEN >> $GITHUB_OUTPUT

      - name: Checkout OSS Teleport
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.oss-teleport-repo }}
          ref: ${{ inputs.oss-teleport-ref }}
          token: ${{ steps.select-deploy-token.outputs.oss_teleport }}
          path: ./teleport

      - name: Copy Docker Image context
        run: |
          mkdir ./build
          echo "${{ inputs.image-build-context }}" | xargs -I '{}' cp -r '{}' ./build
          tree ./build

      - name: Assume Legacy Drone storage AWS role
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        if: inputs.dronestorage-bucket-name != ''
        with:
          aws-region:  us-west-2
          role-to-assume: ${{ inputs.dronestorage-access-role-arn }}
          role-session-name: "gha-oci-image-build-${{ github.run_number }}-${{ inputs.source-tag }}"
          role-duration-seconds: 3600

      - name: Download Teleport Debian packages
        if: inputs.dronestorage-bucket-name != ''
        env:
          ARCHITECTURES: ${{ inputs.architectures }}
          TELEPORT_VERSION: ${{ inputs.teleport-version }}
          DST_BUCKET: ${{ inputs.dronestorage-bucket-name }}
        run: |
          for arch in $ARCHITECTURES; do
            export TELEPORT_DEB_FILE_NAME=teleport${DEB_RELEASE_INFIX}_${TELEPORT_VERSION}${DEB_FIPS_INFIX}_${arch}.deb
            aws s3 cp s3://${DST_BUCKET}/teleport/tag/${TELEPORT_VERSION}/${TELEPORT_DEB_FILE_NAME} ./build/${TELEPORT_DEB_FILE_NAME}
          done
          tree ./build

      - name: Verify base image
        if: ${{ !inputs.skip-base-image-verify }}
        env:
          CERT_IDENTITY: "keyless@distroless.iam.gserviceaccount.com"
          CERT_OIDC_ISSUER: "https://accounts.google.com"
        run: |
          cosign verify ${BASE_IMAGE} --certificate-oidc-issuer="${CERT_OIDC_ISSUER}" --certificate-identity="${CERT_IDENTITY}" > validated-image.json
          BASE_IMAGE_HASH=$(jq -r '.[0].critical.image."docker-manifest-digest"' validated-image.json)
          # Pin base image to verified hash
          echo "BASE_IMAGE=${BASE_IMAGE}@${BASE_IMAGE_HASH}" >> "$GITHUB_ENV"

      - name: Expand platform names
        id: platforms
        env:
          ARCHITECTURES: ${{ inputs.architectures }}
        run: |
          EOF=END_OF_PLATFORMS
          echo "platforms<<$EOF" >> $GITHUB_OUTPUT
          for a in $ARCHITECTURES; do
            echo "linux/$a" >> $GITHUB_OUTPUT
          done
          echo $EOF >> $GITHUB_OUTPUT

      - name: Expand image tags
        id: expand
        env:
          DST_IMAGE_TAGS: ${{ inputs.dest-image-tags }}
          DST_IMAGE_REPO: "${{ inputs.dest-image-registry }}/${{ inputs.dest-image-repo }}"
        run: |
          EOF=END_OF_TAGS
          echo "tags<<$EOF" >> $GITHUB_OUTPUT
          for TAG in ${DST_IMAGE_TAGS}; do
            echo "${DST_IMAGE_REPO}:${TAG}" >> $GITHUB_OUTPUT
          done
          echo $EOF >> $GITHUB_OUTPUT

      - name: Assume Build AWS role
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          aws-region:  us-west-2
          role-to-assume: ${{ inputs.build-role-arn }}
          role-session-name: "gha-oci-image-build-${{ github.run_number }}"
          role-duration-seconds: 3600

      - name: Login to Destination ECR Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ inputs.dest-image-registry }}
          ecr: true
        env:
          AWS_REGION: ${{ inputs.dest-image-registry-region }}

      - name: Check if building would overwrite destination tag
        id: check
        env:
          TAGS: ${{ steps.expand.outputs.tags }}
        run: |
          build_image=true
          if ${{ inputs.allow-overwrites }}; then
              echo "Overwrites allowed. Skipping existence test."
          else
              for tag in ${TAGS}; do
                  echo "Checking for: ${tag}"
                  if docker buildx imagetools inspect ${tag} > /dev/null ; then
                      echo "found"
                      build_image=false
                      break
                  fi
              done
          fi
          echo build_image=${build_image} >> $GITHUB_OUTPUT

      - name: Build Docker image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        id: build
        if: steps.check.outputs.build_image == 'true'
        with:
          file: "./build/${{ inputs.image-build-dockerfile }}"
          context: ./build
          platforms: ${{ steps.platforms.outputs.platforms }}
          push: true
          tags: ${{ steps.expand.outputs.tags }}
          sbom: true
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            TELEPORT_RELEASE_INFIX=${{ env.DEB_RELEASE_INFIX }}
            ${{ inputs.image-build-args }}

      - name: Sign image using signing key and GitHub OIDC Token
        if: steps.check.outputs.build_image == 'true'
        env:
          SIGNING_KEY_URL: ${{ inputs.signing-key-url }}
          DST_IMAGE: "${{ inputs.dest-image-registry }}/${{ inputs.dest-image-repo }}@${{ steps.build.outputs.digest }}"
        run: |
          cosign sign --yes --key ${SIGNING_KEY_URL} --recursive ${DST_IMAGE}
          cosign sign --yes --upload=false --recursive ${DST_IMAGE}

  trivy-scan:
    name: Scan Multiarch Image with Trivy
    if: inputs.scan-image && (needs.build-docker-image.outputs.image-built == 'true')
    runs-on: ubuntu-latest
    needs: build-docker-image
    environment: staging
    steps:
      - name: Assume tag build AWS role
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          aws-region:  us-west-2
          role-to-assume: ${{ inputs.build-role-arn }}
          role-session-name: "gha-oci-image-build-${{ github.run_number }}-trivy"
          role-duration-seconds: 3600

      - name: Login to ECR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ inputs.dest-image-registry }}
        env:
          AWS_REGION: ${{ inputs.dest-image-registry-region }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@2b6a709cf9c4025c5438138008beaddbb02086f0 # v0.14.0
        with:
          image-ref: "${{ inputs.dest-image-registry }}/${{ inputs.dest-image-repo }}@${{ needs.build-docker-image.outputs.image-digest }}"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
