---
name: Publish Docker image
on:
  workflow_call:
    inputs:
      repository:
        description: |
          The name of the repository that the image should be pulled from, and
          pushed to. Example: `teleport-ent-distroless`
        required: true
        type: string

      pending-tag:
        description: |
          Tag or digest identifying the pending image (or image list) to
          publish from the pending repository
        required: true
        type: string

      production-tags:
        description: |
          Space-delimited list of tags to give the released image
        required: true
        type: string

      environment:
        description: GitHub environment to publish to.
        type: string
        default: stage/publish

run-name: "Publish OCI image ${{ inputs.repository }}:${{ inputs.pending-tag }}"

jobs:
  publish-image:
    name: "Publish ${{ inputs.repository }} image"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: .environments

      - name: Load environment values
        uses: gravitational/shared-workflows/tools/env-loader@e28b4323d6c036f904996b9a4a77578e52560570 # tools/env-loader/v0.0.5
        with:
          tool-version: v0.0.5
          environment-name: ${{ inputs.environment }}
          value-sets: oci

      - name: Set source and destination repos
        env:
          REPOSITORY_NAME: ${{ inputs.repository }}
        run: |
          {
            echo "SRC_REPO=${ECR_PENDING_REPO_BASE}/${REPOSITORY_NAME}"
            echo "DST_REPO=${OCI_PUBLIC_REPO_BASE}/${REPOSITORY_NAME}"
          } >> "${GITHUB_ENV}"

      - name: Install cosign
        uses: sigstore/cosign-installer@398d4b0eeef1380460a10c8013a76f728fb906ac # v3.9.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
        with:
          driver: docker-container

      - name: Assume AWS Pending ECR Pull Role
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          aws-region: us-west-2
          role-to-assume: ${{ env.ECR_OCI_PENDING_PULL_ROLE_ARN }}
          role-session-name: "gha-oci-image-publish-download-${{ github.run_id }}-${{ github.job }}-${{ github.run_attempt }}"
          role-duration-seconds: 900

        # Even after changing AWS roles, the docker daemon should still be able to use these credentials
        # until they expire.
      - name: Login to Pending ECR Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.ECR_PENDING_REPO_BASE }}

      - name: Validate pending image signature using signing key and GitHub OIDC Token
        env:
          CERT_IDENTITY_REGEXP: 'https://github\.com/gravitational/teleport\.e/\.github/workflows/oci-image-build\.yml@refs/tags/.+'
          CERT_OIDC_ISSUER: "https://token.actions.githubusercontent.com/teleport"
          SIGNING_KEY_ARN: "${{ env.OCI_PENDING_SIGNING_KEY_ARN }}"
          SRC_IMAGE_TAG: "${{ env.SRC_REPO }}:${{ inputs.pending-tag }}"
        run: |
          cosign verify --key "awskms:///${SIGNING_KEY_ARN}" "${SRC_IMAGE_TAG}" > validated-image.json
          # TODO(reed): Re-enable OIDC identity verification when signature is attached
          # cosign verify ${SRC_IMAGE_TAG} --certificate-identity-regexp="${CERT_IDENTITY_REGEXP}" --certificate-oidc-issuer="${CERT_OIDC_ISSUER}"
          TELEPORT_IMAGE_LIST_HASH=$(jq -r '.[0].critical.image."docker-manifest-digest"' validated-image.json)
          echo "TELEPORT_IMAGE_LIST_HASH=$TELEPORT_IMAGE_LIST_HASH" >> "$GITHUB_ENV"

      - name: Assume AWS ECR Push Role
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          aws-region: us-west-2
          role-to-assume: ${{ env.ECR_OCI_PUSH_ROLE_ARN }}
          role-session-name: "gha-oci-image-publish-upload-${{ github.run_id }}-${{ github.job }}-${{ github.run_attempt }}"
          role-duration-seconds: 900

      - name: Login to Production ECR Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          # Don't use `env.OCI_PUBLIC_REPO_BASE` here due to a bug with the login action.
          # The login action checks to see if the registry is exactly equal to `public.ecr.aws`,
          # and defaults to private if `registry` contains the registry name (despite being still
          # being a valid value). For details, see:
          # https://github.com/docker/login-action/blob/e92390c5fb421da1463c202d546fed0ec5c39f20/src/aws.ts#L15
          registry: public.ecr.aws
        env:
          # Public ECR _always_ uses this region
          AWS_REGION: us-east-1

      - name: Jitter to spread out image pushes
        # Sleep for a random amount of seconds between 0 and 59 seconds
        # This is to spread out the images pushed to avoid hitting the ECR rate limit
        run: sleep $((RANDOM % 60))

      - name: Copy multiarch image to production repository
        env:
          PRODUCTION_TAGS: ${{ inputs.production-tags }}
        run: |
          SRC_IMAGE_HASH="${SRC_REPO}@${TELEPORT_IMAGE_LIST_HASH}"
          read -ra DST_TAGS <<<"${PRODUCTION_TAGS}"
          for DST_TAG in "${DST_TAGS[@]}"; do
            docker buildx imagetools create --tag "$DST_REPO:$DST_TAG" "$SRC_IMAGE_HASH"
          done

      - name: Sign production images using signing key and GitHub OIDC Token
        env:
          SIGNING_KEY_ARN: ${{ env.OCI_PUBLIC_SIGNING_KEY_ARN }}
        run: |
          DST_IMAGE_HASH="${DST_REPO}@${TELEPORT_IMAGE_LIST_HASH}"
          cosign sign --yes --key "awskms:///${SIGNING_KEY_ARN}" --recursive "${DST_IMAGE_HASH}"
          cosign sign --yes --upload=false --recursive "${DST_IMAGE_HASH}"
