---
name: Publish Docker image
on:
  workflow_call:
    inputs:
      repository:
        description: |
          The name of the repository that the image should be pulled from, and
          pushed to. Example: `teleport-ent-distroless`
        required: true
        type: string

      pending-tag:
        description: |
          Tag or digest identifying the pending image (or image list) to
          publish from the pending repository
        required: true
        type: string

      production-tags:
        description: |
          Space-delimited list of tags to give the released image
        required: true
        type: string

      environment:
        description: GitHub environment to publish to.
        type: string
        default: publish-stage

run-name: "Publish OCI image ${{ inputs.repository }}:${{ inputs.pending-tag }}"

jobs:
  publish-image:
    name: "Publish ${{ inputs.repository }} image"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      DST_REPO: '${{ vars.OCI_PUBLIC_REPO_BASE }}/${{ inputs.repository }}'
      SRC_REPO: "${{ vars.ECR_PENDING_REPO_BASE }}/${{ inputs.repository }}"
    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@4959ce089c160fddf62f7b42464195ba1a56d382 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
        with:
          driver: docker-container

      - name: Assume AWS Pending ECR Pull Role
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: us-west-2
          role-to-assume: ${{ vars.ECR_OCI_PENDING_PULL_ROLE_ARN }}
          role-session-name: "gha-oci-image-publish-download-${{ github.run_number }}"
          role-duration-seconds: 900

        # Even after changing AWS roles, the docker daemon should still be able to use these credentials
        # until they expire.  
      - name: Login to Pending ECR Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ vars.ECR_PENDING_REPO_BASE }}

      - name: Validate pending image signature using signing key and GitHub OIDC Token
        env:
          CERT_IDENTITY_REGEXP: 'https://github\.com/gravitational/teleport\.e/\.github/workflows/oci-image-build\.yml@refs/tags/.+'
          CERT_OIDC_ISSUER: "https://token.actions.githubusercontent.com/teleport"
          SIGNING_KEY_ARN: "${{ vars.OCI_PENDING_SIGNING_KEY_ARN }}"
          SRC_IMAGE_TAG: "${{ env.SRC_REPO }}:${{ inputs.pending-tag }}"
        run: |
          cosign verify --key "awskms:///${SIGNING_KEY_ARN}" "${SRC_IMAGE_TAG}" > validated-image.json
          # TODO(reed): Re-enable OIDC identity verification when signature is attached
          # cosign verify ${SRC_IMAGE_TAG} --certificate-identity-regexp="${CERT_IDENTITY_REGEXP}" --certificate-oidc-issuer="${CERT_OIDC_ISSUER}"
          TELEPORT_IMAGE_LIST_HASH=$(jq -r '.[0].critical.image."docker-manifest-digest"' validated-image.json)
          echo "TELEPORT_IMAGE_LIST_HASH=$TELEPORT_IMAGE_LIST_HASH" >> "$GITHUB_ENV"

      - name: Assume AWS ECR Push Role
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: us-west-2
          role-to-assume: ${{ vars.ECR_OCI_PUSH_ROLE_ARN }}
          role-session-name: "gha-oci-image-publish-upload-${{ github.run_number }}"
          role-duration-seconds: 900

      - name: Login to Production ECR Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          # Don't use `vars.OCI_PUBLIC_REPO_BASE` here due to a bug with the login action.
          # The login action checks to see if the registry is exactly equal to `public.ecr.aws`,
          # and defaults to prvite if `registry` contains the registry name (despite being still
          # being a valid value). For details, see:
          # https://github.com/docker/login-action/blob/e92390c5fb421da1463c202d546fed0ec5c39f20/src/aws.ts#L15
          registry: public.ecr.aws
        env:
          # Public ECR _always_ uses this region
          AWS_REGION: us-east-1

      - name: Copy multiarch image to production repository
        env:
          PRODUCTION_TAGS: ${{ inputs.production-tags }}
        run: |
          SRC_IMAGE_HASH="${SRC_REPO}@${TELEPORT_IMAGE_LIST_HASH}"
          read -ra DST_TAGS <<<"${PRODUCTION_TAGS}"
          for DST_TAG in "${DST_TAGS[@]}"; do
            docker buildx imagetools create --tag "$DST_REPO:$DST_TAG" "$SRC_IMAGE_HASH"
          done

      - name: Sign production images using signing key and GitHub OIDC Token
        env:
          SIGNING_KEY_ARN: ${{ vars.OCI_PUBLIC_SIGNING_KEY_ARN }}
        run: |
          DST_IMAGE_HASH="${DST_REPO}@${TELEPORT_IMAGE_LIST_HASH}"
          cosign sign --yes --key "awskms:///${SIGNING_KEY_ARN}" --recursive "${DST_IMAGE_HASH}"
          cosign sign --yes --upload=false --recursive "${DST_IMAGE_HASH}"
