---
name: Publish Operator OCI images
on:
  workflow_call:
    inputs:
      teleport-version:
        description: The semver version of Teleport version that we're publishing.
        type: string
        required: true

      environment:
        description: GitHub environment to publish to.
        type: string
        default: stage/publish

  workflow_dispatch:
    inputs:
      teleport-version:
        type: string
        required: true

      environment:
        type: string
        default: stage/publish

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: .environments

      - name: Load environment values
        uses: gravitational/shared-workflows/tools/env-loader@b90d744feb39522329fba9c7764a4fe07d039d29 # tools/env-loader/v0.1.2
        with:
          tool-version: v0.0.5
          environment-name: ${{ inputs.environment }}
          value-sets: operator

      - name: Parse version
        id: version
        uses: gravitational/teleport.e/.github/actions/parse-version@master
        with:
          version: ${{ inputs.teleport-version }}

      - name: Install cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Assume AWS Publishing Role
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region:  us-west-2
          role-to-assume: ${{ env.PUBLISH_OPERATOR_OCI_AWS_ROLE }}
          role-session-name: "gha-publish-operator-oci-${{ github.run_attempt }}"
          # Publishing should take roughly a minute, so 15 mins gives us plenty
          # of leeway (and is the miminum value we can ask for).
          role-duration-seconds: 900

      - name: Login to Source ECR Registry
        uses: aws-actions/amazon-ecr-login@fa648b43de3d4d023bcb3f89ed6940096949c419 # v2.1.5

      - name: Validate source image signature using signing key and GitHub OIDC Token
        env:
          CERT_IDENTITY_REGEXP: 'https://github\.com/gravitational/teleport\.e/\.github/workflows/build-operator-oci\.yaml@refs/tags/.+'
          CERT_OIDC_ISSUER: "https://token.actions.githubusercontent.com/teleport"
          SIGNING_KEY_ARN: "${{ env.OCI_PENDING_SIGNING_KEY_ARN }}"
          SRC_IMAGE_TAG: "${{ env.OPERATOR_PENDING_ECR_REPO }}:${{ steps.version.outputs.full }}"
        run: |
          cosign verify --key "awskms:///${SIGNING_KEY_ARN}" "${SRC_IMAGE_TAG}" > validated-image.json
          # TODO(reed): Re-enable OIDC identity verification when signature is attached
          # cosign verify ${SRC_IMAGE_TAG} --certificate-identity-regexp="${CERT_IDENTITY_REGEXP}" --certificate-oidc-issuer="${CERT_OIDC_ISSUER}"
          TELEPORT_IMAGE_LIST_HASH=$(jq -r '.[0].critical.image."docker-manifest-digest"' validated-image.json)
          echo "TELEPORT_IMAGE_LIST_HASH=$TELEPORT_IMAGE_LIST_HASH" >> "$GITHUB_ENV"

      - name: Login to Destination ECR Registry
        uses: aws-actions/amazon-ecr-login@fa648b43de3d4d023bcb3f89ed6940096949c419 # v2.1.5
        with:
          registry-type: public
        env:
          # GetAuthorizationToken command is only supported in us-east-1.
          AWS_REGION: us-east-1

      - name: Publish Multi-arch Images
        env:
          SRC_REPO: ${{ env.OPERATOR_PENDING_ECR_REPO }}
          SRC_LABEL: ${{ steps.version.outputs.full }}
          DST_REPO: ${{ env.OPERATOR_PUBLISH_ECR_REPO }}
          DST_LABELS: ${{ steps.version.outputs.labels }}
        run: |
          read -ra labels <<< "${DST_LABELS}" # split on whitespace into array

          echo "Publishing:"
          echo "  source: ${SRC_REPO}:${SRC_LABEL}"
          echo "  dest:   ${DST_REPO}"
          echo "  labels: ${labels[*]}"

          for label in "${labels[@]}"; do
            dst="${DST_REPO}:${label}"
            exists=false
            if docker manifest inspect "${dst}"; then exists=true; fi
            docker buildx imagetools create --tag "${dst}" "${SRC_REPO}:${SRC_LABEL}"
            if "${exists}"; then
              echo "Updated existing image tag: ${dst}"
            else
              echo "Published image: ${dst}"
            fi >> "$GITHUB_STEP_SUMMARY"
          done

      - name: Sign production images using signing key and GitHub OIDC Token
        env:
          DST_REPO: ${{ env.OPERATOR_PUBLISH_ECR_REPO }}
          SIGNING_KEY_ARN: ${{ env.OCI_PUBLIC_SIGNING_KEY_ARN }}
        run: |
          DST_IMAGE_HASH="${DST_REPO}@${TELEPORT_IMAGE_LIST_HASH}"
          cosign sign --yes --key "awskms:///${SIGNING_KEY_ARN}" --recursive "${DST_IMAGE_HASH}"
          cosign sign --yes --upload=false --recursive "${DST_IMAGE_HASH}"
