---
name: Publish releases via the Release service
on:
  workflow_call:
    inputs:
      version:
        description: The version should be published.
        type: string
        required: true
      environment:
        description: GitHub environment to publish to.
        type: string
        default: stage/publish

  # The workflow_dispatch event duplicates the workflow_call input parameters, without descriptions.
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
      environment:
        type: string
        default: stage/publish

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    env:
      ARTIFACT_DIRECTORY: /tmp/artifacts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: .environments

      - name: Load environment values
        uses: gravitational/shared-workflows/tools/env-loader@e28b4323d6c036f904996b9a4a77578e52560570 # tools/env-loader/v0.0.5
        with:
          tool-version: v0.0.5
          environment-name: ${{ inputs.environment }}
          value-sets: release-server

      # Setup
      - name: Assume AWS ECR pull role
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-skip-session-tagging: true
          aws-region: ${{ env.RELCLI_IMAGE_REGION }}
          role-to-assume: ${{ env.RELCLI_IMAGE_PULL_ROLE_ARN }}
          role-session-name: "publish-release-server-${{ github.run_attempt }}"
          role-duration-seconds: 900

      - name: Log into ECR
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      
      - name: Setup
        run: |
          docker pull "$RELCLI_IMAGE"
          mkdir -pv "$ARTIFACT_DIRECTORY"
        
      - name: Assume artifact download role
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-skip-session-tagging: true
          aws-region: us-west-2
          role-to-assume: ${{ env.ARTIFACT_DOWNLOAD_AWS_ROLE }}
          role-session-name: "publish-release-server-${{ github.run_attempt }}"
          role-duration-seconds: 900
      
      - name: Download the artifacts (with manifests)
        env:
          PENDING_BUCKET_NAME: ${{ env.ARTIFACT_SOURCE_BUCKET }}
          RELEASE_VERSION: ${{ inputs.version }}
        working-directory: ${{ env.ARTIFACT_DIRECTORY }}
        run: |
          # The manifests could refer to any file under this path, so it's generally best just to pull
          # all artifacts for the tag.
          aws s3 cp "s3://$PENDING_BUCKET_NAME/teleport/tag/${RELEASE_VERSION#v}/" . --recursive --include "*" --no-progress
          aws s3 cp "s3://$PENDING_BUCKET_NAME/teleport-plugins/tag/${RELEASE_VERSION#v}/" . --recursive --include "*" --no-progress

      - name: Install Teleport
        uses: teleport-actions/setup@a820ebbf1bc1a496efca348ad21042d6e8df73a6 # v1
        with:
          version: 17.4.7

      - name: Fetch release service application credentials
        id: relsrv-auth
        uses: teleport-actions/auth-application@f7d42b0ac9f5b7911cbadb2313b5dd2d6ae6d6f3 # v2
        with:
          proxy: platform.teleport.sh:443
          token: ${{ env.RELCLI_TBOT_TOKEN }}
          app: ${{ env.RELCLI_TBOT_APP_NAME }}
      
      - name: Upload artifacts and publish release
        env:
          DRONE_TAG: ${{ inputs.version }}  # I swear we'll get rid of this some day
          VERSION: ${{ inputs.version }}
          RELCLI_BASE_URL: ${{ env.RELEASES_HOST }}
          RELCLI_CERT: ${{ steps.relsrv-auth.outputs.certificate-file }}
          RELCLI_KEY: ${{ steps.relsrv-auth.outputs.key-file }}
        working-directory: ${{ env.ARTIFACT_DIRECTORY }}
        run: |

          # Use docker run instead of running the whole job in a container as running a
          # job in a container requires the `tail` command be available and the relcli
          # image does not have `tail` (GHA seems to run `tail -f /dev/null` when
          # initializing a container to keep it alive between each step).
          # Upload artifacts
          docker run -u "$(id -u):$(id -g)" \
            -e RELCLI_BASE_URL -e RELCLI_CERT -e RELCLI_KEY \
            -v "${RELCLI_CERT}:${RELCLI_CERT}" -v "${RELCLI_KEY}:${RELCLI_KEY}" \
            -v "$(pwd):/assets" \
            "${RELCLI_IMAGE}" upload-manifest \
            --manifest-directory-path "/assets" --artifact-version "$VERSION" -f -v 6

          # Publish releases
          docker run -u "$(id -u):$(id -g)" \
            -e RELCLI_BASE_URL -e RELCLI_CERT -e RELCLI_KEY \
            -v "${RELCLI_CERT}:${RELCLI_CERT}" -v "${RELCLI_KEY}:${RELCLI_KEY}" \
            -e DRONE_TAG \
            "${RELCLI_IMAGE}" auto_publish -f -v 6
