---
name: Publish Operator OCI images
on:
  workflow_call:
    inputs:
      teleport-version:
        description: The semver version of Teleport version that we're publishing.
        type: string
        required: true

      environment:
        description: GitHub environment to publish to.
        type: string
        default: stage/publish

  workflow_dispatch:
    inputs:
      teleport-version:
        type: string
        required: true

      environment:
        type: string
        default: stage/publish

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: .environments

      - name: Load environment values
        uses: gravitational/shared-workflows/tools/env-loader@e28b4323d6c036f904996b9a4a77578e52560570 # tools/env-loader/v0.0.5
        with:
          tool-version: v0.0.5
          environment-name: ${{ inputs.environment }}
          value-sets: operator

      - name: Parse version
        id: version
        uses: gravitational/teleport.e/.github/actions/parse-version@master
        with:
          version: ${{ inputs.teleport-version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Assume AWS Publishing Role
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          aws-region:  us-west-2
          role-to-assume: ${{ env.PUBLISH_OPERATOR_OCI_AWS_ROLE }}
          role-session-name: "gha-publish-operator-oci-${{ github.run_attempt }}"
          # Publishing should take roughly a minute, so 15 mins gives us plenty
          # of leeway (and is the miminum value we can ask for).
          role-duration-seconds: 900

      - name: Login to Source ECR Registry
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Login to Destination ECR Registry
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registry-type: public
        env:
          # GetAuthorizationToken command is only supported in us-east-1.
          AWS_REGION: us-east-1

      - name: Publish Multi-arch Images
        env:
          SRC_REPO: ${{ env.OPERATOR_PENDING_ECR_REPO }}
          SRC_LABEL: ${{ steps.version.outputs.full }}
          DST_REPO: ${{ env.OPERATOR_PUBLISH_ECR_REPO }}
          DST_LABELS: ${{ steps.version.outputs.labels }}
        run: |
          read -ra labels <<< "${DST_LABELS}" # split on whitespace into array

          echo "Publishing:"
          echo "  source: ${SRC_REPO}:${SRC_LABEL}"
          echo "  dest:   ${DST_REPO}"
          echo "  labels: ${labels[*]}"

          for label in "${labels[@]}"; do
            dst="${DST_REPO}:${label}"
            exists=false
            if docker manifest inspect "${dst}"; then exists=true; fi
            docker buildx imagetools create --tag "${dst}" "${SRC_REPO}:${SRC_LABEL}"
            if "${exists}"; then
              echo "Updated existing image tag: ${dst}"
            else
              echo "Published image: ${dst}"
            fi >> "$GITHUB_STEP_SUMMARY"
          done
