---
name: Publish Distroless Teleport Images
on:
  workflow_call:
    inputs:
      release-source-tag:
        description: The semver version tag of the Teleport revision that we're building.
        type: string
        required: true

      environment:
        description: GitHub environment to publish to.
        type: string
        default: stage/publish

  # The workflow_dispatch event duplicates the workflow_call input parameters, without descriptions.
  workflow_dispatch:
    inputs:
      release-source-tag:
        type: string
        required: true
      environment:
        type: environment
        default: stage/publish

run-name: 'Publish OCI images for Teleport ${{ inputs.release-source-tag }}'

jobs:
  configure:
    name: Configure Build
    runs-on: ubuntu-latest
    outputs:
      teleport-version: ${{ steps.version.outputs.full }}
      teleport-version-major: ${{ steps.version.outputs.major }}
      teleport-version-minor: ${{ steps.version.outputs.minor }}
      teleport-version-patch: ${{ steps.version.outputs.patch }}
      teleport-version-prerelease: ${{ steps.version.outputs.prerelease }}
      dest-image-tags: ${{ steps.version.outputs.image_tags }}
    steps:
      # Generates a list of tags that will be applied to the published image. In the
      # case of a "normal" release (identified by a version tag with no pre-release
      # suffix) the published image is assumed to take over all of the more-significant
      # release numbers, as well as its own (e.g 11.2.3 implies tags of 11 and 11.2).
      #
      # A version tag with a pre-release sufffix will only be published as itself, in
      # order to allow things like RCs and Betas to be published without overriding any
      # existing release.
      - name: Generate Tags
        id: version
        run: |
          version=${{ inputs.release-source-tag }}
          version="${version#v}"

          if ! [[ "${version}" =~ [^0-9]*([0-9]+)\.([0-9]+)\.([0-9]+)(-[0-9A-Za-z.+-]+)? ]]; then
                  echo bad version
                  exit 1
          fi

          set -- "${BASH_REMATCH[@]:1}" # get regex groups as $1, $2, ... etc
          tags="${version}"
          [[ -z "$4" ]] && tags+=" $1.$2 $1" # add major.minor and major tags if not prerelease

          {
            echo full="${version}"
            echo major="$1"
            echo minor="$2"
            echo patch="$3"
            echo prerelease="$4"
            echo image_tags="${tags}"
          } >> "$GITHUB_OUTPUT"

  publish-images:
    needs: configure
    permissions:
      id-token: write  # required for aws-actions/configure-aws-credentials
      contents: read
    strategy:
      fail-fast: false
      matrix:
        mode: ['debug', 'production']
        release: ['oss', 'enterprise', 'fips']
        include:
          - mode: 'production'
            repo-debug-suffix: ''
          - mode: 'debug'
            repo-debug-suffix: '-debug'
          - release: 'oss'
            repo-enterprise-infix: ''
          - release: 'enterprise'
            repo-enterprise-infix: '-ent'
          - release: 'fips'
            repo-enterprise-infix: '-ent-fips'
    uses: ./.github/workflows/oci-image-publish.yml
    with:
      repository: teleport${{ matrix.repo-enterprise-infix }}-distroless${{ matrix.repo-debug-suffix }}
      pending-tag: ${{ needs.configure.outputs.teleport-version }}
      production-tags: ${{ needs.configure.outputs.dest-image-tags }}
      environment: ${{ inputs.environment }}
