---
name: Publish Hardened Teleport AMIs
on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: The name of the OSS teleport repo to checkout.
        type: string
        default: gravitational/teleport

      oss-teleport-ref:
        description: Git SHA, tag or branch of the revision of OSS teleport to build.
        type: string
        required: true

      release-source-tag:
        description: |
          The semver version of Teleport that we're building for. If not set
          will be inferred form the `oss-teleport-ref` by assuming that it's
          a standard Teleport release tag in the form vX.Y.Z.
        type: string

      dest-ami-regions:
        description: A comma-separated list of AWS regions to search for the AMIs.
        type: string
        default: eu-north-1,ap-south-1,eu-west-3,eu-west-2,eu-west-1,ap-northeast-3,ap-northeast-2,ap-northeast-1,sa-east-1,ca-central-1,ap-southeast-1,ap-southeast-2,eu-central-1,us-east-1,us-east-2,us-west-1,us-west-2

      environment:
        description: GitHub environment to publish to.
        type: string
        default: stage/publish

  # The workflow_dispatch event duplicates the workflow_call input parameters, without descriptions.
  workflow_dispatch:
    inputs:
      oss-teleport-repo:
        type: string
        default: gravitational/teleport
      oss-teleport-ref:
        type: string
        required: true
      release-source-tag:
        type: string
      dest-ami-regions:
        type: string
        default: eu-north-1,ap-south-1,eu-west-3,eu-west-2,eu-west-1,ap-northeast-3,ap-northeast-2,ap-northeast-1,sa-east-1,ca-central-1,ap-southeast-1,ap-southeast-2,eu-central-1,us-east-1,us-east-2,us-west-1,us-west-2
      environment:
        type: environment
        default: stage/publish

run-name: 'Publish Hardened AMIs for Teleport ${{ inputs.release-source-tag }}'

jobs:
  publish-images:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # required for aws-actions/configure-aws-credentials
      contents: read

    environment: ${{ inputs.environment }}

    steps:
      - name: Parse Teleport version tag
        id: version
        env:
          VERSION: ${{ inputs.release-source-tag || inputs.oss-teleport-ref }}
        run: |
          echo teleport="${VERSION#v}" >> "$GITHUB_OUTPUT"

      - name: Checkout Teleport
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        with:
          oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
          oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
          edition: enterprise
          repo-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
          repo-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}

      - name: Load environment values
        uses: gravitational/shared-workflows/tools/env-loader@e28b4323d6c036f904996b9a4a77578e52560570 # tools/env-loader/v0.0.5
        with:
          tool-version: v0.0.5
          environment-name: ${{ inputs.environment }}
          value-sets: amis
          environments-directory: e/.environments

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Assume promotion AWS role
        id: aws-login
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          aws-region: us-west-2
          role-to-assume: ${{ env.AMI_PUBLISHING_ROLE_ARN }}
          role-session-name: 'gha-ami-publishing-${{ github.run_number }}'
          role-duration-seconds: 3600

      - name: Publish images
        working-directory: ./assets/aws
        env:
          AWS_ACCOUNT_ID: ${{ steps.aws-login.outputs.aws-account-id }}
          AWS_REGIONS: ${{ inputs.dest-ami-regions }}
          TELEPORT_VERSION: ${{ steps.version.outputs.teleport }}
        run: |
          go run ./cmd/make-public \
            --aws-account "${AWS_ACCOUNT_ID}" \
            --regions "${AWS_REGIONS}" \
            --teleport-version "${TELEPORT_VERSION}"
