---
name: Publish Teleport Plugins

on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: The name of the OSS teleport repo to checkout.
        type: string
        default: gravitational/teleport

      oss-teleport-ref:
        description: Git SHA, tag or branch of the revision of OSS teleport to build.
        type: string
        required: true

      teleport-version:
        description: |
          The semver version of Teleport version that we're building for.
        type: string

      environment:
        description: GitHub environment to publish to.
        type: string
        default: stage/publish

jobs:
  publish:
    # Larger runner is used for additional disk space, see
    # https://docs.github.com/en/enterprise-cloud@latest/actions/using-github-hosted-runners/using-larger-runners/about-larger-runners#specifications-for-general-larger-runners
    runs-on: ubuntu-22.04-8core
    # Unfortunately this cannot be set as a global env var as they are not evaluated until runtime
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
    env:
      ARTIFACT_TAG: ${{ inputs.teleport-version }}
      LOCAL_ARTIFACTS_PATH: /tmp/artifacts
      LOCAL_TERRAFORM_REGISTRY_PATH: /tmp/terraform-registry
      ENVIRONMENT_NAME: ${{ inputs.environment }}
    steps:
      # This is needed to download the Terraform promotion tool, and for makefiles
      - name: Checkout Teleport
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        with:
          oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
          oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
          edition: enterprise
          repo-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
          repo-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}

      - name: Assume env-loader secrets decryption AWS role
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          aws-region: us-west-2
          role-to-assume: ${{ vars.PUBLISH_PLUGINS_ENV_LOADER_AWS_ROLE_ARN }}
          role-session-name: "gha-publish-plugins-env-loader-${{ github.run_number }}"
          role-duration-seconds: 900

      - name: Load environment values
        uses: gravitational/shared-workflows/tools/env-loader@e28b4323d6c036f904996b9a4a77578e52560570 # tools/env-loader/v0.0.5
        with:
          tool-version: v0.0.5
          environment-name: ${{ inputs.environment }}
          value-sets: terraform
          environments-directory: e/.environments

      - name: Setup tooling Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "./e/tooling/plugins/go.mod"
          cache-dependency-path: "./e/tooling/plugins/go.sum"
          check-latest: true

      # Sync artifacts down (required by everything)
      - name: Assume AWS role for uploading the artifacts
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-skip-session-tagging: true
          aws-region: us-west-2
          role-to-assume: ${{ env.ARTIFACT_DOWNLOAD_AWS_ROLE }}
          role-session-name: "tag-publish-plugins-artifact-download-${{ github.run_attempt }}"
          role-duration-seconds: 900

      - name: Download artifacts from S3
        env:
          PENDING_BUCKET: ${{ env.ARTIFACT_SOURCE_BUCKET }}
        run: |
          aws s3 cp "s3://$PENDING_BUCKET/teleport-plugins/tag/$ARTIFACT_TAG/" "$LOCAL_ARTIFACTS_PATH" --recursive

      # Terraform promotion
      - name: Assume AWS role for syncing the Terraform artifacts
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-skip-session-tagging: true
          aws-region: us-west-2
          role-to-assume: ${{ env.TERRAFORM_PUBLISHING_SYNC_AWS_ROLE }}
          role-session-name: "tag-publish-plugins-terraform-publishing-sync-${{ github.run_attempt }}"
          role-duration-seconds: 1800 # bumped from 15m to 30m because downloading the TF registry bucket can take longer than 15m.

      - name: Download the Terraform repo from S3
        env:
          TERRAFORM_REGISTRY_BUCKET: ${{ env.TERRAFORM_REGISTRY_BUCKET }}
        run: |
          aws s3 cp "s3://$TERRAFORM_REGISTRY_BUCKET/" "$LOCAL_TERRAFORM_REGISTRY_PATH" --recursive

      - name: Run the terraform-publish tool for teleport
        env:
          TERRAFORM_REGISTRY_URL: ${{ env.TERRAFORM_REGISTRY_URL }}
          SIGNING_KEY: ${{ env.TERRAFORM_SIGNING_KEY }}
        run: |
          go run -C e/tooling/plugins ./cmd/promote-terraform \
            --tag "$ARTIFACT_TAG" \
            --artifact-directory-path "$LOCAL_ARTIFACTS_PATH" \
            --registry-directory-path "$LOCAL_TERRAFORM_REGISTRY_PATH" \
            --protocol 6 \
            --registry-url "$TERRAFORM_REGISTRY_URL" \
            --namespace gravitational \
            --name teleport

      - name: Run the terraform-publish tool for teleportmwi
        env:
          TERRAFORM_REGISTRY_URL: ${{ env.TERRAFORM_REGISTRY_URL }}
          SIGNING_KEY: ${{ env.TERRAFORM_SIGNING_KEY }}
        run: |
          go run -C e/tooling/plugins ./cmd/promote-terraform \
            --tag "$ARTIFACT_TAG" \
            --artifact-directory-path "$LOCAL_ARTIFACTS_PATH" \
            --registry-directory-path "$LOCAL_TERRAFORM_REGISTRY_PATH" \
            --protocol 6 \
            --registry-url "$TERRAFORM_REGISTRY_URL" \
            --namespace gravitational \
            --name teleportmwi \
            --variant mwi

      - name: Run the terraform-publish tool for teleport terraform modules
        env:
          TERRAFORM_REGISTRY_URL: ${{ env.TERRAFORM_REGISTRY_URL }}
          SIGNING_KEY: ${{ env.TERRAFORM_SIGNING_KEY }}
        run: |
          go run -C e/tooling/plugins ./cmd/promote-terraform \
            --tag "$ARTIFACT_TAG" \
            --artifact-directory-path "$LOCAL_ARTIFACTS_PATH" \
            --registry-directory-path "$LOCAL_TERRAFORM_REGISTRY_PATH" \
            --publish-modules

      - name: Upload the Terraform repo to S3
        env:
          TERRAFORM_REGISTRY_BUCKET: ${{ env.TERRAFORM_REGISTRY_BUCKET }}
        run: |
          aws s3 sync "$LOCAL_TERRAFORM_REGISTRY_PATH" "s3://$TERRAFORM_REGISTRY_BUCKET/"

  # Image publishing
  images-setup:
    name: Setup for image publishing
    runs-on: ubuntu-latest
    outputs:
      teleport-version: ${{ steps.version.outputs.full }}
      dest-image-tags: ${{ steps.version.outputs.labels }}
    steps:
      # Generates a list of tags that will be applied to the published image. In the
      # case of a "normal" release (identified by a version tag with no pre-release
      # suffix) the published image is assumed to take over all of the more-significant
      # release numbers, as well as its own (e.g 11.2.3 implies tags of 11 and 11.2).
      #
      # A version tag with a pre-release sufffix will only be published as itself, in
      # order to allow things like RCs and Betas to be published without overriding any
      # existing release.
      - name: Parse version
        id: version
        uses: gravitational/teleport.e/.github/actions/parse-version@master
        with:
          version: ${{ inputs.teleport-version }}

  publish-images:
    needs: images-setup
    permissions:
      contents: read
      id-token: write  # required for aws-actions/configure-aws-credentials
    strategy:
      fail-fast: false
      matrix:
        plugins:
          # Access plugins
          - discord
          - email
          - jira
          - mattermost
          - msteams
          - pagerduty
          - slack
          - datadog
          # Event handler
          - event-handler
        image-type:
          - name: production  # The `name` field is just here for documentation
            repo-suffix: ''
          - name: debug
            repo-suffix: '-debug'
    uses: ./.github/workflows/oci-image-publish.yml
    with:
      repository: teleport-plugin-${{ matrix.plugins }}${{ matrix.image-type.repo-suffix }}
      pending-tag: ${{ needs.images-setup.outputs.teleport-version }}
      production-tags: ${{ needs.images-setup.outputs.dest-image-tags }}
      environment: ${{ inputs.environment }}
