---
name: Publish releases via the Release service
on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: The name of the OSS teleport repo to publish the release for.
        type: string
        default: gravitational/teleport
      version:
        description: The version should be published.
        type: string
        required: true
      environment:
        description: GitHub environment to publish to.
        type: string
        default: publish-stage

  # The workflow_dispatch event duplicates the workflow_call input parameters, without descriptions.
  workflow_dispatch:
    inputs:
      oss-teleport-repo:
        type: string
        default: gravitational/teleport
      version:
        type: string
        required: true
      environment:
        type: string
        default: publish-stage

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
    steps:
      - name: Assume AWS ECR pull role
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-skip-session-tagging: true
          aws-region: ${{ vars.ECR_PRIVATE_REPOS_REGION }}
          role-to-assume: ${{ vars.ECR_PROD_PULL_ROLE_ARN }}
          role-session-name: "publish-release-server-${{ github.run_attempt }}"
          role-duration-seconds: 900

      - name: Log into ECR
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Publish the release
        env:
          DRONE_TAG: ${{ inputs.version }}
          RELCLI_BASE_URL: ${{ vars.RELEASES_HOST }}
          RELCLI_REPO: 146628656107.dkr.ecr.us-west-2.amazonaws.com/gravitational/relcli
          RELCLI_LABEL: prod-a004819-20240213T215723
          RELCLI_CERT: /tmp/releases.crt
          RELCLI_KEY: /tmp/releases.key
          RELEASES_CERT: ${{ vars.RELEASES_CERT }}
          RELEASES_KEY: ${{ secrets.RELEASES_KEY }}
        run: |
          printenv RELEASES_CERT > "$RELCLI_CERT"
          printenv RELEASES_KEY > "$RELCLI_KEY"
          # Use docker run instead of running the whole job in a container as running a
          # job in a container requires the `tail` command be available and the relcli
          # image does not have `tail` (GHA seems to run `tail -f /dev/null` when
          # initializing a container to keep it alive between each step).
          docker run \
            -e DRONE_TAG -e RELCLI_BASE_URL -e RELCLI_CERT -e RELCLI_KEY \
            -v "${RELCLI_CERT}":"${RELCLI_CERT}" -v "${RELCLI_KEY}":"${RELCLI_KEY}" \
            "${RELCLI_REPO}:${RELCLI_LABEL}" auto_publish -f -v 6
