---
name: Publish Helm charts
on:
  workflow_call:
    inputs:
      teleport-version:
        description: The semver version of Teleport version that we're publishing.
        type: string
        required: true

      environment:
        description: GitHub environment to publish to.
        type: string
        default: stage/publish

  # The workflow_dispatch event duplicates the workflow_call input parameters, without descriptions.
  workflow_dispatch:
    inputs:
      teleport-version:
        type: string
        required: true
      environment:
        type: string
        default: stage/publish

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    env:
      ARITFACTS_DIR: /tmp/artifacts
      # WARNING: anything copied to this directory will become publicly available. Copy with caution.
      REPO_DIR: /tmp/repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: .environments

      - name: Load environment values
        uses: gravitational/shared-workflows/tools/env-loader@b90d744feb39522329fba9c7764a4fe07d039d29 # tools/env-loader/v0.1.2
        with:
          tool-version: v0.0.5
          environment-name: ${{ inputs.environment }}
          value-sets: helm

      - name: Make the artifacts and repo directories
        run: |
          mkdir -pv "${ARITFACTS_DIR}" "${REPO_DIR}"

      - name: Assume AWS role for downloading the artifacts
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-skip-session-tagging: true
          aws-region: us-west-2
          role-to-assume: ${{ env.ARTIFACT_DOWNLOAD_AWS_ROLE }}
          role-session-name: "gha-helm-chart-download-${{ github.run_number }}"
          role-duration-seconds: 900

      - name: Download the Helm chart artifacts
        working-directory: ${{ env.ARITFACTS_DIR }}
        env:
          PENDING_BUCKET_NAME: ${{ env.ARTIFACT_SOURCE_BUCKET }}
          TELEPORT_VERSION: ${{ inputs.teleport-version }}
        run: |
          # If we ever add non-Helm chart artifacts that end in ".tgz" then this will need to be made more selective
          aws s3 cp "s3://$PENDING_BUCKET_NAME/teleport/tag/${TELEPORT_VERSION#v}/" . --recursive --exclude "*" --include "*.tgz"
          aws s3 cp "s3://$PENDING_BUCKET_NAME/teleport/tag/${TELEPORT_VERSION#v}/helm-index.html" index.html

      - name: Assume helm chart publishing role
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: us-west-2
          role-to-assume: ${{ env.HELM_PUBLISHING_SYNC_AWS_ROLE }}
          role-session-name: "gha-publish-helm-${{ github.run_attempt }}"
          role-duration-seconds: 3600

      - name: Download Helm chart repository
        working-directory: ${{ env.REPO_DIR }}
        env:
          S3_PATH: s3://${{ env.HELM_REPO_BUCKET }}/
        run: |
          aws s3 sync "${S3_PATH}" .

      - name: Copy the new artifacts on top of the existing repository
        working-directory: ${{ env.REPO_DIR }}
        run: |
          cp -rv "${ARITFACTS_DIR}/"* .

      - name: Package chart repository
        working-directory: ${{ env.REPO_DIR }}
        run: |
          helm repo index .
          ls -l

      - name: Publish chart repository to S3
        working-directory: ${{ env.REPO_DIR }}
        env:
          S3_PATH: s3://${{ env.HELM_REPO_BUCKET }}/
        run: |
          aws s3 sync . "${S3_PATH}"
