name: Build Linux (Push)
on:
  workflow_dispatch:
    inputs:
      oss-teleport-repo:
        description: "The name of the OSS teleport repo to build"
        required: false
        default: "gravitational/teleport"
        type: string

      oss-teleport-ref:
        description: "Tag, branch or reference to OSS teleport to build"
        type: string
        required: true

      ent-teleport-ref:
        description: |
          Tag, branch or reference to Enterprise teleport to include in the
          build. If no value is supplied this workflow will use whatever
          reference is specified in the OSS teleport submodule record.
        type: string
        required: false
        default: ""

      release-target:
        description: "Release target to run from build.assets/Makefile."
        type: string
        required: true

      build-connect:
        description: "Should Teleport Connect be built"
        required: false
        type: boolean
        default: false

      workflow-tag:
        description: |
          Tag used to identify workflow runs spawned by this event
        type: string
        default: ""

run-name: "Push Build for ${{ inputs.release-target }} of ${{ inputs.oss-teleport-repo }} branch ${{ inputs.oss-teleport-ref }}"

jobs:
  identity:
    runs-on: ubuntu-latest
    if: inputs.workflow-tag != ''
    steps:
      - name: ${{ inputs.workflow-tag }}
        run: echo ${{ inputs.workflow-tag }}

  select:
    runs-on: ubuntu-latest
    outputs:
      builder: ${{ steps.select-builder.outputs.builder }}
    steps:
      - name: Select builder
        id: select-builder
        env:
          BUILD_CONNECT: ${{ inputs.build-connect }}
        # Teleport Connect builds need to use a GitHub runner as the use UID 1000 which
        # is needed for the Teleport Connect builder image. Self-hosted runners use 1001.
        # TODO(camscale): Make the connect builder work with UID 1001 as well as 1000.
        run: |
          if [ "$BUILD_CONNECT" = 'true' ]; then
            echo 'builder="ubuntu-22.04-16core"'
          else
            echo 'builder={"group": "prod", "labels": ["self-hosted", "linux", "x64"]}'
          fi >> $GITHUB_OUTPUT

  build-artifacts:
    name: Build Artifacts
    needs: [ select ]
    secrets: inherit
    uses: ./.github/workflows/build-linux.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      ent-teleport-ref: ${{ inputs.ent-teleport-ref }}
      release: enterprise
      release-target: ${{ inputs.release-target }}
      builder: ${{ needs.select.outputs.builder }}
      build-connect: ${{ inputs.build-connect }}
