---
name: Build Windows (native) release artifacts

on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: The name of the OSS teleport repo to build.
        type: string
        default: gravitational/teleport

      oss-teleport-ref:
        description: Tag, branch or reference to OSS teleport to build.
        type: string
        required: true

      ent-teleport-ref:
        description: |
          Tag, branch or reference to Enterprise teleport to include in the
          build. If no value is supplied this workflow will use whatever
          reference is specified in the OSS teleport submodule record.
        type: string
      
      release-version:
        description: |
          Override the default release version tag when uploading the build
          artifacts. The default value is deduced from `oss-teleport-ref`,
          which is assumed to be a version tag with a leading `v`. Use this
          override to specify a tag for build debugging purposes.
        type: string
      
      environment:
        description: |
          GitHub Actions environment in which to run the build. Can be either
          `build-stage` or `build-prod`.
        type: string
        default: build-prod

      workflow-tag:
        description: Tag used to identify workflow runs spawned by this event.
        type: string

jobs:
  # Do the build
  build:
    name: Build Windows (native) release artifacts
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    uses: ./.github/workflows/build-windows.yaml
    with:
      artifact-version: ${{ inputs.release-version || inputs.oss-teleport-ref }}
      environment: ${{ inputs.environment }}
      ent-teleport-ref: ${{ inputs.ent-teleport-ref }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
