name: Build Linux-based Release Artifacts
on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: The name of the OSS teleport repo to build.
        type: string
        default: gravitational/teleport

      oss-teleport-ref:
        description: Tag, branch or reference to OSS teleport to build.
        type: string
        required: true

      ent-teleport-ref:
        description: |
          Tag, branch or reference to Enterprise teleport to include in the
          build. If no value is supplied this workflow will use whatever
          reference is specified in the OSS teleport submodule record.
        type: string

      release-target:
        description: Release target to run from build.assets/Makefile.
        type: string
        required: true

      release-artifacts:
        description: Should the workflow upload the resulting artifacts to the Release server?
        type: boolean
        default: false

      release-version:
        description: |
          Override the default release version tag when uploading the build
          artifacts. The default value is deduced from `oss-teleport-ref`,
          which is assumed to be a version tag with a leading `v`. Use this
          override to specify a tag for build debugging purposes.
        type: string

      build-connect:
        description: Should Teleport Connect be built.
        type: boolean
        default: false

      build-os-packages:
        description: Should Debian and RPM packages of the release be built.
        type: boolean
        default: false

      environment:
        description: |
          GitHub Actions environment in which to run the build. Can be either
          `build-stage` or `build-prod`.
        type: string
        default: build-stage

      workflow-tag:
        description: Tag used to identify workflow runs spawned by this event.
        type: string

  # The workflow_dispatch event duplicates the workflow_call input parameters, without descriptions.
  workflow_dispatch:
    inputs:
      oss-teleport-repo:
        type: string
        default: gravitational/teleport
      oss-teleport-ref:
        type: string
        required: true
      ent-teleport-ref:
        type: string
      release-target:
        type: string
        required: true
      release-artifacts:
        type: boolean
        default: false
      release-version:
        type: string
      build-connect:
        type: boolean
        default: false
      build-os-packages:
        type: boolean
        default: false
      environment:
        type: string
        default: build-stage
      workflow-tag:
        type: string

run-name: "Build of ${{ inputs.release-target }} of ${{ inputs.oss-teleport-repo }} branch ${{ inputs.oss-teleport-ref }}"

jobs:
  identity:
    runs-on: ubuntu-latest
    if: inputs.workflow-tag != ''
    steps:
      - name: ${{ inputs.workflow-tag }}
        run: echo ${{ inputs.workflow-tag }}

  select:
    runs-on: ubuntu-latest
    outputs:
      arch: ${{ steps.determine-arch.outputs.arch }}
      builder: ${{ steps.select-builder.outputs.builder }}
    steps:
      - name: Select builder
        id: select-builder
        env:
          BUILD_CONNECT: ${{ inputs.build-connect }}
          RELEASE_ARTIFACTS: ${{ inputs.release-artifacts }}
          RELEASE_TARGET: ${{ inputs.release-target }}
        # arm64 needs an arm64 runner, which we self-host.
        # Teleport Connect builds need to use a GitHub runner as they use UID 1000 which
        # is needed for the Teleport Connect builder image. Self-hosted runners use 1001.
        # TODO(camscale): Make the connect builder work with UID 1001 as well as 1000.
        run: |
          if [[ "$RELEASE_TARGET" == *-arm64* ]]; then
            echo 'builder={"group": "prod", "labels": ["self-hosted", "linux", "arm64"]}'
          elif [ "$BUILD_CONNECT" = 'true' ] || [ "$RELEASE_ARTIFACTS" = 'true' ]; then
            echo 'builder="ubuntu-22.04-16core"'
          else
            echo 'builder={"group": "prod", "labels": ["self-hosted", "linux", "x64"]}'
          fi >> "$GITHUB_OUTPUT"
      - name: Determine architecture
        id: determine-arch
        env:
          RELEASE_TARGET: ${{ inputs.release-target }}
        run: |
          case "$RELEASE_TARGET" in
          *amd64*) echo 'arch=amd64' ;;
          *arm64*) echo 'arch=arm64' ;;
          *arm*) echo 'arch=arm' ;;
          *386*) echo 'arch=386' ;;
          esac >> "$GITHUB_OUTPUT"

  build-artifacts:
    name: Build Artifacts
    needs: [ select ]
    secrets: inherit
    permissions:
      id-token: write # required for aws-actions/configure-aws-credentials in called workflow
      contents: read
    uses: ./.github/workflows/build-linux.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      ent-teleport-ref: ${{ inputs.ent-teleport-ref }}
      release: enterprise
      release-target: ${{ inputs.release-target }}
      builder: ${{ needs.select.outputs.builder }}
      build-connect: ${{ inputs.build-connect }}
      build-deb: ${{ inputs.build-os-packages }}
      build-rpm: ${{ inputs.build-os-packages }}
      arch: ${{ needs.select.outputs.arch }}
      environment: ${{ inputs.environment }}
