name: Build Kube Agent Updater Images
on:
  workflow_dispatch:
    inputs: 
      oss-teleport-repo:
        description: |
          The name of the OSS teleport repo to checkout
        required: false
        type: string
        default: "gravitational/teleport"

      oss-teleport-ref:
        description: |
          Git SHA, tag or branch of the revision of OSS teleport to build
        required: true
        type: string

      source-tag:
        description: |
          The semver version of Teleport that we're building for. If not set 
          will be inferred form the `oss-teleport-ref` by assuming that it's
          a standard Teleport release tag in the form vX.Y.Z.
        type: string
        default: ""

      build-role-arn:
        description: |
          The ARN of the role used to sign and store the resulting image(s) in
          ECR
        required: true
        type: string
        default: arn:aws:iam::146628656107:role/teleport-oci-tag-build-gha

      signing-key-url:
        description: |
          URL of the KMS key used to sign the resulting images. Must be
          readable from the role specified by `build-role-arn`.
        required: true
        type: string
        default: awskms:///arn:aws:kms:us-west-2:146628656107:alias/teleport-oci-pending-build-signing

      dest-repo-prefix:
        description: |
          Registry and namespace prefix for the destination repository,
          formatted for use with Docker (that is, like a URI, not the AWS
          ARN). 
        type: string
        required: true
        default: 146628656107.dkr.ecr.us-west-2.amazonaws.com/gravitational

      environment:
        description: |
          GitHub Actions environment in which to run the build. Can be either
          `build` or `promote`.
        type: string
        default: promote

      workflow-tag:
        description: |
          Tag used to identify workflow runs spawned by this event
        type: string
        default: ""

run-name: Build Distroless Images for Teleport ${{ inputs.source-tag }}

jobs:
  identity:
    runs-on: ubuntu-latest
    if: inputs.workflow-tag != ''
    steps:
      - name: ${{ inputs.workflow-tag }}
        run: echo ${{ inputs.workflow-tag }}

  configure:
    name: Configure Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      teleport_version: ${{ steps.version.outputs.teleport_version }}
      buildbox: ${{ steps.get-buildbox.outputs.buildbox }}
      public_ecr_login_role_arn: ${{ steps.get-buildbox.outputs.public_ecr_login_role_arn }}
    steps:
      - name: Parse version tag
        id: version
        run: |
          TAG=${{ inputs.source-tag }}
          if [[ -z "$TAG" ]]; then
            TAG=${{ inputs.oss-teleport-ref }}
          fi
          VERSION=${TAG#v}
          echo teleport_version=$VERSION >> "$GITHUB_OUTPUT"
      - name: Checkout OSS Teleport
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        with:
          oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
          oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
          edition: oss
          repo-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
          repo-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}
      - name: Get buildbox image ref
        id: get-buildbox
        env:
          ECR_READ_ONLY_ROLE: ${{ vars.ECR_READ_ONLY_ROLE }}
        run: |
          BUILDBOX="$(make -s -C ./build.assets/ show-buildbox-base-image)"
          echo "buildbox: $BUILDBOX"
          echo "buildbox=$BUILDBOX" >> "$GITHUB_OUTPUT"
          # pulling the buildbox needs public ecr auth to raise rate limits
          echo "public_ecr_login_role_arn=$ECR_READ_ONLY_ROLE" >> "$GITHUB_OUTPUT"

  build-docker-images:
    name: Build OCI container images
    needs: configure
    permissions:
      id-token: write  # required for aws-actions/configure-aws-credentials
      security-events: write # required for trivy scan
      contents: read
      actions: read
    strategy:
      matrix:
        mode: ['debug', 'production']
        include:
          - mode: 'production'
            base-image: 'gcr.io/distroless/static-debian12:latest'
            repo-debug-suffix: ''
          - mode: 'debug'
            base-image: 'gcr.io/distroless/static-debian12:debug'
            repo-debug-suffix: '-debug'
    uses: ./.github/workflows/oci-image-build.yml
    with:
      # Integrations don't have an enterprise version
      teleport-release: oss
      base-image: ${{ matrix.base-image }}
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      source-tag: ${{ inputs.source-tag }}
      teleport-version: ${{ needs.configure.outputs.teleport_version }}
      dest-image-registry: ${{ inputs.dest-repo-prefix }}
      dest-image-repo: teleport-kube-agent-updater${{ matrix.repo-debug-suffix }}
      dest-image-tags: ${{ needs.configure.outputs.teleport_version }}
      public-ecr-login-role-arn: ${{ needs.configure.outputs.public_ecr_login_role_arn }}
      build-role-arn: ${{ inputs.build-role-arn }}
      signing-key-url: ${{ inputs.signing-key-url }}
      allow-overwrites: false
      image-build-args: |
        BUILDBOX=${{ needs.configure.outputs.buildbox }}
      image-build-context: ./teleport/.
      image-build-dockerfile: ./integrations/kube-agent-updater/Dockerfile
    secrets:
      deploy-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
      deploy-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}
