name: Release OCI
on:
  workflow_dispatch:
    inputs:
      oss-teleport-repo:
        description: |
          The name of the OSS teleport repo to checkout.
        required: false
        type: string
        default: "gravitational/teleport"

      oss-teleport-ref:
        description: |
          Git SHA, tag or branch of the revision of OSS teleport to build.
        required: true
        type: string

      release-version:
        description: |
          The semver version of Teleport that we're building for. If not set
          will be inferred form the `oss-teleport-ref` by assuming that it's
          a standard Teleport release tag in the form vX.Y.Z. Use this override
          to specify the version when oss-teleport-ref is not a formal semver
          release tag.
        type: string

      workflow-tag:
        description: |
          Tag used to identify workflow runs spawned by this event.
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      teleport-version: ${{ steps.config.outputs.teleport-version }}
    steps:

      - name: ${{ inputs.workflow-tag }}
        if: inputs.workflow-tag != ''
        run: echo ${{ inputs.workflow-tag }}

      - name: Configure vars
        id: config
        env:
          ref: ${{ inputs.release-version || inputs.oss-teleport-ref }}
        run: |
          echo "teleport-version=${ref#v}" >> "$GITHUB_OUTPUT"

  build-legacy-images:
    name: Build legacy images
    needs: setup
    secrets: inherit
    permissions:
      id-token: write  # required for aws-actions/configure-aws-credentials
      contents: read
    uses: ./.github/workflows/build-legacy-oci.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      teleport-version: ${{ needs.setup.outputs.teleport-version }}
