name: Build MacOS Release Artifacts
on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: The name of the OSS Teleport repo to build.
        type: string
        default: gravitational/teleport

      oss-teleport-ref:
        description: Tag, branch or reference to OSS teleport to build.
        type: string
        required: true

      ent-teleport-ref:
        description: |
          Tag, branch or reference to Enterprise teleport to include in the
          build. If no value is supplied this workflow will use whatever
          reference is specified in the OSS teleport submodule record.
        type: string

      build-packages:
        description: |
          Build Mac packages for Teleport, tsh and Teleport Connect.
          Packages are not build for push builds. Release builds do
          build packages.
        type: boolean
        default: false

      release-artifacts:
        description: |
          Should the workflow upload the resulting artifacts to the Release
          server?
        type: boolean
        default: false

      release-version:
        description: |
          Override the default release version tag when uploading the build
          artifacts. The default value is deduced from `oss-teleport-ref`,
          which is assumed to be a version tag with a leading `v`. Use this
          override to specify a tag for build debugging purposes.
        type: string

      environment:
        description: |
          GitHub Actions environment in which to run the build. Can be either
          `build-stage` or `build-prod`.
        type: string
        default: build-stage

      workflow-tag:
        description: |
          Tag used to identify workflow runs spawned by this event
        type: string

  # The workflow_dispatch event duplicates the workflow_call input parameters, without descriptions.
  workflow_dispatch:
    inputs:
      oss-teleport-repo:
        type: string
        default: gravitational/teleport
      oss-teleport-ref:
        type: string
        required: true
      ent-teleport-ref:
        type: string
      build-packages:
        type: boolean
        default: false
      release-artifacts:
        type: boolean
        default: false
      release-version:
        type: string
      environment:
        type: string
        default: build-stage
        
      workflow-tag:
        type: string

run-name: "Build MacOS Release Artifacts for ${{ inputs.oss-teleport-ref }}"
jobs:

  identity:
    runs-on: ubuntu-latest
    if: inputs.workflow-tag != ''
    steps:
      - name: ${{ inputs.workflow-tag }}
        run: echo ${{ inputs.workflow-tag }}

  version:
    runs-on: ubuntu-latest
    outputs:
      teleport-version: ${{ steps.determine-version.outputs.teleport-version }}
    steps:
      - name: Determine Teleport version
        id: determine-version
        env:
          # If a teleport version is not explicitly given we assume that the
          # `oss-teleport-ref` is a release tag of the form vX.Y.Z and deduce
          # the version from that.
          TELEPORT_VERSION: ${{ inputs.release-version || inputs.oss-teleport-ref }}
        run: |
          echo "teleport-version=${TELEPORT_VERSION#v}" >> $GITHUB_OUTPUT

  build-artifacts:
    uses: ./.github/workflows/build-mac.yaml
    secrets: inherit # Allows the build-mac workflow to access signing keys/passwords
    strategy:
      # Turn off fail-fast so we don't terminate a working build if another fails
      # for transient reasons. We can re-run the failed jobs to move forward.
      fail-fast: false
      matrix:
        arch: ['amd64', 'arm64']
    with:
      release: "enterprise"
      arch: ${{ matrix.arch }}
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      ent-teleport-ref: ${{ inputs.ent-teleport-ref }}
      release-version: ${{ inputs.release-version }}
      environment: ${{ inputs.environment }}

  build-artifacts-universal:
    uses: ./.github/workflows/build-mac-universal.yaml
    needs: [ build-artifacts ]
    secrets: inherit # Allows the build-mac workflow to access signing keys/passwords
    with:
      release: "enterprise"
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      ent-teleport-ref: ${{ inputs.ent-teleport-ref }}
      build-packages: ${{ inputs.build-packages }}
      release-version: ${{ inputs.release-version }}
      environment: ${{ inputs.environment }}
