# This is a placeholder workflow and will be replaced once the appropriate
# functionality passes code review.
#
# Dispatching workflow calls to a GHA workflow on a branch requires that a
# workflow file with the correct name exists in the default branch, even
# if that workflow bears no resemblance to the target workflow

name: Release Teleport Hardened AMIs
on:
  workflow_dispatch:
    inputs:
      oss-teleport-repo:
        description: |
          The name of the OSS teleport repo to checkout
        required: false
        type: string
        default: "gravitational/teleport"

      oss-teleport-ref:
        description: |
          Git SHA, tag or branch of the revision of OSS teleport to build
        required: true
        type: string

      source-tag:
        description: |
          The semver version of Teleport that we're building for. If not set 
          will be inferred form the `oss-teleport-ref` by assuming that it's
          a standard Teleport release tag in the form vX.Y.Z.
        type: string
        default: ""

      ci-storage-bucket-name:
        description: |
          Name of the AWS S3 bucket holding the Teleport binary tarballs for
          this release
        required: true
        type: string
        default: dronestorage.gravitational.io

      ci-storage-access-role-arn:
        description: |
          ARN of the role used to access the dronestorage bucket, for retrieving 
          artifacts built by Drone.
        required: true
        type: string
        default: arn:aws:iam::126027368216:role/tf-teleport-oci-tag-build-gha

      build-role-arn:
        description: |
          The ARN of the role used to build and store the AMI
        required: true
        type: string
        default: arn:aws:iam::146628656107:role/teleport-ami-tag-build-gha

      build-vpc-id:
        description: |
          ID of the AWS VPC that will house the build infrastructure
        required: true
        type: string
        default: vpc-0af029ea1b68f02dc

      dest-ami-regions:
        description: |
          A comma-separated list of AWS regions to receive the AMIs.
        type: string
        default: eu-north-1,ap-south-1,eu-west-3,eu-west-2,eu-west-1,ap-northeast-3,ap-northeast-2,ap-northeast-1,sa-east-1,ca-central-1,ap-southeast-1,ap-southeast-2,eu-central-1,us-east-1,us-east-2,us-west-1,us-west-2

      workflow-tag:
        description: |
          Tag used to identify workflow runs spawned by this event
        type: string
        default: ""

run-name: Build Hardened AMIs for Teleport ${{ inputs.source-tag != '' && inputs.source-tag || inputs.oss-teleport-ref }}
jobs:
  identity:
    runs-on: ubuntu-latest
    if: inputs.workflow-tag != ''
    steps:
      - name: ${{ inputs.workflow-tag }}
        run: echo ${{ inputs.workflow-tag }}
        
  build-amis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # Required for aws-actions/configure-aws-credentials
    strategy:
        matrix:
          teleport-edition: ['oss', 'ent']
          fips: [true, false]
          exclude:
            # There's no such thing as an OSS FIPS release
            - teleport-edition: oss
              fips: true
          include:
            - teleport-edition: oss
              edition-infix: ""
            - teleport-edition: ent
              edition-infix: "-ent"
            - fips: false
              fips-infix: ""
            - fips: true
              fips-infix: "-fips"
              
    steps:
      - name: Parse Teleport version tag
        id: version
        env:
          VERSION: ${{ inputs.source-tag || inputs.oss-teleport-ref }}
        run: |
          echo teleport=${VERSION#v} >> $GITHUB_OUTPUT

      - name: Checkout Teleport
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        with:
          oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
          oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
          edition: oss # We don't need teleport.e even when building enterprise AMI 
          repo-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
          repo-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}

      - name: Assume Legacy Drone storage AWS role
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          aws-region:  us-west-2
          role-to-assume: ${{ inputs.ci-storage-access-role-arn }}
          role-session-name: "gha-ami-build-${{ github.run_number }}-${{ inputs.source-tag }}"
          role-duration-seconds: 3600

      - name: Download Teleport tarballs
        id: download-tarball
        env:
          ARCHITECTURE: amd64
          TELEPORT_VERSION: ${{ steps.version.outputs.teleport }}
          TAR_EDITION_INFIX: ${{ matrix.edition-infix }}
          TAR_FIPS_INFIX: ${{ matrix.fips-infix }}
          SRC_BUCKET: ${{ inputs.ci-storage-bucket-name }}
        run: |
          TARBALL_NAME=teleport${TAR_EDITION_INFIX}-v${TELEPORT_VERSION}-linux-${ARCHITECTURE}${TAR_FIPS_INFIX}-bin.tar.gz
          aws s3 cp s3://${SRC_BUCKET}/teleport/tag/${TELEPORT_VERSION}/${TARBALL_NAME} ./${TARBALL_NAME}
          echo path=$(readlink -f ./${TARBALL_NAME}) >> $GITHUB_OUTPUT

      - name: Assume tag build AWS role
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          aws-region:  us-west-2
          role-to-assume: ${{ inputs.build-role-arn }}
          role-session-name: "gha-${{ matrix.teleport-edition }}-ami-build-${{ github.run_number }}"
          role-duration-seconds: 3600

      - name: Initialize packer
        working-directory: "${{ github.workspace }}/assets/aws"
        env:
          PACKER_GITHUB_API_TOKEN: ${{ github.token }}
        run: packer init single-ami.pkr.hcl

      - name: Build AMI
        env:
          AWS_VPC_ID: ${{ inputs.build-vpc-id }}
          TELEPORT_VERSION: ${{ steps.version.outputs.teleport }}
          TELEPORT_TYPE: ${{ matrix.teleport-edition }}
          TELEPORT_FIPS: ${{ matrix.fips }}
          TELEPORT_TARBALL: ${{ steps.download-tarball.outputs.path  }}
          DEST_AMI_REGIONS: ${{ inputs.dest-ami-regions }}
        working-directory: "${{ github.workspace }}/assets/aws"
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          export TZ=UTC
          BUILD_TIMESTAMP=$(/bin/date "+%Y%m%d-%H%M%S%Z")
          echo timestamp=${BUILD_TIMESTAMP} >> $GITHUB_OUTPUT

          TELEPORT_FIPS_TAG=""
          if ${TELEPORT_FIPS}; then 
            TELEPORT_FIPS_TAG="-fips"
          fi

          packer build \
            -var aws_account_id=${AWS_ACCOUNT_ID} \
            -var aws_region=us-west-2 \
            -var aws_vpc_id=${AWS_VPC_ID} \
            -var aws_instance_type=t2.medium \
            -var teleport_version=${TELEPORT_VERSION} \
            -var teleport_type=${TELEPORT_TYPE} \
            -var teleport_fips=${TELEPORT_FIPS} \
            -var teleport_tarball=${TELEPORT_TARBALL} \
            -var ami_name=teleport-${TELEPORT_TYPE}-${TELEPORT_VERSION}${TELEPORT_FIPS_TAG}-${BUILD_TIMESTAMP} \
            -var ami_build_timestamp=${BUILD_TIMESTAMP} \
            -var ami_destination_regions=${DEST_AMI_REGIONS} \
            single-ami.pkr.hcl
