name: Release - Build & Publish
run-name: ${{ inputs.cloud-only && 'Cloud ' || '' }}Release of ${{ inputs.oss-teleport-repo }}@${{ inputs.oss-teleport-ref }}${{ inputs.teleport-version && format(' ({0})', inputs.teleport-version) }}
on:
  workflow_dispatch:
    inputs:
      oss-teleport-repo:
        description: The name of the OSS teleport repo to build.
        default: gravitational/teleport
        type: string
      oss-teleport-ref:
        description: Tag, branch or reference to OSS teleport to build.
        type: string
        required: true
      teleport-version:
        description: The semver version of Teleport version that we're building for.
        type: string
      environment:
        description: |
          GitHub Actions environment in which to run the build. Can be either
          `stage` or `prod`.
        type: string
        default: stage
      cloud-only:
        description: Perform a cloud-only release (distroless OCI only)
        type: boolean
        default: false
      slack-notify-channel:
        description: The slack channel to notify the status of the job.
        type: string
  # workflow_call is not supported for this workflow yet as this workflow
  # has already reached the max depth limit of 3 for reusable workflow calls.
  #
  # See: https://docs.github.com/en/actions/sharing-automations/reusing-workflows#limitations
  workflow_call: {}
jobs:
  tag-build:
    name: Build
    secrets: inherit
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    uses: ./.github/workflows/tag-build.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      teleport-version: ${{ inputs.teleport-version }}
      cloud-only: ${{ inputs.cloud-only }}
      environment: build-${{ inputs.environment }}
  tag-publish:
    name: Publish
    needs:
      - tag-build
    secrets: inherit
    permissions:
      actions: write
      contents: read
      id-token: write
    uses: ./.github/workflows/tag-publish.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      teleport-version: ${{ inputs.teleport-version }}
      cloud-only: ${{ inputs.cloud-only }}
      environment: publish-${{ inputs.environment }}
  post-workflow:
    name: Post Workflow Steps
    runs-on: ubuntu-latest
    # The combination of always and needs means this will always run after all other jobs are done
    if: always()
    needs:
      - tag-build
      - tag-publish
    steps:
      # Success
      - name: Slack Notify Succes
        if: inputs.slack-notify-channel && !(contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'))
        uses: slackapi/slack-github-action@37ebaef184d7626c5f204ab8d3baff4262dd30f0 # v1.27.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.TOOLING_ALERTS_SLACK_TOKEN }}
        with:
          channel-id: ${{ inputs.slack-notify-channel }}
          payload: |
            {
              "username": "Release Reporter",
              "text": "*Release Report*",
              "mrkdwn": true,
              "parse": "none",
              "unfurl_links": false,
              "unfurl_media": false,
              "attachments": [
                {
                  "color": "good",
                  "title": "Release for ${{ inputs.teleport-version }} succeeded",
                  "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              ]
            }
      # Failure
      - name: Slack Notify Failure
        if: inputs.slack-notify-channel && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'))
        uses: slackapi/slack-github-action@37ebaef184d7626c5f204ab8d3baff4262dd30f0 # v1.27.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.TOOLING_ALERTS_SLACK_TOKEN }}
        with:
          channel-id: ${{ inputs.slack-notify-channel }}
          payload: |
            {
              "username": "Release Reporter",
              "text": "*Release Report*",
              "mrkdwn": true,
              "parse": "none",
              "unfurl_links": false,
              "unfurl_media": false,
              "attachments": [
                {
                  "color": "danger",
                  "title": "Release for ${{ inputs.teleport-version }} failed - click here to investigate",
                  "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              ]
            }
