# Build a Teleport release from a tag.

name: Tag Build
run-name: ${{ inputs.cloud-only && 'Cloud ' || '' }}Tag Build of ${{ inputs.oss-teleport-repo }}@${{ inputs.oss-teleport-ref }}${{ inputs.teleport-version && format(' ({0})', inputs.teleport-version) }}
on:
  workflow_dispatch:
    inputs:
      oss-teleport-repo:
        description: The name of the OSS teleport repo to build.
        default: gravitational/teleport
        type: string

      oss-teleport-ref:
        description: Tag, branch or reference to OSS teleport to build.
        type: string
        required: true

      teleport-version:
        description: The semver version of Teleport version that we're building for.
        type: string

      environment:
        description: |
          GitHub Actions environment in which to run the build. Can be either
          `build-stage` or `build-prod`.
        type: string
        default: build-stage

      cloud-only:
        description: Perform a cloud-only release (distroless OCI only)
        type: boolean
        default: false
  # The workflow_call event duplicates the workflow_dispatch input parameters, without descriptions. 
  workflow_call:
    inputs:
      oss-teleport-repo:
        default: gravitational/teleport
        type: string
      oss-teleport-ref:
        type: string
      teleport-version:
        type: string
      environment:
        type: string
        default: build-stage
      cloud-only:
        type: boolean
        default: false

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.determine-version.outputs.full }}
    steps:
      - name: Determine Teleport version
        id: determine-version
        uses: gravitational/teleport.e/.github/actions/parse-version@master
        with:
          ref: ${{ inputs.oss-teleport-ref }}
          version: ${{ inputs.teleport-version }}
      - name: Reject non-cloud prereleases being sent to production
        env:
          PRERELEASE_VERSION: ${{ steps.determine-version.outputs.pre-release }}
          IS_CLOUD_ONLY: ${{ inputs.cloud-only }}
          TARGET_ENVIRONMENT: ${{ inputs.environment }}
        run: |
          # If not a production release, allow it
          if [[ "${TARGET_ENVIRONMENT}" != *prod* ]]; then
            exit 0
          fi

          # If the prerelease version is not set (full release),
          # allow it
          if [[ -z "${PRERELEASE_VERSION}"  ]]; then
            exit 0
          fi

          # If a cloud prerelease and a cloud only build, allow it
          if [[ "${PRERELEASE_VERSION}" == cloud* && "${IS_CLOUD_ONLY}" == 'true' ]]; then
            exit 0
          fi

          # Else reject it
          echo "::error title=Prerelease sent to production environment::Prereleases must not be sent to production environments (${TARGET_ENVIRONMENT})." >&2
          exit 1

      - name: Checkout Teleport
        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
        if: inputs.teleport-version == ''
        with:
          oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
          oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
          edition: "oss"
          repo-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
          repo-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}
  
      - name: Reject Tag/Version Mismatch
        env:
          TAG: ${{ inputs.oss-teleport-ref }}
        if: inputs.teleport-version == ''
        run: |
          MAKE_VERSION=$(make print-version)
          if [[ "$TAG" != "v$MAKE_VERSION" ]]; then
            echo "::error title=Version Mismatch::Tag '$TAG' does not match version in Makefile '$MAKE_VERSION'" >&2
            exit 1
          fi

  build-linux:
    needs: setup
    strategy:
      # Turn off fail-fast so one matrix job failure does not cancel others. We
      # can let the others run to completion so we can re-run just the failed jobs.
      fail-fast: false
      matrix:
        arch: [ 'amd64', 'arm64', '386', 'arm' ]
        fips: [ false, true ]
        cloud-only:
          - ${{ inputs.cloud-only }}
        include:
          # Build Teleport connect on amd64 non-fips regular releases (not cloud-only)
          - arch: amd64
            fips: false
            build-connect: ${{ !inputs.cloud-only }}
        exclude:
          # No FIPS for 386 or arm
          - arch: '386'
            fips: true
          - arch: arm
            fips: true
          # No 386 for cloud-only
          - arch: '386'
            cloud-only: true
    name: Build Linux ${{ matrix.arch }}${{ matrix.fips && ' FIPS' || '' }}${{ matrix.build-connect && ' w/Connect' || '' }}
    secrets: inherit
    permissions:
      contents: read
      id-token: write # required for aws-actions/configure-aws-credentials in called workflow
    uses: ./.github/workflows/build-linux.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      release: enterprise
      release-target: ${{ format('release-{0}', matrix.arch) }}${{ matrix.fips && '-fips' || '' }}
      release-version: ${{ needs.setup.outputs.version }}
      build-connect: ${{ matrix.build-connect || false }}
      build-deb: true
      build-rpm: true
      environment: ${{ inputs.environment }}

  build-darwin:
    name: Build Darwin (macOS) Artifacts
    if: ${{ !inputs.cloud-only }}
    needs: setup
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/release-mac.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      build-packages: true
      release-version: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  build-windows:
    name: Build Windows Artifacts
    if: ${{ !inputs.cloud-only }}
    needs: setup
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/build-windows.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      artifact-version: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  build-updater:
    name: Build Teleport Updater
    if: ${{ !inputs.cloud-only }}
    needs: setup
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/build-teleport-updater.yaml
    with:
      updater-version: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  build-operator-oci:
    name: Build Operator OCI
    if: ${{ !inputs.cloud-only }}
    needs: setup
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    # Note we call build-operator-oci directly and not release-teleport-oci as the
    # release workflow does nothing we do not do ourselves.
    uses: ./.github/workflows/build-operator-oci.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      teleport-version: ${{ needs.setup.outputs.version }}
      architectures: "amd64 arm64 arm"
      environment: ${{ inputs.environment }}

  build-kube-agent-updater-oci:
    name: Build Kube Agent Updater OCI
    if: ${{ !inputs.cloud-only }}
    needs: setup
    secrets: inherit
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    uses: ./.github/workflows/release-teleport-kube-agent-updater-oci.yml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      source-tag: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  build-spacelift-runner-oci:
    name: Build Spacelift Runner OCI
    if: ${{ !inputs.cloud-only }}
    needs: setup
    secrets: inherit
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    uses: ./.github/workflows/release-teleport-spacelift-runner-oci.yml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      source-tag: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  build-distroless-oci:
    name: Build Teleport Distroless OCI
    needs: [setup, build-linux]
    secrets: inherit
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    uses: ./.github/workflows/release-teleport-oci-distroless.yml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      source-tag: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  build-tbot-distroless-oci:
    name: Build Tbot Distroless OCI
    if: ${{ !inputs.cloud-only }}
    needs: [setup, build-linux]
    secrets: inherit
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    uses: ./.github/workflows/build-tbot-distroless-oci.yml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      source-tag: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  build-helm:
    name: Build Helm charts
    if: ${{ !inputs.cloud-only }}
    needs: setup
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/build-helm.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      teleport-version: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  build-hardened-ami:
    name: Build Hardened AMI
    if: ${{ !inputs.cloud-only }}
    needs: [setup, build-linux]
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/release-teleport-hardened-amis.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      source-tag: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  build-plugins:
    name: Build Teleport Plugins
    if: ${{ !inputs.cloud-only }}
    needs: setup
    secrets: inherit
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write # required for trivy scan
    uses: ./.github/workflows/build-plugins.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      teleport-version: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  build-install-scripts:
    name: Build install scripts
    if: ${{ !inputs.cloud-only }}
    needs: setup
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/build-install-scripts.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      teleport-version: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}
