---
name: Publish Tag Build
run-name: Publish ${{ inputs.cloud-only && 'Cloud ' || '' }}Tag Build of ${{ inputs.oss-teleport-repo }}@${{ inputs.oss-teleport-ref }}${{ inputs.teleport-version && format(' ({0})', inputs.teleport-version) }}
on:
  workflow_dispatch:
    inputs:
      oss-teleport-repo:
        description: The name of the OSS teleport repo to checkout.
        type: string
        default: gravitational/teleport

      oss-teleport-ref:
        description: Git SHA, tag or branch of the revision of OSS teleport to build.
        type: string
        required: true

      teleport-version:
        description: |
          The tag/semver of the version to publish. If the oss-teleport-ref
          input is not a version tag, this input must be provided.
        type: string

      cloud-only:
        description: Perform a cloud-only release (distroless OCI only)
        type: boolean
        default: false

      environment:
        description: GitHub environment to publish to.
        type: environment
        default: publish-stage

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      pre-release: ${{ steps.determine-version.outputs.pre-release }}
      version: ${{ steps.determine-version.outputs.full }}
    steps:
      - name: Determine Teleport version
        id: determine-version
        uses: gravitational/teleport.e/.github/actions/parse-version@master
        with:
          ref: ${{ inputs.oss-teleport-ref }}
          version: ${{ inputs.teleport-version }}
      - name: Reject non-cloud prereleases being sent to production
        if: ${{ contains(inputs.environment, 'prod') && !contains(fromJson('["", "cloud"]'), steps.determine-version.outputs.pre-release) }}
        env:
          VERSION: ${{ steps.determine-version.outputs.full }}
          GH_ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "::error title=Prerelease sent to production environment::Prereleases ($VERSION) must not be sent to production environments ($GH_ENVIRONMENT)." >&2
          exit 1

  publish-distroless-oci:
    name: Publish distroless OCI images
    needs: setup
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish-teleport-oci-distroless.yml
    with:
      release-source-tag: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  publish-tbot-distroless-oci:
    name: Publish Tbot distroless OCI images
    if: ${{ !inputs.cloud-only }}
    needs: setup
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish-tbot-distroless-oci.yml
    with:
      release-source-tag: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  publish-hardened-amis:
    name: Publish hardened AMIs
    if: ${{ !inputs.cloud-only }}
    needs: setup
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish-teleport-hardened-amis.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      release-source-tag: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  publish-helm:
    name: Publish Helm charts
    if: ${{ !inputs.cloud-only }}
    needs: setup
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish-helm.yaml
    with:
      teleport-version: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  publish-to-houston:
    name: Publish to Houston
    # No staging version of Houston is available, and Houston will be
    # terminated soon.
    if: ${{ !inputs.cloud-only && inputs.environment == 'publish-prod' }}
    needs: setup
    secrets: inherit
    permissions:
      id-token: write
    uses: ./.github/workflows/publish-to-houston.yaml
    with:
      teleport-version: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  publish-kube-agent-updater-oci:
    name: Publish kube agent updater OCI images
    if: ${{ !inputs.cloud-only }}
    needs: setup
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish-teleport-kube-agent-updater-oci.yml
    with:
      release-source-tag: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  publish-operator-oci:
    name: Publish operator OCIs
    if: ${{ !inputs.cloud-only }}
    needs: setup
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish-operator-oci.yaml
    with:
      teleport-version: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  publish-os-packages:
    name: Publish OS Packages
    if: ${{ !inputs.cloud-only }}
    needs: setup
    secrets: inherit
    permissions:
      actions: write
      contents: read
    uses: ./.github/workflows/publish-os-packages.yaml
    with:
      artifact-version: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  publish-spacelift-runner:
    name: Publish spacelift runner OCI image
    if: ${{ !inputs.cloud-only }}
    needs: setup
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish-teleport-spacelift-runner-oci.yml
    with:
      release-source-tag: ${{ needs.setup.outputs.version }}
      environment: ${{ inputs.environment }}

  publish-release:
    name: Publish release
    # This janky logic is because `needs` does not support conditionals.
    # Instead, all the `needs` logic must be packed into `if`.
    # This can, and should be removed once the publish-to-houston step is removed
    if: |
      always()
      && !inputs.cloud-only
      && needs.setup.result == 'success'
      && needs.publish-distroless-oci.result == 'success'
      && needs.publish-hardened-amis.result == 'success'
      && needs.publish-helm.result == 'success'
      && needs.publish-kube-agent-updater-oci.result == 'success'
      && needs.publish-operator-oci.result == 'success'
      && needs.publish-os-packages.result == 'success'
      && needs.publish-spacelift-runner.result == 'success'
      && contains(fromJSON('["success", "skipped"]'), needs.publish-to-houston.result)
    needs:
      - setup
      - publish-distroless-oci
      - publish-hardened-amis
      - publish-helm
      - publish-to-houston
      - publish-kube-agent-updater-oci
      - publish-operator-oci
      - publish-os-packages
      - publish-spacelift-runner
    secrets: inherit
    permissions:
      id-token: write
    uses: ./.github/workflows/publish-release-server.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      version: "v${{ needs.setup.outputs.version }}"
      environment: ${{ inputs.environment }}
