---
# Unit tests for ../actions/get-gha-environment-vars
name: Test Get GHA environment vars action
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/actions/get-gha-environment-vars/**'
      - '.github/workflows/test-get-gha-environment-vars-action.yaml'
jobs:
  test-get-environment-vars:
    runs-on: ubuntu-latest
    strategy:
      # Tests run under separate jobs to ensure that test contexts are not 
      # cross-contaminated by leaving vars set after running a test
      matrix:
        test:
          - name: without a filter
            count-test: '> 0'
          - name: with a filter
            variables: |
              ENVIRONMENT_NAME
            count-test: '== 1'
      fail-fast: false  # Run all tests even if one fails
    name: Test ${{ matrix.test.name }}
    env:
      VAR_PREFIX: TEST_VAR_PREFIX_
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v6
      - name: Run the action ${{ matrix.test.name }}
        uses: ./.github/actions/get-gha-environment-vars
        with:
          environment: stage/build  # Environment doesn't really matter, as long as it contains at least one var
          prefix: ${{ env.VAR_PREFIX }}
          # TODO migrate these to env-loader when/if we set a standard for non-release environments
          github-app-id: ${{ vars.CROSS_ENV_VAR_READING_APP_ID }} # This is a repo-level variable
          github-app-private-key: ${{ secrets.CROSS_ENV_VAR_READING_APP_PRIVATE_KEY }} # This is a repo-level secret
          variables: ${{ matrix.test.variables }}
      - name: Log the environment variables
        run: |
          echo "New environment variables:"
          echo
          env | grep "^$VAR_PREFIX.*="
      - name: Ensure that the expected number of vars were loaded
        run: |
          VAR_COUNT=$(env | grep -c "^$VAR_PREFIX.*=")
          echo "Loaded $VAR_COUNT vars"
          # shellcheck disable=SC1105
          if ! (( VAR_COUNT ${{ matrix.test.count-test }} )); then
            echo "Expected ${{ matrix.test.count-test }} variables to be loaded into the environment, found $VAR_COUNT" >&2
            exit 1
          fi

          echo "Test passed"
