---
# Tests for ../actions/latest-version
name: Test Latest version action
on:
    workflow_dispatch:
    pull_request:
      paths:
        - '.github/actions/latest-version/**'
        - '.github/workflows/test-latest-version-action.yaml'

jobs:
  test-latest-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Ensure tests pass for all valid release server options
        release-server-domain-name:
          - rlz.teleport.sh # Production
          - rlz.cloud.gravitational.io  # Staging
        check-version-prerelease-suffix:
          - null # No prerelease
          - '-dev.some-prerelease'
      fail-fast: false
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v6

      - name: Get the default outputs
        uses: ./.github/actions/latest-version
        id: latest-version-test
        with:
          release-server-domain-name: ${{ matrix.release-server-domain-name }}
      - name: Parse the latest version
        id: parsed-real-latest
        uses: gravitational/teleport.e/.github/actions/parse-version@master
        with:
          version: ${{ steps.latest-version-test.outputs.latest-version }}
      - name: Validate the latest version
        env:
          LATEST_VERSION: ${{ steps.latest-version-test.outputs.latest-version }}
          IS_LATEST_VERSION: ${{ steps.latest-version-test.outputs.is-latest }}
          IS_NEW_MAJOR: ${{ steps.latest-version-test.outputs.is-new-major }}
          # Note that this explicitly checks that the provided value is a full release,
          # and does not contain a 'v' prefix.
          SEMVER_REGEX: ^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)$
          LATEST_HAS_PRE_RELEASE: ${{ !!steps.parsed-real-latest.outputs.pre-release }}
        run: |
          # Check for an invalid value
          if ! echo "$LATEST_VERSION" | grep --perl-regexp --quiet "$SEMVER_REGEX"; then
            echo "The received latest version '$LATEST_VERSION' is not a proper full release version." >&2
            exit 1
          fi

          # Ensure that the other values are empty, as no input was provided
          if [ -n "$IS_NEW_MAJOR" ]; then
            echo "Expected is-latest to be empty, got $IS_LATEST_VERSION" >&2
            exit 1
          fi

          if [ -n "$IS_LATEST_VERSION" ]; then
            echo "Expected is-new-major to be empty, got $IS_LATEST_VERSION" >&2
            exit 1
          fi

          if [[ "$LATEST_HAS_PRE_RELEASE" == "true" ]]; then
            echo "Expected no pre-release on latest version, but found one" >&2
            exit 1
          fi
      
      - name: Set newer "check versions" for future tests
        id: newer-check-versions
        env:
          LATEST_MAJOR: ${{ steps.parsed-real-latest.outputs.major }}
          LATEST_MINOR: ${{ steps.parsed-real-latest.outputs.minor }}
          LATEST_PATCH: ${{ steps.parsed-real-latest.outputs.patch }}
          SUFFIX: ${{ matrix.check-version-prerelease-suffix }}
        run: |
          NEWER_MAJOR=$(( LATEST_MAJOR + 1 ))
          NEWER_MINOR=$(( LATEST_MINOR + 1 ))
          NEWER_PATCH=$(( LATEST_PATCH + 1 ))
          {
            echo "newer-major-version=$NEWER_MAJOR.0.0$SUFFIX"
            echo "newer-minor-version=$LATEST_MAJOR.$NEWER_MINOR.0$SUFFIX"
            echo "newer-patch-version=$LATEST_MAJOR.$LATEST_MINOR.$NEWER_PATCH$SUFFIX"
          } > "$GITHUB_OUTPUT"

      - name: Get outputs for new major version
        uses: ./.github/actions/latest-version
        id: new-major
        with:
          release-server-domain-name: ${{ matrix.release-server-domain-name }}
          check-version: ${{ steps.newer-check-versions.outputs.newer-major-version }}
      - name: Check outputs for new major version
        env:
          IS_LATEST_VERSION: ${{ steps.new-major.outputs.is-latest }}
          IS_NEW_MAJOR: ${{ steps.new-major.outputs.is-new-major }}
        run: |
          # Check the value explicitly, avoiding any bash truthy coercions
          if [ "$IS_LATEST_VERSION" != "true" ]; then
            echo "Expected is-latest to be 'true', got '$IS_LATEST_VERSION'" >&2
            exit 1
          fi

          if [ "$IS_NEW_MAJOR" != "true" ]; then
            echo "Expected is-new-major to be 'true', got '$IS_NEW_MAJOR'" >&2
            exit 1
          fi

      - name: Get outputs for new minor version, same major
        uses: ./.github/actions/latest-version
        id: new-minor
        with:
          release-server-domain-name: ${{ matrix.release-server-domain-name }}
          check-version: ${{ steps.newer-check-versions.outputs.newer-minor-version }}
      - name: Check outputs for new minor version, same major
        env:
          IS_LATEST_VERSION: ${{ steps.new-minor.outputs.is-latest }}
          IS_NEW_MAJOR: ${{ steps.new-minor.outputs.is-new-major }}
        run: |
          # Check the value explicitly, avoiding any bash truthy coercions
          if [ "$IS_LATEST_VERSION" != "true" ]; then
            echo "Expected is-latest to be 'true', got '$IS_LATEST_VERSION'" >&2
            exit 1
          fi

          if [ "$IS_NEW_MAJOR" != "false" ]; then
            echo "Expected is-new-major to be 'false', got '$IS_NEW_MAJOR'" >&2
            exit 1
          fi

      - name: Get outputs for new patch version, same major and minor
        uses: ./.github/actions/latest-version
        id: new-patch
        with:
          release-server-domain-name: ${{ matrix.release-server-domain-name }}
          check-version: ${{ steps.newer-check-versions.outputs.newer-patch-version }}
      - name: Check outputs for new patch version, same major and minor
        env:
          IS_LATEST_VERSION: ${{ steps.new-patch.outputs.is-latest }}
          IS_NEW_MAJOR: ${{ steps.new-patch.outputs.is-new-major }}
        run: |
          # Check the value explicitly, avoiding any bash truthy coercions
          if [ "$IS_LATEST_VERSION" != "true" ]; then
            echo "Expected is-latest to be 'true', got '$IS_LATEST_VERSION'" >&2
            exit 1
          fi

          if [ "$IS_NEW_MAJOR" != "false" ]; then
            echo "Expected is-new-major to be 'false', got '$IS_NEW_MAJOR'" >&2
            exit 1
          fi

      - name: Get outputs for same version
        uses: ./.github/actions/latest-version
        id: same-version
        with:
          release-server-domain-name: ${{ matrix.release-server-domain-name }}
          check-version: ${{ format('{0}{1}', steps.latest-version-test.outputs.latest-version, matrix.check-version-prerelease-suffix ) }}
      - name: Check outputs for same version
        env:
          IS_LATEST_VERSION: ${{ steps.same-version.outputs.is-latest }}
          IS_NEW_MAJOR: ${{ steps.same-version.outputs.is-new-major }}
          IS_CHECK_PRE_RELEASE: ${{ !!matrix.check-version-prerelease-suffix }}
        run: |
          # Check the value explicitly, avoiding any bash truthy coercions
          if [ "$IS_LATEST_VERSION" != "$IS_CHECK_PRE_RELEASE" ]; then
            echo "Expected is-latest to be '$IS_CHECK_PRE_RELEASE', got '$IS_LATEST_VERSION'" >&2
            exit 1
          fi

          if [ "$IS_NEW_MAJOR" != "false" ]; then
            echo "Expected is-new-major to be 'false', got '$IS_NEW_MAJOR'" >&2
            exit 1
          fi

      - name: Get outputs for an older version
        uses: ./.github/actions/latest-version
        id: older-version
        with:
          release-server-domain-name: ${{ matrix.release-server-domain-name }}
          # This must be < 0.0.1 because there is a release for 0.0.1
          check-version: ${{ format('0.0.0{0}', matrix.check-version-prerelease-suffix) }}
      - name: Check outputs for an older version
        env:
          IS_LATEST_VERSION: ${{ steps.older-version.outputs.is-latest }}
          IS_NEW_MAJOR: ${{ steps.older-version.outputs.is-new-major }}
        run: |
          # Check the value explicitly, avoiding any bash truthy coercions
          if [ "$IS_LATEST_VERSION" != "false" ]; then
            echo "Expected is-latest to be 'false', got '$IS_LATEST_VERSION'" >&2
            exit 1
          fi

          if [ "$IS_NEW_MAJOR" != "false" ]; then
            echo "Expected is-new-major to be 'false', got '$IS_NEW_MAJOR'" >&2
            exit 1
          fi
