---
name: Test the Teleport updater

on:
  pull_request:
    paths:
      - .github/workflows/build-teleport-updater.yaml
      - .github/workflows/deploy-packages.yaml
      - .github/actions/load-gpg-key/action.yaml
      - .github/actions/deploy-os-package/action.yaml
      - assets/systemd-unit-upgrader/**

jobs:
  setup:
    name: Setup for the test
    runs-on: ubuntu-latest
    outputs:
      artifact-version: ${{ steps.gen-version.outputs.artifact-version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a new unique version based on the nearest tag
        id: gen-version
        run: |
          ARTIFACT_VERSION="$(git describe --tags --match "v[[:digit:]]*.[[:digit:]]*.[[:digit:]]")"
          echo "Artifact version: $ARTIFACT_VERSION" >> "$GITHUB_STEP_SUMMARY"
          echo "artifact-version=$ARTIFACT_VERSION" >> "$GITHUB_OUTPUT"
  build:
    name: Build the updater
    uses: ./.github/workflows/build-teleport-updater.yaml
    needs:
      - setup
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    with:
      environment: "build-stage"  # If a QA environment is ever deployed then this should probably to it
      updater-version: ${{ needs.setup.outputs.artifact-version }}
  # The updater is tightly coupled with OS package repos, so the package must be published to OS package repos to test
  publish:
    name: Publish the updater
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    needs:
      - setup
      - build
    concurrency: Only allow a single teleport-ent-updater ${{ matrix.repo-type }} deployment at a time
    strategy:
      fail-fast: false  # If either APT or YUM deployment fails, let the other one run before failing
      matrix:
        repo-type:
          - apt
          - yum
    env:
      VERSION_CHANNEL: cloud
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Deploy package to `stable/${{ env.VERSION_CHANNEL }}` ${{ matrix.repo-type }} repos
        uses: ./.github/actions/deploy-os-package
        with:
          environment: "publish-stage"
          repo-type: ${{ matrix.repo-type }}
          artifact-tag: ${{ needs.setup.outputs.artifact-version }}
          version-channel: ${{ env.VERSION_CHANNEL }}
          package-name-filter: "teleport-ent-updater*"
          package-to-test: teleport-ent-updater
          do-teleport-package-tests: true
          workflow-git-reference: ${{ github.head_ref }}
    
