name: Tests

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-22.04-16core

    permissions:
      contents: read

    container:
      image: ghcr.io/gravitational/teleport-buildbox:teleport15
      options: --cap-add=SYS_ADMIN --privileged

    steps:
      - name: Checkout OSS Teleport
        uses: actions/checkout@v4
        with:
          repository: gravitational/teleport  # This may need to be updated
          ref: ${{ github.base_ref }}

      - name: Checkout Enterprise Teleport
        uses: actions/checkout@v4
        with:
          path: e

      - name: Fetch go cache paths
        id: go-cache-paths
        shell: bash
        run: |
          echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          go build ${GITHUB_WORKSPACE}/e/tool/tctl
          go build ${GITHUB_WORKSPACE}/e/tool/teleport

      - name: Run tests
        timeout-minutes: 40
        run: |
          GOFLAGS="-tags=tpmsimulator" make -C ${GITHUB_WORKSPACE}/e/ -j test
          cd ${GITHUB_WORKSPACE}/e; go test -run=IGNOREME -bench=. -benchtime=1x ./...
