name: Tests

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      go: ${{ steps.changes.outputs.go }}
    steps:
      - name: Checkout
        # Only checkout if not a pull request. dorny/paths-filter accesses changed files
        # on a PR via the API and does not need a checked-out repo.
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v6
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          base: ${{ github.event.pull_request.base.ref || github.event.merge_group.base_ref }}
          ref: ${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref }}
          list-files: escape
          filters: |
            go:
              - '.github/workflows/unit-tests.yaml'
              - '**.go'
              - 'go.mod'
              - 'go.sum'
              - 'fixtures/**'
  test:
    name: Tests
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' }}
    runs-on: ubuntu-22.04-16core

    permissions:
      contents: read
      id-token: write # required for AWS credentials

    container:
      image: ghcr.io/gravitational/teleport-buildbox:teleport19
      options: --cap-add=SYS_ADMIN --privileged

    steps:
      - name: Checkout OSS Teleport
        uses: actions/checkout@v6
        with:
          repository: gravitational/teleport  # This may need to be updated
          # base_ref is only available for pull_request triggers
          # for merge_group triggers we need to pull from the event payload
          ref: ${{ github.event.pull_request.base.ref || github.event.merge_group.base_ref }}

      - name: Checkout Enterprise Teleport
        uses: actions/checkout@v6
        with:
          path: e

      - name: Fetch go cache paths
        id: go-cache-paths
        shell: bash
        run: |
          echo "go-build=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
          echo "go-mod=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"

      - name: Build
        run: |
          go build "${GITHUB_WORKSPACE}/e/tool/teleport"

      - name: Run tests
        timeout-minutes: 40
        run: |
          make -C "${GITHUB_WORKSPACE}/e/" -j test TPMSIMULATOR_TEST_TAG=tpmsimulator
          cd "${GITHUB_WORKSPACE}/e"; go test -run=IGNOREME -bench=. -benchtime=1x ./...

      - name: Upload test metrics
        if: always()
        continue-on-error: true # Do not fail the workflow
        uses: ./e/.github/actions/upload-test-metrics
