name: "Windows Authentication Package Build"

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'windowsauth/**'
  merge_group:
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'windowsauth/installer/go.mod'
      - name: Setup Rust
        #embedded-resource crate doesn't like cross-compilation from msvc to mingw
        run: |
          rustup toolchain install 1.71.1-x86_64-pc-windows-gnu
          rustup default 1.71.1-x86_64-pc-windows-gnu
          rustup show
      - name: Build all
        run: make -C windowsauth VERSION=${env:VERSION} all
        env:
          VERSION: ${{ inputs.version }}
      - name: Test
        run: make -C windowsauth test
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: windowsauth/build/
