/**
 * Teleport
 * Copyright (C) 2023  Gravitational, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import type { ComponentType } from 'react';

import * as i from './icons';
import type { MonoIconProps } from './MonoIcon';
import * as Icons from './MonoIcons';

export type IconSpec =
  | { kind: 'mono'; Icon: ComponentType<MonoIconProps> }
  | { kind: 'themed'; dark: string; light: string }
  | { kind: 'static'; src: string };

/**
 * A map of icon name -> rendering spec.
 *
 * Use all lowercap for naming the icon keys.
 *
 * Since the icon key names will be used against matchers (eg: function guessAppIcon),
 * name the icon as close to the real names as possible.
 *
 * In case of duplicate icon names, name the keys with their brand domain extension
 *   eg: apollo -> 'apollo.io'
 */
export const resourceIconSpecs = {
  activemq: staticIcon(i.activemq),
  adept: themed(i.adeptDark, i.adeptLight),
  adobe: staticIcon(i.adobe),
  adobecreativecloud: mono(Icons.Adobecreativecloud),
  adobemarketo: staticIcon(i.adobemarketo),
  airbase: staticIcon(i.airbase),
  airtable: staticIcon(i.airtable),
  algolia: themed(i.algoliaDark, i.algoliaLight),
  altisales: mono(Icons.Altisales),
  ansible: mono(Icons.Ansible),
  anthem: staticIcon(i.anthem),
  'apollo.io': mono(Icons.ApolloIo),
  anthropic: mono(Icons.Anthropic),
  apple: mono(Icons.Apple),
  application: staticIcon(i.application),
  argocd: staticIcon(i.argocd),
  asana: staticIcon(i.asana),
  assemble: themed(i.assembleDark, i.assembleLight),
  atlassian: staticIcon(i.atlassian),
  atlassianbitbucket: staticIcon(i.atlassianbitbucket),
  atlassianjiraservice: staticIcon(i.atlassianjiraservicemanagement),
  atlassianstatus: staticIcon(i.atlassianstatuspage),
  auth0: mono(Icons.Auth0),
  avalara: staticIcon(i.avalara),
  aws: themed(i.awsDark, i.awsLight),
  awsaccount: staticIcon(i.awsAccount),
  awsathena: staticIcon(i.awsathena),
  awsaurora: staticIcon(i.awsaurora),
  awscommandlineinterface: staticIcon(i.awscommandlineinterface),
  awsdynamodb: staticIcon(i.awsdynamodb),
  awsec2: staticIcon(i.awsec2),
  awseks: staticIcon(i.awseks),
  awselasticache: staticIcon(i.awselasticache),
  awselasticblockstore: staticIcon(i.awselasticblockstore),
  awselasticcontainerservice: staticIcon(i.awselasticcontainerservice),
  awselasticsearchservice: staticIcon(i.awselasticsearchservice),
  awsfargate: staticIcon(i.awsfargate),
  awsiamidentitycenter: staticIcon(i.awsiamidentitycenter),
  awsidentityandaccessmanagementiam: staticIcon(
    i.awsidentityandaccessmanagementiam
  ),
  awskeyspaces: staticIcon(i.awskeyspaces),
  awsmanagementconsole: staticIcon(i.awsmanagementconsole),
  awsmemorydb: staticIcon(i.awsmemorydb),
  awsrds: staticIcon(i.awsrds),
  awsredshift: staticIcon(i.awsredshift),
  awssimplestorageservices3: staticIcon(i.awssimplestorageservices3),
  awssinglesignon: staticIcon(i.awssinglesignon),
  awsquicksight: staticIcon(i.awsquicksight),
  azure: staticIcon(i.azure),
  bill: staticIcon(i.bill),
  bolt: mono(Icons.Bolt),
  bonusly: staticIcon(i.bonusly),
  box: staticIcon(i.box),
  browserstack: staticIcon(i.browserstack),
  calendly: staticIcon(i.calendly),
  calm: staticIcon(i.calm),
  canva: mono(Icons.Canva),
  captivateiq: mono(Icons.Captivateiq),
  careerminds: themed(i.careermindsDark, i.careermindsLight),
  carta: mono(Icons.Carta),
  chatgpt: mono(Icons.Openai),
  checkly: staticIcon(i.checkly),
  checkr: staticIcon(i.checkr),
  circleci: mono(Icons.Circleci),
  clari: staticIcon(i.clari),
  claude: staticIcon(i.anthropicclaude),
  clay: staticIcon(i.clay),
  clearbit: staticIcon(i.clearbit),
  clearfeed: staticIcon(i.clearfeed),
  clickhouse: mono(Icons.Clickhouse),
  cloudflare: staticIcon(i.cloudflare),
  cloudzero: staticIcon(i.cloudzero),
  cockroach: themed(i.cockroachDark, i.cockroachLight),
  coder: mono(Icons.Coder),
  codex: mono(Icons.Openai),
  coefficient: mono(Icons.Coefficient),
  commonroom: mono(Icons.Commonroom),
  conveyor: staticIcon(i.conveyor),
  coreweave: themed(i.coreweaveDark, i.coreweaveLight),
  cronitor: staticIcon(i.cronitor),
  cultureamp: mono(Icons.Cultureamp),
  cursor: mono(Icons.Cursor),
  customerio: mono(Icons.Customerio),
  database: staticIcon(i.database),
  datadog: themed(i.datadogDark, i.datadogLight),
  dealhub: staticIcon(i.dealhub),
  deel: mono(Icons.Deel),
  desktop: staticIcon(i.desktop),
  digicert: mono(Icons.Digicert),
  digitalocean: staticIcon(i.digitalocean),
  discord: staticIcon(i.discord),
  dmarcian: staticIcon(i.dmarcian),
  docker: mono(Icons.Docker),
  docusign: themed(i.docusignDark, i.docusignLight),
  donut: staticIcon(i.donut),
  drata: mono(Icons.Drata),
  drift: mono(Icons.Drift),
  dropbox: staticIcon(i.dropbox),
  duo: themed(i.duoDark, i.duoLight),
  dynamo: staticIcon(i.awsdynamodb),
  ec2: staticIcon(i.ec2),
  eks: staticIcon(i.eks),
  elastic: staticIcon(i.elastic),
  elevenlabs: mono(Icons.Elevenlabs),
  email: mono(Icons.Email),
  entraid: staticIcon(i.entraid),
  eventbrite: staticIcon(i.eventbrite),
  excalidraw: staticIcon(i.excalidraw),
  figma: staticIcon(i.figma),
  fontawesome: staticIcon(i.fontawesome),
  foqal: staticIcon(i.foqal),
  fossa: staticIcon(i.fossa),
  'frame.io': mono(Icons.FrameIo),
  fyxer: staticIcon(i.fyxer),
  g2: staticIcon(i.g2),
  gable: staticIcon(i.gable),
  gem: mono(Icons.Gem),
  gemini: staticIcon(i.gemini),
  git: mono(Icons.Git),
  github: themed(i.githubDark, i.githubLight),
  gitlab: staticIcon(i.gitlab),
  glean: mono(Icons.Glean),
  gmail: staticIcon(i.gmail),
  go1: mono(Icons.Go1),
  goldcast: staticIcon(i.goldcast),
  google: staticIcon(i.google),
  googleanalytics: staticIcon(i.googleanalytics),
  googlecalendar: staticIcon(i.googlecalendar),
  googlecloud: staticIcon(i.googlecloud),
  googledrive: staticIcon(i.googledrive),
  googletag: staticIcon(i.googletag),
  googlevoice: staticIcon(i.googlevoice),
  grafana: staticIcon(i.grafana),
  grammarly: staticIcon(i.grammarly),
  grok: themed(i.grokDark, i.grokLight),
  grubhub: staticIcon(i.grubhub),
  guideline: mono(Icons.Guideline),
  hackerone: mono(Icons.Hackerone),
  hashicorpvault: staticIcon(i.hashicorpvault),
  headliner: staticIcon(i.headliner),
  highspot: staticIcon(i.highspot),
  hootsuite: staticIcon(i.hootsuite),
  cilium: themed(i.ciliumDark, i.ciliumLight),
  ibm: mono(Icons.Ibm),
  'incident.io': staticIcon(i.incidentio),
  inkeep: staticIcon(i.inkeep),
  instantly: mono(Icons.Instantly),
  instruqt: themed(i.instruqtDark, i.instruqtLight),
  intellimize: staticIcon(i.intellimize),
  intune: staticIcon(i.intune),
  ipstack: staticIcon(i.ipstack),
  jamf: staticIcon(i.jamf),
  jenkins: staticIcon(i.jenkins),
  jetbrains: staticIcon(i.jetbrains),
  jira: staticIcon(i.jira),
  kaiser: mono(Icons.Kaiser),
  kisi: mono(Icons.Kisi),
  kling: mono(Icons.Klingai),
  kollide: staticIcon(i.kollide),
  kube: staticIcon(i.kube),
  kubeserver: staticIcon(i.kubeserver),
  laptop: staticIcon(i.laptop),
  leadiq: staticIcon(i.leadiq),
  lean: themed(i.leanDark, i.leanLight),
  leandata: staticIcon(i.leandata),
  lever: staticIcon(i.lever),
  linkedin: mono(Icons.Linkedin),
  linux: themed(i.linuxDark, i.linuxLight),
  loom: staticIcon(i.loom),
  lorikeet: staticIcon(i.lorikeet),
  lovable: staticIcon(i.lovable),
  'lucid.co': mono(Icons.LucidCo),
  lusha: mono(Icons.Lusha),
  magnific: mono(Icons.Magnific),
  mailgun: staticIcon(i.mailgun),
  mariadb: themed(i.mariadbDark, i.mariadbLight),
  markdown: mono(Icons.Markdown),
  mattermost: themed(i.mattermostDark, i.mattermostLight),
  maxio: mono(Icons.Maxio),
  mcp: mono(Icons.Mcp),
  mcpCursor: themed(i.mcpCursorDark, i.mcpCursorLight),
  mcpVscode: staticIcon(i.mcpVscode),
  mcpVscodeInsiders: staticIcon(i.mcpVscodeInsiders),
  metabase: staticIcon(i.metabase),
  metaview: themed(i.metaviewDark, i.metaviewLight),
  micro1: mono(Icons.Micro1),
  microsoft: staticIcon(i.microsoft),
  microsoftactivedirectory: staticIcon(i.microsoftactivedirectory),
  microsoftadvertising: staticIcon(i.microsoftadvertising),
  microsoftexcel: staticIcon(i.microsoftexcel),
  microsoftonedrive: staticIcon(i.microsoftonedrive),
  microsoftonenote: staticIcon(i.microsoftonenote),
  microsoftoutlook: staticIcon(i.microsoftoutlook),
  microsoftpowerpoint: staticIcon(i.microsoftpowerpoint),
  microsoftteams: staticIcon(i.microsoftteams),
  microsoftvisualstudiocode: staticIcon(i.microsoftvisualstudiocode),
  microsoftword: staticIcon(i.microsoftword),
  mongo: mono(Icons.Mongo),
  mysqllarge: themed(i.mysqlLargeDark, i.mysqlLargeLight),
  mysqlsmall: mono(Icons.MysqlSmall),
  n8n: staticIcon(i.n8n),
  namecheap: staticIcon(i.namecheap),
  navan: mono(Icons.Navan),
  neverbounce: themed(i.neverbounceDark, i.neverbounceLight),
  notion: staticIcon(i.notion),
  oasisopen: staticIcon(i.oasisopen),
  okta: mono(Icons.Okta),
  oktaAlt: staticIcon(i.oktaAlt),
  '101domain': staticIcon(i.onehundredonedomain),
  onelogin: themed(i.oneloginDark, i.oneloginLight),
  '1password': mono(Icons.Onepassword),
  openai: mono(Icons.Openai),
  opencomp: staticIcon(i.opencomp),
  openid: staticIcon(i.openid),
  opsgenie: staticIcon(i.opsgenie),
  'orbit.love': staticIcon(i.orbitLove),
  oracle: staticIcon(i.oracle),
  orcasecurity: themed(i.orcasecurityDark, i.orcasecurityLight),
  'outreach.io': staticIcon(i.outreachIo),
  pagerduty: staticIcon(i.pagerduty),
  panther: mono(Icons.Panther),
  parallels: staticIcon(i.parallels),
  pencil: themed(i.pencilDark, i.pencilLight),
  perplexity: mono(Icons.Perplexity),
  photoroom: mono(Icons.Photoroom),
  pingdom: staticIcon(i.pingdom),
  podigee: staticIcon(i.podigee),
  polleverywhere: staticIcon(i.polleverywhere),
  portswigger: staticIcon(i.portswigger),
  postgres: staticIcon(i.postgres),
  posthog: themed(i.posthogDark, i.posthogLight),
  productboard: staticIcon(i.productboard),
  prometheus: staticIcon(i.prometheus),
  putty: staticIcon(i.putty),
  qualified: staticIcon(i.qualified),
  quickbooks: staticIcon(i.quickbooks),
  rabbitmq: staticIcon(i.rabbitmq),
  rds: staticIcon(i.rds),
  reachdesk: mono(Icons.Reachdesk),
  redhat: staticIcon(i.redhat),
  redis: staticIcon(i.redis),
  redshift: staticIcon(i.awsredshift),
  relay: staticIcon(i.relay),
  replit: staticIcon(i.replit),
  retell: mono(Icons.Retellai),
  ringlead: staticIcon(i.ringlead),
  rippling: mono(Icons.Rippling),
  salesforce: staticIcon(i.salesforce),
  sanity: staticIcon(i.sanity),
  scim: mono(Icons.Scim),
  securecodewarrior: themed(i.securecodewarriorDark, i.securecodewarriorLight),
  semrush: staticIcon(i.semrush),
  sendgrid: staticIcon(i.sendgrid),
  sentry: mono(Icons.Sentry),
  sequoia: mono(Icons.Sequoia),
  selfhosted: staticIcon(i.database),
  server: staticIcon(i.server),
  servicenow: staticIcon(i.servicenow),
  shopify: staticIcon(i.shopify),
  '6sense': themed(i.sixsenseDark, i.sixsenseLight),
  skype: staticIcon(i.skype),
  slab: staticIcon(i.slab),
  slack: staticIcon(i.slack),
  snowflake: staticIcon(i.snowflake),
  snyk: mono(Icons.Snyk),
  solveintelligence: mono(Icons.Solveintelligence),
  spacelift: themed(i.spaceliftDark, i.spaceliftLight),
  sparrow: staticIcon(i.sparrow),
  strapi: staticIcon(i.strapi),
  stripe: mono(Icons.Stripe),
  tableau: staticIcon(i.tableau),
  tabnine: staticIcon(i.tabnine),
  temporal: mono(Icons.Temporal),
  terraform: staticIcon(i.terraform),
  tlaplus: themed(i.tlaplusDark, i.tlaplusLight),
  'tla+': themed(i.tlaplusDark, i.tlaplusLight),
  torq: themed(i.torqDark, i.torqLight),
  'troops.ai': mono(Icons.TroopsAi),
  twilio: staticIcon(i.twilio),
  twitter: mono(Icons.Twitter),
  userorbit: themed(i.userorbitDark, i.userorbitLight),
  validity: staticIcon(i.validity),
  valimail: staticIcon(i.valimail),
  varicent: mono(Icons.Varicent),
  vendr: staticIcon(i.vendr),
  vercel: mono(Icons.Vercel),
  weavegitops: staticIcon(i.weavegitops),
  windows: mono(Icons.Windows),
  windsurf: mono(Icons.Windsurf),
  wiz: mono(Icons.Wiz),
  workshop: mono(Icons.Workshop),
  youtube: staticIcon(i.youtube),
  zapier: staticIcon(i.zapier),
  zendesk: mono(Icons.Zendesk),
  zoom: staticIcon(i.zoom),
  zoominfo: staticIcon(i.zoominfo),
} satisfies Record<string, IconSpec>;

export type ResourceIconName = keyof typeof resourceIconSpecs;

export const iconNames = Object.keys(resourceIconSpecs) as ResourceIconName[];

/** Single full-color image used for all themes. */
function staticIcon(src: string): IconSpec {
  return { kind: 'static', src };
}

/** Generated monochrome `currentColor` component; themed via CSS. */
function mono(Icon: ComponentType<MonoIconProps>): IconSpec {
  return {
    kind: 'mono',
    Icon,
  };
}

/** Distinct dark/light artwork swapped via the theme class on `<html>`. */
function themed(dark: string, light: string): IconSpec {
  return {
    kind: 'themed',
    dark,
    light,
  };
}
