// Copyright 2023 Gravitational, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts"
// @generated from file teleport/resourceusage/v1/resourceusage_service.proto (package teleport.resourceusage.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetUsageRequest, GetUsageResponse } from "./resourceusage_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ResourceUsageService is a service to fetch information about the usage of limited resources on usage-billed plans.
 *
 * @generated from service teleport.resourceusage.v1.ResourceUsageService
 */
export const ResourceUsageService = {
  typeName: "teleport.resourceusage.v1.ResourceUsageService",
  methods: {
    /**
     * GetUsage returns usage information for all limited resources.
     *
     * @generated from rpc teleport.resourceusage.v1.ResourceUsageService.GetUsage
     */
    getUsage: {
      name: "GetUsage",
      I: GetUsageRequest,
      O: GetUsageResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

