// Code generated by _gen/main.go DO NOT EDIT
/*
Copyright 2015-2024 Gravitational, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package legacy

import (
	"context"

	apitypes "github.com/gravitational/teleport/api/types"
	"github.com/gravitational/trace"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"

	token "github.com/gravitational/teleport/integrations/terraform/tfschema"
	"github.com/gravitational/teleport/integrations/terraform/provider/internal/tfdiag"
)

var _ datasource.DataSource = &dataSourceTeleportProvisionToken{}

// dataSourceTeleportProvisionToken is the resource
type dataSourceTeleportProvisionToken struct {
	p Provider
}

// NewDataSourceProvisionToken creates the empty data source
func NewDataSourceProvisionToken(p provider.Provider) datasource.DataSource {
	return dataSourceTeleportProvisionToken{
		p: p.(Provider),
	}
}

// Metadata returns the full name of the data source.
func (r dataSourceTeleportProvisionToken) Metadata(_ context.Context, _ datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "teleport_provision_token"
}

// GetSchema returns the data source schema
func (r dataSourceTeleportProvisionToken) GetSchema(ctx context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return token.GenSchemaProvisionTokenV2(ctx)
}

// Read reads teleport ProvisionToken
func (r dataSourceTeleportProvisionToken) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var id types.String
	diags := req.Config.GetAttribute(ctx, path.Root("metadata").AtName("name"), &id)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	provisionTokenI, err := r.p.Client().GetToken(ctx, id.Value)
	if err != nil {
		resp.Diagnostics.Append(tfdiag.DiagFromWrappedErr("Error reading ProvisionToken", trace.Wrap(err), "token"))
		return
	}

	var state types.Object
	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Todo: Remove after updating terraform-plugin to >=v1.5.0.
	// terraform-plugin-testing version <1.5.0 requires data resources to
	// implement the 'id' attribute.
	// https://developer.hashicorp.com/terraform/plugin/framework/acctests#no-id-found-in-attributes
	v, ok := state.Attrs["id"]
	if !ok || v.IsNull() {
		state.Attrs["id"] = id
	}

	
	provisionToken := provisionTokenI.(*apitypes.ProvisionTokenV2)
	diags = token.CopyProvisionTokenV2ToTerraform(ctx, provisionToken, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}
