// Code generated by _gen/main.go DO NOT EDIT
/*
Copyright 2015-2024 Gravitational, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package legacy

import (
	"context"
	"fmt"
	apitypes "github.com/gravitational/teleport/api/types"

	autoupdatev1 "github.com/gravitational/teleport/api/gen/proto/go/teleport/autoupdate/v1"
	headerv1 "github.com/gravitational/teleport/api/gen/proto/go/teleport/header/v1"
	"github.com/gravitational/trace"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"

	schemav1 "github.com/gravitational/teleport/integrations/terraform/tfschema/autoupdate/v1"
	"github.com/gravitational/teleport/integrations/terraform/provider/internal/tfdiag"
)

var _ resource.Resource = &resourceTeleportAutoUpdateConfig{}

// resourceTeleportAutoUpdateConfig is the resource
type resourceTeleportAutoUpdateConfig struct {
	p Provider
}

// NewResourceAutoUpdateConfig creates the empty resource
func NewResourceAutoUpdateConfig(p provider.Provider) resource.Resource {
	return resourceTeleportAutoUpdateConfig{
		p: p.(Provider),
	}
}

// Metadata returns the full name of the resource
func (r resourceTeleportAutoUpdateConfig) Metadata(_ context.Context, _ resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "teleport_autoupdate_config"
}

// GetSchema returns the resource schema
func (r resourceTeleportAutoUpdateConfig) GetSchema(ctx context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return schemav1.GenSchemaAutoUpdateConfig(ctx)
}

// Create creates the AutoUpdateConfig
func (r resourceTeleportAutoUpdateConfig) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	if !r.p.IsConfigured(resp.Diagnostics) {
		return
	}

	var plan types.Object
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	autoUpdateConfig := &autoupdatev1.AutoUpdateConfig{}
	diags = schemav1.CopyAutoUpdateConfigFromTerraform(ctx, plan, autoUpdateConfig)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	autoUpdateConfig.Kind = apitypes.KindAutoUpdateConfig

	
	if autoUpdateConfig.GetMetadata() == nil {
		autoUpdateConfig.Metadata = &headerv1.Metadata{}
	}
	if autoUpdateConfig.GetMetadata().GetName() == "" {
		autoUpdateConfig.Metadata.Name = apitypes.MetaNameAutoUpdateConfig
	}

	autoUpdateConfigBefore, err := r.p.Client().GetAutoUpdateConfig(ctx)
	if err != nil && !trace.IsNotFound(err) {
		resp.Diagnostics.Append(tfdiag.DiagFromWrappedErr("Error reading AutoUpdateConfig", trace.Wrap(err), "autoupdate_config"))
		return
	}

	_, err = r.p.Client().CreateAutoUpdateConfig(ctx, autoUpdateConfig)
	if err != nil {
		resp.Diagnostics.Append(tfdiag.DiagFromWrappedErr("Error creating AutoUpdateConfig", trace.Wrap(err), "autoupdate_config"))
		return
	}

	// Not really an inferface, just using the same name for easier templating.
	var autoUpdateConfigI *autoupdatev1.AutoUpdateConfig
	

	// Try getting the resource until it exists and is different than the previous ones.
	// There are two types of singleton resources:
	// - the ones who can deleted and return a trace.NotFoundErr
	// - the ones who cannot be deleted, only reset. In this case, the resource revision is used to know if the change got applied.
	tries := 0
	retry, err := r.p.Retry()
	if err != nil {
		return
	}
	for {
		tries = tries + 1
		autoUpdateConfigI, err = r.p.Client().GetAutoUpdateConfig(ctx)
		if trace.IsNotFound(err) {
		    select {
			case <-ctx.Done():
			    resp.Diagnostics.Append(tfdiag.DiagFromWrappedErr("Error reading AutoUpdateConfig", trace.Wrap(ctx.Err()), "autoupdate_config"))
				return
			case <-retry.After():
			}
			if tries >= r.p.MaxRetries() {
				diagMessage := fmt.Sprintf("Error reading AutoUpdateConfig (tried %d times) - state outdated, please import resource", tries)
				resp.Diagnostics.AddError(diagMessage, "autoupdate_config")
				return
			}
			continue
		}
		if err != nil {
			resp.Diagnostics.Append(tfdiag.DiagFromWrappedErr("Error reading AutoUpdateConfig", trace.Wrap(err), "autoupdate_config"))
			return
		}

		previousMetadata := autoUpdateConfigBefore.GetMetadata()
		currentMetadata := autoUpdateConfigI.GetMetadata()
		if previousMetadata.GetRevision() != currentMetadata.GetRevision() || false {
			break
		}
		select {
		case <-ctx.Done():
		    resp.Diagnostics.Append(tfdiag.DiagFromWrappedErr("Error reading AutoUpdateConfig", trace.Wrap(ctx.Err()), "autoupdate_config"))
			return
		case <-retry.After():
		}
		if tries >= r.p.MaxRetries() {
			diagMessage := fmt.Sprintf("Error reading AutoUpdateConfig (tried %d times) - state outdated, please import resource", tries)
			resp.Diagnostics.AddError(diagMessage, "autoupdate_config")
			return
		}
	}
	if err != nil {
		resp.Diagnostics.Append(tfdiag.DiagFromWrappedErr("Error reading AutoUpdateConfig", trace.Wrap(err), "autoupdate_config"))
		return
	}

	autoUpdateConfig = autoUpdateConfigI
	

	diags = schemav1.CopyAutoUpdateConfigToTerraform(ctx, autoUpdateConfig, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	plan.Attrs["id"] = types.String{Value: autoUpdateConfig.Metadata.Name}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// Read reads teleport AutoUpdateConfig
func (r resourceTeleportAutoUpdateConfig) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state types.Object
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	autoUpdateConfigI, err := r.p.Client().GetAutoUpdateConfig(ctx)
	if trace.IsNotFound(err) {
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		resp.Diagnostics.Append(tfdiag.DiagFromWrappedErr("Error reading AutoUpdateConfig", trace.Wrap(err), "autoupdate_config"))
		return
	}

	autoUpdateConfig := autoUpdateConfigI
	diags = schemav1.CopyAutoUpdateConfigToTerraform(ctx, autoUpdateConfig, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// Update updates teleport AutoUpdateConfig
func (r resourceTeleportAutoUpdateConfig) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	if !r.p.IsConfigured(resp.Diagnostics) {
		return
	}

	var plan types.Object
	diags := req.Plan.Get(ctx, &plan)

	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	autoUpdateConfig := &autoupdatev1.AutoUpdateConfig{}
	diags = schemav1.CopyAutoUpdateConfigFromTerraform(ctx, plan, autoUpdateConfig)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	autoUpdateConfig.Kind = apitypes.KindAutoUpdateConfig
	if autoUpdateConfig.GetMetadata() == nil {
		autoUpdateConfig.Metadata = &headerv1.Metadata{}
	}
	if autoUpdateConfig.GetMetadata().GetName() == "" {
		autoUpdateConfig.Metadata.Name = apitypes.MetaNameAutoUpdateConfig
	}

	autoUpdateConfigBefore, err := r.p.Client().GetAutoUpdateConfig(ctx)
	if err != nil {
		resp.Diagnostics.Append(tfdiag.DiagFromWrappedErr("Error reading AutoUpdateConfig", trace.Wrap(err), "autoupdate_config"))
		return
	}

	_, err = r.p.Client().UpsertAutoUpdateConfig(ctx, autoUpdateConfig)
	if err != nil {
		resp.Diagnostics.Append(tfdiag.DiagFromWrappedErr("Error updating AutoUpdateConfig", trace.Wrap(err), "autoupdate_config"))
		return
	}
	var autoUpdateConfigI *autoupdatev1.AutoUpdateConfig

	tries := 0
	retry, err := r.p.Retry()
	if err != nil {
		return
	}
	for {
		tries = tries + 1
		autoUpdateConfigI, err = r.p.Client().GetAutoUpdateConfig(ctx)
		if err != nil {
			resp.Diagnostics.Append(tfdiag.DiagFromWrappedErr("Error reading AutoUpdateConfig", trace.Wrap(err), "autoupdate_config"))
			return
		}
		if autoUpdateConfigBefore.GetMetadata().Revision != autoUpdateConfigI.GetMetadata().Revision || false {
			break
		}
		select {
		case <-ctx.Done():
		    resp.Diagnostics.Append(tfdiag.DiagFromWrappedErr("Error reading AutoUpdateConfig", trace.Wrap(ctx.Err()), "autoupdate_config"))
			return
		case <-retry.After():
		}
		if tries >= r.p.MaxRetries() {
			diagMessage := fmt.Sprintf("Error reading AutoUpdateConfig (tried %d times) - state outdated, please import resource", tries)
			resp.Diagnostics.AddError(diagMessage, "autoupdate_config")
			return
		}
	}
	if err != nil {
		resp.Diagnostics.Append(tfdiag.DiagFromWrappedErr("Error reading AutoUpdateConfig", trace.Wrap(err), "autoupdate_config"))
		return
	}

	autoUpdateConfig = autoUpdateConfigI
	diags = schemav1.CopyAutoUpdateConfigToTerraform(ctx, autoUpdateConfig, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// Delete deletes Teleport AutoUpdateConfig
func (r resourceTeleportAutoUpdateConfig) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	err := r.p.Client().DeleteAutoUpdateConfig(ctx)
	if err != nil {
		resp.Diagnostics.Append(tfdiag.DiagFromWrappedErr("Error deleting AutoUpdateConfig", trace.Wrap(err), "autoupdate_config"))
		return
	}

	resp.State.RemoveResource(ctx)
}

// ImportState imports AutoUpdateConfig state
func (r resourceTeleportAutoUpdateConfig) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	autoUpdateConfigI, err := r.p.Client().GetAutoUpdateConfig(ctx)
	if err != nil {
		resp.Diagnostics.Append(tfdiag.DiagFromWrappedErr("Error updating AutoUpdateConfig", trace.Wrap(err), "autoupdate_config"))
		return
	}
	autoUpdateConfig := autoUpdateConfigI

	var state types.Object

	diags := resp.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = schemav1.CopyAutoUpdateConfigToTerraform(ctx, autoUpdateConfig, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := autoUpdateConfig.Metadata.Name

	state.Attrs["id"] = types.String{Value: id}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// ModifyPlan modifies the planned value, normalizing null values.
func (r resourceTeleportAutoUpdateConfig) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	// If the entire plan is null, the resource is planned for destruction.
	if req.Plan.Raw.IsNull() {
		return
	}

	// If the state is null, the resource is being created. No need to modify plan.
	if req.State.Raw.IsNull() {
		return
	}

	var config types.Object
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	autoUpdateConfig := &autoupdatev1.AutoUpdateConfig{}
	resp.Diagnostics.Append(schemav1.CopyAutoUpdateConfigFromTerraform(ctx, config, autoUpdateConfig)...)
	if resp.Diagnostics.HasError() {
		return
	}

	autoUpdateConfigResource := autoUpdateConfig
	autoUpdateConfigResource.Kind = apitypes.KindAutoUpdateConfig

	autoUpdateConfig = autoUpdateConfigResource

	const preserveUnknown = true
	resp.Diagnostics.Append(schemav1.CopyAutoUpdateConfigToTerraformPreserveUnknown(ctx, autoUpdateConfig, &config, preserveUnknown)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var plan types.Object
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	plan.Attrs["spec"] = config.Attrs["spec"]

	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}
