// Code generated by 'go generate'; DO NOT EDIT.

package autoupdate

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modcrypt32 = windows.NewLazySystemDLL("crypt32.dll")

	procCertCompareCertificateName = modcrypt32.NewProc("CertCompareCertificateName")
	procCryptMsgClose              = modcrypt32.NewProc("CryptMsgClose")
	procCryptMsgGetParam           = modcrypt32.NewProc("CryptMsgGetParam")
)

func CertCompareCertificateName(encodingType uint32, name1 *windows.CertNameBlob, name2 *windows.CertNameBlob) (ok bool) {
	r0, _, _ := syscall.SyscallN(procCertCompareCertificateName.Addr(), uintptr(encodingType), uintptr(unsafe.Pointer(name1)), uintptr(unsafe.Pointer(name2)))
	ok = r0 != 0
	return
}

func CryptMsgClose(msg windows.Handle) (err error) {
	r1, _, e1 := syscall.SyscallN(procCryptMsgClose.Addr(), uintptr(msg))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func CryptMsgGetParam(msg windows.Handle, paramType uint32, index uint32, data *byte, dataLen *uint32) (err error) {
	r1, _, e1 := syscall.SyscallN(procCryptMsgGetParam.Addr(), uintptr(msg), uintptr(paramType), uintptr(index), uintptr(unsafe.Pointer(data)), uintptr(unsafe.Pointer(dataLen)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}
