package devicetrustpublicv1

const EnrollPairingApprovalTimeout = enrollPairingApprovalTimeout

var ErrPairingClaimed = errPairingClaimed
var ErrInvalidPairingToken = errInvalidPairingToken
var ErrPairingLookupUnavailable = errPairingLookupUnavailable
var ErrPairingDeniedOrExpired = errPairingDeniedOrExpired
var ErrPairingConsumed = errPairingConsumed
var ErrEnrollVerificationFailed = errEnrollVerificationFailed
var ErrEnrollTokenIssuanceFailed = errEnrollTokenIssuanceFailed
var ErrUserAuthzUnavailable = errUserAuthzUnavailable
var ErrEnrollDeviceUnavailable = errEnrollDeviceUnavailable
var ErrEnrollDeviceFailed = errEnrollDeviceFailed

var RedactEnrollError = redactEnrollError
