{
 "title": "Self-hosted Teleport Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "teleport_job",
    "query": {
     "query": "label_values(teleport_build_info,job)"
    }
   },
   {
    "name": "backend_metrics",
    "query": {
     "query": "{__name__=~\"backend_.*_requests_total\",namespace=\"$namespace\", component=\"backend\", job=~\"$teleport_job\"}"
    }
   },
   {
    "name": "cache_metrics",
    "query": {
     "query": "{__name__=~\"backend_.*_requests_total\",namespace=\"$namespace\", component=\"cache\", job=~\"$teleport_job\"}"
    }
   },
   {
    "name": "metrics_per",
    "query": {
     "query": "label_names(teleport_build_info)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(teleport_build_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Teleport Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Teleport Build Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(job, goversion, version) (teleport_build_info{namespace=\"$namespace\", job=~\"$teleport_job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Teleport Versions",
   "type": "piechart",
   "description": "The number of Teleport services connected to an Auth Service instance, grouped by version.",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (teleport_registered_servers{namespace=\"$namespace\", job=~\"$teleport_job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Teleport Versions",
   "type": "timeseries",
   "description": "Count and version of connected Teleport agents.",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum by (version) (teleport_registered_servers{namespace=\"$namespace\", job=~\"$teleport_job\"})",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "sum(teleport_registered_servers{namespace=\"$namespace\", job=~\"$teleport_job\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Teleport Process State",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_state{namespace=\"$namespace\", job=~\"$teleport_job\"}",
     "legendFormat": "{{$metrics_per}}"
    }
   ]
  },
  {
   "title": "Login Count",
   "type": "state-timeline",
   "description": "- Number of user logins\n- Number of failed `tsh login` or `tsh ssh` logins",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(user_login_total{namespace=\"$namespace\",job=~\"$teleport_job\"}[$__rate_interval]))",
     "legendFormat": "User login count"
    },
    {
     "expr": "sum(rate(failed_login_attempts_total{namespace=\"$namespace\",job=~\"$teleport_job\"}[$__rate_interval]))",
     "legendFormat": "Failed login attempts"
    }
   ]
  },
  {
   "title": "Connected Resources",
   "type": "stat",
   "description": "Number of resources connected to the Teleport Cluster.",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum(teleport_connected_resources{namespace=\"$namespace\", job=~\"$teleport_job\"}) by (type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Tunnels",
   "type": "stat",
   "description": "Number of reverse SSH tunnels connected to the Teleport Proxy Service by Teleport instances.",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (teleport_reverse_tunnels_connected{namespace=\"$namespace\", job=~\"$teleport_job\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Managed Updates V2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rollout Spec",
     "type": "table",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "count(teleport_agent_autoupdates_rollout_start{namespace=\"$namespace\", job=~\"$teleport_job\"} == 1) by (version)",
       "legendFormat": "start version"
      },
      {
       "expr": "count(teleport_agent_autoupdates_rollout_target{namespace=\"$namespace\", job=~\"$teleport_job\"} == 1) by (version)",
       "legendFormat": "target version"
      }
     ]
    },
    {
     "title": "Teleport Agent Updates Settings",
     "type": "state-timeline",
     "gridPos": { "h": 4, "w": 10, "x": 4, "y": 21 },
     "targets": [
      {
       "expr": "max by(__name__) ({__name__=~\"teleport_agent_autoupdates_.*_present\", namespace=\"$namespace\", job=~\"$teleport_job\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Auto Update Mode",
     "type": "state-timeline",
     "gridPos": { "h": 4, "w": 10, "x": 14, "y": 21 },
     "targets": [
      {
       "expr": "max by(__name__) ({__name__=~\"teleport_agent_autoupdates_.*_mode\", namespace=\"$namespace\", job=~\"$teleport_job\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rollout State",
     "type": "state-timeline",
     "description": "The rollout state aggregates the state of every group. It becomes active as soon as the first group is updated, and done when the last group is updated.\n\nThe operator makes update decisions based on this state. For example, if there is an unstarted v1 -> v2 rollout and you want to update to v3, the operator will choose to do v1 -> v3 instead of v2 -> v3.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "max(teleport_agent_autoupdates_rollout_state{namespace=\"$namespace\", job=~\"$teleport_job\"}) ",
       "legendFormat": "State "
      },
      {
       "expr": "max(teleport_agent_autoupdates_rollout_group_state{namespace=\"$namespace\", job=~\"$teleport_job\"}) by (group_number)",
       "legendFormat": "Group {{group_number}}"
      }
     ]
    },
    {
     "title": "Reconciliations Triggered Rate (per minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "r/m" } },
     "targets": [
      {
       "expr": "avg by(result)(rate(teleport_agent_autoupdates_reconciliations_total{namespace=\"$namespace\", job=~\"$teleport_job\"}[5m])*60)",
       "legendFormat": "[{{result}}] reconciliation "
      },
      {
       "expr": "avg by(result)(rate(teleport_agent_autoupdates_reconciliation_tries_total{namespace=\"$namespace\", job=~\"$teleport_job\"}[5m])*60)",
       "legendFormat": "[{{result}}] attempt"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backend Write Availability",
     "type": "state-timeline",
     "description": "Percentage of write requests to the backend that succeed.\n\n---\n\nA Teleport cluster cannot function if the Auth Service does not have a healthy cluster state backend.\nYou need to track the ability of the Auth Service to read from and write to its backend.\n\nIf your backend becomes unavailable, you can investigate your backend infrastructure.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "\n1 - ((\n        sum by ($metrics_per) (rate(backend_write_requests_failed_total{component=\"backend\",namespace=\"$namespace\",job=~\"$teleport_job\"}[$__rate_interval]))\n        - \n        sum by ($metrics_per) (rate(teleport_backend_write_requests_failed_precondition_total{component=\"backend\",namespace=\"$namespace\",job=~\"$teleport_job\"}[$__rate_interval])) OR on() vector(0)\n    ) / (\n        sum by ($metrics_per) (rate(backend_write_requests_total{component=\"backend\",namespace=\"$namespace\",job=~\"$teleport_job\"}[$__rate_interval]))\n    ))\n",
       "legendFormat": "{{$metrics_per}}"
      }
     ]
    },
    {
     "title": "Backend Read Availability",
     "type": "state-timeline",
     "description": "Percentage of read requests to the backend that succeed.\n\n---\n\nA Teleport cluster cannot function if the Auth Service does not have a healthy cluster state backend.\nYou need to track the ability of the Auth Service to read from and write to its backend.\n\nIf your backend becomes unavailable, you can investigate your backend infrastructure.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1- ((\n    (\n        (sum by ($metrics_per) (rate(backend_read_requests_failed_total{component=\"backend\",namespace=\"$namespace\"}[$__rate_interval])) OR vector(0))\n            /\n        (sum by ($metrics_per) (rate(backend_read_requests_total{component=\"backend\",namespace=\"$namespace\"}[$__rate_interval])))\n    )\n  )) or group by ($metrics_per) (rate(backend_read_requests_total{component=\"backend\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "[[backend_metrics]]",
     "type": "timeseries",
     "description": "Count of successful and failed backend requests.\n\nDuring failed backend writes, a Teleport process also increments the `Precondition failed` metric if the cause of the failure is expected. For example, the metric increments during a create operation if a record already exists, during an update or delete operation if the record is not found, and during an atomic write if the resource was modified concurrently. All of these conditions can occur in a well-functioning Teleport cluster.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "repeat": "backend_metrics",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate({__name__=\"[[backend_metrics]]_total\",component=\"backend\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Success"
      },
      {
       "expr": "sum(rate({__name__=\"[[backend_metrics]]_failed_total\",component=\"backend\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Failed"
      },
      {
       "expr": "sum(rate({__name__=\"teleport_[[backend_metrics]]_failed_precondition_total\",component=\"backend\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Precondition failed"
      }
     ]
    },
    {
     "title": "[cache] [[cache_metrics]]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
     "repeat": "cache_metrics",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate({__name__=\"[[cache_metrics]]_total\",component=\"cache\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Total Count"
      },
      {
       "expr": "sum(rate({__name__=\"[[cache_metrics]]_failed_total\",component=\"cache\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Total Failed Count"
      },
      {
       "expr": "sum(rate({__name__=\"teleport_[[cache_metrics]]_failed_precondition_total\",component=\"cache\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Total Precondition Failed Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Audit Events",
     "type": "timeseries",
     "description": "- Number of audit events emitted.\n- Number of times emitting audit events failed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum(rate(teleport_audit_emit_events{namespace=\"$namespace\", job=~\"$teleport_job\"}[$__rate_interval]))",
       "legendFormat": "Emitted"
      },
      {
       "expr": "sum(rate(audit_failed_emit_events{namespace=\"$namespace\", job=~\"$teleport_job\"}[$__rate_interval]))",
       "legendFormat": "Failed to emit"
      }
     ]
    },
    {
     "title": "Watcher Events by Resource",
     "type": "timeseries",
     "description": "Per-resource count of events emitted.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum(rate(watcher_events_count{namespace=\"$namespace\", job=~\"$teleport_job\"}[$__rate_interval])) by (resource)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "description": "Resident memory size in bytes.\n\nIf available, [GOMEMLIMIT](https://pkg.go.dev/runtime) is shown as a dotted line.",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{namespace=\"$namespace\",job=~\"$teleport_job\"}",
       "legendFormat": "{{$metrics_per}}"
      },
      {
       "expr": "(go_gc_gomemlimit_bytes{namespace=\"$namespace\",job=~\"$teleport_job\"} < 9000000000000000000)",
       "legendFormat": "GOMEMLIMIT {{$metrics_per}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "description": "Number of goroutines that currently exist.",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{namespace=\"$namespace\",job=~\"$teleport_job\"}",
       "legendFormat": "{{$metrics_per}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Total user and system CPU time spent in seconds.\n\nIf available, the [GOMAXPROCS](https://pkg.go.dev/runtime) value is shown as a dotted line.",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "CPU/s" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{namespace=\"$namespace\",job=~\"$teleport_job\"}[$__rate_interval])",
       "legendFormat": "{{$metrics_per}}"
      },
      {
       "expr": "go_sched_gomaxprocs_threads{namespace=\"$namespace\",job=~\"$teleport_job\"}",
       "legendFormat": "GOMAXPROCS {{$metrics_per}}"
      }
     ]
    },
    {
     "title": "Open FDs",
     "type": "timeseries",
     "description": "Number of open file descriptors.",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 31 },
     "targets": [
      {
       "expr": "process_open_fds{namespace=\"$namespace\",job=~\"$teleport_job\"}",
       "legendFormat": "{{$metrics_per}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPCs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Invocations Handled",
     "type": "timeseries",
     "description": "Total number of RPCs completed on the server, regardless of success or failure.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$teleport_job\"}[$__rate_interval])) by (grpc_service, grpc_method)",
       "legendFormat": "{{grpc_service}}/{{grpc_method}}"
      }
     ]
    },
    {
     "title": "RPC Invocation Failures",
     "type": "timeseries",
     "description": "Total number of RPCs completed on the server, with a non-OK status code.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",grpc_code!=\"OK\",job=~\"$teleport_job\"}[$__rate_interval])) by (grpc_service, grpc_method, grpc_code)",
       "legendFormat": "{{grpc_service}}/{{grpc_method}} - {{grpc_code}}"
      }
     ]
    }
   ]
  }
 ]
}