export const UPDATE_CONNECTORS = 'SETTINGS_AUTH_CONN_UPDATE';
export const RECEIVE_CONNECTORS = 'SETTINGS_AUTH_CONN_RECEIVE';
export const SET_CURRENT = 'SETTINGS_AUTH_SET_CURRENT';
export const DELETE_CONN = 'SETTINGS_AUTH_DELETE';