export const UPDATE_CONNECTORS = 'SETTINGS_AUTH_CONN_UPDATE';
export const RECEIVE_CONNECTORS = 'SETTINGS_AUTH_CONN_RECEIVE';
export const SET_TO_DELETE = 'SETTINGS_AUTH_CONN_SET_TO_DELETE';
export const SET_CURRENT = 'SETTINGS_AUTH_SET_CURRENT';
