#!/bin/bash

# This before remove script is run each time the teleport package is removed.

set -eu

case "$1" in
    remove|deconfigure)
        echo "Removing symlinks from teleport system paths..."
        /usr/local/teleport-system/bin/teleport-update unlink-package || true
        ;;
esac

