#!/bin/bash

# This post install script is run each time the teleport package is installed/upgraded.

set -eu

case "$1" in
    configure)
        echo "Teleport system symlinks creation..."
        /usr/local/teleport-system/bin/teleport-update link-package
        ;;
esac
