#!/bin/bash

# this post upgrade script is run each time the teleport package is upgraded

set -eu

# skip reload and restart when systemd is disabled. This is only relevant when
# testing in a container.
if systemctl status > /dev/null 2>&1; then
    # reload systemd configuration
    systemctl daemon-reload
fi
