#!/bin/bash

# This post install script is run each time the teleport package is installed/upgraded.

set -eu

case "$1" in
    configure)
        echo "Teleport system symlinks creation..."
        /usr/local/teleport-system/bin/teleport-update link-package
        ;;
esac

# Skip reload and restart when systemd is disabled. This is only relevant when
# testing in a container.
if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi
