// Code generated by "make version". DO NOT EDIT.
package teleport

const Version = "13.1.3-tcsc.test.01"

// Gitref is set to the output of "git describe" during the build process.
var Gitref string
