/* DO NOT EDIT THIS FILE. IT IS GENERATED BY 'make setver'*/

package teleport

const (
	Version = "1.3.2-beta"
)

// Gitref variable is automatically set to the output of git-describe
// during the build process
var Gitref string
