// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: api/tenants/v1/tenants.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TenantsServiceClient is the client API for TenantsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TenantsServiceClient interface {
	// SubmitUsageReports reports usage
	SubmitUsageReports(ctx context.Context, in *SubmitUsageReportsRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// GetBillingInformation returns customer billing information
	GetBillingInformation(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetBillingInformationResponse, error)
	// CreateSetupIntent creates an intent in stripe and returns the client secret
	CreateSetupIntent(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*CreateSetupIntentResponse, error)
	// AddCard adds a new credit card to customer account
	AddCard(ctx context.Context, in *AddCardRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// RemoveCardRequest removes a credit card from tenant account
	RemoveCard(ctx context.Context, in *RemoveCardRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// UpdateCard updates tenant credit card
	UpdateCard(ctx context.Context, in *UpdateCardRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// GetAccountUpgradeWindowStartHour returns tenant account upgrade window start
	GetAccountUpgradeWindowStartHour(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetAccountUpgradeWindowStartHourResponse, error)
	// UpdateAccountUpgradeWindowStartHour updates tenant account upgrade window start
	UpdateAccountUpgradeWindowStartHour(ctx context.Context, in *UpdateAccountUpgradeWindowStartHourRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// SendAccountRecoveryLink sends an email with the recovery link to the user who requested to recover their account.
	SendAccountRecoveryLink(ctx context.Context, in *SendAccountRecoveryLinkRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// SendAccountLocked sends an email to the user whose account is locked due to max failed attempts at recovering.
	SendAccountLocked(ctx context.Context, in *SendAccountLockedRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// SendAccountRecovered sends an email to the user who successfully recovered their account.
	SendAccountRecovered(ctx context.Context, in *SendAccountRecoveredRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// GetFeatures returns the cluster features
	GetFeatures(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetFeaturesResponse, error)
	// GetBillingSummaryInformation returns the users Billing Summary Information
	GetBillingSummaryInformation(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetBillingSummaryInformationResponse, error)
	// GetPaymentsInvoicesInformation returns users the Payments Invoices Information
	GetPaymentsInvoicesInformation(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetPaymentsInvoicesInformationResponse, error)
	// GetInvoiceSettingsInformation returns the users Invoice Settings Information
	GetInvoiceSettingsInformation(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetInvoiceSettingsInformationResponse, error)
	// UpdateStripeAddress updates customer address information in Stripe
	UpdateStripeAddress(ctx context.Context, in *StripeBillingAddressRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// UpdateEmail updates customer email address
	UpdateEmail(ctx context.Context, in *UpdateEmailRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// UpdatePurchaseOrderPrefix updates customer PO number
	UpdatePurchaseOrderPrefix(ctx context.Context, in *UpdatePurchaseOrderPrefixRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// CancelSubscription marks a users Stripe account for cancellation at the end of the current billing cycle
	CancelSubscription(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// GetSurveyCompany returns the company survey responses for the account associated with the current user.
	// These are answered by only the first user who completes the survey
	GetSurveyCompany(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*SurveyCompanyResponse, error)
	// SetSurveyResults updates the account object with onboarding survey results
	SetSurveyResults(ctx context.Context, in *SetSurveyResultsRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// SendTeleportInvite sends a user invite link to onboard a new user in an existing cluster
	SendTeleportInvite(ctx context.Context, in *SendTeleportInviteRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// ClusterAlertInfo returns information about a cluster that will determine if the Teleport usage reporter should
	// generate a cluster alert; e/lib/cloud/usagereporter/reporter.go.
	ClusterAlertInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ClusterAlertInfoResponse, error)
}

type tenantsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantsServiceClient(cc grpc.ClientConnInterface) TenantsServiceClient {
	return &tenantsServiceClient{cc}
}

func (c *tenantsServiceClient) SubmitUsageReports(ctx context.Context, in *SubmitUsageReportsRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/SubmitUsageReports", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) GetBillingInformation(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetBillingInformationResponse, error) {
	out := new(GetBillingInformationResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/GetBillingInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) CreateSetupIntent(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*CreateSetupIntentResponse, error) {
	out := new(CreateSetupIntentResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/CreateSetupIntent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) AddCard(ctx context.Context, in *AddCardRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/AddCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) RemoveCard(ctx context.Context, in *RemoveCardRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/RemoveCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) UpdateCard(ctx context.Context, in *UpdateCardRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/UpdateCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) GetAccountUpgradeWindowStartHour(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetAccountUpgradeWindowStartHourResponse, error) {
	out := new(GetAccountUpgradeWindowStartHourResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/GetAccountUpgradeWindowStartHour", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) UpdateAccountUpgradeWindowStartHour(ctx context.Context, in *UpdateAccountUpgradeWindowStartHourRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/UpdateAccountUpgradeWindowStartHour", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) SendAccountRecoveryLink(ctx context.Context, in *SendAccountRecoveryLinkRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/SendAccountRecoveryLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) SendAccountLocked(ctx context.Context, in *SendAccountLockedRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/SendAccountLocked", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) SendAccountRecovered(ctx context.Context, in *SendAccountRecoveredRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/SendAccountRecovered", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) GetFeatures(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetFeaturesResponse, error) {
	out := new(GetFeaturesResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/GetFeatures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) GetBillingSummaryInformation(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetBillingSummaryInformationResponse, error) {
	out := new(GetBillingSummaryInformationResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/GetBillingSummaryInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) GetPaymentsInvoicesInformation(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetPaymentsInvoicesInformationResponse, error) {
	out := new(GetPaymentsInvoicesInformationResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/GetPaymentsInvoicesInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) GetInvoiceSettingsInformation(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetInvoiceSettingsInformationResponse, error) {
	out := new(GetInvoiceSettingsInformationResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/GetInvoiceSettingsInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) UpdateStripeAddress(ctx context.Context, in *StripeBillingAddressRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/UpdateStripeAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) UpdateEmail(ctx context.Context, in *UpdateEmailRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/UpdateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) UpdatePurchaseOrderPrefix(ctx context.Context, in *UpdatePurchaseOrderPrefixRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/UpdatePurchaseOrderPrefix", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) CancelSubscription(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/CancelSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) GetSurveyCompany(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*SurveyCompanyResponse, error) {
	out := new(SurveyCompanyResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/GetSurveyCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) SetSurveyResults(ctx context.Context, in *SetSurveyResultsRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/SetSurveyResults", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) SendTeleportInvite(ctx context.Context, in *SendTeleportInviteRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/SendTeleportInvite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) ClusterAlertInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ClusterAlertInfoResponse, error) {
	out := new(ClusterAlertInfoResponse)
	err := c.cc.Invoke(ctx, "/gravitational.cloud.tenants.v1.TenantsService/ClusterAlertInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantsServiceServer is the server API for TenantsService service.
// All implementations must embed UnimplementedTenantsServiceServer
// for forward compatibility
type TenantsServiceServer interface {
	// SubmitUsageReports reports usage
	SubmitUsageReports(context.Context, *SubmitUsageReportsRequest) (*EmptyResponse, error)
	// GetBillingInformation returns customer billing information
	GetBillingInformation(context.Context, *EmptyRequest) (*GetBillingInformationResponse, error)
	// CreateSetupIntent creates an intent in stripe and returns the client secret
	CreateSetupIntent(context.Context, *EmptyRequest) (*CreateSetupIntentResponse, error)
	// AddCard adds a new credit card to customer account
	AddCard(context.Context, *AddCardRequest) (*EmptyResponse, error)
	// RemoveCardRequest removes a credit card from tenant account
	RemoveCard(context.Context, *RemoveCardRequest) (*EmptyResponse, error)
	// UpdateCard updates tenant credit card
	UpdateCard(context.Context, *UpdateCardRequest) (*EmptyResponse, error)
	// GetAccountUpgradeWindowStartHour returns tenant account upgrade window start
	GetAccountUpgradeWindowStartHour(context.Context, *EmptyRequest) (*GetAccountUpgradeWindowStartHourResponse, error)
	// UpdateAccountUpgradeWindowStartHour updates tenant account upgrade window start
	UpdateAccountUpgradeWindowStartHour(context.Context, *UpdateAccountUpgradeWindowStartHourRequest) (*EmptyResponse, error)
	// SendAccountRecoveryLink sends an email with the recovery link to the user who requested to recover their account.
	SendAccountRecoveryLink(context.Context, *SendAccountRecoveryLinkRequest) (*EmptyResponse, error)
	// SendAccountLocked sends an email to the user whose account is locked due to max failed attempts at recovering.
	SendAccountLocked(context.Context, *SendAccountLockedRequest) (*EmptyResponse, error)
	// SendAccountRecovered sends an email to the user who successfully recovered their account.
	SendAccountRecovered(context.Context, *SendAccountRecoveredRequest) (*EmptyResponse, error)
	// GetFeatures returns the cluster features
	GetFeatures(context.Context, *EmptyRequest) (*GetFeaturesResponse, error)
	// GetBillingSummaryInformation returns the users Billing Summary Information
	GetBillingSummaryInformation(context.Context, *EmptyRequest) (*GetBillingSummaryInformationResponse, error)
	// GetPaymentsInvoicesInformation returns users the Payments Invoices Information
	GetPaymentsInvoicesInformation(context.Context, *EmptyRequest) (*GetPaymentsInvoicesInformationResponse, error)
	// GetInvoiceSettingsInformation returns the users Invoice Settings Information
	GetInvoiceSettingsInformation(context.Context, *EmptyRequest) (*GetInvoiceSettingsInformationResponse, error)
	// UpdateStripeAddress updates customer address information in Stripe
	UpdateStripeAddress(context.Context, *StripeBillingAddressRequest) (*EmptyResponse, error)
	// UpdateEmail updates customer email address
	UpdateEmail(context.Context, *UpdateEmailRequest) (*EmptyResponse, error)
	// UpdatePurchaseOrderPrefix updates customer PO number
	UpdatePurchaseOrderPrefix(context.Context, *UpdatePurchaseOrderPrefixRequest) (*EmptyResponse, error)
	// CancelSubscription marks a users Stripe account for cancellation at the end of the current billing cycle
	CancelSubscription(context.Context, *EmptyRequest) (*EmptyResponse, error)
	// GetSurveyCompany returns the company survey responses for the account associated with the current user.
	// These are answered by only the first user who completes the survey
	GetSurveyCompany(context.Context, *EmptyRequest) (*SurveyCompanyResponse, error)
	// SetSurveyResults updates the account object with onboarding survey results
	SetSurveyResults(context.Context, *SetSurveyResultsRequest) (*EmptyResponse, error)
	// SendTeleportInvite sends a user invite link to onboard a new user in an existing cluster
	SendTeleportInvite(context.Context, *SendTeleportInviteRequest) (*EmptyResponse, error)
	// ClusterAlertInfo returns information about a cluster that will determine if the Teleport usage reporter should
	// generate a cluster alert; e/lib/cloud/usagereporter/reporter.go.
	ClusterAlertInfo(context.Context, *EmptyRequest) (*ClusterAlertInfoResponse, error)
	mustEmbedUnimplementedTenantsServiceServer()
}

// UnimplementedTenantsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTenantsServiceServer struct {
}

func (UnimplementedTenantsServiceServer) SubmitUsageReports(context.Context, *SubmitUsageReportsRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitUsageReports not implemented")
}
func (UnimplementedTenantsServiceServer) GetBillingInformation(context.Context, *EmptyRequest) (*GetBillingInformationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBillingInformation not implemented")
}
func (UnimplementedTenantsServiceServer) CreateSetupIntent(context.Context, *EmptyRequest) (*CreateSetupIntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSetupIntent not implemented")
}
func (UnimplementedTenantsServiceServer) AddCard(context.Context, *AddCardRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCard not implemented")
}
func (UnimplementedTenantsServiceServer) RemoveCard(context.Context, *RemoveCardRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCard not implemented")
}
func (UnimplementedTenantsServiceServer) UpdateCard(context.Context, *UpdateCardRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCard not implemented")
}
func (UnimplementedTenantsServiceServer) GetAccountUpgradeWindowStartHour(context.Context, *EmptyRequest) (*GetAccountUpgradeWindowStartHourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountUpgradeWindowStartHour not implemented")
}
func (UnimplementedTenantsServiceServer) UpdateAccountUpgradeWindowStartHour(context.Context, *UpdateAccountUpgradeWindowStartHourRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccountUpgradeWindowStartHour not implemented")
}
func (UnimplementedTenantsServiceServer) SendAccountRecoveryLink(context.Context, *SendAccountRecoveryLinkRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAccountRecoveryLink not implemented")
}
func (UnimplementedTenantsServiceServer) SendAccountLocked(context.Context, *SendAccountLockedRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAccountLocked not implemented")
}
func (UnimplementedTenantsServiceServer) SendAccountRecovered(context.Context, *SendAccountRecoveredRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAccountRecovered not implemented")
}
func (UnimplementedTenantsServiceServer) GetFeatures(context.Context, *EmptyRequest) (*GetFeaturesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeatures not implemented")
}
func (UnimplementedTenantsServiceServer) GetBillingSummaryInformation(context.Context, *EmptyRequest) (*GetBillingSummaryInformationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBillingSummaryInformation not implemented")
}
func (UnimplementedTenantsServiceServer) GetPaymentsInvoicesInformation(context.Context, *EmptyRequest) (*GetPaymentsInvoicesInformationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentsInvoicesInformation not implemented")
}
func (UnimplementedTenantsServiceServer) GetInvoiceSettingsInformation(context.Context, *EmptyRequest) (*GetInvoiceSettingsInformationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInvoiceSettingsInformation not implemented")
}
func (UnimplementedTenantsServiceServer) UpdateStripeAddress(context.Context, *StripeBillingAddressRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStripeAddress not implemented")
}
func (UnimplementedTenantsServiceServer) UpdateEmail(context.Context, *UpdateEmailRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEmail not implemented")
}
func (UnimplementedTenantsServiceServer) UpdatePurchaseOrderPrefix(context.Context, *UpdatePurchaseOrderPrefixRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePurchaseOrderPrefix not implemented")
}
func (UnimplementedTenantsServiceServer) CancelSubscription(context.Context, *EmptyRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelSubscription not implemented")
}
func (UnimplementedTenantsServiceServer) GetSurveyCompany(context.Context, *EmptyRequest) (*SurveyCompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSurveyCompany not implemented")
}
func (UnimplementedTenantsServiceServer) SetSurveyResults(context.Context, *SetSurveyResultsRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSurveyResults not implemented")
}
func (UnimplementedTenantsServiceServer) SendTeleportInvite(context.Context, *SendTeleportInviteRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTeleportInvite not implemented")
}
func (UnimplementedTenantsServiceServer) ClusterAlertInfo(context.Context, *EmptyRequest) (*ClusterAlertInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterAlertInfo not implemented")
}
func (UnimplementedTenantsServiceServer) mustEmbedUnimplementedTenantsServiceServer() {}

// UnsafeTenantsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantsServiceServer will
// result in compilation errors.
type UnsafeTenantsServiceServer interface {
	mustEmbedUnimplementedTenantsServiceServer()
}

func RegisterTenantsServiceServer(s grpc.ServiceRegistrar, srv TenantsServiceServer) {
	s.RegisterService(&TenantsService_ServiceDesc, srv)
}

func _TenantsService_SubmitUsageReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitUsageReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).SubmitUsageReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/SubmitUsageReports",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).SubmitUsageReports(ctx, req.(*SubmitUsageReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_GetBillingInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).GetBillingInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/GetBillingInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).GetBillingInformation(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_CreateSetupIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).CreateSetupIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/CreateSetupIntent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).CreateSetupIntent(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_AddCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).AddCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/AddCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).AddCard(ctx, req.(*AddCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_RemoveCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).RemoveCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/RemoveCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).RemoveCard(ctx, req.(*RemoveCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_UpdateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).UpdateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/UpdateCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).UpdateCard(ctx, req.(*UpdateCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_GetAccountUpgradeWindowStartHour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).GetAccountUpgradeWindowStartHour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/GetAccountUpgradeWindowStartHour",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).GetAccountUpgradeWindowStartHour(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_UpdateAccountUpgradeWindowStartHour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountUpgradeWindowStartHourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).UpdateAccountUpgradeWindowStartHour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/UpdateAccountUpgradeWindowStartHour",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).UpdateAccountUpgradeWindowStartHour(ctx, req.(*UpdateAccountUpgradeWindowStartHourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_SendAccountRecoveryLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAccountRecoveryLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).SendAccountRecoveryLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/SendAccountRecoveryLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).SendAccountRecoveryLink(ctx, req.(*SendAccountRecoveryLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_SendAccountLocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAccountLockedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).SendAccountLocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/SendAccountLocked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).SendAccountLocked(ctx, req.(*SendAccountLockedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_SendAccountRecovered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAccountRecoveredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).SendAccountRecovered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/SendAccountRecovered",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).SendAccountRecovered(ctx, req.(*SendAccountRecoveredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_GetFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).GetFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/GetFeatures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).GetFeatures(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_GetBillingSummaryInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).GetBillingSummaryInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/GetBillingSummaryInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).GetBillingSummaryInformation(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_GetPaymentsInvoicesInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).GetPaymentsInvoicesInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/GetPaymentsInvoicesInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).GetPaymentsInvoicesInformation(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_GetInvoiceSettingsInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).GetInvoiceSettingsInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/GetInvoiceSettingsInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).GetInvoiceSettingsInformation(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_UpdateStripeAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StripeBillingAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).UpdateStripeAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/UpdateStripeAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).UpdateStripeAddress(ctx, req.(*StripeBillingAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_UpdateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).UpdateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/UpdateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).UpdateEmail(ctx, req.(*UpdateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_UpdatePurchaseOrderPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePurchaseOrderPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).UpdatePurchaseOrderPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/UpdatePurchaseOrderPrefix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).UpdatePurchaseOrderPrefix(ctx, req.(*UpdatePurchaseOrderPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_CancelSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).CancelSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/CancelSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).CancelSubscription(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_GetSurveyCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).GetSurveyCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/GetSurveyCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).GetSurveyCompany(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_SetSurveyResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSurveyResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).SetSurveyResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/SetSurveyResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).SetSurveyResults(ctx, req.(*SetSurveyResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_SendTeleportInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTeleportInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).SendTeleportInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/SendTeleportInvite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).SendTeleportInvite(ctx, req.(*SendTeleportInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_ClusterAlertInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).ClusterAlertInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitational.cloud.tenants.v1.TenantsService/ClusterAlertInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).ClusterAlertInfo(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantsService_ServiceDesc is the grpc.ServiceDesc for TenantsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gravitational.cloud.tenants.v1.TenantsService",
	HandlerType: (*TenantsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitUsageReports",
			Handler:    _TenantsService_SubmitUsageReports_Handler,
		},
		{
			MethodName: "GetBillingInformation",
			Handler:    _TenantsService_GetBillingInformation_Handler,
		},
		{
			MethodName: "CreateSetupIntent",
			Handler:    _TenantsService_CreateSetupIntent_Handler,
		},
		{
			MethodName: "AddCard",
			Handler:    _TenantsService_AddCard_Handler,
		},
		{
			MethodName: "RemoveCard",
			Handler:    _TenantsService_RemoveCard_Handler,
		},
		{
			MethodName: "UpdateCard",
			Handler:    _TenantsService_UpdateCard_Handler,
		},
		{
			MethodName: "GetAccountUpgradeWindowStartHour",
			Handler:    _TenantsService_GetAccountUpgradeWindowStartHour_Handler,
		},
		{
			MethodName: "UpdateAccountUpgradeWindowStartHour",
			Handler:    _TenantsService_UpdateAccountUpgradeWindowStartHour_Handler,
		},
		{
			MethodName: "SendAccountRecoveryLink",
			Handler:    _TenantsService_SendAccountRecoveryLink_Handler,
		},
		{
			MethodName: "SendAccountLocked",
			Handler:    _TenantsService_SendAccountLocked_Handler,
		},
		{
			MethodName: "SendAccountRecovered",
			Handler:    _TenantsService_SendAccountRecovered_Handler,
		},
		{
			MethodName: "GetFeatures",
			Handler:    _TenantsService_GetFeatures_Handler,
		},
		{
			MethodName: "GetBillingSummaryInformation",
			Handler:    _TenantsService_GetBillingSummaryInformation_Handler,
		},
		{
			MethodName: "GetPaymentsInvoicesInformation",
			Handler:    _TenantsService_GetPaymentsInvoicesInformation_Handler,
		},
		{
			MethodName: "GetInvoiceSettingsInformation",
			Handler:    _TenantsService_GetInvoiceSettingsInformation_Handler,
		},
		{
			MethodName: "UpdateStripeAddress",
			Handler:    _TenantsService_UpdateStripeAddress_Handler,
		},
		{
			MethodName: "UpdateEmail",
			Handler:    _TenantsService_UpdateEmail_Handler,
		},
		{
			MethodName: "UpdatePurchaseOrderPrefix",
			Handler:    _TenantsService_UpdatePurchaseOrderPrefix_Handler,
		},
		{
			MethodName: "CancelSubscription",
			Handler:    _TenantsService_CancelSubscription_Handler,
		},
		{
			MethodName: "GetSurveyCompany",
			Handler:    _TenantsService_GetSurveyCompany_Handler,
		},
		{
			MethodName: "SetSurveyResults",
			Handler:    _TenantsService_SetSurveyResults_Handler,
		},
		{
			MethodName: "SendTeleportInvite",
			Handler:    _TenantsService_SendTeleportInvite_Handler,
		},
		{
			MethodName: "ClusterAlertInfo",
			Handler:    _TenantsService_ClusterAlertInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/tenants/v1/tenants.proto",
}
