// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: teleport/legacy/client/proto/oktaservice.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gravitational/teleport/api/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ListOktaGroupsRequest is a request for listing Okta groups.
type ListOktaGroupsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOktaGroupsRequest) Reset()         { *m = ListOktaGroupsRequest{} }
func (m *ListOktaGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*ListOktaGroupsRequest) ProtoMessage()    {}
func (*ListOktaGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3524976505a33edb, []int{0}
}
func (m *ListOktaGroupsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListOktaGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListOktaGroupsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListOktaGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOktaGroupsRequest.Merge(m, src)
}
func (m *ListOktaGroupsRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListOktaGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOktaGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOktaGroupsRequest proto.InternalMessageInfo

// ListOktaGroupsResponse is the response to listing Okta groups.
type ListOktaGroupsResponse struct {
	// The list of groups.
	Groups               []*types.OktaGroupV1 `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListOktaGroupsResponse) Reset()         { *m = ListOktaGroupsResponse{} }
func (m *ListOktaGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListOktaGroupsResponse) ProtoMessage()    {}
func (*ListOktaGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3524976505a33edb, []int{1}
}
func (m *ListOktaGroupsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListOktaGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListOktaGroupsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListOktaGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOktaGroupsResponse.Merge(m, src)
}
func (m *ListOktaGroupsResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListOktaGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOktaGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOktaGroupsResponse proto.InternalMessageInfo

func (m *ListOktaGroupsResponse) GetGroups() []*types.OktaGroupV1 {
	if m != nil {
		return m.Groups
	}
	return nil
}

// ListOktaApplicationRequest is a request for listing Okta applications.
type ListOktaApplicationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOktaApplicationsRequest) Reset()         { *m = ListOktaApplicationsRequest{} }
func (m *ListOktaApplicationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListOktaApplicationsRequest) ProtoMessage()    {}
func (*ListOktaApplicationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3524976505a33edb, []int{2}
}
func (m *ListOktaApplicationsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListOktaApplicationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListOktaApplicationsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListOktaApplicationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOktaApplicationsRequest.Merge(m, src)
}
func (m *ListOktaApplicationsRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListOktaApplicationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOktaApplicationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOktaApplicationsRequest proto.InternalMessageInfo

// ListOktaGroupsResponse is the response to listing Okta applications.
type ListOktaApplicationsResponse struct {
	// The list of applications.
	Applications         []*types.OktaApplicationV1 `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ListOktaApplicationsResponse) Reset()         { *m = ListOktaApplicationsResponse{} }
func (m *ListOktaApplicationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListOktaApplicationsResponse) ProtoMessage()    {}
func (*ListOktaApplicationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3524976505a33edb, []int{3}
}
func (m *ListOktaApplicationsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListOktaApplicationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListOktaApplicationsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListOktaApplicationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOktaApplicationsResponse.Merge(m, src)
}
func (m *ListOktaApplicationsResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListOktaApplicationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOktaApplicationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOktaApplicationsResponse proto.InternalMessageInfo

func (m *ListOktaApplicationsResponse) GetApplications() []*types.OktaApplicationV1 {
	if m != nil {
		return m.Applications
	}
	return nil
}

func init() {
	proto.RegisterType((*ListOktaGroupsRequest)(nil), "proto.ListOktaGroupsRequest")
	proto.RegisterType((*ListOktaGroupsResponse)(nil), "proto.ListOktaGroupsResponse")
	proto.RegisterType((*ListOktaApplicationsRequest)(nil), "proto.ListOktaApplicationsRequest")
	proto.RegisterType((*ListOktaApplicationsResponse)(nil), "proto.ListOktaApplicationsResponse")
}

func init() {
	proto.RegisterFile("teleport/legacy/client/proto/oktaservice.proto", fileDescriptor_3524976505a33edb)
}

var fileDescriptor_3524976505a33edb = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2b, 0x49, 0xcd, 0x49,
	0x2d, 0xc8, 0x2f, 0x2a, 0xd1, 0xcf, 0x49, 0x4d, 0x4f, 0x4c, 0xae, 0xd4, 0x4f, 0xce, 0xc9, 0x4c,
	0xcd, 0x2b, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0xcf, 0x2e, 0x49, 0x2c, 0x4e, 0x2d,
	0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0x8b, 0x08, 0xb1, 0x82, 0x29, 0x29, 0x45, 0x74, 0x6d, 0x25,
	0x95, 0x05, 0xa9, 0xc5, 0x10, 0x12, 0xa2, 0x52, 0x49, 0x9c, 0x4b, 0xd4, 0x27, 0xb3, 0xb8, 0xc4,
	0x3f, 0xbb, 0x24, 0xd1, 0xbd, 0x28, 0xbf, 0xb4, 0xa0, 0x38, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8,
	0x44, 0xc9, 0x85, 0x4b, 0x0c, 0x5d, 0xa2, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x8b, 0x8b,
	0x2d, 0x1d, 0x2c, 0x22, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xa4, 0x07, 0x31, 0x10, 0xae,
	0x34, 0xcc, 0x30, 0x08, 0xaa, 0x42, 0x49, 0x96, 0x4b, 0x1a, 0x66, 0x8a, 0x63, 0x41, 0x41, 0x4e,
	0x66, 0x72, 0x62, 0x49, 0x66, 0x7e, 0x1e, 0xdc, 0x92, 0x18, 0x2e, 0x19, 0xec, 0xd2, 0x50, 0xab,
	0x6c, 0xb8, 0x78, 0x12, 0x91, 0xc4, 0xa1, 0x16, 0x4a, 0x20, 0x59, 0x88, 0xa4, 0x2d, 0xcc, 0x30,
	0x08, 0x45, 0xb5, 0xd1, 0x09, 0x46, 0x2e, 0x31, 0x90, 0x1a, 0xcf, 0xbc, 0x92, 0xd4, 0xf4, 0x22,
	0xb0, 0x60, 0x30, 0x24, 0x98, 0x84, 0x7c, 0xb9, 0xf8, 0x50, 0x7d, 0x27, 0x24, 0x03, 0x09, 0x10,
	0x3d, 0xac, 0xa1, 0x21, 0x25, 0x8b, 0x43, 0x16, 0xea, 0xce, 0x78, 0x2e, 0x11, 0x6c, 0xfe, 0x10,
	0x52, 0x42, 0xd3, 0x86, 0x25, 0x0c, 0xa4, 0x94, 0xf1, 0xaa, 0x81, 0x58, 0xe0, 0xe4, 0x70, 0xe2,
	0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x46, 0x19, 0xa5, 0x67, 0x96,
	0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xa7, 0x17, 0x25, 0x96, 0x65, 0x96, 0x80, 0x95,
	0x27, 0xe6, 0xe8, 0xc3, 0x23, 0x3c, 0xb1, 0x20, 0x13, 0x25, 0x91, 0x24, 0xb1, 0x81, 0x29, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xac, 0xab, 0x9d, 0x25, 0x4b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OktaIntegrationServiceClient is the client API for OktaIntegrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OktaIntegrationServiceClient interface {
	// ListOktaGroups will return a list of groups from the Okta integration service.
	ListOktaGroups(ctx context.Context, in *ListOktaGroupsRequest, opts ...grpc.CallOption) (*ListOktaGroupsResponse, error)
	// ListApplications will return a list of applications from the Okta integration service.
	ListOktaApplications(ctx context.Context, in *ListOktaApplicationsRequest, opts ...grpc.CallOption) (*ListOktaApplicationsResponse, error)
}

type oktaIntegrationServiceClient struct {
	cc *grpc.ClientConn
}

func NewOktaIntegrationServiceClient(cc *grpc.ClientConn) OktaIntegrationServiceClient {
	return &oktaIntegrationServiceClient{cc}
}

func (c *oktaIntegrationServiceClient) ListOktaGroups(ctx context.Context, in *ListOktaGroupsRequest, opts ...grpc.CallOption) (*ListOktaGroupsResponse, error) {
	out := new(ListOktaGroupsResponse)
	err := c.cc.Invoke(ctx, "/proto.OktaIntegrationService/ListOktaGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oktaIntegrationServiceClient) ListOktaApplications(ctx context.Context, in *ListOktaApplicationsRequest, opts ...grpc.CallOption) (*ListOktaApplicationsResponse, error) {
	out := new(ListOktaApplicationsResponse)
	err := c.cc.Invoke(ctx, "/proto.OktaIntegrationService/ListOktaApplications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OktaIntegrationServiceServer is the server API for OktaIntegrationService service.
type OktaIntegrationServiceServer interface {
	// ListOktaGroups will return a list of groups from the Okta integration service.
	ListOktaGroups(context.Context, *ListOktaGroupsRequest) (*ListOktaGroupsResponse, error)
	// ListApplications will return a list of applications from the Okta integration service.
	ListOktaApplications(context.Context, *ListOktaApplicationsRequest) (*ListOktaApplicationsResponse, error)
}

// UnimplementedOktaIntegrationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOktaIntegrationServiceServer struct {
}

func (*UnimplementedOktaIntegrationServiceServer) ListOktaGroups(ctx context.Context, req *ListOktaGroupsRequest) (*ListOktaGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOktaGroups not implemented")
}
func (*UnimplementedOktaIntegrationServiceServer) ListOktaApplications(ctx context.Context, req *ListOktaApplicationsRequest) (*ListOktaApplicationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOktaApplications not implemented")
}

func RegisterOktaIntegrationServiceServer(s *grpc.Server, srv OktaIntegrationServiceServer) {
	s.RegisterService(&_OktaIntegrationService_serviceDesc, srv)
}

func _OktaIntegrationService_ListOktaGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOktaGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OktaIntegrationServiceServer).ListOktaGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OktaIntegrationService/ListOktaGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OktaIntegrationServiceServer).ListOktaGroups(ctx, req.(*ListOktaGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OktaIntegrationService_ListOktaApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOktaApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OktaIntegrationServiceServer).ListOktaApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OktaIntegrationService/ListOktaApplications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OktaIntegrationServiceServer).ListOktaApplications(ctx, req.(*ListOktaApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OktaIntegrationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.OktaIntegrationService",
	HandlerType: (*OktaIntegrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOktaGroups",
			Handler:    _OktaIntegrationService_ListOktaGroups_Handler,
		},
		{
			MethodName: "ListOktaApplications",
			Handler:    _OktaIntegrationService_ListOktaApplications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "teleport/legacy/client/proto/oktaservice.proto",
}

func (m *ListOktaGroupsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListOktaGroupsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListOktaGroupsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *ListOktaGroupsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListOktaGroupsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListOktaGroupsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Groups) > 0 {
		for iNdEx := len(m.Groups) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Groups[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintOktaservice(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ListOktaApplicationsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListOktaApplicationsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListOktaApplicationsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *ListOktaApplicationsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListOktaApplicationsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListOktaApplicationsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Applications) > 0 {
		for iNdEx := len(m.Applications) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Applications[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintOktaservice(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintOktaservice(dAtA []byte, offset int, v uint64) int {
	offset -= sovOktaservice(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ListOktaGroupsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListOktaGroupsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Groups) > 0 {
		for _, e := range m.Groups {
			l = e.Size()
			n += 1 + l + sovOktaservice(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListOktaApplicationsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListOktaApplicationsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Applications) > 0 {
		for _, e := range m.Applications {
			l = e.Size()
			n += 1 + l + sovOktaservice(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovOktaservice(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOktaservice(x uint64) (n int) {
	return sovOktaservice(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ListOktaGroupsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOktaservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListOktaGroupsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListOktaGroupsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipOktaservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOktaservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListOktaGroupsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOktaservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListOktaGroupsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListOktaGroupsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Groups", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOktaservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOktaservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOktaservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Groups = append(m.Groups, &types.OktaGroupV1{})
			if err := m.Groups[len(m.Groups)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOktaservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOktaservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListOktaApplicationsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOktaservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListOktaApplicationsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListOktaApplicationsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipOktaservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOktaservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListOktaApplicationsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOktaservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListOktaApplicationsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListOktaApplicationsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Applications", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOktaservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOktaservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOktaservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Applications = append(m.Applications, &types.OktaApplicationV1{})
			if err := m.Applications[len(m.Applications)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOktaservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOktaservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOktaservice(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOktaservice
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOktaservice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOktaservice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOktaservice
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOktaservice
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOktaservice
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOktaservice        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOktaservice          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOktaservice = fmt.Errorf("proto: unexpected end of group")
)
