.version: &version "18.7.6-rc.1-dev.entra-delta-sync.1"

name: teleport-operator
apiVersion: v2
version: *version
appVersion: *version
description: Teleport Operator provides management of select Teleport resources.
icon: https://goteleport.com/static/teleport-symbol-bimi.svg
keywords:
  - Teleport
