package services

import (
	"context"
	"encoding/base64"
	"fmt"
	"log/slog"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/gravitational/trace"

	"github.com/gravitational/teleport"
	"github.com/gravitational/teleport/api/types"
	"github.com/gravitational/teleport/e/lib/okta"
	oktaapi "github.com/gravitational/teleport/e/lib/okta/api"
	"github.com/gravitational/teleport/e/lib/okta/leader"
	oktaplugin "github.com/gravitational/teleport/e/lib/okta/plugin"
	eteleport "github.com/gravitational/teleport/e/lib/teleport"
	"github.com/gravitational/teleport/integrations/access/common"
	"github.com/gravitational/teleport/lib/auth/authclient"
	"github.com/gravitational/teleport/lib/authz"
	"github.com/gravitational/teleport/lib/cache"
	"github.com/gravitational/teleport/lib/service"
	"github.com/gravitational/teleport/lib/services"
)

const (
	oktaInit = "okta.init"
)

// oktaSettings holds externally-supplied, high-level options and to the Okta
// service factory (As opposed to the okta.Config struct, which holds a lot of
// implementation details)
type oktaSettings struct {
	orgUrl           string
	authProvider     oktaapi.AuthProvider
	pluginStatusSink common.StatusSink
	syncSettings     types.PluginOktaSyncSettings
	scimEnabled      bool
	plugin           types.Plugin
}

func (s *oktaSettings) orgURLBase64() string {
	orgURL := strings.TrimSuffix(s.orgUrl, "/")
	return base64.RawURLEncoding.EncodeToString([]byte(orgURL))
}

// OktaPluginPrams holds the parameters needed to initialize the Okta plugin.
type OktaPluginPrams struct {
	// Process is the Teleport process.
	Process *service.TeleportProcess
	// PluginStatusSink is the sink for plugin status events.
	PluginStatusSink common.StatusSink
	// PluginName is the name of the plugin.
	PluginName string
	// OrgUrl is Okta org URL.
	OrgUrl string
	// AuthProvider is the Okta auth provider.
	AuthProvider oktaapi.AuthProvider
	// SyncSettings are the Okta sync settings.
	SyncSettings types.PluginOktaSyncSettings
	// SCIMEnabled indicates that SCIM sync is enabled for this plugin instance.
	SCIMEnabled bool
	// Plugin is the Okta Plugin object.
	Plugin types.Plugin
}

// InitOktaPlugin will initialize and start the Okta service for plugin use. This will not
// fail the parent process on failure. A close event will be emitted when the okta init function ends.
func InitOktaPlugin(ctx context.Context, params OktaPluginPrams) string {
	// timestamp will be used to have a unique value to append to the end of the events generated by the Okta service.
	timestamp := fmt.Sprintf("%d", params.Process.Clock.Now().Unix())

	components := []string{params.PluginName, timestamp}
	identityEvent := EventWithComponents(OktaIdentityEvent, components...)

	process := params.Process
	// Set the expected instance role for this identity event since it's unique to this plugin.
	process.SetExpectedHostedPluginRole(types.RoleOkta, identityEvent)

	process.RegisterWithAuthServer(types.RoleOkta, identityEvent)
	process.RegisterFunc(oktaInit, func() error {
		return initOktaService(
			ctx, process,
			oktaSettings{
				orgUrl:           params.OrgUrl,
				authProvider:     params.AuthProvider,
				pluginStatusSink: params.PluginStatusSink,
				syncSettings:     params.SyncSettings,
				scimEnabled:      params.SCIMEnabled,
				plugin:           params.Plugin,
			},
			pluginLogComponent(params.PluginName),
			components...,
		)
	})

	return EventWithComponents(OktaStopped, components...)
}

// initOktaService initializes, starts, and waits for the Okta service.
func initOktaService(ctx context.Context, process *service.TeleportProcess, settings oktaSettings, logComponent string, components ...string) error {
	defer process.BroadcastEvent(service.Event{Name: EventWithComponents(OktaStopped, components...), Payload: nil})

	logger := process.Config.Logger.With(teleport.ComponentKey, teleport.Component(eteleport.ComponentOkta, logComponent))

	conn, err := process.WaitForConnector(EventWithComponents(OktaIdentityEvent, components...), logger)
	if conn == nil {
		return trace.Wrap(err)
	}

	accessPoint, cacheCleanup, err := newLocalCacheForOkta(process, conn.Client, []string{eteleport.ComponentOkta})
	if err != nil {
		return trace.Wrap(err)
	}

	// Cleanup the cache if a cleanup function is returned.
	if cacheCleanup != nil {
		defer func() {
			if err := cacheCleanup(); err != nil {
				logger.WarnContext(process.ExitContext(), "Error while closing Okta cache", "error", err)
			}
		}()
	}

	// Create the authorizer.
	clusterName := conn.ClusterName()
	lockWatcher, err := services.NewLockWatcher(ctx, services.LockWatcherConfig{
		ResourceWatcherConfig: services.ResourceWatcherConfig{
			Component: eteleport.ComponentOkta,
			Logger:    process.Config.Logger.With(teleport.ComponentKey, teleport.Component(eteleport.ComponentOkta, logComponent)),
			Client:    conn.Client,
		},
	})
	if err != nil {
		return trace.Wrap(err)
	}

	authorizer, err := authz.NewAuthorizer(authz.AuthorizerOpts{
		ClusterName: clusterName,
		AccessPoint: accessPoint,
		LockWatcher: lockWatcher,
	})
	if err != nil {
		return trace.Wrap(err)
	}

	// asyncEmitter makes sure that sessions do not block
	// in case if connections are slow
	asyncEmitter, err := process.NewAsyncEmitter(conn.Client)
	if err != nil {
		return trace.Wrap(err)
	}

	// Make sure that we close the emitter when this function exits
	defer func() {
		if err := asyncEmitter.Close(); err != nil {
			logger.WarnContext(process.ExitContext(), "Error while closing emitter", "error", err)
		}
	}()

	tlsConfig, err := conn.ServerTLSConfig(process.Config.CipherSuites)
	if err != nil {
		return trace.Wrap(err)
	}

	oktaLeader, err := leader.New(leader.Config{
		SemaphoreKind: okta.OktaServiceSemaphoreKind,
		SemaphoreName: settings.orgURLBase64(),
		HostIDHolder:  conn.HostUUID(),
		Clock:         process.Clock,
		Semaphores:    accessPoint,
	})
	if err != nil {
		return trace.Wrap(err)
	}
	oktaLeader.Start(ctx)

	timeBetweenImports, err := oktaplugin.GetTimeBetweenImports(&settings.syncSettings)
	if err != nil {
		return trace.Wrap(err)
	}

	timeBetweenAssignmentProcessLoops, err := oktaplugin.GetTimeBetweenAssignmentProcessLoops(&settings.syncSettings)
	if err != nil {
		return trace.Wrap(err)
	}

	var clt *http.Client
	if process.Config.Testing.HTTPTransport != nil {
		clt = &http.Client{Transport: process.Config.Testing.HTTPTransport}
	}

	oktaService, err := okta.New(ctx, okta.Config{
		Leader:                            oktaLeader,
		ConnectorService:                  conn.Client,
		Logger:                            process.Config.Logger.With(teleport.ComponentKey, teleport.Component(eteleport.ComponentOkta, logComponent)),
		Clock:                             process.Clock,
		TLSConfig:                         tlsConfig,
		Authorizer:                        authorizer,
		ClusterName:                       clusterName,
		Hostname:                          process.Config.Hostname,
		HostID:                            conn.HostUUID(),
		Emitter:                           asyncEmitter,
		AccessPoint:                       accessPoint,
		Access:                            conn.Client,
		AccessLists:                       conn.Client.AccessListClient(),
		OktaAPIEndpoint:                   settings.orgUrl,
		PluginStatusSink:                  settings.pluginStatusSink,
		TimeBetweenImports:                timeBetweenImports,
		TimeBetweenAssignmentProcessLoops: timeBetweenAssignmentProcessLoops,
		SyncSettings:                      settings.syncSettings,
		SCIMEnabled:                       settings.scimEnabled,
		AuthProvider:                      settings.authProvider,
		AssignmentsService:                conn.Client.OktaClient(),
		TestHTTPClient:                    clt,
		Plugin:                            settings.plugin,
	})
	if err != nil {
		return trace.Wrap(err)
	}

	var oktaServiceMu sync.Mutex

	process.OnExit("okta.stop", func(payload any) {
		if err := conn.Close(); err != nil {
			logger.WarnContext(ctx, "Error while closing connection", "error", err)
		}
		logger.InfoContext(process.ExitContext(), "Shutting down.")
		if err := oktaLeader.Close(); err != nil {
			logger.WarnContext(process.ExitContext(), "Error closing Okta leader", "error", err)
		}

		closeCtx := context.Background()
		if payload != nil {
			if payloadCtx, ok := payload.(context.Context); ok {
				closeCtx = payloadCtx
			}
		}

		oktaServiceMu.Lock()
		defer oktaServiceMu.Unlock()
		closeOktaService(closeCtx, logger, oktaService)
	})

	process.BroadcastEvent(service.Event{Name: EventWithComponents(OktaReady, components...), Payload: nil})

	if err := oktaService.Start(ctx); err != nil {
		return trace.Wrap(err)
	}

	if settings.syncSettings.GetEnableSystemLogExport() {
		oktaService.StartSystemLogExporter(ctx, okta.StartIntegrationOpts{
			AccessGraphConfig:  process.Config.AccessGraph,
			BootstrapStartDate: time.Now().UTC().Add(-10 * time.Hour * 24), // 10 days back
			ClusterFeatures:    process.GetClusterFeatures,
			GetCreds:           conn.ClientGetCertificate,
		})
	}

	logger.InfoContext(process.ExitContext(), "Okta service has successfully started")

	oktaService.Wait(ctx)

	// If we get here, we can attempt to clean up the service. Either this is a result of the
	// context being canceled (will happen with plugins), or the OnExit is running.
	// If OnExit has finished, the Okta service's Shutdown/Close will be skipped.
	oktaServiceMu.Lock()

	// We'll use a context with a short timeout in case Close() was not run by OnExit.
	closeCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	closeOktaService(closeCtx, logger, oktaService)
	cancel()

	// Set the okta service to nil so that the OnExit function is not holding onto a reference
	// to the okta service despite no longer being necessary.
	oktaService = nil
	oktaServiceMu.Unlock()

	return nil
}

// combinedOktaClient is an auth.Client client with services.Okta added to it.
type combinedOktaClient struct {
	authclient.ClientI
	services.AccessLists
	services.Okta
}

// newLocalCacheForOkta returns a new instance of access point for an Okta service. Returns
// a cleanup function for the cache as well.
func newLocalCacheForOkta(process *service.TeleportProcess, clt authclient.ClientI, cacheName []string) (authclient.OktaAccessPoint, func() error, error) {
	accessListClient := clt.AccessListClient()
	oktaClient := clt.OktaClient()
	client := combinedOktaClient{clt, accessListClient, oktaClient}
	// if caching is disabled, return access point
	if !process.Config.CachePolicy.Enabled {
		return client, nil, nil
	}
	cache, err := process.NewLocalCache(clt, cache.ForOkta, cacheName)
	if err != nil {
		return nil, nil, trace.Wrap(err)
	}
	return authclient.NewOktaWrapper(client, cache), cache.Close, nil
}

// closeOktaService will close the Okta service.
func closeOktaService(ctx context.Context, log *slog.Logger, oktaService *okta.Service) {
	// Don't bother if the Okta service is nil.
	if oktaService == nil {
		return
	}

	if err := oktaService.Shutdown(); err != nil {
		log.ErrorContext(ctx, "Error shutting down Okta service", "error", err)
	}
}
