// package aws implements AWS marketplace license enforcement
package aws

import (
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"io/ioutil"
	"net/http"

	"github.com/gravitational/teleport/api/v7/types"
	apiutils "github.com/gravitational/teleport/api/v7/utils"

	liblicense "github.com/gravitational/license"
	"github.com/gravitational/trace"
)

// Verify verifies license generated by built in production certificate authority
func Verify(licenseKeyPair liblicense.License, license types.License) error {
	if err := licenseKeyPair.Verify([]byte(TeleportCACert)); err != nil {
		return trace.Wrap(err)
	}

	meta, err := GetInstanceMetadata()
	if err != nil {
		return trace.Wrap(err)
	}

	// unsupported mode - either account id or metadata should be present
	if license.GetAWSAccountID() == "" && license.GetAWSProductID() == "" {
		return trace.BadParameter("internal error #21, contact support@gravitational.com")
	}

	// license is bound to account ID
	if license.GetAWSAccountID() != "" && license.GetAWSAccountID() != meta.AccountID {
		return trace.BadParameter("this teleport version should run on instances of AWS account %v", license.GetAWSAccountID())
	}

	// license is bound to marketplace product code
	if license.GetAWSProductID() != "" && !apiutils.SliceContainsStr(meta.MarketplaceProductCodes, license.GetAWSProductID()) {
		return trace.BadParameter("this teleport version should run on instances of AWS with marketplace product code %v", license.GetAWSProductID())
	}

	return nil
}

// InstanceMetadata is a partial of AWS instance metadata
type InstanceMetadata struct {
	// BillingProducts is a list of billing products AMI is associated with
	BillingProducts []string `json:"billingProducts"`
	// MarketplaceProductCodes is a list of marketplace product codes the AMI is associated with
	MarketplaceProductCodes []string `json:"marketplaceProductCodes"`
	// AccountID is id of the account
	AccountID string `json:"accountId"`
}

// GetInstanceMetadata fetches instance metadata and returns parsed result
// caller can supply custom downloader function (used in tests)
func GetInstanceMetadata(downloader ...Downloader) (*InstanceMetadata, error) {
	fn := download
	if len(downloader) != 0 {
		fn = downloader[0]
	}
	doc, err := fn("http://169.254.169.254/latest/dynamic/instance-identity/document")
	if err != nil {
		return nil, trace.ConnectionProblem(err, "failed to fetch instance metadata, this version can only run on AWS instance")
	}
	sig, err := fn("http://169.254.169.254/latest/dynamic/instance-identity/signature")
	if err != nil {
		return nil, trace.ConnectionProblem(err, "failed to fetch instance metadata, this version can only run on AWS instance")
	}
	return DecodeAndVerify(doc, sig)
}

// DecodeAndVerify verifies AWS instance metadata document with SHA256 with RSA signature
// the signature is generated by AWS and is using public certificate published
// in the docs.
func DecodeAndVerify(doc, sig []byte) (*InstanceMetadata, error) {
	sigBytes, err := base64.StdEncoding.DecodeString(string(sig))
	if err != nil {
		return nil, trace.Wrap(err, "failed to decode signature")
	}

	block, _ := pem.Decode([]byte(AWSCACert))
	if block == nil {
		return nil, trace.BadParameter("could not decode certificate PEM")
	}

	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return nil, trace.Wrap(err)
	}

	if err := cert.CheckSignature(x509.SHA256WithRSA, doc, sigBytes); err != nil {
		return nil, trace.Wrap(err)
	}

	var meta InstanceMetadata
	if err := json.Unmarshal(doc, &meta); err != nil {
		return nil, trace.Wrap(err)
	}

	return &meta, nil
}

// Downloader function downloads document from URI
type Downloader func(uri string) ([]byte, error)

// download downloads document from URI
func download(uri string) ([]byte, error) {
	re, err := http.Get(uri)
	if err != nil {
		return nil, trace.ConvertSystemError(err)
	}
	defer re.Body.Close()
	data, err := ioutil.ReadAll(re.Body)
	if err != nil {
		return nil, trace.ConvertSystemError(err)
	}
	return data, nil
}

// AWSCACert is a certificate issued by AWS and is used to sign
// all instance metadata documents
const AWSCACert = `-----BEGIN CERTIFICATE-----
MIIDIjCCAougAwIBAgIJAKnL4UEDMN/FMA0GCSqGSIb3DQEBBQUAMGoxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdTZWF0dGxlMRgw
FgYDVQQKEw9BbWF6b24uY29tIEluYy4xGjAYBgNVBAMTEWVjMi5hbWF6b25hd3Mu
Y29tMB4XDTE0MDYwNTE0MjgwMloXDTI0MDYwNTE0MjgwMlowajELMAkGA1UEBhMC
VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1NlYXR0bGUxGDAWBgNV
BAoTD0FtYXpvbi5jb20gSW5jLjEaMBgGA1UEAxMRZWMyLmFtYXpvbmF3cy5jb20w
gZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAIe9GN//SRK2knbjySG0ho3yqQM3
e2TDhWO8D2e8+XZqck754gFSo99AbT2RmXClambI7xsYHZFapbELC4H91ycihvrD
jbST1ZjkLQgga0NE1q43eS68ZeTDccScXQSNivSlzJZS8HJZjgqzBlXjZftjtdJL
XeE4hwvo0sD4f3j9AgMBAAGjgc8wgcwwHQYDVR0OBBYEFCXWzAgVyrbwnFncFFIs
77VBdlE4MIGcBgNVHSMEgZQwgZGAFCXWzAgVyrbwnFncFFIs77VBdlE4oW6kbDBq
MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHU2Vh
dHRsZTEYMBYGA1UEChMPQW1hem9uLmNvbSBJbmMuMRowGAYDVQQDExFlYzIuYW1h
em9uYXdzLmNvbYIJAKnL4UEDMN/FMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEF
BQADgYEAFYcz1OgEhQBXIwIdsgCOS8vEtiJYF+j9uO6jz7VOmJqO+pRlAbRlvY8T
C1haGgSI/A1uZUKs/Zfnph0oEI0/hu1IIJ/SKBDtN5lvmZ/IzbOPIJWirlsllQIQ
7zvWbGd9c9+Rm3p04oTvhup99la7kZqevJK0QRdD/6NpCKsqP/0=
-----END CERTIFICATE-----`

// TeleportCACert is a teleport license certificate authority
// certificate used for license checking
const TeleportCACert = `-----BEGIN CERTIFICATE-----
MIIDCjCCAfKgAwIBAgIUJQC5YEYaz6p85zRLw+jAVHgiI1MwDQYJKoZIhvcNAQEL
BQAwHDEaMBgGA1UEAxMRZ3Jhdml0YXRpb25hbC5jb20wIBcNMTgwMzMxMTk1NjAw
WhgPMjExODAzMDcxOTU2MDBaMBwxGjAYBgNVBAMTEWdyYXZpdGF0aW9uYWwuY29t
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwPzZlqYhi71S9YDa1ImW
O610hxeEl8zMneAUTyy38UWRuCBNb4rzHWKrAL+ZAQI7jGBJJwqPOoiCHEt+bpk7
CT9VWeakfGIF0dTCyMnFfUBgNkB494MQtwTP5KBIZSw9mrC3i5MNm6eP1zJYBZp8
7CXoXRDiHvA/26tJlRWGr7pBhtnnqvjsp24Bv8P6HFF3sw1g7iyNC9gBXo22Vhj/
vVUhe05gx5E+m2Bav2sIL6mIvw27Mzk404LlSRgXpCAf3x2yYX9T6cndG+SmIAld
FGUz3fTe4kZH7nV0AzUTS9+n0cv5Zu7slCHFXIm7hV7pUAJN/ndTKFgVcnJ11lY6
bQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNV
HQ4EFgQU8x5p1sqRgeIQVWGMLv8A410hMfUwDQYJKoZIhvcNAQELBQADggEBAHpR
unpu5Mpe7L3FSpyIr+0uNstM9xeG8g6/1fkwZYJnUATAGCgQv5oW+2WKMbQEoJR1
4XQNsADZJ18CcS61L6dAP+5moJkh5X1EzdfJRwL6WhY4W4232T64TfTlAdDZ3skR
daD6yNQGlrruIXVWDQqV5qpFQY5wRK8xaKGlaRF8EPkkOb82tcaSB6QDVDl9J+J2
TlwryD9252TBFpuU4xk+k6Zk3yVOs9xRno2bOcJ97WXx4yhRSLpUGs9sInKyNdUt
LfEedVgpWc65lEoCvw8BOVHnXkJLnI7tloTWKa6XqEmvzkixDT5nrxXyKXBXqAcQ
SxronfUa5laGm6SkeVE=
-----END CERTIFICATE-----`
