apiVersion: v2
name: teleport-plugin-jira
description: A Helm chart for the Teleport Jira Plugin
type: application
version: &version "19.0.0-dev.terraform.3"
appVersion: *version

dependencies:
  - name: tbot
    version: *version
    condition: tbot.enabled
