
# Runs subcommand assign-reviewers
assign: 
	go run cmd/bot.go assign-reviewers 

# Runs subcommand check-reviewers
check: 
	go run cmd/bot.go check-reviewers 

# Runs all Go tests and shows the coverage
test: 
	go test ./... -cover

lint: 
	golangci-lint run
