#!/bin/sh

#
# the directory where Teleport binaries will be located
#
BINDIR=/usr/local/bin

# the directory where Teleport plugins store their certificates
# and other data files
#
DATADIR=/var/lib/teleport/plugins/datadog

[ ! $(id -u) != "0" ] || { echo "ERROR: You must be root"; exit 1; }
cd $(dirname $0)
mkdir -p $BINDIR $DATADIR
cp -f teleport-datadog $BINDIR/ || exit 1

echo "Teleport Datadog Incident Management plugin binaries have been copied to $BINDIR"
echo "You can run teleport-datadog configure > /etc/teleport-datadog.toml to bootstrap your config file."
