steps:
  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-root:v0.1.0
    id: pull-buildbox-image
    args: ["echo", "done"]

  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-root:v0.1.0
    id: checkout
    secretEnv:
      - WEBASSETS_DEPLOYMENT_KEY
    entrypoint: /bin/bash
    args:
      - "-c"
      - "go run .cloudbuild/ci/checkout.go -workspace=/tmp/teleport -target=$_BASE_BRANCH"

  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-root:v0.1.0
    id: check
    env:
      - FLAGS=-cover -race
      - TELEPORT_ETCD_TEST="yes"
    entrypoint: /bin/bash
    dir: /tmp/teleport
    args:
      - "-c"
      - "(make run-etcd &); sleep 1; make test"
      
availableSecrets:
  secretManager:
  - versionName: projects/771512790633/secrets/webassets-e-deployment-key/versions/2
    env: WEBASSETS_DEPLOYMENT_KEY

timeout: 20m

options:
  volumes:
    - name: oss_teleport
      path: /tmp/teleport

  machineType: 'E2_HIGHCPU_32'
  
