export const UPSERT_ROLES = 'CLUSTER_ROLES_UPSERT';
export const RECEIVE_ROLES = 'CLUSTER_ROLES_RECEIVE';
export const SET_CURRENT = 'CLUSTER_ROLES_SET_CURRENT';
export const DELETE_ROLE = 'CLUSTER_ROLES_DELETE';