{{- $proxy := mustDeepCopy . -}}

{{/* Merge .Values.proxy up into the top level so teleport-proxy-lib templates
     read everything from .Values.* (see examples/chart/lib/README.md) */}}
{{- $_ := set $proxy "Values" (mustMergeOverwrite (mustDeepCopy .Values) .Values.proxy) -}}
{{- $_ := set $proxy.Values.serviceAccount "name" (include "teleport-cluster.proxy.serviceAccountName" .) -}}

{{/* Prepend an initContainer to wait for auth server upgrades */}}
{{- $proxyValues := $proxy.Values -}}
{{- $waitAuthUpdate := dict
  "name" "wait-auth-update"
  "skipDefaultVolumeMounts" true
  "image" (printf "%s:%s" (ternary $proxyValues.enterpriseImage $proxyValues.image $proxyValues.enterprise) (include "teleport-cluster.version" .))
  "command" (list
    "teleport"
    "wait"
    "no-resolve"
    (printf "%s.%s.svc.%s" (include "teleport-cluster.auth.previousVersionServiceName" .) .Release.Namespace (include "teleport-cluster.clusterDomain" .))
  )
-}}
{{- if $proxyValues.resources }}
{{- $_ := set $waitAuthUpdate "resources" (dict
  "requests" (dict "cpu" 0.1 "memory" "256Mi")
  "limits" (dict "cpu" 1 "memory" "512Mi")
) -}}
{{- end }}
{{- if $proxyValues.securityContext }}
{{- $_ := set $waitAuthUpdate "securityContext" $proxyValues.securityContext -}}
{{- end }}
{{- $_ := set $proxy.Values "initContainers" (prepend (default (list) $proxy.Values.initContainers) $waitAuthUpdate) -}}

{{/* Set the auth server URL to the internal k8s cluster service */}}
{{- $_ := set $proxy.Values "teleportAuthServiceFQDN" (printf "%s:3025" (include "teleport-cluster.auth.serviceFQDN" .)) -}}
{{- $_ := set $proxy.Values "forceHAReplicas" (hasKey (default (dict) .Values.proxy.highAvailability) "replicaCount") -}}

{{/* Render all proxy charts */}}
{{- include "teleport-proxy-lib.all" $proxy -}}
