ARG TELEPORT_VERSION=18
FROM public.ecr.aws/gravitational/teleport-ent-distroless:${TELEPORT_VERSION} AS src
FROM debian:bookworm-slim
COPY --from=src /usr/local/bin/teleport /usr/local/bin/teleport
ENTRYPOINT ["teleport", "start", "--insecure", "-c", "/etc/teleport/node.yaml"]
