package api

import (
	"strings"

	"github.com/gravitational/trace"
)

// AppCredentials are OAuth credentials necessary to authorize with the Microsoft identity platform.
// https://learn.microsoft.com/en-us/graph/auth-v2-service?tabs=http
type AppCredentials struct {
	// Tenant is the primary domain name (e.g. contoso.onmicrosoft.com) or the tenant ID (e.g.
	// 38d49456-54d4-455d-a8d6-c383c71e0a6d) of an organization within Microsoft Entra ID.
	//
	// https://learn.microsoft.com/en-us/partner-center/account-settings/find-ids-and-domain-names#find-the-microsoft-entra-tenant-id-and-primary-domain-name
	Tenant string
	// ClientID is the application ID generated by the app registration portal.
	// https://learn.microsoft.com/en-us/graph/auth-register-app-v2
	ClientID string
	// ClientID is the client secret generated by the app registration portal.
	// https://learn.microsoft.com/en-us/graph/auth-register-app-v2
	ClientSecret string
}

// Validate checks if AppCredentials contains values required to authenticate to the Graph API.
func (c AppCredentials) Validate() error {
	switch {
	case c.ClientID == "":
		return trace.BadParameter("param ClientID required")
	case c.ClientSecret == "":
		return trace.BadParameter("param ClientSecret required")
	case c.Tenant == "":
		return trace.BadParameter("param Tenant required")
	}

	// Tenant can be either a domain name or a UUID. It becomes a part of the URL that the request for
	// an access token is sent to. If the tenant includes a scheme and is then put in the URL, such
	// request returns a vague 404 with no extra details as to what is wrong.
	if strings.HasPrefix(c.Tenant, "http://") {
		return trace.BadParameter("param Tenant must not start with http://")
	}
	if strings.HasPrefix(c.Tenant, "https://") {
		return trace.BadParameter("param Tenant must not start with https://")
	}

	return nil
}
