/*
 * Teleport
 * Copyright (C) 2023  Gravitational, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package authclient

import (
	"context"
	"encoding/json"
	"net/url"
	"strings"

	"github.com/gravitational/trace"

	"github.com/gravitational/teleport/api/client/proto"
	presencev1 "github.com/gravitational/teleport/api/gen/proto/go/teleport/presence/v1"
	trustpb "github.com/gravitational/teleport/api/gen/proto/go/teleport/trust/v1"
	"github.com/gravitational/teleport/api/types"
	"github.com/gravitational/teleport/api/utils/clientutils"
	"github.com/gravitational/teleport/lib/defaults"
	"github.com/gravitational/teleport/lib/services"
)

// httpfallback.go holds endpoints that have been converted to gRPC
// but still need http fallback logic in the old client.

// ValidateTrustedCluster is called by the proxy on behalf of a cluster that
// wishes to join another as a leaf cluster.
func (c *Client) ValidateTrustedCluster(ctx context.Context, validateRequest *ValidateTrustedClusterRequest) (*ValidateTrustedClusterResponse, error) {
	protoReq, err := validateRequest.ToProto()
	if err != nil {
		return nil, trace.Wrap(err, "converting native ValidateTrustedClusterRequest to proto")
	}
	protoResp, err := c.APIClient.ValidateTrustedCluster(ctx, protoReq)
	if err != nil {
		if trace.IsNotImplemented(err) {
			return c.HTTPClient.validateTrustedCluster(ctx, validateRequest)
		}
		return nil, trace.Wrap(err, "calling ValidateTrustedCluster on gRPC client")
	}
	return ValidateTrustedClusterResponseFromProto(protoResp), nil
}

// ValidateGithubAuthCallback validates Github auth callback returned from redirect.
func (c *Client) ValidateGithubAuthCallback(ctx context.Context, q url.Values) (*GithubAuthResponse, error) {
	protoResp, err := c.APIClient.ValidateGithubAuthCallback(ctx, ValidateGithubAuthCallbackRequestToProto(q))
	if err != nil {
		if trace.IsNotImplemented(err) {
			return c.HTTPClient.validateGithubAuthCallback(ctx, q)
		}
		return nil, trace.Wrap(err)
	}
	return GithubAuthResponseFromProto(protoResp), nil
}

// validateGithubAuthCallbackReq is a request to validate Github OAuth2 callback
//
// TODO(strideynet): DELETE IN v20.0.0
type validateGithubAuthCallbackReq struct {
	// Query is the callback query string
	Query url.Values `json:"query"`
}

// githubAuthRawResponse is returned when auth server validated callback
// parameters returned from Github during OAuth2 flow
//
// TODO(strideynet): DELETE IN v20.0.0
type githubAuthRawResponse struct {
	// Username is authenticated teleport username
	Username string `json:"username"`
	// Identity contains validated OIDC identity
	Identity types.ExternalIdentity `json:"identity"`
	// Web session will be generated by auth server if requested in OIDCAuthRequest
	Session json.RawMessage `json:"session,omitempty"`
	// Cert will be generated by certificate authority
	Cert []byte `json:"cert,omitempty"`
	// TLSCert is PEM encoded TLS certificate
	TLSCert []byte `json:"tls_cert,omitempty"`
	// Req is original oidc auth request
	Req GithubAuthRequest `json:"req"`
	// HostSigners is a list of signing host public keys
	// trusted by proxy, used in console login
	HostSigners []json.RawMessage `json:"host_signers"`
	// ClientOptions contains some options that the cluster wants the client to
	// use.
	ClientOptions ClientOptions `json:"client_options"`
}

// validateGithubAuthCallback validates Github auth callback returned from redirect
//
// TODO(strideynet): DELETE IN v20.0.0
func (c *HTTPClient) validateGithubAuthCallback(ctx context.Context, q url.Values) (*GithubAuthResponse, error) {
	out, err := c.PostJSON(ctx, c.Endpoint("github", "requests", "validate"),
		validateGithubAuthCallbackReq{Query: q})
	if err != nil {
		return nil, trace.Wrap(err)
	}
	var rawResponse githubAuthRawResponse
	if err := json.Unmarshal(out.Bytes(), &rawResponse); err != nil {
		return nil, trace.Wrap(err)
	}
	response := GithubAuthResponse{
		Username:      rawResponse.Username,
		Identity:      rawResponse.Identity,
		Cert:          rawResponse.Cert,
		Req:           rawResponse.Req,
		TLSCert:       rawResponse.TLSCert,
		ClientOptions: rawResponse.ClientOptions,
	}
	if len(rawResponse.Session) != 0 {
		session, err := services.UnmarshalWebSession(
			rawResponse.Session)
		if err != nil {
			return nil, trace.Wrap(err)
		}
		response.Session = session
	}
	response.HostSigners = make([]types.CertAuthority, len(rawResponse.HostSigners))
	for i, raw := range rawResponse.HostSigners {
		ca, err := services.UnmarshalCertAuthority(raw)
		if err != nil {
			return nil, trace.Wrap(err)
		}
		response.HostSigners[i] = ca
	}
	return &response, nil
}

// ValidateSAMLResponse validates response returned by SAML identity provider.
func (c *Client) ValidateSAMLResponse(ctx context.Context, samlResponse, connectorID, clientIP string) (*SAMLAuthResponse, error) {
	protoResp, err := c.APIClient.ValidateSAMLResponse(ctx, &proto.ValidateSAMLResponseRequest{
		Response:    samlResponse,
		ConnectorId: connectorID,
		ClientIp:    clientIP,
	})
	if err != nil {
		if trace.IsNotImplemented(err) {
			return c.HTTPClient.validateSAMLResponse(ctx, samlResponse, connectorID, clientIP)
		}
		if trace.IsLimitExceeded(err) && strings.Contains(err.Error(), "received message larger than max") {
			return nil, trace.Wrap(err, "SAML response is too large for the Auth Service to accept, configure the identity provider to include fewer groups or attributes in the assertion")
		}
		return nil, trace.Wrap(err)
	}
	return SAMLAuthResponseFromProto(protoResp), nil
}

// ValidateSAMLResponseReq is the request made by the proxy to validate
// and activate a login via SAML.
//
// Still exported because the legacy HTTP handler in e/lib/auth references it.
//
// TODO(strideynet): DELETE IN v20.0.0
type ValidateSAMLResponseReq struct {
	// Response is SAML statements coming from the identity provider.
	Response string `json:"response"`
	// ConnectorID is ID of a SAML connector that should be used for this request.
	ConnectorID string `json:"connector_id,omitempty"`
	// ClientIP is IP of the logging in client, used in identity provider initiated login case,
	// when we don't have original client's request with their IP stored.
	ClientIP string `json:"client_ip,omitempty"`
}

// SAMLAuthRawResponse is returned when auth server validated callback parameters
// returned from SAML provider
//
// Still exported because the legacy HTTP handler in e/lib/auth references it.
//
// TODO(strideynet): DELETE IN v20.0.0
type SAMLAuthRawResponse struct {
	// Username is authenticated teleport username
	Username string `json:"username"`
	// Identity contains validated OIDC identity
	Identity types.ExternalIdentity `json:"identity"`
	// Web session will be generated by auth server if requested in OIDCAuthRequest
	Session json.RawMessage `json:"session,omitempty"`
	// Cert will be generated by certificate authority
	Cert []byte `json:"cert,omitempty"`
	// Req is original oidc auth request
	Req SAMLAuthRequest `json:"req"`
	// HostSigners is a list of signing host public keys
	// trusted by proxy, used in console login
	HostSigners []json.RawMessage `json:"host_signers"`
	// TLSCert is TLS certificate authority certificate
	TLSCert []byte `json:"tls_cert,omitempty"`
	// MFAToken is an SSO MFA token.
	MFAToken string `json:"mfa_token"`
	// ClientOptions contains some options that the cluster wants the client to
	// use.
	ClientOptions ClientOptions `json:"client_options"`
}

// validateSAMLResponse validates response returned by SAML identity provider
// via the legacy HTTP endpoint.
//
// TODO(strideynet): DELETE IN v20.0.0
func (c *HTTPClient) validateSAMLResponse(ctx context.Context, samlResponse, connectorID, clientIP string) (*SAMLAuthResponse, error) {
	out, err := c.PostJSON(ctx, c.Endpoint("saml", "requests", "validate"), ValidateSAMLResponseReq{
		Response:    samlResponse,
		ConnectorID: connectorID,
		ClientIP:    clientIP,
	})
	if err != nil {
		return nil, trace.Wrap(err)
	}
	var rawResponse SAMLAuthRawResponse
	if err := json.Unmarshal(out.Bytes(), &rawResponse); err != nil {
		return nil, trace.Wrap(err)
	}
	response := SAMLAuthResponse{
		Username:      rawResponse.Username,
		Identity:      rawResponse.Identity,
		Cert:          rawResponse.Cert,
		Req:           rawResponse.Req,
		TLSCert:       rawResponse.TLSCert,
		MFAToken:      rawResponse.MFAToken,
		ClientOptions: rawResponse.ClientOptions,
	}
	if len(rawResponse.Session) != 0 {
		session, err := services.UnmarshalWebSession(rawResponse.Session)
		if err != nil {
			return nil, trace.Wrap(err)
		}
		response.Session = session
	}
	response.HostSigners = make([]types.CertAuthority, len(rawResponse.HostSigners))
	for i, raw := range rawResponse.HostSigners {
		ca, err := services.UnmarshalCertAuthority(raw)
		if err != nil {
			return nil, trace.Wrap(err)
		}
		response.HostSigners[i] = ca
	}
	return &response, nil
}

// AuthenticateWebUser authenticates a web user with their credentials and
// issues a web session on success.
func (c *Client) AuthenticateWebUser(ctx context.Context, req AuthenticateUserRequest) (types.WebSession, error) {
	resp, err := c.APIClient.AuthenticateWebUser(ctx, &proto.AuthenticateWebUserRequest{
		Request: req.ToProto(),
	})
	if err != nil {
		if trace.IsNotImplemented(err) {
			return c.HTTPClient.authenticateWebUser(ctx, req)
		}
		return nil, trace.Wrap(err)
	}
	if resp.Session == nil {
		return nil, trace.BadParameter("missing session in AuthenticateWebUserResponse")
	}
	return resp.Session, nil
}

// authenticateWebUser authenticates a web user via the legacy HTTP endpoint.
//
// TODO(strideynet): DELETE IN v20.0.0
func (c *HTTPClient) authenticateWebUser(ctx context.Context, req AuthenticateUserRequest) (types.WebSession, error) {
	out, err := c.PostJSON(
		ctx,
		c.Endpoint("users", url.PathEscape(req.Username), "web", "authenticate"),
		req,
	)
	if err != nil {
		return nil, trace.Wrap(err)
	}
	return services.UnmarshalWebSession(out.Bytes())
}

// AuthenticateSSHUser authenticates a local user with their credentials and
// issues SSH and TLS certificates on success.
func (c *Client) AuthenticateSSHUser(ctx context.Context, req AuthenticateSSHRequest) (*CLILoginResponse, error) {
	resp, err := c.APIClient.AuthenticateSSHUser(ctx, req.ToProto())
	if err != nil {
		if trace.IsNotImplemented(err) {
			return c.authenticateSSHUserHTTP(ctx, req)
		}
		// gRPC surfaces an expired caller context as a status error with a
		// timing-dependent message. Return the context error itself to keep
		// the HTTP client's errors.Is behavior for callers.
		if ctxErr := ctx.Err(); ctxErr != nil {
			return nil, trace.Wrap(ctxErr)
		}
		return nil, trace.Wrap(err)
	}
	return CLILoginResponseFromProto(resp), nil
}

// authenticateSSHUserHTTP authenticates a local user via the legacy HTTP
// endpoint.
//
// TODO(strideynet): DELETE IN v20.0.0
func (c *Client) authenticateSSHUserHTTP(ctx context.Context, req AuthenticateSSHRequest) (*CLILoginResponse, error) {
	httpClient := c.HTTPClient
	if req.HeadlessAuthenticationID != "" {
		// Headless authentication blocks until approval, so apply the longer
		// timeout to a clone of the shared HTTP client.
		var err error
		httpClient, err = c.CloneHTTPClient(
			ClientParamTimeout(defaults.HeadlessLoginTimeout),
			ClientParamResponseHeaderTimeout(defaults.HeadlessLoginTimeout),
		)
		if err != nil {
			return nil, trace.Wrap(err)
		}
	}
	out, err := httpClient.PostJSON(
		ctx,
		httpClient.Endpoint("users", url.PathEscape(req.Username), "ssh", "authenticate"),
		req,
	)
	if err != nil {
		return nil, trace.Wrap(err)
	}
	var re CLILoginResponse
	if err := json.Unmarshal(out.Bytes(), &re); err != nil {
		return nil, trace.Wrap(err)
	}
	return &re, nil
}

// TODO(noah): DELETE IN 21.0.0
func (c *HTTPClient) validateTrustedCluster(ctx context.Context, validateRequest *ValidateTrustedClusterRequest) (*ValidateTrustedClusterResponse, error) {
	validateRequestRaw, err := validateRequest.ToRaw()
	if err != nil {
		return nil, trace.Wrap(err)
	}

	out, err := c.PostJSON(ctx, c.Endpoint("trustedclusters", "validate"), validateRequestRaw)
	if err != nil {
		return nil, trace.Wrap(err)
	}

	var validateResponseRaw ValidateTrustedClusterResponseRaw
	err = json.Unmarshal(out.Bytes(), &validateResponseRaw)
	if err != nil {
		return nil, trace.Wrap(err)
	}

	validateResponse, err := validateResponseRaw.ToNative()
	if err != nil {
		return nil, trace.Wrap(err)
	}

	return validateResponse, nil
}

// UpsertTunnelConnection creates or updates a tunnel connection record.
//
// TODO(strideynet): DELETE IN v20.0.0
func (c *Client) UpsertTunnelConnection(ctx context.Context, conn types.TunnelConnection) error {
	connV2, ok := conn.(*types.TunnelConnectionV2)
	if !ok {
		return trace.BadParameter("unsupported tunnel connection type %T", conn)
	}
	_, err := c.TrustClient().UpsertTunnelConnection(ctx, trustpb.UpsertTunnelConnectionRequest_builder{
		TunnelConnection: connV2,
	}.Build())
	if err != nil {
		if trace.IsNotImplemented(err) {
			return trace.Wrap(c.HTTPClient.upsertTunnelConnection(ctx, conn))
		}
		return trace.Wrap(err)
	}
	return nil
}

// TODO(strideynet): DELETE IN v20.0.0
func (c *HTTPClient) upsertTunnelConnection(ctx context.Context, conn types.TunnelConnection) error {
	data, err := services.MarshalTunnelConnection(conn)
	if err != nil {
		return trace.Wrap(err)
	}
	args := &struct {
		TunnelConnection json.RawMessage `json:"tunnel_connection"`
	}{
		TunnelConnection: data,
	}
	_, err = c.PostJSON(ctx, c.Endpoint("tunnelconnections"), args)
	return trace.Wrap(err)
}

// DeleteTunnelConnection removes a tunnel connection by cluster and connection name.
//
// TODO(strideynet): DELETE IN v20.0.0
func (c *Client) DeleteTunnelConnection(ctx context.Context, clusterName, connName string) error {
	_, err := c.TrustClient().DeleteTunnelConnection(ctx, trustpb.DeleteTunnelConnectionRequest_builder{
		ClusterName:    clusterName,
		ConnectionName: connName,
	}.Build())
	if err != nil {
		if trace.IsNotImplemented(err) {
			return trace.Wrap(c.HTTPClient.deleteTunnelConnection(ctx, clusterName, connName))
		}
		return trace.Wrap(err)
	}
	return nil
}

// TODO(strideynet): DELETE IN v20.0.0
func (c *HTTPClient) deleteTunnelConnection(ctx context.Context, clusterName, connName string) error {
	if clusterName == "" {
		return trace.BadParameter("missing parameter cluster name")
	}
	if connName == "" {
		return trace.BadParameter("missing parameter connection name")
	}
	_, err := c.Delete(ctx, c.Endpoint("tunnelconnections", clusterName, connName))
	return trace.Wrap(err)
}

// GetTunnelConnections returns all tunnel connections for a given cluster.
//
// TODO(noah): DELETE IN 20.0.0 — inline the gRPC page-loop directly once the
// HTTP fallback is removed; keep the method signature.
func (c *Client) GetTunnelConnections(ctx context.Context, clusterName string) ([]types.TunnelConnection, error) {
	if clusterName == "" {
		return nil, trace.BadParameter("missing cluster name parameter")
	}
	return c.listAllTunnelConnections(ctx, clusterName)
}

// GetAllTunnelConnections returns all tunnel connections across all clusters.
//
// TODO(noah): DELETE IN 20.0.0
func (c *Client) GetAllTunnelConnections(ctx context.Context) ([]types.TunnelConnection, error) {
	return c.listAllTunnelConnections(ctx, "")
}

// TODO(noah): DELETE IN 20.0.0
func (c *Client) listAllTunnelConnections(ctx context.Context, clusterName string) ([]types.TunnelConnection, error) {
	var filter *trustpb.ListTunnelConnectionsFilter
	if clusterName != "" {
		filter = trustpb.ListTunnelConnectionsFilter_builder{ClusterName: clusterName}.Build()
	}

	items, err := clientutils.CollectWithFallback(
		ctx,
		func(
			ctx context.Context, pageSize int, pageToken string,
		) ([]types.TunnelConnection, string, error) {
			return c.APIClient.ListTunnelConnections(ctx, pageSize, pageToken, filter)
		},
		func(ctx context.Context) ([]types.TunnelConnection, error) {
			if clusterName != "" {
				return c.HTTPClient.getTunnelConnectionsLegacy(ctx, clusterName)
			}
			return c.HTTPClient.getAllTunnelConnectionsLegacy(ctx)
		},
	)
	if err != nil {
		return nil, trace.Wrap(err)
	}
	return items, nil
}

// getTunnelConnectionsLegacy returns tunnel connections for a given cluster.
//
// TODO(noah): DELETE IN 20.0.0
func (c *HTTPClient) getTunnelConnectionsLegacy(ctx context.Context, clusterName string) ([]types.TunnelConnection, error) {
	if clusterName == "" {
		return nil, trace.BadParameter("missing cluster name parameter")
	}
	out, err := c.Get(ctx, c.Endpoint("tunnelconnections", clusterName), url.Values{})
	if err != nil {
		return nil, trace.Wrap(err)
	}
	var items []json.RawMessage
	if err := json.Unmarshal(out.Bytes(), &items); err != nil {
		return nil, trace.Wrap(err)
	}
	conns := make([]types.TunnelConnection, len(items))
	for i, raw := range items {
		conn, err := services.UnmarshalTunnelConnection(raw)
		if err != nil {
			return nil, trace.Wrap(err)
		}
		conns[i] = conn
	}
	return conns, nil
}

// getAllTunnelConnectionsLegacy returns all tunnel connections.
//
// TODO(noah): DELETE IN 20.0.0
func (c *HTTPClient) getAllTunnelConnectionsLegacy(ctx context.Context) ([]types.TunnelConnection, error) {
	out, err := c.Get(ctx, c.Endpoint("tunnelconnections"), url.Values{})
	if err != nil {
		return nil, trace.Wrap(err)
	}
	var items []json.RawMessage
	if err := json.Unmarshal(out.Bytes(), &items); err != nil {
		return nil, trace.Wrap(err)
	}
	conns := make([]types.TunnelConnection, len(items))
	for i, raw := range items {
		conn, err := services.UnmarshalTunnelConnection(raw)
		if err != nil {
			return nil, trace.Wrap(err)
		}
		conns[i] = conn
	}
	return conns, nil
}

// GetAuthServers returns the list of auth servers registered in the cluster.
//
// Deprecated: Prefer paginated variant [APIClient.ListAuthServers].
//
// TODO(kiosion): DELETE IN 21.0.0
func (c *HTTPClient) GetAuthServers() ([]types.Server, error) {
	out, err := c.Get(context.TODO(), c.Endpoint("authservers"), url.Values{})
	if err != nil {
		return nil, trace.Wrap(err)
	}
	var items []json.RawMessage
	if err := json.Unmarshal(out.Bytes(), &items); err != nil {
		return nil, trace.Wrap(err)
	}
	re := make([]types.Server, len(items))
	for i, raw := range items {
		server, err := services.UnmarshalServer(raw, types.KindAuthServer)
		if err != nil {
			return nil, trace.Wrap(err)
		}
		re[i] = server
	}
	return re, nil
}

// UpsertProxyServerWithoutReturn registers a proxy server heartbeat. It calls
// the gRPC PresenceService and falls back to the legacy HTTP endpoint if the
// server does not yet implement the gRPC RPC. The upserted proxy server is not
// returned because the HTTP fallback path cannot provide it; once the fallback
// is removed in v20 this can be replaced with a method that returns the
// upserted server.
//
// TODO(noah): DELETE IN v20.0.0
func (c *Client) UpsertProxyServerWithoutReturn(ctx context.Context, s types.Server) error {
	serverV2, ok := s.(*types.ServerV2)
	if !ok {
		return trace.BadParameter("unsupported proxy server type %T", s)
	}
	_, err := c.APIClient.PresenceServiceClient().UpsertProxyServer(ctx, presencev1.UpsertProxyServerRequest_builder{
		Server: serverV2,
	}.Build())
	if err == nil {
		return nil
	}
	if !trace.IsNotImplemented(err) {
		return trace.Wrap(err)
	}
	return c.HTTPClient.upsertProxyServerLegacy(ctx, s)
}

// upsertProxyServerLegacy registers a proxy server heartbeat via the legacy
// HTTP endpoint.
//
// TODO(noah): DELETE IN v20.0.0
func (c *HTTPClient) upsertProxyServerLegacy(ctx context.Context, s types.Server) error {
	data, err := services.MarshalServer(s)
	if err != nil {
		return trace.Wrap(err)
	}
	args := &upsertServerRawReq{
		Server: data,
	}
	_, err = c.PostJSON(ctx, c.Endpoint("proxies"), args)
	return trace.Wrap(err)
}

// DeleteProxyServer deletes a proxy server heartbeat by name. It calls the
// gRPC PresenceService and falls back to the legacy HTTP endpoint if the
// server does not yet implement the gRPC RPC.
//
// TODO(noah): DELETE IN v20.0.0
func (c *Client) DeleteProxyServer(ctx context.Context, name string) error {
	_, err := c.APIClient.PresenceServiceClient().DeleteProxyServer(ctx, presencev1.DeleteProxyServerRequest_builder{
		Name: name,
	}.Build())
	if err == nil {
		return nil
	}
	if !trace.IsNotImplemented(err) {
		return trace.Wrap(err)
	}
	return c.HTTPClient.deleteProxyServerLegacy(ctx, name)
}

// deleteProxyServerLegacy deletes proxy by name via the legacy HTTP endpoint.
//
// TODO(noah): DELETE IN v20.0.0
func (c *HTTPClient) deleteProxyServerLegacy(ctx context.Context, name string) error {
	if name == "" {
		return trace.BadParameter("missing parameter name")
	}
	_, err := c.Delete(ctx, c.Endpoint("proxies", name))
	if err != nil {
		return trace.Wrap(err)
	}
	return nil
}

// ExtendWebSession creates a new web session for a user based on a valid
// existing web session, e.g. to apply an approved access request, switch back
// to default roles, or pick up recent user changes. It calls the gRPC
// AuthService and falls back to the legacy HTTP endpoint if the server does
// not yet implement the gRPC RPC.
//
// TODO(strideynet): DELETE IN v20.0.0 - remove the fallback and call the gRPC
// RPC directly.
func (c *Client) ExtendWebSession(ctx context.Context, req WebSessionReq) (types.WebSession, error) {
	resp, err := c.APIClient.ExtendWebSession(ctx, &proto.ExtendWebSessionRequest{
		User:            req.User,
		PrevSessionId:   req.PrevSessionID,
		AccessRequestId: req.AccessRequestID,
		Switchback:      req.Switchback,
		ReloadUser:      req.ReloadUser,
	})
	if err != nil {
		if trace.IsNotImplemented(err) {
			return c.HTTPClient.extendWebSessionLegacy(ctx, req)
		}
		return nil, trace.Wrap(err)
	}
	return resp.GetSession(), nil
}

// extendWebSessionLegacy creates a new web session for a user based on a
// valid existing web session via the legacy HTTP endpoint.
//
// TODO(strideynet): DELETE IN v20.0.0
func (c *HTTPClient) extendWebSessionLegacy(ctx context.Context, req WebSessionReq) (types.WebSession, error) {
	out, err := c.PostJSON(ctx, c.Endpoint("users", req.User, "web", "sessions"), req)
	if err != nil {
		return nil, trace.Wrap(err)
	}
	return services.UnmarshalWebSession(out.Bytes())
}

// GetProxies returns the list of auth servers registered in the cluster.
//
// Deprecated: Prefer paginated variant [APIClient.ListProxyServers].
//
// TODO(kiosion): DELETE IN 21.0.0
func (c *HTTPClient) GetProxies() ([]types.Server, error) {
	out, err := c.Get(context.TODO(), c.Endpoint("proxies"), url.Values{})
	if err != nil {
		return nil, trace.Wrap(err)
	}
	var items []json.RawMessage
	if err := json.Unmarshal(out.Bytes(), &items); err != nil {
		return nil, trace.Wrap(err)
	}
	re := make([]types.Server, len(items))
	for i, raw := range items {
		server, err := services.UnmarshalServer(raw, types.KindProxy)
		if err != nil {
			return nil, trace.Wrap(err)
		}
		re[i] = server
	}
	return re, nil
}
