---
kind: pipeline
type: kubernetes
name: push-build-linux-amd64

environment:
  RUNTIME: go1.21.4
  UID: 1000
  GID: 1000

trigger:
  event:
    include:
      - push
    exclude:
      - pull_request
  branch:
    include:
      - master
      - branch/*
  repo:
    include:
      - gravitational/*

workspace:
  path: /go

clone:
  disable: true

steps:
  - name: Check out code
    image: docker:git
    environment:
      GITHUB_PRIVATE_KEY:
        from_secret: GITHUB_PRIVATE_KEY
    commands:
      - mkdir -p /go/src/github.com/gravitational/teleport/e /go/cache
      - cd /go/src/github.com/gravitational/teleport
      # check out teleport code from the matching upstream branch name
      # (this is the best indicator of the correct target branch)
      - |
        git init && git remote add origin https://github.com/gravitational/teleport
        git fetch origin +refs/heads/${DRONE_COMMIT_BRANCH}:
        git checkout ${DRONE_COMMIT_BRANCH}
      # write private key
      - mkdir -m 0700 /root/.ssh && echo -n "$GITHUB_PRIVATE_KEY" > /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa
      - ssh-keyscan -H github.com > /root/.ssh/known_hosts 2>/dev/null && chmod 600 /root/.ssh/known_hosts
      # now manually clone the teleport.e repo and check out the correct commit hash
      # this ensures that tests will run against the changed teleport.e code
      - cd /go/src/github.com/gravitational/teleport/e
      - |
        git init && git remote add origin ${DRONE_REMOTE_URL}
        git fetch origin
        git checkout -qf ${DRONE_COMMIT_SHA}
      - rm -f /root/.ssh/id_rsa

  - name: Build artifacts
    image: docker
    environment:
      UID: 1000
      GID: 1000
      GOCACHE: /go/cache
      GOPATH: /go
      OS: linux
      ARCH: amd64
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - apk add --no-cache make
      - chown -R $UID:$GID /go
      - cd /go/src/github.com/gravitational/teleport
      - make -C build.assets release OS=$OS ARCH=$ARCH

  - name: Send Slack notification
    image: plugins/slack:1.4.1
    settings:
      template: |-
        *✘ Failed:* `{{ build.event }}` / `${DRONE_STAGE_NAME}` / <{{ build.link }}|Build: #{{ build.number }}>
        Author: <https://github.com/{{ build.author }}|{{ build.author }}> Repo: <https://github.com/{{ repo.owner }}/{{ repo.name }}/|{{ repo.owner }}/{{ repo.name }}> Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}> Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
      webhook:
        from_secret: SLACK_WEBHOOK_DEV_TELEPORT
    when:
      status:
        - failure

services:
  - name: Start Docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

---
kind: pipeline
type: kubernetes
name: push-build-linux-i386

environment:
  RUNTIME: go1.21.4
  UID: 1000
  GID: 1000

trigger:
  event:
    include:
      - push
    exclude:
      - pull_request
  branch:
    include:
      - master
      - branch/*
  repo:
    include:
      - gravitational/*

workspace:
  path: /go

clone:
  disable: true

steps:
  - name: Check out code
    image: docker:git
    environment:
      GITHUB_PRIVATE_KEY:
        from_secret: GITHUB_PRIVATE_KEY
    commands:
      - mkdir -p /go/src/github.com/gravitational/teleport/e /go/cache
      - cd /go/src/github.com/gravitational/teleport
      # check out teleport code from the matching upstream branch name
      # (this is the best indicator of the correct target branch)
      - |
        git init && git remote add origin https://github.com/gravitational/teleport
        git fetch origin +refs/heads/${DRONE_COMMIT_BRANCH}:
        git checkout ${DRONE_COMMIT_BRANCH}
      # write private key
      - mkdir -m 0700 /root/.ssh && echo -n "$GITHUB_PRIVATE_KEY" > /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa
      - ssh-keyscan -H github.com > /root/.ssh/known_hosts 2>/dev/null && chmod 600 /root/.ssh/known_hosts
      # now manually clone the teleport.e repo and check out the correct commit hash
      # this ensures that tests will run against the changed teleport.e code
      - cd /go/src/github.com/gravitational/teleport/e
      - |
        git init && git remote add origin ${DRONE_REMOTE_URL}
        git fetch origin
        git checkout -qf ${DRONE_COMMIT_SHA}
      - rm -f /root/.ssh/id_rsa

  - name: Build artifacts
    image: docker
    environment:
      UID: 1000
      GID: 1000
      GOCACHE: /go/cache
      GOPATH: /go
      OS: linux
      ARCH: 386
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - apk add --no-cache make
      - chown -R $UID:$GID /go
      - cd /go/src/github.com/gravitational/teleport
      - make -C build.assets release OS=$OS ARCH=$ARCH

  - name: Send Slack notification
    image: plugins/slack:1.4.1
    settings:
      template: |-
        *✘ Failed:* `{{ build.event }}` / `${DRONE_STAGE_NAME}` / <{{ build.link }}|Build: #{{ build.number }}>
        Author: <https://github.com/{{ build.author }}|{{ build.author }}> Repo: <https://github.com/{{ repo.owner }}/{{ repo.name }}/|{{ repo.owner }}/{{ repo.name }}> Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}> Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
      webhook:
        from_secret: SLACK_WEBHOOK_DEV_TELEPORT
    when:
      status:
        - failure

services:
  - name: Start Docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

---
kind: pipeline
type: kubernetes
name: push-build-linux-amd64-fips

environment:
  RUNTIME: go1.21.4
  UID: 1000
  GID: 1000

trigger:
  event:
    include:
      - push
    exclude:
      - pull_request
  branch:
    include:
      - master
      - branch/*
  repo:
    include:
      - gravitational/*

workspace:
  path: /go

clone:
  disable: true

steps:
  - name: Check out code
    image: docker:git
    environment:
      GITHUB_PRIVATE_KEY:
        from_secret: GITHUB_PRIVATE_KEY
    commands:
      - mkdir -p /go/src/github.com/gravitational/teleport/e /go/cache
      - cd /go/src/github.com/gravitational/teleport
      # check out teleport code from the matching upstream branch name
      # (this is the best indicator of the correct target branch)
      - |
        git init && git remote add origin https://github.com/gravitational/teleport
        git fetch origin +refs/heads/${DRONE_COMMIT_BRANCH}:
        git checkout ${DRONE_COMMIT_BRANCH}
      # write private key
      - mkdir -m 0700 /root/.ssh && echo -n "$GITHUB_PRIVATE_KEY" > /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa
      - ssh-keyscan -H github.com > /root/.ssh/known_hosts 2>/dev/null && chmod 600 /root/.ssh/known_hosts
      # now manually clone the teleport.e repo and check out the correct commit hash
      # this ensures that tests will run against the changed teleport.e code
      - cd /go/src/github.com/gravitational/teleport/e
      - |
        git init && git remote add origin ${DRONE_REMOTE_URL}
        git fetch origin
        git checkout -qf ${DRONE_COMMIT_SHA}
      - rm -f /root/.ssh/id_rsa
      # set version
      - cd /go/src/github.com/gravitational/teleport
      - egrep ^VERSION Makefile | cut -d= -f2 > /go/.version.txt; cat /go/.version.txt

  - name: Build FIPS artifacts
    image: docker
    environment:
      UID: 1000
      GID: 1000
      GOCACHE: /go/cache
      GOPATH: /go
      OS: linux
      ARCH: amd64
      FIPS: "yes"
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - apk add --no-cache make
      - chown -R $UID:$GID /go
      - cd /go/src/github.com/gravitational/teleport
      - export VERSION=$(cat /go/.version.txt)
      - make -C build.assets release-amd64-centos7-fips
  - name: Send Slack notification
    image: plugins/slack:1.4.1
    settings:
      template: |-
        *✘ Failed:* `{{ build.event }}` / `${DRONE_STAGE_NAME}` / <{{ build.link }}|Build: #{{ build.number }}>
        Author: <https://github.com/{{ build.author }}|{{ build.author }}> Repo: <https://github.com/{{ repo.owner }}/{{ repo.name }}/|{{ repo.owner }}/{{ repo.name }}> Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}> Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
      webhook:
        from_secret: SLACK_WEBHOOK_DEV_TELEPORT
    when:
      status:
        - failure

services:
  - name: Start Docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

---
kind: pipeline
type: kubernetes
name: push-build-windows-amd64

environment:
  RUNTIME: go1.21.4
  UID: 1000
  GID: 1000

trigger:
  event:
    include:
      - push
    exclude:
      - pull_request
  branch:
    include:
      - master
      - branch/*
  repo:
    include:
      - gravitational/*

workspace:
  path: /go

clone:
  disable: true

steps:
  - name: Check out code
    image: docker:git
    environment:
      GITHUB_PRIVATE_KEY:
        from_secret: GITHUB_PRIVATE_KEY
    commands:
      - mkdir -p /go/src/github.com/gravitational/teleport/e /go/cache
      - cd /go/src/github.com/gravitational/teleport
      # check out teleport code from the matching upstream branch name
      # (this is the best indicator of the correct target branch)
      - |
        git init && git remote add origin https://github.com/gravitational/teleport
        git fetch origin +refs/heads/${DRONE_COMMIT_BRANCH}:
        git checkout ${DRONE_COMMIT_BRANCH}
      # write private key
      - mkdir -m 0700 /root/.ssh && echo -n "$GITHUB_PRIVATE_KEY" > /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa
      - ssh-keyscan -H github.com > /root/.ssh/known_hosts 2>/dev/null && chmod 600 /root/.ssh/known_hosts
      # now manually clone the teleport.e repo and check out the correct commit hash
      # this ensures that tests will run against the changed teleport.e code
      - cd /go/src/github.com/gravitational/teleport/e
      - |
        git init && git remote add origin ${DRONE_REMOTE_URL}
        git fetch origin
        git checkout -qf ${DRONE_COMMIT_SHA}
      - rm -f /root/.ssh/id_rsa

  - name: Build artifacts
    image: docker
    environment:
      UID: 1000
      GID: 1000
      GOCACHE: /go/cache
      GOPATH: /go
      OS: windows
      ARCH: amd64
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - apk add --no-cache make
      - chown -R $UID:$GID /go
      - cd /go/src/github.com/gravitational/teleport
      - make -C build.assets release-windows-unsigned OS=$OS ARCH=$ARCH

  - name: Send Slack notification
    image: plugins/slack:1.4.1
    settings:
      template: |-
        *✘ Failed:* `{{ build.event }}` / `${DRONE_STAGE_NAME}` / <{{ build.link }}|Build: #{{ build.number }}>
        Author: <https://github.com/{{ build.author }}|{{ build.author }}> Repo: <https://github.com/{{ repo.owner }}/{{ repo.name }}/|{{ repo.owner }}/{{ repo.name }}> Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}> Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
      webhook:
        from_secret: SLACK_WEBHOOK_DEV_TELEPORT
    when:
      status:
        - failure

services:
  - name: Start Docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

---
kind: pipeline
type: kubernetes
name: push-build-linux-arm

environment:
  RUNTIME: go1.21.4
  UID: 1000
  GID: 1000

trigger:
  event:
    include:
      - push
    exclude:
      - pull_request
  branch:
    include:
      - master
      - branch/*
  repo:
    include:
      - gravitational/*

workspace:
  path: /go

clone:
  disable: true

steps:
  - name: Check out code
    image: docker:git
    environment:
      GITHUB_PRIVATE_KEY:
        from_secret: GITHUB_PRIVATE_KEY
    commands:
      - mkdir -p /go/src/github.com/gravitational/teleport/e /go/cache
      - cd /go/src/github.com/gravitational/teleport
      # check out teleport code from the matching upstream branch name
      # (this is the best indicator of the correct target branch)
      - |
        git init && git remote add origin https://github.com/gravitational/teleport
        git fetch origin +refs/heads/${DRONE_COMMIT_BRANCH}:
        git checkout ${DRONE_COMMIT_BRANCH}
      # write private key
      - mkdir -m 0700 /root/.ssh && echo -n "$GITHUB_PRIVATE_KEY" > /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa
      - ssh-keyscan -H github.com > /root/.ssh/known_hosts 2>/dev/null && chmod 600 /root/.ssh/known_hosts
      # now manually clone the teleport.e repo and check out the correct commit hash
      # this ensures that tests will run against the changed teleport.e code
      - cd /go/src/github.com/gravitational/teleport/e
      - |
        git init && git remote add origin ${DRONE_REMOTE_URL}
        git fetch origin
        git checkout -qf ${DRONE_COMMIT_SHA}
      - rm -f /root/.ssh/id_rsa

  - name: Build artifacts
    image: docker
    environment:
      UID: 1000
      GID: 1000
      GOCACHE: /go/cache
      GOPATH: /go
      OS: linux
      ARCH: arm
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - apk add --no-cache make
      - chown -R $UID:$GID /go
      - cd /go/src/github.com/gravitational/teleport
      - make -C build.assets release-arm

  - name: Send Slack notification
    image: plugins/slack:1.4.1
    settings:
      template: |-
        *✘ Failed:* `{{ build.event }}` / `${DRONE_STAGE_NAME}` / <{{ build.link }}|Build: #{{ build.number }}>
        Author: <https://github.com/{{ build.author }}|{{ build.author }}> Repo: <https://github.com/{{ repo.owner }}/{{ repo.name }}/|{{ repo.owner }}/{{ repo.name }}> Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}> Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
      webhook:
        from_secret: SLACK_WEBHOOK_DEV_TELEPORT
    when:
      status:
        - failure

services:
  - name: Start Docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

---
kind: pipeline
type: kubernetes
name: push-build-linux-arm64

environment:
  RUNTIME: go1.21.4
  UID: 1000
  GID: 1000

trigger:
  event:
    include:
      - push
    exclude:
      - pull_request
  branch:
    include:
      - master
      - branch/*
  repo:
    include:
      - gravitational/*

workspace:
  path: /go

clone:
  disable: true

steps:
  - name: Check out code
    image: docker:git
    environment:
      GITHUB_PRIVATE_KEY:
        from_secret: GITHUB_PRIVATE_KEY
    commands:
      - mkdir -p /go/src/github.com/gravitational/teleport/e /go/cache
      - cd /go/src/github.com/gravitational/teleport
      # check out teleport code from the matching upstream branch name
      # (this is the best indicator of the correct target branch)
      - |
        git init && git remote add origin https://github.com/gravitational/teleport
        git fetch origin +refs/heads/${DRONE_COMMIT_BRANCH}:
        git checkout ${DRONE_COMMIT_BRANCH}
      # write private key
      - mkdir -m 0700 /root/.ssh && echo -n "$GITHUB_PRIVATE_KEY" > /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa
      - ssh-keyscan -H github.com > /root/.ssh/known_hosts 2>/dev/null && chmod 600 /root/.ssh/known_hosts
      # now manually clone the teleport.e repo and check out the correct commit hash
      # this ensures that tests will run against the changed teleport.e code
      - cd /go/src/github.com/gravitational/teleport/e
      - |
        git init && git remote add origin ${DRONE_REMOTE_URL}
        git fetch origin
        git checkout -qf ${DRONE_COMMIT_SHA}
      - rm -f /root/.ssh/id_rsa

  - name: Build artifacts
    image: docker
    environment:
      UID: 1000
      GID: 1000
      GOCACHE: /go/cache
      GOPATH: /go
      OS: linux
      ARCH: arm64
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - apk add --no-cache make
      - chown -R $UID:$GID /go
      - cd /go/src/github.com/gravitational/teleport
      - make -C build.assets release-arm64

  - name: Send Slack notification
    image: plugins/slack:1.4.1
    settings:
      template: |-
        *✘ Failed:* `{{ build.event }}` / `${DRONE_STAGE_NAME}` / <{{ build.link }}|Build: #{{ build.number }}>
        Author: <https://github.com/{{ build.author }}|{{ build.author }}> Repo: <https://github.com/{{ repo.owner }}/{{ repo.name }}/|{{ repo.owner }}/{{ repo.name }}> Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}> Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
      webhook:
        from_secret: SLACK_WEBHOOK_DEV_TELEPORT
    when:
      status:
        - failure

services:
  - name: Start Docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

---
kind: signature
hmac: 2ff572307735ae0dbbc1f997705eab5e8a1c1691cca7565e58f1b3a912a29883

...
