# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# This Vagrantfile is for quick making a multi-host environment
# to experiment & play with Teleport.
#
#   1. Creates several identical VMs
#   2. Based on Debian Jessie 8
#   3. With private networking
#   4. With Docker installed
#
require "../base.rb"

Vagrant.configure(2) do |config|
  config.vbguest.auto_update = true

  config.vm.box = "debian/contrib-jessie64"
  config.vm.box_check_update = false

  basic_config(config.vm)
  configure_ssh(config.vm)
  apt_update(config.vm)
  install_docker(config.vm, DOCKER_VER)
  install_teleport(config.vm)
  configure_teleport(config.vm)

  config.vm.synced_folder "../../", "/home/vagrant/teleport"

  NODES.each do |role, array|
      conf = array[0]
      addr = array[1]
      config.vm.define role do |config|
          config.vm.hostname = role
          config.vm.network "private_network", ip: addr
          config.vm.provider "virtualbox" do |vb|
              vb.cpus = 1
              vb.memory = 380
          end

          config.vm.synced_folder "../data/opt/#{conf}", "/opt/teleport", disabled: false, accessmode: "mapped"
          data_dir = "../data/var/#{conf}"
          if File.directory? data_dir
            config.vm.synced_folder(data_dir, "/var/lib/teleport", type: "rsync", disabled: false)
          end
      end
  end 
end


def install_teleport(vm)
    vm.provision "shell", inline: <<-SHELL
        cd /tmp
        curl -L https://github.com/gravitational/teleport/releases/download/v1.2.0/teleport-v1.2.0-linux-amd64-bin.tar.gz | tar -xz
        make -C teleport install
    SHELL
end
