# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# This Vagrantfile is for quick making a multi-host environment
# to experiment & play with Teleport.
#
#   1. Creates several identical VMs
#   2. Based on Debian Jessie 8
#   3. With private networking
#   4. With Docker installed
#
require "../base.rb"
NODES = {
  "a-auth"  => "10.0.10.10", 
  "a-node"  => "10.0.10.12",
  "b-auth"  => "10.0.10.20", 
}

DOCKER_VER ||= "1.10.3"

Vagrant.configure(2) do |config|
  config.vm.box = "debian/contrib-jessie64"
  config.vm.box_check_update = false

  basic_config(config.vm)
  configure_ssh(config.vm)
  #apt_update(config.vm)
  install_docker(config.vm, DOCKER_VER)
  install_teleport(config.vm)
  configure_teleport(config.vm)

  config.vm.synced_folder "../../", "/home/vagrant/teleport"

  NODES.each do |role, addr|
      config.vm.define role do |config|
          config.vm.hostname = role
          config.vm.network "private_network", ip: addr
          config.vm.provider "virtualbox" do |vb|
              vb.cpus = 1
              vb.memory = 512
          end
          config.vm.synced_folder "../data/opt/#{role}", "/opt/teleport", disabled: false, accessmode: "mapped"
          config.vm.synced_folder "../data/var/#{role}", "/var/lib/teleport", type: "rsync", disabled: false
      end
  end 
end


def install_teleport(vm)
    vm.provision "shell", inline: <<-SHELL
        cd /tmp
        curl -L https://github.com/gravitational/teleport/releases/download/v1.0.0/teleport-v1.0.0-linux-amd64-bin.tar.gz | tar -xz
        make -C teleport install
    SHELL
end
