[package]
name = "teleport-auth-package"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# Empty workspace list to prevent this from being
# included in Teleport's cargo workspace.
[workspace]

[profile.release]
lto = "thin"
strip = true
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
embed-resource = "2.4.0"
regex = "1.10.2"

[dependencies]
log = "0.4.20"
rand = { version = "0.8.5", default-features = false, features = ["getrandom"] }
serde_json = "1.0.107"
serde = { version = "1.0.190", features = ["derive"] }
anyhow = "1.0.75"
humantime = "2.1.0"
include-flate = { version = "0.2.0", features = ["stable"] }

[dependencies.windows]
version = "0.51.1"
features = [
    "implement",
    "Foundation",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_NetworkManagement_NetManagement",
    "Win32_Security",
    "Win32_Security_Credentials",
    "Win32_Security_Authentication_Identity",
    "Win32_Security_Authorization",
    "Win32_Security_Cryptography",
    "Win32_System_Com",
    "Win32_System_Kernel",
    "Win32_System_Memory",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_UI_Shell",
]
