package main

import (
	"context"
	"strings"
	"time"

	"github.com/gravitational/trace"

	apiclient "github.com/gravitational/teleport/api/client"
	apidefaults "github.com/gravitational/teleport/api/defaults"
	"github.com/gravitational/teleport/api/types"
	apievents "github.com/gravitational/teleport/api/types/events"
	"github.com/gravitational/teleport/api/utils/clientutils"
	workloadclient "github.com/gravitational/teleport/e/tests/antithesis/workloads/lib/client"
	"github.com/gravitational/teleport/e/tests/antithesis/workloads/lib/eventually"
	"github.com/gravitational/teleport/lib/events"
)

type auditEventsPageFunc = func(context.Context, int, string) ([]apievents.AuditEvent, string, error)

func getEventsPage(clt *apiclient.Client, start, end time.Time, eventTypes ...string) auditEventsPageFunc {
	return func(ctx context.Context, limit int, startKey string) ([]apievents.AuditEvent, string, error) {
		return clt.SearchEvents(
			ctx, start, end, apidefaults.Namespace,
			eventTypes,
			limit, types.EventOrderAscending, startKey, "")
	}
}

func (p *TestCaseParams) assertSSHCommandAuditEvents(ctx context.Context, marker string, start, end time.Time) error {
	admin, err := workloadclient.NewAPIClient(ctx, adminIdentity)
	if err != nil {
		return trace.Wrap(err, "creating api client")
	}
	defer admin.Close()

	details := p.Details(map[string]any{
		"marker": marker,
		"from":   start,
		"to":     end,
	})

	var discoveredSID string
	// We don't know our session ID that is generated by Teleport, discover it by searching for [events.SessionStartEvent]
	// with the command matching the marker we have used.
	err = eventually.Assert(ctx, eventually.AssertParams{
		Message: "exec event for marker command is discoverable",
		Timeout: auditEventEmitDeadline,
		Details: details,
		Condition: func(ctx context.Context, addDetail eventually.AddDetailFunc) (bool, error) {
			for evt, err := range clientutils.Resources(ctx, getEventsPage(admin, start, end, events.SessionStartEvent)) {
				if err != nil {
					return false, trace.Wrap(err, "reading events")
				}
				e, ok := evt.(*apievents.SessionStart)
				if !ok {
					continue
				}
				for _, arg := range e.InitialCommand {
					if strings.Contains(arg, marker) {
						discoveredSID = e.SessionMetadata.SessionID
						addDetail("discovered_session_id", discoveredSID)
						return true, nil
					}
				}
			}
			return false, nil
		},
	})
	if err != nil {
		return trace.Wrap(err, "discovering session id")
	}

	// Finally using the discovered marker, search all events, including SessionStartEvent,
	// to ensure no duplicate events have been emitted.
	return trace.Wrap(eventually.Assert(ctx, eventually.AssertParams{
		Message: "Successful SSH command has exactly one SessionLeaveEvent, SessionStartEvent and SessionEndEvent event",
		Timeout: auditEventEmitDeadline,
		Details: details,
		Condition: func(ctx context.Context, addDetail eventually.AddDetailFunc) (bool, error) {
			eventmap := map[string]int{}
			for evt, err := range clientutils.Resources(ctx, getEventsPage(
				admin,
				start,
				end,
				events.SessionStartEvent,
				events.SessionLeaveEvent,
				events.SessionEndEvent,
			)) {
				if err != nil {
					return false, trace.Wrap(err, "reading events")
				}

				if g, ok := evt.(events.SessionMetadataGetter); ok {
					if g.GetSessionID() != discoveredSID {
						continue
					}
				}

				// Map all events for this session ID.
				eventmap[evt.GetType()]++
			}

			addDetail("eventcounts", eventmap)
			condition := eventmap[events.SessionStartEvent] == 1 &&
				eventmap[events.SessionLeaveEvent] == 1 &&
				eventmap[events.SessionEndEvent] == 1
			return condition, nil
		},
	}))
}
