# extends teleport.service env to inform teleport that
# it should be exporting an appropriate upgrade schedule
[Service]
Environment="TELEPORT_EXT_UPGRADER=unit"
Environment="TELEPORT_EXT_UPGRADER_VERSION=v13.0.0-unset"
