# extends teleport.service env to inform teleport that
# it should be exporting an appropriate upgrade schedule
[Service]
Environment="TELEPORT_EXT_UPGRADER=unit"
Environment="TELEPORT_EXT_UPGRADER_VERSION=v13.0.0-unset"

# Extends teleport.service to export the timestamp of the last restart.
# This is used by the updater to help determine if the agent is in an
# unhealthy state.
ExecStopPost=/bin/bash -c 'date +%%s > /var/lib/teleport-upgrade/state-last-restart'
