clusterName: helm-lint
auth_server: teleport-auth.example.com
join_params:
  method: kubernetes
  token_name: teleport-proxy
authentication:
  secondFactors:
    - sso
    - webauthn
  webauthn:
    attestationAllowedCas:
      - "/etc/ssl/certs/ca-certificates.crt"
    attestationDeniedCas:
      - "/etc/ssl/certs/ca-certificates.crt"
