clusterName: helm-lint.example.com
auth_server: teleport-auth.example.com
join_params:
  method: kubernetes
  token_name: teleport-proxy
extraContainers:
  - name: nscenter
    command:
      - /bin/bash
      - -c
      - sleep infinity & wait
    image: praqma/network-multitool
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
      runAsNonRoot: false
