clusterName: test-standalone-cluster
auth_server: teleport-auth.example.com
join_params:
  method: kubernetes
  token_name: teleport-proxy
chartMode: standalone
imagePullSecrets:
- name: myRegistryKeySecretName
