clusterName: teleport.example.com
auth_server: teleport-auth.example.com
join_params:
  method: kubernetes
  token_name: teleport-proxy
publicAddr: ["my-teleport-ingress.example.com:443"]
ingress:
  enabled: true
  suppressAutomaticWildcards: true
proxyListenerMode: multiplex
service:
  type: ClusterIP
