clusterName: test-log-cluster
auth_server: teleport-auth.example.com
join_params:
  method: kubernetes
  token_name: teleport-proxy
log:
  format: json
  level: DEBUG
  output: /var/lib/teleport/test.log
  extraFields: ["level", "timestamp", "component", "caller"]
