clusterName: helm-lint
auth_server: teleport-auth.example.com
join_params:
  method: kubernetes
  token_name: teleport-proxy
podSecurityContext:
  fsGroup: 99
  fsGroupChangePolicy: OnRootMismatch
  runAsGroup: 99
  runAsNonRoot: true
  runAsUser: 99
