clusterName: test-standalone-cluster
auth_server: teleport-auth.example.com
join_params:
  method: kubernetes
  token_name: teleport-proxy
chartMode: standalone
persistence:
  enabled: true
  existingClaimName: teleport-storage
acme: true
acmeEmail: test@email.com
labels:
  env: standalone
