export const TRYING_TO_SAVE_AUTH_PROVIDER = 'TRYING_TO_SAVE_AUTH_PROVIDER';
export const TRYING_TO_SAVE_CLUSTER = 'TRYING_TO_SAVE_CLUSTER';
export const TRYING_TO_SAVE_ROLE = 'TRYING_TO_SAVE_ROLE';
export const TRYING_TO_DELETE_RESOURCE = 'TRYING_TO_DELETE_RESOURCE';
