apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headlamp.fullname" . }}-kubeconfig
  namespace: {{ include "headlamp.namespace" . }}
  labels:
    {{- include "headlamp.labels" . | nindent 4 }}
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        server: http://127.0.0.1:6443
      name: main
    users:
    - name: default
      user: {}
    contexts:
    - context:
        cluster: main
        user: default
      name: main
    current-context: main
