{{- if .Values.headlamp.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-headlamp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
