{{- if .Values.headlamp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-headlamp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: headlamp
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: headlamp
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-headlamp
      automountServiceAccountToken: true
      containers:
        - name: headlamp
          image: "{{ .Values.headlamp.image.registry }}/{{ .Values.headlamp.image.repository }}:{{ .Values.headlamp.image.tag }}"
          imagePullPolicy: {{ .Values.headlamp.image.pullPolicy }}
          args:
            - "-kubeconfig=/etc/headlamp-proxy/kubeconfig"
            - "-plugins-dir=/headlamp/plugins"
            - "-port=4467"
          ports:
            - name: headlamp
              containerPort: 4467
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: headlamp
          readinessProbe:
            httpGet:
              path: /
              port: headlamp
          securityContext:
            runAsNonRoot: true
            privileged: false
            runAsUser: 100
            runAsGroup: 101
          volumeMounts:
            - name: kubeconfig
              mountPath: /etc/headlamp-proxy
              readOnly: true
        - name: auth-proxy
          image: "{{ .Values.headlamp.authProxy.image.registry }}/{{ .Values.headlamp.authProxy.image.repository }}:{{ .Values.headlamp.authProxy.image.tag }}"
          imagePullPolicy: {{ .Values.headlamp.authProxy.image.pullPolicy }}
          args:
            - "--headlamp-addr=127.0.0.1:4467"
            - "--listen-http=:4466"
            - "--listen-k8s=127.0.0.1:6443"
            {{- with .Values.headlamp.authProxy.groupsClaim }}
            - "--groups-claim={{ . }}"
            {{- end }}
          ports:
            - name: http
              containerPort: 4466
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
      volumes:
        - name: kubeconfig
          configMap:
            name: {{ .Release.Name }}-headlamp-kubeconfig
{{- end }}
