{{- if .Values.headlamp.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-headlamp-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        server: http://127.0.0.1:6443
      name: main
    users:
    - name: default
      user: {}
    contexts:
    - context:
        cluster: main
        user: default
      name: main
    current-context: main
{{- end }}
