# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# This Vagrantfile is for quick making a multi-host environment
# to experiment & play with Teleport.
#
#   1. Creates several identical VMs
#   2. Based on Debian Jessie 8
#   3. With private networking
#   4. With Docker installed
#
require "../base.rb"

Vagrant.configure(2) do |config|
  config.vm.box = "http://s3.gravitational.io/vms/libvirt-debian.box"
  config.vm.box_check_update = false

  basic_config(config.vm)
  configure_ssh(config.vm)
  #apt_update(config.vm)
  install_docker(config.vm, DOCKER_VER)
  install_teleport(config.vm)
  configure_teleport(config.vm)

  config.vm.synced_folder "../../", "/home/vagrant/teleport", type: "9p", disabled: false, accessmode: "mapped"

  NODES.each do |role, array|
      addr = array[0]
      config.vm.define role do |config|
          config.vm.hostname = role
          config.vm.network "private_network", ip: addr
          config.vm.provider "libvirt" do |vb|
              vb.driver = "kvm"
              vb.cpus = 1
              vb.memory = 512
          end
          config.vm.synced_folder "../data/opt/#{role}", "/opt/teleport", type: "9p", disabled: false, accessmode: "mapped"
          config.vm.synced_folder "../data/var/#{role}", "/var/lib/teleport", type: "rsync", disabled: false
      end
  end 
end


def install_teleport(vm)
    vm.provision "shell", inline: <<-SHELL
        ln -s /home/vagrant/teleport/build/teleport /usr/local/bin/teleport
        ln -s /home/vagrant/teleport/build/tsh /usr/local/bin/tsh
        ln -s /home/vagrant/teleport/build/tctl /usr/local/bin/ctl
    SHELL
end
