export const UPSERT_ROLES = 'SETTINGS_ROLES_UPSERT';
export const RECEIVE_ROLES = 'SETTINGS_ROLES_RECEIVE';
export const SET_TO_DELETE = 'SETTINGS_ROLES_SET_TO_DELETE';
export const SET_CURRENT = 'SETTINGS_ROLES_SET_CURRENT';
