export const UPSERT_ROLES = 'SETTINGS_ROLES_UPSERT';
export const RECEIVE_ROLES = 'SETTINGS_ROLES_RECEIVE';
export const SET_CURRENT = 'SETTINGS_ROLES_SET_CURRENT';
export const DELETE_ROLE = 'SETTINGS_ROLES_DELETE';
