import {
  AccessListMember,
  AccessListMemberKind,
  AccessListType,
  IneligibleStatus,
} from 'e-teleport/services/accessmanagement';
import { getIneligibleReason } from 'e-teleport/services/accessmanagement/accessmanagement';

import { AccessListWithModifiedGrants } from '../AccessLists';

export const mockAccessLists: AccessListWithModifiedGrants[] = [
  {
    id: '1',
    title: 'All Employees',
    description: 'Adding new hires!',
    grants: { roles: ['core-apps'], traitList: [], traits: {} },
    ownerGrants: {
      traits: {},
      traitList: [],
      roles: ['admin', 'root'],
    },
    membersCount: 273,
    audit: {} as any,
    ownershipRequires: {} as any,
    type: AccessListType.Okta,
    owners: [],
    needsReviewBy: null,
    inheritedMemberGrants: { roles: [], traits: {} },
  },
  {
    id: '2',
    title: 'Design',
    description: 'Allocating PostHog so Design Team...',
    grants: {
      traits: {},
      traitList: [],
      roles: ['auditor', 'editor', 'reviewer'],
    },
    ownerGrants: {
      traits: {},
      traitList: [],
      roles: [],
    },
    membersCount: 8,
    audit: {} as any,
    ownershipRequires: {} as any,
    owners: [],
    needsReviewBy: null,
    inheritedMemberGrants: { roles: [], traits: {} },
  },
  {
    id: '3',
    title: 'Engineering',
    description: 'Adding new engineers to eng team res...',
    grants: {
      traits: {},
      traitList: [],
      roles: ['auditor', 'editor', 'reviewer'],
    },
    ownerGrants: {
      traits: {},
      traitList: [],
      roles: [],
    },
    membersCount: 186,
    audit: {} as any,
    ownershipRequires: {} as any,
    owners: [],
    needsReviewBy: null,
    inheritedMemberGrants: { roles: [], traits: {} },
  },
  {
    id: '4',
    title: 'Finance',
    description: 'Removed deprecated procurement platform...',
    grants: {
      traits: {},
      traitList: [],
      roles: ['auditor', 'editor', 'reviewer'],
    },
    ownerGrants: {
      traits: {},
      traitList: [],
      roles: [],
    },
    membersCount: 6,
    audit: {} as any,
    ownershipRequires: {} as any,
    owners: [],
    needsReviewBy: null,
    inheritedMemberGrants: { roles: [], traits: {} },
  },
  {
    id: '5',
    title: 'HR',
    type: AccessListType.AwsIdentityCenter,
    description: 'All things human resource...',
    grants: {
      traits: {},
      traitList: [],
      roles: ['auditor', 'editor', 'reviewer'],
    },
    ownerGrants: {
      traits: {},
      traitList: [],
      roles: [],
    },
    membersCount: 6,
    audit: {} as any,
    ownershipRequires: {} as any,
    owners: [],
    needsReviewBy: null,
    inheritedMemberGrants: { roles: [], traits: {} },
  },
  {
    id: '6',
    title: 'Marketing',
    description: 'All things marketing...',
    grants: {
      traits: {},
      traitList: [],
      roles: ['auditor', 'editor', 'reviewer'],
    },
    ownerGrants: {
      traits: {},
      traitList: [],
      roles: [],
    },
    membersCount: 4,
    audit: {} as any,
    ownershipRequires: {} as any,
    owners: [],
    needsReviewBy: null,
    inheritedMemberGrants: { roles: [], traits: {} },
  },
];

export const mockMembers: AccessListMember[] = [
  {
    name: 'barkley@example.com',
    joined: new Date('September 09, 2023'),
    expires: new Date('October 02, 2023'),
    addedBy: 'admin',
    ineligibleReason: '',
    membershipKind: AccessListMemberKind.User,
  },
  {
    name: 'bob@example.com',
    joined: new Date('May 12, 2023'),
    expires: new Date('November 12, 2023'),
    addedBy: 'admin',
    ineligibleReason: '',
    membershipKind: AccessListMemberKind.User,
  },
  {
    name: 'betty.lou@example.com',
    joined: new Date('May 12, 2023'),
    expires: new Date('November 12, 2023'),
    addedBy: 'admin',
    ineligibleReason: '',
    membershipKind: AccessListMemberKind.User,
  },
  {
    name: 'ernie@example.com',
    joined: new Date('May 12, 2023'),
    expires: new Date('November 12, 2023'),
    addedBy: 'admin',
    ineligibleReason: getIneligibleReason(IneligibleStatus.MissingRequirements),
    membershipKind: AccessListMemberKind.User,
  },
  {
    name: 'jane@example.com',
    joined: new Date('May 12, 2023'),
    expires: new Date('November 12, 2023'),
    addedBy: 'admin',
    ineligibleReason: '',
    membershipKind: AccessListMemberKind.User,
  },
  {
    name: 'sherlock@example.com',
    joined: new Date('May 12, 2023'),
    expires: new Date('November 12, 2023'),
    addedBy: 'admin',
    ineligibleReason: getIneligibleReason(IneligibleStatus.UserNotExist),
    membershipKind: AccessListMemberKind.User,
  },
];
