#!/bin/bash

curl https://goteleport.com/static/install.sh | bash -s ${teleport_version} ${teleport_edition}

# Edit the configuration below to enable any services you plan to run on your
# Teleport agent nodes. We recommend running the SSH Service at a minimum to
# enable secure access to the nodes.
echo ${token} > /var/lib/teleport/token
cat<<EOF >/etc/teleport.yaml
version: v3
teleport:
  auth_token: /var/lib/teleport/token
  proxy_server: ${proxy_service_address}
app_service:
  enabled: false
  resources:
  - labels:
      "*": "*"
auth_service:
  enabled: false
db_service:
  enabled: false
  resources:
  - labels:
      "*": "*"
discovery_service:
  enabled: false
kubernetes_service:
  enabled: false
  resources:
  - labels:
      "*": "*"
proxy_service:
  enabled: false
ssh_service:
  enabled: true
  labels:
    role: agent-pool
EOF

systemctl restart teleport;

# Disable OpenSSH and any longstanding authorized keys.
systemctl disable --now ssh.service
find / -wholename "*/.ssh/authorized_keys" -delete

