FROM node:16.18.1-slim
RUN apt update && apt install -y git g++ make python3 tree

WORKDIR webapp

COPY yarn.lock package.json .
COPY web/ web/
# optionally copy in e if exists
COPY README.md e/we[b]/ e/web/

RUN yarn install

ARG NPM_CMD=nop
RUN yarn $NPM_CMD