# #############################################################################
# This Dockerfile aims to be the single source of truth for linux buildboxes on
# all supported architectures.
## #############################################################################

ARG BUILDBOX_VERSION
ARG BUILDBOX_PREFIX

FROM centos:7 AS base

# Automatically supplied by the Docker buildkit
ARG TARGETARCH

# Aliases
FROM $BUILDBOX_PREFIX/buildbox-multiarch-clang12:$BUILDBOX_VERSION-$TARGETARCH AS clang12

# Root target with ci user
FROM $BUILDBOX_PREFIX/buildbox-multiarch-base:$BUILDBOX_VERSION-$TARGETARCH AS gcc

ARG UID
ARG GID

RUN groupadd ci --gid=$GID -o && \
    useradd ci --uid=$UID --gid=$GID --create-home --shell=/bin/sh

RUN install --directory --mode=0700 --owner=ci --group=ci /var/lib/teleport

## LIBPCSCLITE ################################################################
#
FROM gcc AS libpcsclite
ARG LIBPCSCLITE_VERSION

# Configure fails to determine correct std on ARM
ENV CFLAGS="-std=gnu99"

# Install libpcsclite - compile with a newer GCC. The one installed by default is not able to compile it.
RUN git clone --depth=1 https://github.com/gravitational/PCSC.git -b ${LIBPCSCLITE_VERSION} && \
    cd PCSC && \
    ./bootstrap && \
    ./configure --enable-static --with-pic --disable-libsystemd && \
    make install && \
    rm -rf PCSC

## LIBFIDO2 ###################################################################
#

# Build libfido2 separately for isolation, speed and flexibility.
FROM gcc AS libfido2

# Install libudev-zero.
# libudev-zero replaces systemd's libudev.
RUN git clone --depth=1 https://github.com/illiliti/libudev-zero.git -b 1.0.3 && \
    cd libudev-zero && \
    [ "$(git rev-parse HEAD)" = 'ee32ac5f6494047b9ece26e7a5920650cdf46655' ] && \
    make install-static LIBDIR='$(PREFIX)/lib64'

# Install libcbor.
RUN git clone --depth=1 https://github.com/PJK/libcbor.git -b v0.10.2 && \
    cd libcbor && \
    [ "$(git rev-parse HEAD)" = 'efa6c0886bae46bdaef9b679f61f4b9d8bc296ae' ] && \
    cmake3 \
        -DCMAKE_CXX_FLAGS=-lpthread \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
        -DWITH_EXAMPLES=OFF . && \
    make && \
    make install

# Install openssl.
# install_sw install only binaries, skips docs.
RUN git clone --depth=1 https://github.com/openssl/openssl.git -b openssl-3.0.11 && \
    cd openssl && \
    [ "$(git rev-parse HEAD)" = '6ba3884c3235e1bb474b379026087f8216afacf4' ] && \
    ./config --release --libdir=/usr/local/lib64 && \
    make -j"$(nproc)" && \
    make install_sw
# Necessary for libfido2 to find the correct libcrypto.
ENV PKG_CONFIG_PATH="/usr/local/lib64/pkgconfig"

# Install libfido2.
# Depends on libcbor, libcrypto (OpenSSL 3.x), libudev and zlib1g-dev.
RUN git clone --depth=1 https://github.com/Yubico/libfido2.git -b 1.13.0 && \
    cd libfido2 && \
    [ "$(git rev-parse HEAD)" = '486a8f8667e42f55cee2bba301b41433cacec830' ] && \
    CFLAGS="-lpthread" cmake3 \
        -DBUILD_EXAMPLES=OFF \
        -DBUILD_MANPAGES=OFF \
        -DBUILD_TOOLS=OFF \
        -DCMAKE_BUILD_TYPE=Release . && \
    grep 'CRYPTO_VERSION:INTERNAL=3\.0\.' CMakeCache.txt && \
    make && \
    make install && \
    make clean

## LIBBPF ########################################################################
#
FROM gcc AS libbpf

# Install libbpf - compile with a newer GCC. The one installed by default is not able to compile it.
# BUILD_STATIC_ONLY disables libbpf.so build as we don't need it.
ARG LIBBPF_VERSION
RUN mkdir -p /opt && cd /opt && \
    curl -L https://github.com/libbpf/libbpf/archive/refs/tags/v${LIBBPF_VERSION}.tar.gz | tar xz && \
    cd /opt/libbpf-${LIBBPF_VERSION}/src && \
    make && BUILD_STATIC_ONLY=y DESTDIR=/opt/libbpf make install

## Integral image for 64-bit targets #############################################
#
FROM gcc AS deps-64

# Make clang12 available
COPY --from=clang12 /opt/llvm /opt/llvm
ENV PATH="/opt/llvm/bin:$PATH"

ARG RUST_VERSION

## Install Rust ###############################################################
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH \
    RUST_VERSION=$RUST_VERSION

RUN mkdir -p $RUSTUP_HOME && chmod a+w $RUSTUP_HOME && \
    mkdir -p $CARGO_HOME/registry && chmod -R a+w $CARGO_HOME

USER ci
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain ${RUST_VERSION} --default-host ${RUST_ARCH} && \
    rustup --version && \
    cargo --version && \
    rustc --version && \
    rustup target add ${RUST_ARCH}

ARG WASM_PACK_VERSION
# Install wasm-pack for targeting WebAssembly from Rust.
RUN cargo install wasm-pack --version ${WASM_PACK_VERSION}

USER root

# Copy libfido2 libraries.
# Do this near the end to take better advantage of the multi-stage build.
COPY --from=libfido2 /usr/local/include/ /usr/local/include/
COPY --from=libfido2 /usr/local/lib64/engines-3/ /usr/local/lib64/engines-3/
COPY --from=libfido2 /usr/local/lib64/ossl-modules/ /usr/local/lib64/ossl-modules/
COPY --from=libfido2 /usr/local/lib64/pkgconfig/ /usr/local/lib64/pkgconfig/
COPY --from=libfido2 \
    /usr/local/lib64/libcbor.a \
    /usr/local/lib64/libcrypto.a \
    /usr/local/lib64/libcrypto.so.3 \
    /usr/local/lib64/libfido2.a \
    /usr/local/lib64/libfido2.so.1.13.0 \
    /usr/local/lib64/libssl.a \
    /usr/local/lib64/libssl.so.3 \
    /usr/local/lib64/libudev.a \
    /usr/local/lib64/
# Re-create usual lib64 links.
RUN cd /usr/local/lib64 && \
    ln -s libcrypto.so.3 libcrypto.so && \
    ln -s libfido2.so.1.13.0 libfido2.so.1 && \
    ln -s libfido2.so.1 libfido2.so && \
    ln -s libssl.so.3 libssl.so && \
# Update ld.
    echo /usr/local/lib64 > /etc/ld.so.conf.d/libfido2.conf && \
    ldconfig
# Configure pkg-config.
COPY pkgconfig/centos7/ /
ENV PKG_CONFIG_PATH="/usr/local/lib64/pkgconfig"

COPY --from=libpcsclite /usr/local/include/ /usr/local/include/
COPY --from=libpcsclite /usr/local/lib/pkgconfig/ /usr/local/lib64/pkgconfig/
COPY --from=libpcsclite \
    /usr/local/lib/libpcsclite.a \
    /usr/local/lib/

ARG LIBBPF_VERSION
COPY --from=libbpf /opt/libbpf/usr /usr/libbpf-${LIBBPF_VERSION}

## Intermediate targets ########################################################
#
FROM gcc AS deps-arm

ENV GOARCH=arm
ENV GOARM=7

FROM gcc AS deps-386

FROM deps-64 AS deps-arm64
FROM deps-64 AS deps-amd64

ENV GOEXPERIMENT=boringcrypto

# Install node.
# Node is required to build teleterm. It does not work on 32-bit archs, and is not required for them.
RUN yum install -y python3
ARG NODE_ARCH=x64
ARG NODE_VERSION
ENV NODE_URL="https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-${NODE_ARCH}.tar.xz"
ENV NODE_PATH="/usr/local/lib/nodejs-linux"
ENV PATH="$PATH:${NODE_PATH}/bin"
RUN mkdir -p ${NODE_PATH} && \
     curl -o /tmp/nodejs.tar.xz -Lf ${NODE_URL} && \
     tar -xJf /tmp/nodejs.tar.xz -C /usr/local/lib/nodejs-linux --strip-components=1

RUN node --version
RUN corepack enable yarn

## Final target image with go #################################################
#
FROM deps-$TARGETARCH

# NOTE: We expect the GOLANG_VERSION to contain the leading `go` in the version
#       string (e,g, go1.19), as produced by `go version`
ARG GOLANG_VERSION

## Install Go #################################################################
RUN mkdir -p /opt && \
    mkdir -p /go  && \
    curl https://storage.googleapis.com/golang/$GOLANG_VERSION.linux-$GOLANG_ARCH.tar.gz | tar xz -C /opt && \
    chmod a+w /go && \
    chmod a+w /var/lib && \
    /opt/go/bin/go version
ENV GOPATH="/go" \
    GOROOT="/opt/go" \
    PATH="$PATH:/opt/go/bin:/go/bin"

# Install PAM module and policies for testing.
COPY pam/ /opt/pam_teleport/
RUN make -C /opt/pam_teleport install

RUN chmod a-w /

USER ci
