# This Dockerfile creates build assets needed for CentOS 6 builds.
#
# Go 1.17 does not build programs that use CGO (like Teleport) with the
# version of gcc (4.4.7) and ld (2.20) that CentOS 6 ships with.
#
# When you attempt to compile Teleport, you will run into the below error.
#
#  cc1: error: unrecognized command line option "-fno-lto"
#
# Upgrading to gcc 4.8.5 will resolve that issue. However, Teleport still will
# not compile, you will run into the below error.
#
#  unrecognized relocation (0x2a) in section .text
#
# Which requires you to upgrade to ld 2.26.
#
# Because gcc can take hours to compile, this script is used to build and
# package the needed versions of gcc and binutils so speed up Teleport builds.
FROM centos:6

ENV LANGUAGE=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    LC_CTYPE=en_US.UTF-8

# Replace regular CentOS 6 mirror list with vault.centos.org, as CentOS 6 is EOL
# and regular mirrors aren't hosted any more.
RUN sed -i 's%^mirrorlist%#mirrorlist%g' /etc/yum.repos.d/* && \
    sed -i 's%#baseurl=http://mirror.centos.org%baseurl=http://vault.centos.org%g' /etc/yum.repos.d/* && \
    yum makecache fast && \
    yum -y install gcc gcc-c++ glibc-devel glibc-devel.i686 net-tools tree git zip wget && \
    yum clean all

# Download, build, and install gcc.
RUN mkdir -p /opt && cd /opt && curl -L https://ftp.gnu.org/gnu/gcc/gcc-4.8.5/gcc-4.8.5.tar.gz | tar -xz && \
    cd gcc-4.8.5 && \
    ./contrib/download_prerequisites && \
    ./configure --prefix=/opt --enable-languages=c,c++ && \
    make && \
    make install && \
    rm -fr ../gcc-4.8.5

# Download, build, and install binuils.
RUN mkdir -p /opt && cd /opt && curl -L https://ftp.gnu.org/gnu/binutils/binutils-2.26.tar.gz | tar -xz && \
    cd binutils-2.26 && \
    ./configure --prefix=/opt && \
    make && \
    make install && \
    rm -fr ../binutils-2.26

# Create the archive and copy it to the host.
RUN tar -czvf centos6-assets.tar.gz /opt
