# syntax=docker/dockerfile:1

# This image builds clang from source. clang12 is required to build boringssl, clang10+ is required for BPF.
ARG BUILDBOX_VERSION
ARG BUILDBOX_PREFIX

FROM centos:7 AS base

# Automatically supplied by the Docker buildkit
ARG TARGETARCH

## GCC built from sources #####################################################
FROM $BUILDBOX_PREFIX/buildbox-multiarch-base:$BUILDBOX_VERSION-$TARGETARCH

ARG CLANG_VERSION

RUN git clone --branch llvmorg-${CLANG_VERSION} --depth=1 https://github.com/llvm/llvm-project.git && \
    cd llvm-project/ && \
    mkdir build && cd build/ && \
    cmake3 \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/opt/llvm \
        -DLLVM_ENABLE_PROJECTS=clang \
        -DLLVM_BUILD_TOOLS=ON \
        -G "Unix Makefiles" ../llvm && \
    make -j$(grep -c processor /proc/cpuinfo) install-llvm-strip install-clang-format install-clang && \
    cd ../.. && \
    rm -rf llvm-project

ENV PATH="/opt/llvm/bin:$PATH"
