#!/bin/sh

#
# the directory where Teleport binaries will be located
#
BINDIR=/usr/local/bin

#
# the directory where Teleport will keep its state/data
#
VARDIR=/var/lib/teleport

[ ! $(id -u) != "0" ] || { echo "ERROR: You must be root"; exit 1; }
cd $(dirname $0)
mkdir -p $VARDIR $BINDIR
cp -f teleport tctl tsh $BINDIR/ || exit 1

#
# What operating system is the user running?
#
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=linux;;
    Darwin*)    machine=darwin;;
    CYGWIN*)    machine=cygwin;;
    MINGW*)     machine=minGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

#
# What Teleport Version?
# Sets version edition + version number e.g. Enterprisev5.1.0
#
teleportVersion="$(teleport version)"
set -- $teleportVersion; version=$2$3

echo "Teleport binaries have been copied to $BINDIR"
echo ""
echo "Thanks for installing Teleport. Is it OK if we collect some metrics about your install?"
echo ""
echo "If you don't mind please run:"
echo "# Update email if you would like to receive link to get swag"
echo "$ curl -X POST https://9sjnq1g1j9.execute-api.us-west-2.amazonaws.com/Prod/usage -F OS=${machine} -F version=${version} -F email=alice@example.com"
echo ""
echo "Otherwise, ignore!"
