{{- /*
If validateConfigOnDeploy is true, a hook is used to validate the config. The
hook job creates a pod with the same volumes at the final Proxy pod. Because we
append the bound keypair registration secret as a projected volume to that pod,
we must create the secret during install so it's available for the validation
pod before the chart's permanent manifests exist.

This hook is pre-install only. On upgrades, the permanent Secret from the
previous release already exists and can be mounted by the pre-upgrade
validation Job.
*/ -}}
{{- $proxy := mustDeepCopy . -}}
{{- $_ := set $proxy "Values" (mustMergeOverwrite (mustDeepCopy .Values) .Values.proxy) -}}
{{- if and $proxy.Values.validateConfigOnDeploy (include "teleport-proxy.uses-bound-keypair-registration-secret" $proxy) -}}
{{- $_ := set $proxy.Values "annotations" (default (dict) $proxy.Values.annotations) -}}
{{- $_ := set $proxy.Values.annotations "secret" (default (dict) $proxy.Values.annotations.secret) -}}
{{- $_ := set $proxy.Values.annotations.secret "helm.sh/hook" "pre-install" -}}
{{- $_ := set $proxy.Values.annotations.secret "helm.sh/hook-weight" "2" -}}
{{- $_ := set $proxy.Values.annotations.secret "helm.sh/hook-delete-policy" "before-hook-creation,hook-succeeded" -}}
{{- include "teleport-proxy.bound-keypair-registration-secret" $proxy -}}
{{- end -}}
