{{- /*
If validateConfigOnDeploy is true, a hook is used to validate the config. The
hook job creates a pod with the same volumes at the final Proxy pod. Because we
append the token secret as a projected volume to that pod, we must create the
secret during the same hook phases so it's available for the validation pod.
This means the secret gets created and deleted for the hook and then recreated
as part the chart's permanent manifests.
*/ -}}
{{- if or .Values.validateConfigOnDeploy -}}
{{- $ctx := mustDeepCopy . -}}
{{- $_ := set $ctx.Values.annotations.joinTokenSecret "helm.sh/hook" "pre-install,pre-upgrade" -}}
{{- $_ := set $ctx.Values.annotations.joinTokenSecret "helm.sh/hook-weight" "0" -}}
{{- $_ := set $ctx.Values.annotations.joinTokenSecret "helm.sh/hook-delete-policy" "before-hook-creation,hook-succeeded" -}}
{{- include "teleport-proxy.join-token-secret" $ctx -}}
{{- end -}}