{{- if and .Values.joinTokenSecret.create (eq .Values.join_params.method "token") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.joinTokenSecret.name }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.extraLabels.joinTokenSecretSecret }}
  labels:
  {{- toYaml .Values.extraLabels.joinTokenSecret | nindent 4 }}
{{- end }}
{{- if .Values.annotations.joinTokenSecret}}
  annotations:
  {{- toYaml .Values.annotations.joinTokenSecret | nindent 4 }}
{{- end }}
type: Opaque
stringData:
  auth-token: |
    {{ .Values.join_params.token_name }}
{{- end -}}