{{- $proxy := mustDeepCopy . -}}

{{/* Merge .Values.proxy into .Values because teleport-proxy-lib templates
     read everything from .Values.* (see examples/chart/lib/README.md) */}}
{{- $_ := set $proxy "Values" (mustMergeOverwrite (mustDeepCopy .Values) .Values.proxy) -}}

{{/* TODO:(adamcarheden): The lib chart shouldn't take auth service or token. The caller should specify it in the teleportConfig. */}}
{{- $_ := set $proxy.Values "teleportAuthService" (include "teleport-proxy.auth_server" $proxy) -}}

{{- include "teleport-proxy.validate" $proxy -}}
{{- $_ := set $proxy.Values "teleportConfig" (include "teleport-proxy.teleportConfig" $proxy | fromYaml) -}}
{{- $_ := set $proxy.Values.serviceAccount "name" (include "teleport-proxy.serviceAccountName" $proxy) -}}
{{- $_ := set $proxy.Values "forceHAReplicas" (not (empty (get (default (dict) .Values.proxy.highAvailability) "replicaCount"))) -}}
{{- if eq $proxy.Values.join_params.method "kubernetes" -}}
{{- $_ := set $proxy.Values "serviceAccountTokenAudience" $proxy.Values.clusterName -}}
{{- $_ := set $proxy.Values "serviceAccountTokenExpirationSeconds" 600 -}}
{{- end -}}
{{- $_ := set $proxy.Values "extraVolumes" (include "teleport-proxy.extraVolumes" $proxy | fromYamlArray) -}}
{{- $_ := set $proxy.Values "extraVolumeMounts" (include "teleport-proxy.extraVolumeMounts" $proxy | fromYamlArray) -}}

{{/* Render all proxy charts */}}
{{- include "teleport-proxy-lib.all" $proxy -}}
