{{/* We explicitly validate top-level values only, not the merged $proxy nor the
generated/overridden teleportConfig. This allows users to inject otherwise
disallowed values, but forces them to acknowledge that they're unsupported by
putting something in the top-level fields we do validate.
*/}}
{{- include "teleport-proxy.validate" . -}}
{{- $proxy := mustDeepCopy . -}}

{{/* TODO:(adamcarheden): The lib chart shouldn't take auth service or token. The caller should specify it in the teleportConfig. */}}
{{- $_ := set $proxy.Values "teleportAuthService" (include "teleport-proxy.authServer" $proxy) -}}
{{- if eq $proxy.Values.serviceAccountTokenExpirationSeconds nil -}}
{{- $_ := unset $proxy.Values "serviceAccountTokenExpirationSeconds" -}}
{{- end -}}

{{- $_ := set $proxy.Values "teleportConfig" (include "teleport-proxy.teleportConfig" $proxy | fromYaml) -}}
{{- $_ := set $proxy.Values.serviceAccount "name" (include "teleport-proxy.serviceAccountName" $proxy) -}}
{{- $_ := set $proxy.Values "forceHAReplicas" true -}}{{/* This feature is to support legacy behavior in teleport-cluster. For teleport-proxy we always set replicas*/}}
{{- if eq (coalesce (dig "teleportConfig" "teleport" "join_params" "method" "" $proxy.Values.AsMap) (dig "joinParams" "method" "" $proxy.Values.AsMap)) "kubernetes" -}}
{{- $_ := set $proxy.Values "serviceAccountTokenAudience" (coalesce $proxy.Values.serviceAccountTokenAudience $proxy.Values.clusterName) -}}
{{- $_ := set $proxy.Values "serviceAccountTokenExpirationSeconds" (coalesce $proxy.Values.serviceAccountTokenExpirationSeconds 600) -}}
{{- end -}}

{{/* Render all proxy charts */}}
{{- include "teleport-proxy-lib.all" $proxy -}}
