teleportAddress: "example.teleport.sh:443"
token: "my-operator-bot"
teleportClusterName: "example.teleport.sh"
updater:
  enabled: true
  pullCredentials: docker
  extraEnv:
    - name: DOCKER_CONFIG
      value: /mnt/docker/
  extraVolumes:
    - name: docker-config
      projected:
        sources:
          - secret:
              name: my-pull-secret
              items:
                - key: .dockerconfigjson
                  path: config.json
  extraVolumeMounts:
    - name: docker-config
      mountPath: "/mnt/docker"
      readOnly: true
