/* eslint-disable */
// @generated by protobuf-ts 2.9.3 with parameter long_type_number,eslint_disable,add_pb_suffix,client_grpc1,server_grpc1,ts_nocheck
// @generated from protobuf file "ptyHostService.proto" (syntax proto3)
// tslint:disable
// @ts-nocheck
//
//
// Teleport
// Copyright (C) 2023  Gravitational, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//
// TODO(ravicious): Before introducing any changes, move this file to the /proto dir and
// remove the generate-grpc-shared script.
//
import { PtyHost } from "./ptyHostService_pb";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { PtyCwd } from "./ptyHostService_pb";
import type { PtyServerEvent } from "./ptyHostService_pb";
import type { PtyClientEvent } from "./ptyHostService_pb";
import type { PtyId } from "./ptyHostService_pb";
import type { PtyCreate } from "./ptyHostService_pb";
import * as grpc from "@grpc/grpc-js";
/**
 * @generated from protobuf service PtyHost
 */
export interface IPtyHostClient {
    /**
     * @generated from protobuf rpc: CreatePtyProcess(PtyCreate) returns (PtyId);
     */
    createPtyProcess(input: PtyCreate, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: PtyId) => void): grpc.ClientUnaryCall;
    createPtyProcess(input: PtyCreate, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: PtyId) => void): grpc.ClientUnaryCall;
    createPtyProcess(input: PtyCreate, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: PtyId) => void): grpc.ClientUnaryCall;
    createPtyProcess(input: PtyCreate, callback: (err: grpc.ServiceError | null, value?: PtyId) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: ExchangeEvents(stream PtyClientEvent) returns (stream PtyServerEvent);
     */
    exchangeEvents(metadata: grpc.Metadata, options?: grpc.CallOptions): grpc.ClientDuplexStream<PtyClientEvent, PtyServerEvent>;
    exchangeEvents(options?: grpc.CallOptions): grpc.ClientDuplexStream<PtyClientEvent, PtyServerEvent>;
    /**
     * @generated from protobuf rpc: GetCwd(PtyId) returns (PtyCwd);
     */
    getCwd(input: PtyId, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: PtyCwd) => void): grpc.ClientUnaryCall;
    getCwd(input: PtyId, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: PtyCwd) => void): grpc.ClientUnaryCall;
    getCwd(input: PtyId, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: PtyCwd) => void): grpc.ClientUnaryCall;
    getCwd(input: PtyId, callback: (err: grpc.ServiceError | null, value?: PtyCwd) => void): grpc.ClientUnaryCall;
}
/**
 * @generated from protobuf service PtyHost
 */
export class PtyHostClient extends grpc.Client implements IPtyHostClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * @generated from protobuf rpc: CreatePtyProcess(PtyCreate) returns (PtyId);
     */
    createPtyProcess(input: PtyCreate, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: PtyId) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: PtyId) => void), callback?: ((err: grpc.ServiceError | null, value?: PtyId) => void)): grpc.ClientUnaryCall {
        const method = PtyHost.methods[0];
        return this.makeUnaryRequest<PtyCreate, PtyId>(`/${PtyHost.typeName}/${method.name}`, (value: PtyCreate): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): PtyId => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: ExchangeEvents(stream PtyClientEvent) returns (stream PtyServerEvent);
     */
    exchangeEvents(metadata?: grpc.Metadata | grpc.CallOptions, options?: grpc.CallOptions): grpc.ClientDuplexStream<PtyClientEvent, PtyServerEvent> {
        const method = PtyHost.methods[1];
        return this.makeBidiStreamRequest<PtyClientEvent, PtyServerEvent>(`/${PtyHost.typeName}/${method.name}`, (value: PtyClientEvent): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): PtyServerEvent => method.O.fromBinary(value, this._binaryOptions), (metadata as any), options);
    }
    /**
     * @generated from protobuf rpc: GetCwd(PtyId) returns (PtyCwd);
     */
    getCwd(input: PtyId, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: PtyCwd) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: PtyCwd) => void), callback?: ((err: grpc.ServiceError | null, value?: PtyCwd) => void)): grpc.ClientUnaryCall {
        const method = PtyHost.methods[2];
        return this.makeUnaryRequest<PtyId, PtyCwd>(`/${PtyHost.typeName}/${method.name}`, (value: PtyId): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): PtyCwd => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
}
