apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: adamkpickering-loadtest-3
  region: us-west-2
  version: "1.35"
  tags:
    teleport.dev/creator: "adam.pickering@goteleport.com"

iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy

managedNodeGroups:
  - name: adamkpickering-loadtest-3-node-group
    instanceType: m5.4xlarge
    minSize: 3
    maxSize: 10
    tags:
      teleport.dev/creator: "adam.pickering@goteleport.com"
