// Code generated by resource-gen; DO NOT EDIT.

package auth

// Generated services gathering for resource-gen managed resources.
import (
	"github.com/gravitational/trace"

	"github.com/gravitational/teleport/lib/cache"
	"github.com/gravitational/teleport/lib/services"
	"github.com/gravitational/teleport/lib/services/local"
)
type servicesGenerated struct {
	services.Cookies
	services.Tags
	services.Webhooks
}

func newServicesGenerated(cfg *InitConfig) (*servicesGenerated, error) {
	var err error
	gen := &servicesGenerated{}

	gen.Cookies, err = local.NewCookieService(cfg.Backend)
	if err != nil {
		return nil, trace.Wrap(err)
	}

	gen.Tags, err = local.NewTagService(cfg.Backend)
	if err != nil {
		return nil, trace.Wrap(err)
	}

	gen.Webhooks, err = local.NewWebhookService(cfg.Backend)
	if err != nil {
		return nil, trace.Wrap(err)
	}

	return gen, nil
}
// ToCacheConfig builds a cache.GeneratedConfig from the service interfaces
// held in servicesGenerated. This eliminates the need for callers to manually
// construct GeneratedConfig literals when adding new cache-enabled resources.
func (sg *servicesGenerated) ToCacheConfig() cache.GeneratedConfig {
	return cache.GeneratedConfig{
		Cookies: sg.Cookies,
		Tags: sg.Tags,
		Webhooks: sg.Webhooks,
	}
}
