/*
 * Teleport
 * Copyright (C) 2023  Gravitational, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package common

import (
	"encoding/base64"
	"encoding/hex"
	"strings"

	"github.com/gravitational/trace"
)

// KubeLocalProxyPathPrefix returns the kubeconfig `server:` URL suffix that
// encodes the (teleport cluster, kube cluster) pair for URL-based routing.
// Format: /v1/teleport/<base64url(teleport)>/<base64url(kube)>. Mirrors the
// path consumed by the Teleport proxy's single-cert kube handler and the
// format emitted by tbot v2 (lib/tbot/services/k8s/output_v2.go).
func KubeLocalProxyPathPrefix(teleportCluster, kubeCluster string) string {
	return "/v1/teleport/" +
		base64.RawURLEncoding.EncodeToString([]byte(teleportCluster)) + "/" +
		base64.RawURLEncoding.EncodeToString([]byte(kubeCluster))
}

// ClustersFromKubeLocalProxyPath parses the leading
// /v1/teleport/<b64>/<b64> prefix of a request URL path and returns the
// decoded (teleport cluster, kube cluster) pair.
func ClustersFromKubeLocalProxyPath(path string) (teleportCluster, kubeCluster string, err error) {
	trimmed := strings.TrimPrefix(path, "/")
	parts := strings.SplitN(trimmed, "/", 5)
	if len(parts) < 4 || parts[0] != "v1" || parts[1] != "teleport" {
		return "", "", trace.BadParameter("invalid kube local proxy path %q", path)
	}
	tcBytes, err := base64.RawURLEncoding.DecodeString(parts[2])
	if err != nil {
		return "", "", trace.Wrap(err, "decoding teleport cluster name from path")
	}
	kcBytes, err := base64.RawURLEncoding.DecodeString(parts[3])
	if err != nil {
		return "", "", trace.Wrap(err, "decoding kube cluster name from path")
	}
	return string(tcBytes), string(kcBytes), nil
}

// ClustersFromLegacyKubeLocalProxySNI decodes the legacy local-proxy SNI shape
// <hex(kube-cluster)>.<teleport-cluster> emitted by tsh versions prior to URL-based routing.
//
// TODO(jakealti): DELETE IN v20.0.0.
// Kept so kubeconfigs generated by older tsh continue to work against the current local proxy during the deprecation window.
func ClustersFromLegacyKubeLocalProxySNI(serverName string) (teleportCluster, kubeCluster string, err error) {
	hexKube, teleportCluster, ok := strings.Cut(serverName, ".")
	if !ok || teleportCluster == "" {
		return "", "", trace.BadParameter("invalid legacy kube local proxy SNI %q", serverName)
	}
	kc, err := hex.DecodeString(hexKube)
	if err != nil {
		return "", "", trace.Wrap(err, "decoding legacy kube cluster name from SNI")
	}
	return teleportCluster, string(kc), nil
}
