export const UPDATE_CLUSTERS = 'SETTINGS_TRUSTED_CLRS_UPDATE';
export const RECEIVE_CLUSTERS = 'SETTINGS_TRUSTED_CLRS_RECEIVE';
export const SET_CURRENT = 'SETTINGS_TRUSTED_CLRS_SET_CURRENT';
export const DELETE_CLUSTER = 'SETTINGS_TRUSTED_CLRS_DELETE';
