export const UPDATE_CLUSTERS = 'SETTINGS_TRUSTED_CLUSTERS_UPDATE';
export const RECEIVE_CLUSTERS = 'SETTINGS_TRUSTED_CLUSTERS_RECEIVE';
export const SET_TO_DELETE = 'SETTINGS_TRUSTED_CLUSTERS_SET_TO_DELETE';
export const SET_CURRENT = 'SETTINGS_TRUSTED_CLUSTERS_SET_CURRENT';
