// Code generated by "make version". DO NOT EDIT.

package api

const Version = "17.7.23-rc.1"

const VersionMajor = 17
const VersionMinor = 7
const VersionPatch = 23
const VersionPreRelease = "rc.1"
const VersionMetadata = ""
