// Code generated by "make version". DO NOT EDIT.

package api

const Version = "18.9.2-helm-proxy-lib-backport.carheden.1"

const VersionMajor = 18
const VersionMinor = 9
const VersionPatch = 2
const VersionPreRelease = "helm-proxy-lib-backport.carheden.1"
const VersionMetadata = ""
