# This workflow is run whenever a pull request is opened, re-opened, or taken
# out of draft (ready for review).
#
# NOTE: pull_request_target behaves the same as pull_request except it grants a
# read/write token to workflows running on a pull request from a fork. While
# this may seem unsafe, the permissions for the token are limited below and
# the permissions can not be changed without merging to master which is
# protected by CODEOWNERS.
name: Assign
on:
  pull_request_target:
    types: [opened, ready_for_review]

# Limit the permissions on the GitHub token for this workflow to the subset
# that is required. In this case, the assign workflow only needs to be able
# to update the assigned reviewers, so it needs write access to
# "pull-requests", nothing else.
permissions:
    pull-requests: write
    actions: none
    checks: none
    contents: none
    deployments: none
    issues: none
    packages: none
    repository-projects: none
    security-events: none
    statuses: none
    id-token: write

jobs:
  auto-request-review:
    name: Auto Request Review
    if: ${{ !github.event.pull_request.draft && !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get runtime values from kvstore
        id: kvstore
        uses: gravitational/shared-workflows/tools/env-kvstore@tools/env-kvstore/v1.0.0
        with:
          cognito-identity-pool-id: "us-west-2:da53389e-a459-4a28-bd54-43eeb8e4b579"
          cognito-role-arn: "arn:aws:iam::247230412011:role/github-actions-cognito-oidc"
          values: |
            REVIEWERS,secret
      # Checkout main branch of shared-workflow repository.
      - name: Checkout shared-workflow
        uses: actions/checkout@v6
        with:
          repository: gravitational/shared-workflows
          path: .github/shared-workflows
          ref: 02af65890b521ecdf79856c00f6d2c875bf40ea3 # workflows/v0.0.5
      - name: Installing Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
        # Run "check" subcommand on bot.
      - name: Assigning reviewers
        run: cd .github/shared-workflows/bot && go run main.go -workflow=assign -token="${{ secrets.GITHUB_TOKEN }}" -reviewers="${{ env.REVIEWERS }}"
