name: E2E Tests
run-name: E2E Tests
on:
  pull_request:
  merge_group:
  push:
    branches:
      - master
      - branch/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.repo.full_name || github.repository }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    name: Check for relevant changes
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    outputs:
      changed: ${{ steps.changes.outputs.changed }}

    steps:
      - name: Checkout
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v6
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        with:
          base: ${{ github.event.pull_request.base.ref || github.event.merge_group.base_ref }}
          ref: ${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref }}
          filters: |
            changed:
              - '.github/workflows/e2e-tests.yaml'
              - '.github/workflows/e2e-tests-base.yaml'
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'
              - '**/*.rs'
              - 'rust-toolchain.toml'
              - 'Cargo.toml'
              - '**/Cargo.toml'
              - 'Cargo.lock'
              - 'e2e/**'
              - 'web/**'
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'pnpm-workspace.yaml'
              - '.pnpmfile.cjs'
              - '.npmrc'
              - 'tsconfig*.json'
              - 'gen/proto/ts/**'
              - '.github/actions/prepare-workspace/action.yml'
              - 'common.mk'
              - 'build.assets/Makefile'
              - 'build.assets/versions.mk'
              - 'build.assets/Dockerfile*'
              - 'build.assets/build-webassets-if-changed.sh'
              - 'build.assets/build-e2e-binaries.sh'
              - 'Makefile'

  e2e:
    needs: changes
    if: ${{ needs.changes.outputs.changed == 'true' && !startsWith(github.head_ref, 'dependabot/') }}
    uses: ./.github/workflows/e2e-tests-base.yaml
    with:
      build-dir: build
      e2e-dir: e2e
      build-logs-dir: build-logs
      type-check-package: '@gravitational/e2e'
      build-command: make e2e-binaries
    permissions:
      contents: read

  update-pr-comment:
    needs: e2e
    if: ${{ always() && needs.e2e.result != 'skipped' && github.event_name == 'pull_request' }}
    uses: ./.github/workflows/e2e-pr-comment.yaml
    permissions:
      pull-requests: write
