name: E2E Tests
run-name: E2E Tests
on:
  pull_request:
    paths:
      - '.github/workflows/e2e-tests.yaml'
      - '**.go'
      - 'e2e/**'
      - 'web/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  push:
    branches:
      - master
      - branch/**

jobs:
  build:
    name: Build Teleport
    runs-on: ubuntu-22.04-4core

    permissions:
      contents: read

    container:
      image: ghcr.io/gravitational/teleport-buildbox:teleport19

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Prepare workspace
        uses: ./.github/actions/prepare-workspace

      - name: Build Teleport
        run: make binaries

      - name: Upload teleport binary
        uses: actions/upload-artifact@v4
        with:
          name: teleport-binary
          path: build/teleport
          retention-days: 1

  test:
    name: E2E Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v6
        with:
          name: build
          path: ${{ github.workspace }}/build/

      - name: Chmod binaries
        run: |
          chmod +x build/teleport
          chmod +x build/tctl
          chmod +x build/tsh

      - name: Run Tests
        run: |
          pnpm e2e
