# Rebuilds all of the latest-release distroless images on a
# schedule in order to pick up any security fixes (etc.) in
# the base image.

name: Rebuild Distroless OCI Images
on:
  workflow_dispatch:
  schedule:
    # Run daily at 7.23 am UTC. 7am UTC is 0:00 PDT, and the 23-
    # minute offset is not important; just a random offset to
    # stagger jobs.
    # This is only run from the `master` branch. GitHub Actions
    # will not run scheduled/cron jobs from other branches. This
    # file appears on release branches due to how they are created
    # off master, but those scheduled/cron jobs do not run.
    - cron: "23 7 * * *"

env:
  # A space-delimited list of the major teleport versions for which
  # we want to rebuild the images. Make sure this value is kept
  # up-to-date as new major versions are released. See:
  #   https://github.com/gravitational/core/blob/master/docs/postrelease.md
  TELEPORT_MAJOR_VERSIONS: "v17 v18"

permissions:
  actions: write
  contents: read

jobs:
  trigger-builds:
    name: Rebuild Latest OCI releases
    runs-on: ubuntu-latest
    steps:
      - name: Select Teleport releases
        id: select
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          versions=""
          for major_version in ${{ env.TELEPORT_MAJOR_VERSIONS }}; do
            v=$(gh release list \
              --repo "$GITHUB_REPOSITORY" \
              --limit 100 \
              --json tagName,isDraft,isPrerelease \
              --jq '.[] | select((.isDraft | not) and (.isPrerelease | not)) | .tagName' \
              | grep -E "^${major_version}(\\.|$)" \
              | grep -v -- '-' \
              | sort -V \
              | tail -n1)
            versions+="$v "
          done
          echo tags="$versions" >> "$GITHUB_OUTPUT"

      # GHA wants to know all the exact revision of every single action and
      # workflow being pulled into a workflow run *before* it starts running.
      #
      # We, on the other hand, don't know the versions of
      # `rebuild-teleport-oci-distroless.yml` we want to invoke until the
      # previous step complete. This means that we can't use a matrix or any
      # of the calling mechanisms built into GHA, or aggregate the child
      # workflow status under this workflow: we have to treat each versioned
      # invocation of `rebuild-teleport-oci-distroless.yml` as a separate,
      # top-level workflow run.
      - name: Trigger rebuild all distroless OCI images
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAGS: ${{ steps.select.outputs.tags }}
        run: |
          for tag in ${TAGS}; do
            major_branch="branch/${tag%%.*}"
            echo "Triggering rebuild of teleport images for $tag"

            gh workflow run rebuild-teleport-oci-aggregate.yml \
              --repo "$GITHUB_REPOSITORY" \
              --ref "$major_branch" \
              --raw-field teleport-release-tag="$tag" \
              --raw-field environment=prod/oci-rebuild
          done
