# Defines a workflow that triggers rebuild jobs for individual components
#
# This is intended to be run on a schedule from a parent workflow.

name: Rebuild All Distroless OCI Images
on:
  workflow_dispatch:
    inputs:
      oss-teleport-repo:
        description: |
          The name of the OSS teleport repo to checkout
        required: false
        type: string
        default: gravitational/core

      teleport-release-tag:
        description: |
          The semver version of the teleport release to rebuild, including
          the leading `v`
        type: string

      slack-notify-channel:
        description: The slack channel ID of where to send failure notifications.
        type: string
        default: C0351AUPJ8K # internal-tools

      environment:
        description: |
          GitHub Actions environment in which to run the rebuild. Can be either
          `stage/oci-rebuild` or `prod/oci-rebuild`.
        type: string
        default: stage/oci-rebuild

run-name: Rebuild All Distroless Images for ${{ inputs.teleport-release-tag }}

jobs:
  rebuild-operator:
    permissions:
      actions: read
      contents: read
      id-token: write  # required for aws-actions/configure-aws-credentials
    uses: ./.github/workflows/rebuild-operator-oci-distroless.yml
    with:
      environment: ${{ inputs.environment }}
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      teleport-release-tag: ${{ inputs.teleport-release-tag }}
    secrets: inherit

  rebuild-plugins:
    permissions:
      actions: read
      contents: read
      id-token: write  # required for aws-actions/configure-aws-credentials
    uses: ./.github/workflows/rebuild-plugins-oci-distroless.yml
    with:
      environment: ${{ inputs.environment }}
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      teleport-release-tag: ${{ inputs.teleport-release-tag }}
    secrets: inherit

  rebuild-tbot:
    permissions:
      actions: read
      contents: read
      id-token: write  # required for aws-actions/configure-aws-credentials
    uses: ./.github/workflows/rebuild-tbot-oci-distroless.yml
    with:
      environment: ${{ inputs.environment }}
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      teleport-release-tag: ${{ inputs.teleport-release-tag }}
    secrets: inherit

  rebuild-teleport-kube-agent-updater:
    permissions:
      actions: read
      contents: read
      id-token: write  # required for aws-actions/configure-aws-credentials
    uses: ./.github/workflows/rebuild-teleport-kube-agent-updater-oci.yml
    with:
      environment: ${{ inputs.environment }}
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      teleport-release-tag: ${{ inputs.teleport-release-tag }}
    secrets: inherit

  rebuild-teleport:
    permissions:
      actions: read
      contents: read
      id-token: write  # required for aws-actions/configure-aws-credentials
    uses: ./.github/workflows/rebuild-teleport-oci-distroless.yml
    with:
      environment: ${{ inputs.environment }}
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      teleport-release-tag: ${{ inputs.teleport-release-tag }}
      slack-notify-channel: ${{ inputs.slack-notify-channel }}
    secrets: inherit

  slack-on-fail:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs:
      - rebuild-operator
      - rebuild-plugins
      - rebuild-tbot
      - rebuild-teleport-kube-agent-updater
      - rebuild-teleport
    if: always()
    steps:
      - name: Get runtime values from kvstore
        id: kvstore
        uses: gravitational/shared-workflows/tools/env-kvstore@tools/env-kvstore/v1.0.3
        with:
          cognito-identity-pool-id: "us-west-2:da53389e-a459-4a28-bd54-43eeb8e4b579"
          cognito-role-arn: "arn:aws:iam::247230412011:role/github-actions-cognito-oidc"
          values: |
            TOOLING_ALERTS_SLACK_TOKEN,secret
      - name: Slack Notify Failure
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        with:
          method: chat.postMessage
          token: ${{ env.TOOLING_ALERTS_SLACK_TOKEN }}
          payload: |
            {
              "channel": "${{ inputs.slack-notify-channel }}",
              "username": "OCI Rebuild",
              "text": "*OCI Rebuild failure*",
              "mrkdwn": true,
              "parse": "none",
              "unfurl_links": false,
              "unfurl_media": false,
              "attachments": [
                {
                  "color": "danger",
                  "title": "OCI Rebuild for ${{ inputs.teleport-release-tag }} failed",
                  "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              ]
            }
