# Defines a workflow that, given a major version of Teleport:
#  1. Finds the newest released version of that series of Teleport
#  2. Rebuilds all the distroless oci container images for that
#     build of kube-agent-updater, and
#  3. Pushes them to production
#
# This is intended to be run on a schedule from a parent workflow.

name: Rebuild Kube Agent Updater Images
on:
  workflow_dispatch:
    inputs:
      oss-teleport-repo:
        type: string
        default: gravitational/core
        description: |
          OSS Teleport repo

      teleport-release-tag:
        description: |
          The semver version of the teleport release to rebuild, including
          the leading `v`
        type: string
        required: true
      environment:
        description: |
          GitHub Actions environment in which to run the rebuild. Can be either
          `stage/oci-rebuild` or `prod/oci-rebuild`.
        type: string
        default: stage/oci-rebuild

  workflow_call:
    inputs:
      oss-teleport-repo:
        type: string
        default: gravitational/core
        description: |
          OSS Teleport repo

      teleport-release-tag:
        description: |
          The semver version of the teleport release to rebuild, including
          the leading `v`
        type: string
        required: true
      environment:
        description: |
          GitHub Actions environment in which to run the rebuild. Can be either
          `stage/oci-rebuild` or `prod/oci-rebuild`.
        type: string
        default: stage/oci-rebuild

run-name: Rebuild Kube Agent Updater Images for Teleport ${{ inputs.teleport-release-tag }}

jobs:
  configure:
    name: Configure Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      teleport-version: ${{ steps.version.outputs.full }}
      image-tags: ${{ steps.version.outputs.labels }}
      buildbox: ${{ steps.get-buildbox.outputs.buildbox }}
    steps:
      - name: Parse version
        id: version
        uses: gravitational/core/.github/actions/parse-version@master
        with:
          version: ${{ inputs.teleport-release-tag }}
      - name: Checkout OSS Teleport
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.teleport-release-tag }}
      - name: Get buildbox image ref
        id: get-buildbox
        run: |
          BUILDBOX="$(make -s -C ./build.assets/ show-buildbox-base-image)"
          echo "buildbox: $BUILDBOX"
          echo "buildbox=$BUILDBOX" >> "$GITHUB_OUTPUT"

  rebuild-image:
    name: Build OCI container images
    needs: configure
    permissions:
      actions: read
      contents: read
      id-token: write  # required for aws-actions/configure-aws-credentials
    strategy:
      matrix:
        mode: [ 'debug', 'production' ]
        include:
          - mode: 'production'
            base-image: 'gcr.io/distroless/static-debian12:latest'
            repo-debug-suffix: ''
          - mode: 'debug'
            base-image: 'gcr.io/distroless/static-debian12:debug'
            repo-debug-suffix: '-debug'
    uses: ./.github/workflows/oci-image-build.yml
    with:
      # Integrations don't have an enterprise version
      teleport-release: oss
      base-image: ${{ matrix.base-image }}
      oss-teleport-ref: ${{ inputs.teleport-release-tag }}
      source-tag: ${{ inputs.teleport-release-tag }}
      teleport-version: ${{ needs.configure.outputs.teleport-version }}
      # Defaults to us-west-2; rebuild-teleport-oci-distroless sets to us-east-1
      dest-image-registry-region: us-east-1
      dest-image-repo: teleport-kube-agent-updater${{ matrix.repo-debug-suffix }}
      dest-image-tags: ${{ needs.configure.outputs.image-tags }}
      image-build-args: |
        BUILDBOX=${{ needs.configure.outputs.buildbox }}
      image-build-context: ./teleport/.
      image-build-dockerfile: ./integrations/kube-agent-updater/Dockerfile
      should-download-teleport-packages: false
      environment: ${{ inputs.environment }}
