name: Build Kube Agent Updater Images
on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: The name of the OSS teleport repo to checkout.
        type: string
        default: gravitational/core

      oss-teleport-ref:
        description: Git SHA, tag or branch of the revision of OSS teleport to build.
        type: string
        required: true

      source-tag:
        description: |
          The semver version of Teleport that we're building for. If not set
          will be inferred form the `oss-teleport-ref` by assuming that it's
          a standard Teleport release tag in the form vX.Y.Z.
        type: string

      environment:
        description: |
          GitHub Actions environment in which to run the build. Can be either
          `stage/build` or `prod/build`.
        type: string
        default: stage/build

  # The workflow_dispatch event duplicates the workflow_call input parameters, without descriptions.
  workflow_dispatch:
    inputs:
      oss-teleport-repo:
        type: string
        default: gravitational/core
      oss-teleport-ref:
        type: string
        required: true
      source-tag:
        type: string
      environment:
        type: string
        default: stage/build

run-name: Build Kube Agent Updater Images for Teleport ${{ inputs.source-tag }}

jobs:
  configure:
    name: Configure Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      teleport_version: ${{ steps.version.outputs.teleport_version }}
      buildbox: ${{ steps.get-buildbox.outputs.buildbox }}
    steps:
      - name: Parse version tag
        id: version
        run: |
          TAG=${{ inputs.source-tag }}
          if [[ -z "$TAG" ]]; then
            TAG=${{ inputs.oss-teleport-ref }}
          fi
          VERSION=${TAG#v}
          echo "teleport_version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Checkout OSS Teleport
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.oss-teleport-ref }}
      - name: Get buildbox image ref
        id: get-buildbox
        run: |
          BUILDBOX="$(make -s -C ./build.assets/ show-buildbox-base-image)"
          echo "buildbox: $BUILDBOX"
          echo "buildbox=$BUILDBOX" >> "$GITHUB_OUTPUT"

  build-docker-images:
    name: Build OCI container images
    needs: configure
    permissions:
      id-token: write # required for aws-actions/configure-aws-credentials
      contents: read
      actions: read
    strategy:
      matrix:
        mode: ['debug', 'production']
        include:
          - mode: 'production'
            base-image: 'gcr.io/distroless/static-debian12:latest'
            repo-debug-suffix: ''
          - mode: 'debug'
            base-image: 'gcr.io/distroless/static-debian12:debug'
            repo-debug-suffix: '-debug'
    uses: ./.github/workflows/oci-image-build.yml
    with:
      # Integrations don't have an enterprise version
      teleport-release: oss
      base-image: ${{ matrix.base-image }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      source-tag: ${{ inputs.source-tag }}
      teleport-version: ${{ needs.configure.outputs.teleport_version }}
      dest-image-repo: teleport-kube-agent-updater${{ matrix.repo-debug-suffix }}
      dest-image-tags: ${{ needs.configure.outputs.teleport_version }}
      allow-overwrites: false
      image-build-args: |
        BUILDBOX=${{ needs.configure.outputs.buildbox }}
      image-build-context: ./teleport/.
      image-build-dockerfile: ./integrations/kube-agent-updater/Dockerfile
      should-download-teleport-packages: false
      environment: ${{ inputs.environment }}
