name: Build Distroless Images
on:
  workflow_call:
    inputs:
      oss-teleport-repo:
        description: The name of the OSS teleport repo to checkout.
        type: string
        default: gravitational/core

      oss-teleport-ref:
        description: Git SHA, tag or branch of the revision of OSS teleport to build.
        required: true
        type: string

      source-tag:
        description: |
          The semver version of Teleport that we're building for. If not set
          will be inferred form the `oss-teleport-ref` by assuming that it's
          a standard Teleport release tag in the form vX.Y.Z.
        type: string

      environment:
        description: |
          GitHub Actions environment in which to run the build. Can be either
          `stage/build` or `prod/build`.
        type: string
        default: stage/build

  # The workflow_dispatch event duplicates the workflow_call input parameters, without descriptions.
  workflow_dispatch:
    inputs:
      oss-teleport-repo:
        type: string
        default: gravitational/core
      oss-teleport-ref:
        type: string
        required: true
      source-tag:
        type: string
      environment:
        type: string
        default: stage/build

run-name: Build Distroless Images for Teleport ${{ inputs.source-tag }}

jobs:
  configure:
    name: Configure Build
    runs-on: ubuntu-latest
    outputs:
      teleport_version: ${{ steps.version.outputs.teleport_version }}
    steps:
      - name: Parse version tag
        id: version
        run: |
          TAG=${{ inputs.source-tag }}
          if [[ -z "$TAG" ]]; then
            TAG=${{ inputs.oss-teleport-ref }}
          fi
          VERSION=${TAG#v}
          echo teleport_version="$VERSION" >> "$GITHUB_OUTPUT"

  build-docker-images:
    name: Build OCI container images
    needs: configure
    permissions:
      id-token: write  # required for aws-actions/configure-aws-credentials
      contents: read
      actions: read
    strategy:
      matrix:
        mode: ['debug', 'production']
        release: ['oss', 'enterprise', 'fips']
        include:
          - architectures: |
              amd64
              arm
              arm64
          - mode: 'production'
            base-image: 'gcr.io/distroless/cc-debian12:latest'
            repo-debug-suffix: ''
          - mode: 'debug'
            base-image: 'gcr.io/distroless/cc-debian12:debug'
            repo-debug-suffix: '-debug'
          - release: 'oss'
            repo-enterprise-infix: ''
          - release: 'enterprise'
            repo-enterprise-infix: '-ent'

          # FIPS release is currently amd64 and arm64-only
          - release: 'fips'
            repo-enterprise-infix: '-ent-fips'
            dockerfile-suffix: '-fips'
            architectures: |
              amd64
              arm64
    uses: ./.github/workflows/oci-image-build.yml
    with:
      teleport-release: ${{ matrix.release }}
      base-image: ${{ matrix.base-image }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      source-tag: ${{ inputs.source-tag }}
      teleport-version: ${{ needs.configure.outputs.teleport_version }}
      dest-image-repo: teleport${{ matrix.repo-enterprise-infix }}-distroless${{ matrix.repo-debug-suffix }}
      dest-image-tags: ${{ needs.configure.outputs.teleport_version }}
      architectures: ${{ matrix.architectures }}
      image-build-args: |
        TELEPORT_VERSION=${{ needs.configure.outputs.teleport_version }}
      image-build-dockerfile: Dockerfile-distroless${{ matrix.dockerfile-suffix }}
      allow-overwrites: false
      environment: ${{ inputs.environment }}

  smoke-tests:
    runs-on: ubuntu-latest
    needs: [configure, build-docker-images]
    permissions:
      id-token: write  # required for aws-actions/configure-aws-credentials
      contents: read
      actions: read
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64, arm]
        mode: ['debug', 'production']
        release: ['oss', 'enterprise', 'fips']
        include:
          - mode: 'production'
            repo-debug-suffix: ''
          - mode: 'debug'
            repo-debug-suffix: '-debug'
          - release: 'oss'
            repo-enterprise-infix: ''
          - release: 'enterprise'
            repo-enterprise-infix: '-ent'
          - release: 'fips'
            repo-enterprise-infix: '-ent-fips'
        exclude:
          - release: 'fips'
            arch: 'arm'
    name: "Smoke test ${{ matrix.arch }}/${{ matrix.release }}/${{ matrix.mode }}"
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.oss-teleport-ref }}
          path: ./teleport

      - name: Load environment values
        uses: gravitational/shared-workflows/tools/env-loader@b90d744feb39522329fba9c7764a4fe07d039d29 # tools/env-loader/v0.1.2
        with:
          tool-version: v0.0.5
          environment-name: ${{ inputs.environment }}
          environments-directory: ./teleport/e/.environments

      - name: Set up Docker QEMU integration
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Assume tag build AWS role
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          aws-region: us-west-2
          role-to-assume: ${{ env.ECR_READ_ONLY_ROLE }}
          role-session-name: "gha-oci-image-build-${{ github.run_number }}-test"
          role-duration-seconds: 3600

      - name: Login to ECR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ env.ECR_PENDING_REPO_BASE }}

      # NOTE: We're referring to the image by tag here, as there is no nice way
      #       to (de-)mux the outputs from a matrix job. The "pending" registry
      #       has immutable tags enabled, so we're reasonably safe in assuming
      #       that the tag referrs to the image built in the last step is the
      #       correct one
      - name: Smoke tests
        env:
          DESTINATION_REPO_PREFIX: ${{ env.ECR_PENDING_REPO_BASE }}
        run: |
          IMAGE_UNDER_TEST=${DESTINATION_REPO_PREFIX}/teleport${{ matrix.repo-enterprise-infix }}-distroless${{ matrix.repo-debug-suffix }}:${{ needs.configure.outputs.teleport_version }}
          ./run linux/${{ matrix.arch }} "$IMAGE_UNDER_TEST" ${{ matrix.release }}
        working-directory: ./teleport/build.assets/charts/smoke_tests
