name: Release - Build & Publish
run-name: ${{ inputs.cloud-only && 'Cloud ' || '' }}Release of ${{ inputs.oss-teleport-repo }}@${{ inputs.oss-teleport-ref }}${{ inputs.teleport-version && format(' ({0})', inputs.teleport-version) }}
on:
  workflow_dispatch:
    inputs:
      oss-teleport-repo:
        description: The name of the OSS teleport repo to build.
        default: gravitational/core
        type: string
      oss-teleport-ref:
        description: Tag, branch or reference to OSS teleport to build.
        type: string
        required: true
      teleport-version:
        description: The semver version of Teleport version that we're building for.
        type: string
      environment:
        description: |
          GitHub Actions environment in which to run the build. Can be either
          `stage` or `prod`.
        type: string
        default: stage
      cloud-only:
        description: Perform a cloud-only release (distroless OCI only)
        type: boolean
        default: false
      slack-notify-channel:
        description: The slack channel to notify the status of the job.
        type: string
  # workflow_call is not supported for this workflow yet as this workflow
  # has already reached the max depth limit of 3 for reusable workflow calls.
  #
  # See: https://docs.github.com/en/actions/sharing-automations/reusing-workflows#limitations
  workflow_call: {}
jobs:
  tag-build:
    name: Build
    secrets: inherit
    permissions:
      actions: read
      contents: read
      id-token: write
    uses: ./.github/workflows/tag-build.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      teleport-version: ${{ inputs.teleport-version }}
      cloud-only: ${{ inputs.cloud-only }}
      environment: ${{ inputs.environment }}/build
  tag-publish:
    name: Publish
    needs:
      - tag-build
    secrets: inherit
    permissions:
      actions: write
      contents: read
      id-token: write
    uses: ./.github/workflows/tag-publish.yaml
    with:
      oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
      oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
      teleport-version: ${{ inputs.teleport-version }}
      cloud-only: ${{ inputs.cloud-only }}
      environment: ${{ inputs.environment }}/publish
  post-workflow:
    name: Post Workflow Steps
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    # The combination of always and needs means this will always run after all other jobs are done
    if: always()
    needs:
      - tag-build
      - tag-publish
    steps:
      - name: Get runtime values from kvstore
        id: kvstore
        uses: gravitational/shared-workflows/tools/env-kvstore@tools/env-kvstore/v1.0.3
        with:
          cognito-identity-pool-id: "us-west-2:da53389e-a459-4a28-bd54-43eeb8e4b579"
          cognito-role-arn: "arn:aws:iam::247230412011:role/github-actions-cognito-oidc"
          values: |
            TOOLING_ALERTS_SLACK_TOKEN,secret
      # Success
      - name: Slack Notify Succes
        if: inputs.slack-notify-channel && !(contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'))
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        with:
          method: chat.postMessage
          token: ${{ env.TOOLING_ALERTS_SLACK_TOKEN }}
          errors: true
          payload: |
            {
              "channel": "${{ inputs.slack-notify-channel }}",
              "username": "Release Reporter",
              "text": "*Release Report*",
              "mrkdwn": true,
              "parse": "none",
              "unfurl_links": false,
              "unfurl_media": false,
              "attachments": [
                {
                  "color": "good",
                  "title": "Release for ${{ inputs.teleport-version }} succeeded",
                  "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              ]
            }
      # Failure
      - name: Slack Notify Failure
        if: inputs.slack-notify-channel && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'))
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        with:
          method: chat.postMessage
          token: ${{ env.TOOLING_ALERTS_SLACK_TOKEN }}
          errors: true
          payload: |
            {
              "channel": "${{ inputs.slack-notify-channel }}",
              "username": "Release Reporter",
              "text": "*Release Report*",
              "mrkdwn": true,
              "parse": "none",
              "unfurl_links": false,
              "unfurl_media": false,
              "attachments": [
                {
                  "color": "danger",
                  "title": "Release for ${{ inputs.teleport-version }} failed - click here to investigate",
                  "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              ]
            }
