---
name: Test the Teleport updater

on:
  pull_request:
    paths:
      - .github/workflows/build-teleport-updater.yaml
      - .github/workflows/test-teleport-updater.yaml
      - .github/actions/load-gpg-key/action.yaml
      - .github/actions/deploy-os-package/action.yaml
      - e/assets/systemd-unit-upgrader/**
      - e/assets/systemd-unit-upgrader-tests/scripts/**

jobs:
  setup:
    name: Setup for the test
    runs-on: ubuntu-latest
    outputs:
      artifact-version: ${{ steps.gen-version.outputs.artifact-version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Generate a new unique version based on the nearest tag
        id: gen-version
        run: |
          ARTIFACT_VERSION="$(git describe --tags --match "v[[:digit:]]*.[[:digit:]]*.[[:digit:]]")"
          echo "Artifact version: $ARTIFACT_VERSION" >> "$GITHUB_STEP_SUMMARY"
          echo "artifact-version=$ARTIFACT_VERSION" >> "$GITHUB_OUTPUT"
  build:
    name: Build the updater
    uses: ./.github/workflows/build-teleport-updater.yaml
    needs:
      - setup
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    with:
      environment: "stage/build"  # If a QA environment is ever deployed then this should probably to it
      updater-version: ${{ needs.setup.outputs.artifact-version }}
  # The updater is tightly coupled with OS package repos, so the package must be published to OS package repos to test
  publish:
    name: Publish the updater
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    needs:
      - setup
      - build
    concurrency: Only allow a single teleport-ent-updater ${{ matrix.repo-type }} deployment at a time
    strategy:
      fail-fast: false  # If either APT or YUM deployment fails, let the other one run before failing
      matrix:
        repo-type:
          - apt
          - yum
    env:
      VERSION_CHANNEL: cloud
    steps:
      - name: Determine workflow references
        id: refs
        env:
          PR_BASE_REF: ${{ github.base_ref }}
          PR_HEAD_REF: ${{ github.head_ref }}
        run: |
          # Only use the PR ref for PRs that target master, because all other branches should
          # use the version of the OPRT action that lives on master.
          # This relies on `github.base_ref` only being defined for PR events.
          if [[ "$PR_BASE_REF" == 'master' ]]; then
            echo "workflow-ref=$PR_HEAD_REF" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "workflow-ref=refs/heads/master" >> "$GITHUB_OUTPUT"
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ steps.refs.outputs.workflow-ref }}
      - name: Deploy package to `stable/${{ env.VERSION_CHANNEL }}` ${{ matrix.repo-type }} repos
        uses: ./.github/actions/deploy-os-package
        with:
          environment: "stage/publish"
          repo-type: ${{ matrix.repo-type }}
          artifact-tag: ${{ needs.setup.outputs.artifact-version }}
          version-channel: ${{ env.VERSION_CHANNEL }}
          package-name-filter: "teleport-ent-updater*"
          package-to-test: teleport-ent-updater
          do-teleport-package-tests: true
          workflow-git-reference: ${{ steps.refs.outputs.workflow-ref }}
    
