// Code generated by resource-gen; DO NOT EDIT.

package cache

// Generated cache gathering for resource-gen managed resources.

// GeneratedConfig holds service interfaces for cache-enabled resources
// managed by resource-gen. It is embedded in cache.Config and set by
// callers via the exported field.
type GeneratedConfig struct {
}
